### ISSUE TITLE
How to set "handle SIG32 nostop" on gdb

### ISSUE THREAD

**Issue by SuJinpei** [Microsoft/VSLinux#102]
Hi,
debug output:
Program received signal SIG32, Real-time event 32.
[Switching to Thread 2760]
0x00007ffff777e6d5 in ?? ()

so I want to set "handle SIG32 nostop" on GDB, but I don't know where to set.

So sorry for my poor english, but I wish I had expessed what I want.

**Comment by paulmaybee** [comment]
Rrom the VS  command window (View->Other Windows->Command Window) you can execute any gdb command. Use 
  Debug.MIDebugExec <gdb-command>
For example
     Debug.MIDebugExec handle SIG32 nostop
