### ISSUE TITLE
 include directories problems

### ISSUE THREAD

**Issue by hugh71321** [Microsoft/VSLinux#104]
I added an include directory "/usr/include/sys" (because I need unistd.h, it is under the path) and then I just include #include < string > in my .cpp.
 
When I compile it show me these errors.

		‘errno’ was not declared in this scope	SharpAPI	C:\usr\include\c++\4.8.2\ext\string_conversions.h	61	
		‘ERANGE’ was not declared in this scope	SharpAPI	C:\usr\include\c++\4.8.2\ext\string_conversions.h	66	
		#include nested too deeply	SharpAPI	C:\usr\include\sys\errno.h	1

**Comment by sam9116** [comment]
hey @hugh71321  where do you add "/usr/include/sys"? 
btw I'm wondering how this is coming along? One of my school assignment example also needs unistd to work and I'm trying to write this assignment with VSLinux

**Comment by yuehuang010** [comment]
Hello, with the change to the Translator in VS 15.7 Preview 1, paths that start with '/' or '~' will be ignored for translating.  This should address your concern.  Please post if it is not the case.
