### ISSUE TITLE
Unexpected current directory when building

### ISSUE THREAD

**Issue by ardatur** [Microsoft/VSLinux#105]
[Disclaimer: this has been mentioned but ignored in #55, so here's a separate report.]

When building/cleaning/rebuilding, current dir is set to the user's home rather than the project's directory (verified by prepending "pwd &&" to the build command etc.). It would be more convenient to be able to have just "make" and "a.out" as a remote build command/output rather than "cd $(RemoteProjectDir) && make" and "projects/.../a.out" (for whatever reason, "$(RemoteProjectDir)/a.out" does not work, see also: #99).

Tested on: a trivial "makefile" configuration type project, VS2015.3, VSLinux 1.0.6, Fedora 25 x64 (VM).

**Comment by bruceoberg** [comment]
i'm seeing the same thing in a stock makefile project. it is very unexpected.

also, when running the app on the target machine (via gdb), the current directory is also the user's home. there's no shell "cd $(RemoteProjectDir)" trick to fix that.

**Comment by lukka** [comment]
Fixed in VS 15.5
