### ISSUE TITLE
Remote build error/warning messages do not appear in the Error List

### ISSUE THREAD

**Issue by jwt27** [Microsoft/VSLinux#111]
* A brief description  

Previously, I used a plain "makefile project" which called .bat files to invoke gcc in an msys2 shell, and pass its output through a script, to convert gcc's output in a Visual Studio compatible format. Visual Studio would then parse the output and populate the Error List accordingly.  
Now with this extension, doing the same thing over ssh, Visual Studio no longer populates the error list. I can still click lines in the build output window, and VS jumps to the right line in the associated file, but the error list only contains one unhelpful "`make exited with code 2, please see the Output Window - Build output for more details`" message.

To clarify, the script I use converts gcc-style messages like these:  
`src/main.cpp:12:5: error: 'asdf' was not declared in this scope`  
to a format which Visual Studio should be able to parse:  
`D:\msys64\home\JW\projects\jwdpmi_test\src\main.cpp(12,5): error : 'asdf' was not declared in this scope`

* Expected results  

Visual Studio should parse the build output and place error/warning messages in the Error List.  
Ideally, VS should support gcc-style error messages natively, without using any external scripts.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc.  

Visual Studio Community 2015. (I don't think the rest is relevant here)

* Steps required to reproduce the error  

Make a new text file called C:\testfile.txt  
Create a Makefile project using this extension  
Set the build command to `echo "C:\testfile.txt(1,1): error : test"`  
Press ctrl-shift-b to "build"  
The "error" can be clicked in the output window, but does not appear in the Error List.

**Comment by forceprojectx** [comment]
I have the same issue, but it seems to be limited to makefile projects. Unfortunately, for me clicking in the output doesnt do anything. I have to manually open the file and scroll through until I find the appropriate line.

If I let VS do the build (so very slowly), errors properly appear in the error list.

**Comment by jwt27** [comment]
> for me clicking in the output doesnt do anything

I wrote a program to make the messages clickable. See here: https://github.com/jwt27/gcc2vs  
If you're using gcc in msys2/mingw, you may find it useful.

**Comment by dixonqmg** [comment]
This is actually a huge issue with makefile projects, I had the same one reported here. I'm not sure why are they ignoring it frankly.

**Comment by dixonqmg** [comment]
The program that jwt27 refers to helped partially. Messages are clickable, but the error list window is still not being populated

**Comment by jcn9k** [comment]
Yeah it'd be nice if it supported the errors natively.
Though some munging may be required. I've got a similar script to rewrite the output to make it clickible in the output window. but they don't show up in the error list. Using the VsColorOutput extension makes the output window a little easier thou as you can make error red etc.
I also have it remap the header file paths for system headers, which are published via a smb share and mounted on the windows machine.

**Comment by eiva** [comment]
Yeah my dream to use VS in the big legacy project did not come true...

**Comment by itodirel** [comment]
We fixed this recently and the fix will be available in Preview 2 of Visual Studio 2017

**Comment by itodirel** [comment]
@eiva is the error parsing the only problem preventing you from using our tools on your code base? We would be interested to hear from you on your experiences with Visual Studio Linux Makefile projects and existing code bases.

**Comment by itodirel** [comment]
https://github.com/Microsoft/VSLinux/issues/91

**Comment by itodirel** [comment]
Duplicate issue is #91

**Comment by itodirel** [comment]
Closing as fixed.

**Comment by deiruch** [comment]
Related to #231 ?
