### ISSUE TITLE
Natvis DisplayString not working

### ISSUE THREAD

**Issue by forceprojectx** [Microsoft/VSLinux#112]
When using a linux makefile project Natvis DisplayString and StringView tags do not work.
Nothing I do has changed the "**value**" column value (in locals,autos,watch)  from **{...}**

Then instead of overriding the normal display, you get an extra row called [visualized view] that still shows {...} instead of DisplayString and you never get the little magnifying glass to open up the text viewer even if you set the StringView element in your natvis file.

Also, When you hover over a variable with a custom natvis type definition you get an error stating
"Explicit refresh required for visualized expressions."

I just want to be able to check a strings value without having to click through 4 or 5 string members. 
Please help.

**expected:**
stringvar	L"PRGM 0.01"	std::__cxx11::wstring

**actual value:**
-stringvar	{...}	std::__cxx11::wstring
-[Visualized View]	{...}	
+[str]	0x2469020 L"PRGM 0.01"	std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::pointer

![Image of natvis issue0](http://i.imgur.com/TNBnVc8.png)
![Image of natvis issue1](http://i.imgur.com/3Qd5lcB.png)

**natvis type def for std::__cxx11::wstring::**
```
<Type Name="std::__cxx11::wstring">
    <DisplayString>{_M_dataplus._M_p}</DisplayString>
    <StringView>_M_dataplus._M_p</StringView>
    <Expand>
      <Item Name="[str]" >_M_dataplus._M_p</Item>
      <Item Name="[size]" ExcludeView="simple">_M_string_length</Item>
      
      <ArrayItems ExcludeView="simple">
        <Size>_M_string_length</Size>
        <ValuePointer Condition="_M_string_length &gt;= 0">_M_dataplus._M_p</ValuePointer>
      </ArrayItems>
    </Expand>
  </Type>
```

**Dev Env:**
Microsoft Visual Studio Professional 2015
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
Installed Version: Professional
Microsoft Visual C++ 2015
Visual C++ for Linux Development   1.0.6
Clang with Microsoft CodeGen   14.0.25317

**OS Name**	Microsoft Windows 10 Pro
**Version**	10.0.14393 Build 14393

**Build+Deploy Env**
Ubunto 16.  4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
g++ (Ubuntu 5.4.0-6ubuntu1 16.04.4) 5.4.0 20160609
GNU gdb (Ubuntu 7.11.1-0ubuntu1 16.04) 7.11.1

**Comment by paulmaybee** [comment]
Try executing "Debug.MiDebugExec -enable-pretty-printing" in the command window. Or alternatively, set your Project properties "Configuration Properties->Debugging->Additional Debugger Commands" value to "-enable-pretty-printing". 

Pretty printing will be enabled by default in the next release of the Linux extension.

**Comment by AliAskari** [comment]
@paulmaybee Is there any way to have this working in gdbserver mode?

**Comment by forceprojectx** [comment]
@paulmaybee this doesnt help. the value field remains **{...}** as in the screen shots from the first post.

**Comment by itodirel** [comment]
this now works and is available in 1.0.7 which is now available in the extension gallery

**Comment by AliAskari** [comment]
@itodirel Does this also work in gdbserver mode?

**Comment by robotdad** [comment]
@AliAskari natvis works for both gdb and gdbserver mode, python pretty printers work with gdb mode only.
