### ISSUE TITLE
Disassembly Window doesn't work

### ISSUE THREAD

**Issue by ohanson511** [Microsoft/VSLinux#113]
Hi

I am using the latest tool version. 
My remote Linux is an ubuntu docker container version 16.04. 
Compiled the app with GCC version 4.9.1. 
The GDB is MINGW x86_64-linux-gnu-gdb version 7.9 provided with VC. 
GDBServer (Ubuntu 7.11.1-0ubuntu1~16.04) is being run on the remote Linux machine.
Using VC 2015 Enterprise update 3.

When I try to open the disassembly window from visual studio during a debugger session, I get two error message boxes:

1. Disassembly cannot be displayed for the source location. There is no executable code at this location in the source code.
2. GDB exited unexpectedly with exit code 3 (0x3). Debugging will now abort.

Any suggestions  ?

**Comment by paulmaybee** [comment]
I am not able to repro your behavior using "Visual C++ for Linux Development 1.0.6". Is this the version of the Linux extension you have installed? If so, can you please send us a gdb log of a debugging session where you are seeing these error messages? Logging details are here: https://github.com/Microsoft/MIEngine/wiki/Logging

**Comment by robotdad** [comment]
@ohanson511 were you able to get logs, or did this behavior stop reproing?

**Comment by ohanson511** [comment]
This issue seems to have resolved. I guess it was due to slowness of our remote target connection.

There are other issues like being able to change the value of registers and the way they are displayed but that’s a different story.

Thanks
