### ISSUE TITLE
Can not include #include <sys/socket.h>

### ISSUE THREAD

**Issue by tue39408** [Microsoft/VSLinux#115]
Hi, 
 When I try to use linux socket library by adding #include <sys/socket.h>, the IDE give me error: can not open source file "sys/socket.h"

How can I work with Linux built-in libraries ? 

Thank you

**Comment by forceprojectx** [comment]
copy the headers from linux onto your dev box and tell intellisense where to look for them.

**Comment by robotdad** [comment]
This is something we are looking at to copy the includes per remote system locally so they can be referred more easily.

**Comment by itodirel** [comment]
Using #43 for tracking this issue

**Comment by itodirel** [comment]
As an update, we implemented this feature
