### ISSUE TITLE
how to change remote host

### ISSUE THREAD

**Issue by xylcbd** [Microsoft/VSLinux#116]
how to change remote host? and where to watch connection status? thank you.

**Comment by forceprojectx** [comment]
you can add or remove connections in Tools | Options -> Cross Platform
you can select a connection for your project in the project properties
you can read all the instructions on how to do everything here : https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/

**Comment by robotdad** [comment]
@xylcbd did @forceprojectx answer resolve this for you?

**Comment by xylcbd** [comment]
@robotdad yes, it works. I will close this issue now, thanks.
