### ISSUE TITLE
Unable to use VSLinux with remote x86 machine

### ISSUE THREAD

**Issue by allanhaywood** [Microsoft/VSLinux#118]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

This is the first I have attempted to use VSLinux with a remote machine that is 32bit.

I didn't know it was 32 bit until I tried to build the project and got the following error:
Current project architecture 'x64' is incompatible with the remote system architecture 'x86' ('x86'). Please switch the project architecture to 'x86' in Configuration Manager.

I double checked, and indeed the remote system is not 64bit:
uname -m
i686

However, when I switch to x86 in the configuration manager, it then thinks the remote is 64 bit:
This is the error I get:
Current project architecture 'x86' is incompatible with the remote system architecture 'x64' ('x64'). Please switch the project architecture to 'x64' in Configuration Manager.

I am unable to build projects against this machine.

* Expected results

If the correct project architecture is chosen that matches the remote machine, it should work.

* Actual results (with build output window contents if applicable)
I am unable to target a remote machine that is 32bit.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
OS: 
LSB Version:    :core-4.0-ia32:core-4.0-noarch:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 5.11 (Tikanga)
Release:        5.11
Codename:       Tikanga

CPU:
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 9
model name      : AMD Opteron(tm) Processor 6174
stepping        : 1

Visual Studio Community 2017 15.0.0+26228.9
Visual C++ For Linux Development 1.0.6

* Steps required to reproduce the error
For me: attempt to use a remote machine that is 32bit.

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by allanhaywood** [comment]
Looks like this isn't a bug, other than unexpected behavior.

When I chose x86 from the drop down menu, it changed to the connection for my VM (which is 64bit), and when I chose x64 from the drop down menu, it was changing the connection back to the other machine, which was 32bit.

**Comment by allanhaywood** [comment]
I've hit this again. Even though I changed my Remote Build Machine to the right one, I'm getting this error again. It worked for awhile when I switched to the x86 machine, not I am trying to use the x64 machine, and even though my properties has the x64 machine selected as the remote build machine, it is still failing.

**Comment by allanhaywood** [comment]
I removed the architecture validation from the Linux.Makefile.targets file, and it looks like what is happening is it is not using the machine specified.

I have my local vm selected as the Remote Build Machine, but when I attempt a build, it is trying to use the machine that is not selected.

**Comment by stanthomas** [comment]
Is this related to #27 ?

**Comment by allanhaywood** [comment]
It may be, I'll look into it.

**Comment by allanhaywood** [comment]
While it is the same area, it isn't entirely related. #27 is regarding what happens when multiple remote machines are the target architecture.

What I am seeing, is that I have x86 selected, and out of the three remote machines I have configured, only one is x86, and even though it is the one that I selected under project options as the remote machine, it still attempts to use the incorrect x64 machines.

To work around this, I have to delete all remote connections but the one I want to use.

**Comment by robotdad** [comment]
@itodirel is taking a look

**Comment by robotdad** [comment]
We still haven't done anything in this area yet. It's on my plate to come up with something here regarding architecture interactions between app target, build target and deploy target. I hope to have something written up in the next week or two and will share here to get feedback.

**Comment by itodirel** [comment]
We removed the architecture validation from makefile projects.
