### ISSUE TITLE
"error list" windows is not being populated in makefile projects

### ISSUE THREAD

**Issue by dixonqmg** [Microsoft/VSLinux#120]
I have set up a makefile project. After some massaging of gcc output with a script, I formatted it to the point that error messages in the output window are clickable, and get you to the right point in the source code window. But for some reason, "Error list" is still not being populated. It contains only one error about this line of invocation:

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(135,5): error : cd ~/projects/linux_test; ./b.sh exited with code 1, please see the Output Window - Build output for more details (NOTE: the build output verbosity might need to be changed in Tools Options to see more information in the Output Window).

Below is a sample output of my makefile compilation output

C:\Users\dnikitin\linux_test\linux_test\main.cpp: In function 'int main()':
C:\Users\dnikitin\linux_test\linux_test\main.cpp(9,2): error :  'asdf' was not declared in this scope
  asdf
  ^

that error is clickable in the output window, but doesn't get into the "error list"

**Comment by robotdad** [comment]
@itodirel is looking at this

**Comment by itodirel** [comment]
Currently we do not parse the output of Makefile projects to see if there were parsable errors that could go in the Error List. We should do that.

**Comment by itodirel** [comment]
We fixed this bug and the fix will be available in Preview 2 of Visual Studio 2017

**Comment by itodirel** [comment]
See related #91 and #111

**Comment by itodirel** [comment]
Fixed
