### ISSUE TITLE
"Frame not in module" while trying to debug the Default Console Application in VM

### ISSUE THREAD

**Issue by AdiJurca** [Microsoft/VSLinux#121]
I installed latest Ubuntu version on an Oracle Virtual box and set up ssh access to it. I then proceeded to create a Linux Console Application using the template and built and run it easily and normally. 
However, when setting a breakpoint(it stops normally at the breakpoint) and trying to step(F10) from it I get "Frame not in module". It doesn't seem to load the symbols for debugging.

**Using**: Ubuntu 7.11.1-0ubuntu1~16.04 GNU gdb 7.11.1 in Oracle VirtualBox Version 5.1.18 r114002

I'm attaching the project folder.
[HelloLinux.zip](https://github.com/Microsoft/VSLinux/files/879101/HelloLinux.zip)

Any suggestions? Thank you.

**Comment by AdiJurca** [comment]
Some additional information here:

- If I try to step again after the "Frame not in module" I get the message "Unable to step. The message is improperly formatted or was damaged in transit".
- Also, I tried to debug with gdb on the linux machine and it works, so I imagine the debug symbols are generated correctly.

Thanks.

**Comment by AdiJurca** [comment]
Some more information here: It seems to only be doing this when it reaches code that is part of another library(printf, std::cout). Local code can be debugged just fine. 

My question is: why doesn't it jump over the line? I have "Enable Just My Code" checked and I used Step over not Step into.

It works the same when debugging in both gdb and gdbserver modes.

Thanks

**Comment by robotdad** [comment]
@paulmaybee can you take a look?

**Comment by paulmaybee** [comment]
Seems to work fine on a 64bit Ubuntu installation, but I see your project is 32 bit. I'll set up a 32-bit vm and see if I can repro.  In the meantime, what version of VS are you running?

**Comment by paulmaybee** [comment]
Confirmed that this fails on a 32-bit Ubuntu. Looks like an issue with gdb. The log shows that the stepping has completed in an unknown **location**:

5: (345709) <-1019-exec-next
5: (345710) ->1019-exec-next
5: (345717) ->1019^running
5: (345717) ->*running,thread-id="all"
5: (345718) ->(gdb)
5: (345718) ->&"\n"
5: (345719) ->^done
5: (345719) ->(gdb)
5: (345717) 1019: elapsed time 8
5: (345723) ->*stopped,reason="end-stepping-range",frame={addr="0x080482f0",**func="??"**,args=[]},thread-id="1",stopped-threads="all",core="0"

**Comment by AdiJurca** [comment]
Hi, thanks for answering. 

I now see I forgot to mention that I was using a 32-bit Ubuntu. I was also using Visual Studio 2017 Community.

**Comment by BrianSipple** [comment]
I'm encountering this same issue -- just as @AdiJurca described -- using Visual Studio 2017 Community and targeting the WSL's distribution of Linux (Ubuntu 16.04). 

Current Windows Version: 1703
Current OS Build: 15063.296

**Comment by Phantom190** [comment]
I'm having the same problem. Visual Studio 2017 Community Edition, vmware running Ubuntu 32-bit

**Comment by trogper** [comment]
Can you please at least provide some message about why you closed this issue? This is very intransparent.

**Comment by PureRockets** [comment]
This issue is still active in VS 2017, it should not have been closed.

**Comment by paulmaybee** [comment]
This bug in cause by linking on 32-bit machines with the -z,now flag and then debugging with gdb. To work around it change your project property value for Linker->Advanced->"Enable Immediate Function Binding" to "No".

**Comment by PBW99** [comment]
I fixed this problem by deleting ".vs" directory then reopen solution.
