### ISSUE TITLE
Rebuild solution deletes all files on remote host with Copy Sources = No

### ISSUE THREAD

**Issue by karlstiller** [Microsoft/VSLinux#123]
* Brief description:
Rebuild solution deletes all files on remote host with Copy Sources = No

* Expected results
The files stored on the remote side should not be modified.

* Actual results
The files are deleted.

* Versions:
VS Pro 2015 Version 14.0.25431.01 Update 3
CentOs 7
GCC 4.8.5 20150623
GDB/gdbserver 7.6.1-94.el7
CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz

Setup:
Host: CentOs 7
VM: Windows 7

Steps required to reproduce:
1. Create new Console Application.
2. Build the project, and add connection to remote computer.
3. Localize files on remote computer. (~/projects/projectname). Notice the main.cpp source file.
4. Edit the project properties, set "ConfigurationProperties" > "Copy Sources" > "Copy Sources" = No.
5. Execute a rebuild solution (Ctrl+Alt+F7) or "Build" > "Rebuild Solution".
6. Examine the (~/projects/projectname) directory. Notice that main.cpp no longer exists.

**Comment by robotdad** [comment]
Talked with @itodirel about this, it should be fixed in the next release which will be 15.4.

**Comment by itodirel** [comment]
Closed as fixed
