### ISSUE TITLE
Debugging Remotely from VS2017 Community to Ubuntu Linux Failing

### ISSUE THREAD

**Issue by basabuber** [Microsoft/VSLinux#128]
* Create a Console Application for Linux.
  I used the example from the blog for learning 'concepts' in C++ by Andrew Pardoe.
  This builds correctly on Linux:
~/projects$ find .
./consapp-ii-concepts
./consapp-ii-concepts/bin
./consapp-ii-concepts/bin/x64
./consapp-ii-concepts/bin/x64/Debug
./consapp-ii-concepts/bin/x64/Debug/consapp-ii-concepts.out
./consapp-ii-concepts/main.cpp
./consapp-ii-concepts/obj
./consapp-ii-concepts/obj/x64
./consapp-ii-concepts/obj/x64/Debug
./consapp-ii-concepts/obj/x64/Debug/main.o

  and works correctly when run:
~/projects/consapp-ii-concepts$ ./bin/x64/Debug/consapp-ii-concepts.out 
42 is the answer to the ultimate question of life, the universe, and everything!

This shows that the build is configured correctly. However I am not able to run or debug the solution from VS2017 Community. I see the following in the Linux Console Window:
Process #[correct remote executable] created; pid = xyz
Listening on port 4444
Remote debugging from host 127.0.0.1

I am worried about the last line. It should work for Bash on Windows Subsystem for Linux but not for a general Linux host. The gdbserver is running:
~/projects/consapp-ii-concepts$ ps aux | grep gdb
miki      7426  0.0  0.2  20932  8536 pts/1    S    23:20   0:00 gdbserver :4444 /home/miki/projects/consapp-ii-concepts/bin/x64/Debug/consapp-ii-concepts.out

* Expected results - Should talk to the gdbserver on the actual remote host.

* Actual results (with build output window contents if applicable)
 (Will update)

* VS Community 2017 V 15.1 26403.3 Release
  VS C++ Linux Dev 1.06
  Ubuntu 17.04
  gcc,g++ 6.3
  gdb/gdbserver 7.12.50
  x64

* To Reproduce: Launch the Remote GDB Debugger from within VS

**Comment by paulmaybee** [comment]
Are you still having this problem? What does happen when you try to launch the debugger? Can you get a debugger log (see https://github.com/Microsoft/MIEngine/wiki/Logging)?

**Comment by lukka** [comment]
Closing as without further data it is not possible to proceed with investigation. Feel free to reopen it, or open a new ticket if the problem occurring is similar but not identical, thanks.
