### ISSUE TITLE
Stopped (tty input) vs2017

### ISSUE THREAD

**Issue by khou2020** [Microsoft/VSLinux#129]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
Receive the Stopped (tty input) exception (SIGTTIN) whenever my program try to read from stdin.
It is under "gdb server" mode. It works before on 2015, but happened when I update to 2017. 
The stdout do show in the Linux console, seems the stdin redirection did not success.

* Expected results
Program should read stdin from Linux console as in vs2015

* Actual results (with build output window contents if applicable)
=thread-group-added,id="i1"
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-pc-mingw32 --target=x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Loaded 'shared libraries loaded at this time.'. Cannot find or open the symbol file.
Stopped due to shared library event:
  Inferior loaded /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    /lib/x86_64-linux-gnu/libgcc_s.so.1
    /lib/x86_64-linux-gnu/libc.so.6
    /lib/x86_64-linux-gnu/libm.so.6
    /lib64/ld-linux-x86-64.so.2
Loaded '/usr/lib/x86_64-linux-gnu/libstdc++.so.6'. Cannot find or open the symbol file.
Loaded '/lib/x86_64-linux-gnu/libgcc_s.so.1'. Cannot find or open the symbol file.
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Cannot find or open the symbol file.
Loaded '/lib/x86_64-linux-gnu/libm.so.6'. Cannot find or open the symbol file.
Loaded '/lib64/ld-linux-x86-64.so.2'. Cannot find or open the symbol file.

Program received signal SIGTTIN, Stopped (tty input).
0x00007ffffebeb6b0 in ?? ()

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Visual C++ 2017   00369-60000-00001-AA425
Ubuntu 14.04.5 LTS (Bash in windows 10 WSL)
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
GNU gdbserver (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1

* Steps required to reproduce the error
Debug any program that reads from stdin with vc++ Linux project in gdb server mo
de.
* Required packages and commands to install
N/A

**Comment by stanthomas** [comment]
Just tried this on Debian Jessie. I think the behaviour is different in VS2017 in that the Linux console window that you have open before running the program is not the same as the one displayed while it is running. Same sort of thing happens with Find Results windows etc.

When I opened the Linux console, then ran my program I saw the same as you : "Program received signal SIGINT, Interrupt." in Output/Debug.

When I ran my program, then opened the Linux console it ran as expected. Although the input data I typed was duplicated in the Linux console showing after the program terminated.

**Comment by bingzhangdai** [comment]
same problem

**Comment by paulmaybee** [comment]
Which version of 2017 are you using? If not 15.2 or 15.3 then can you update and retest?

**Comment by stanthomas** [comment]
I've just tried it in VS2017 15.3.0 Preview 2.1 (VCLinux 1.0.7).
There appear to be 2 Linux Console windows depending on the VS mode: one while editing and the other when running in debugger.
If the debugger Linux Console window is not open the program stops waiting for input but does not crash. Opening the debugger Linux Console window reveals the prompt and allows input.
It does not matter whether the editor Linux Console window was open or not.

**Comment by Phi-Li** [comment]
Same issue when I try the example program in [Visual C++ for Linux Development | Visual C++ Team Blog](https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#consolewindow).
I've tried to toggle the Linux Console Windows in edit/debug state as mentioned above but it behaves the same.
- Visual Studio 2017 Version 15.3.2
- Ubuntu 14.04.5 (Bash On Windows)
- gdbserver 7.7.1

**Comment by lukka** [comment]
In _gdbserver_ mode using stdin from debuggee application is working Visual Studio 2017 15.3.3.

For _gdb_ mode (note that it is different than _gdbserver_ mode), the fix will be part of Update 5.

**Comment by bingzhangdai** [comment]
@lukka I indeed use *gdbserver* mode and the VS version is 15.3.3.

However, I still get the exception

> Stopped (tty input) occurred

It is not fixed.

**Comment by lukka** [comment]
@bingzhangdai thanks for notifying us. Could you please share some additional data about your error?
- the project type (Console Application, Makefile Application);
- a screenshot of the Debugging property page;
- source code sample you could reproduce the behavior;

That would allow us to investigate further, thanks

**Comment by progsecu** [comment]
I have the same issue.
Using scanf on VS2017 15.3.3 causes a Stopped (tty input) exception.
![image](https://user-images.githubusercontent.com/17171206/30247530-c4bb5ac2-9651-11e7-8c17-9c4d11267cd3.png)
![image](https://user-images.githubusercontent.com/17171206/30247531-d01c18de-9651-11e7-91c2-62d2d3a04543.png)
(No frame in module)

It works when you run it directly.
![image](https://user-images.githubusercontent.com/17171206/30247538-f03bfd5a-9651-11e7-91a8-27d46de5387e.png)

I created the solution with default linux console application and added only scanf.

**Comment by progsecu** [comment]
Stopped (tty input) vs2017
please help me.

vs2017 community 15.3.3
win10 WSL(Ubuntu 16.04)

use scanf = not working at vs2017
direct run at bash = working

![image](https://user-images.githubusercontent.com/17171206/30248546-bb9f1538-9664-11e7-99cd-156e3480d343.png)
![1](https://user-images.githubusercontent.com/17171206/30248553-cdd58142-9664-11e7-9930-7478f735e636.JPG)

**Comment by bingzhangdai** [comment]
My configuration is the same with @progsecu and the symptom is also the same. The project type is "Visual C++, Cross Platform, Console Application (Linux)". The code is
```cpp
int main(int argc, char* argv[]) {
    printf("hello world");
    int n;
    scanf("%d", &n);
    return 0;
}
```
Then, I get the following exception,
![image](https://user-images.githubusercontent.com/9895061/30256114-de5018f4-96da-11e7-8194-413869c4d7bf.png)
I have already open the `Linux Console` in the `Debug` menu.

It works fine if I comment ```scanf```. And I can run this program in bash in the path ```~/projects/HelloLinuxCpp/bin/x64/Debug/```. So I am confident that the compile work is OK.

**Comment by lukka** [comment]
@khou2020   Please if you could check [VS 15.5 Preview](https://blogs.msdn.microsoft.com/visualstudio/2017/10/11/visual-studio-2017-version-15-5-preview/) just go ahead and let us know. The original issue is fixed when using GDB mode (check in the Configuration Properties which Debugging Mode are you actually using under "Debugging".
