### ISSUE TITLE
Sudo: unable to resolve host

### ISSUE THREAD

**Issue by byzeagle** [Microsoft/VSLinux#130]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
when sudo command is run, system gives "sudo: unable to resolve host {}"
Note: It is easy to fix by altering and adding computer name to /etc/hosts file. However, I think when WSL is installed, it should not cause such configuration problems. 

* Expected results

* Actual results (with build output window contents if applicable)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

* Steps required to reproduce the error
Only run sudo command by itself.

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by itodirel** [comment]
@byzeagle is this causing any problems in the context of the Linux extension, beyond the warning?

**Comment by byzeagle** [comment]
No, just the warning "sudo: unable to resolve host {}" if the computer name is not added to /etc/hosts file after fresh installation.

**Comment by itodirel** [comment]
Please let us know if it is causing other problems. @robotdad is this something we should communicate the WSL team?
