### ISSUE TITLE
openfolder project ignores intelliSenseMode

### ISSUE THREAD

**Issue by dixonqmg** [Microsoft/VSLinux#131]
I have tried to set up openfolder project. affter creating cppproperties.json, it seems to be ignoring intelliSenseMode setting in there. No matter what I set it to, _WIN32 and _MSC_VER are defined, so looks like it's always using default intellisense engine. Other settings in the same file do have an effect (e.g.includePath), and .json doens't have any errors listed when I open it inside the VS. 

Please advise.

**Comment by mlamby** [comment]
I am having the same problem opening a linux project using 'openfolder'. 

If I use the following CppProperty.json settings:

```` json
    "intelliSenseMode": "linux-x86",
    "compilerSwitches": "--std=c++11"
````

Intellisense gives errors parsing headers such as `<tuple>` because `__cplusplus` is equal to `199711L` and keywords such as `noexcept` are not recognised.

**Comment by dixonqmg** [comment]
/std:c++11
You set switches in Microsoft format

**Comment by robotdad** [comment]
We don't have support for Linux in open folder yet. We are working on cmake support which will light up some Linux support for open folder. This work is going to show up in 15.4.
