### ISSUE TITLE
Cannot include third party include file from /usr/include

### ISSUE THREAD

**Issue by lpelorosso** [Microsoft/VSLinux#133]
Hi! I installed netcdf library in my linux box, which copy some include files into /src/include. When trying to include .h file doing: #include <netcdf.h>, I get the following error: cannot open source file "netcdf.h".
Any idea what could be wrong? Thank you!

**Comment by stanthomas** [comment]
Have you put `/src/include` on your include path?

**Comment by lpelorosso** [comment]
I realized it was actually including the file and linking correctly inside the linux box, but Intellisense was reporting the file as missing. Thanks!
