### ISSUE TITLE
Starting remote debugger in WSL ends with error in VS 2017 v. 15.2 26419.1

### ISSUE THREAD

**Issue by mvacha** [Microsoft/VSLinux#135]
* A brief description
I've configured VS and SSH as you say on the blog or in issue #42.
Connecting from other ssh client (puttygen) works, but starting debugger ends with error. :(

* Actual results (with build output window contents if applicable)
Unable to start debugging. Unexpected GDB output from command "-interpreter-exec console "target remote localhost:57420"". Remote connection closed

Shouldn't it be just `-interpreter console...` instead of `-interpreter-exec console`?

The GDB Version is 7.11.1

**Comment by mvacha** [comment]
I've tried working around it by putting gdb function in `.bashrc`, but just got different error: 
```
Unable to start debugging. Unexpected GDB output from command "-interpreter-exec console "target remote localhost:57864"". Remote connection closed
```

```
gdb(){
  if [[ $1 == "-interpreter-exec" ]]; then
        command gdb -interpreter "${@:2}"
  else
        command gdb "$@"
   fi
}
```

**Comment by itodirel** [comment]
@paulmaybee can you take a look?

**Comment by paulmaybee** [comment]
What version of Visual Studio are you running? Can you collect a log? For instructions see https://github.com/Microsoft/MIEngine/wiki/Logging

**Comment by EricGT** [comment]
Had either similar or same [problem](https://github.com/Microsoft/BashOnWindows/issues/2236#issue-237058232). 

In short Windows had needed files from previous build, but on Linux (WSL) all files including executable had been deleted from, thus GDB could not find executable on Linux.

**Comment by robotdad** [comment]
@mvacha are you still running into this?

**Comment by robotdad** [comment]
Closing as there hasn't been activity, please reactivate if still running into this
