### ISSUE TITLE
How to install v1.0.7 ?

### ISSUE THREAD

**Issue by boskars** [Microsoft/VSLinux#139]
I have both VS2015 and VS2017 on my computer.  VS_Linux.exe v1.07 only installs in VS2015 and not in VS2017.

My VS2017 should automatically check for extensions updates but haven't found v1.0.7 yet.

How can I install v1.0.7 into VS2017 ?

**Comment by stanthomas** [comment]
I asked Ion about VS2017. He pointed out that, since VClinux is now part of Visual Studio, updates are delivered in VS service packs (or whatever they're called these days). You can get 1.0.7 now with the  [VS 2017 preview 15.2](https://blogs.msdn.microsoft.com/visualstudio/2017/04/18/visual-studio-2017-preview-15-2/) although it's not clear whether everything in 1.0.7 made it into the preview.

I'm going to wait for 15.2 to go to production.

**Comment by boskars** [comment]
Thank you for your answer, I will also wait for 15.2.

**Comment by boskars** [comment]
I just installed the released version of  VS201715.2 and it did not install 1.0.7!!!  How can I get this version?

**Comment by stanthomas** [comment]
Same here.
I've just installed the VS2017 15.2 (26430.4) update. Help/About reports VCLinux 1.0.6 and I don't see any of the improvements in 1.0.7 (looked at ctrl-F5 and natvis).

Just in case I removed the Linux development with C++ via the Visual Studio Installer, rebooted and then reinstated. Doesn't help.

@itodirel Any suggestions?

**Comment by Vault16Software** [comment]
Anyone solved this yet? I can't even download 1.0.7 from Microsoft website. I'm still on 1.0.6.
I'm on VS 15.2 (26430.6) Release

**Comment by wakerley** [comment]
You can download 107 here

https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.VisualCforLinuxDevelopment

**Comment by Vault16Software** [comment]
I have been trying. All the download button does for me is refresh the page and nothing happens.

**Comment by wakerley** [comment]
I'm using chrome.
I use "Open in a new tab".

Once it refreashed the screen.
I pressed download again an d it worked.
Just did it now

**Comment by wakerley** [comment]
Glad it worked for you.

**Comment by stanthomas** [comment]
@wakerley - the download for 1.0.7 you have linked is for Visual Studio 2015. Are you saying you have been able to get 1.0.7 installed with VS 2017?

**Comment by wakerley** [comment]
On 2017  it comes as part of the install package.

**Comment by wakerley** [comment]
But it didn't work very well. Just basic apps failed to compile. Have to test further

**Comment by stanthomas** [comment]
Just installed the latest VS2017 preview : 15.3 (26510.0). Help/About reports VCLinux 1.0.7. Haven't run it to check the new features yet.
[Visual Studio 2017 Preview](https://www.visualstudio.com/vs/preview/?utm_source=VSIDE-15-3)

My guess is 1.0.7 missed the cut for the 15.2 release and we'll have to wait for 15.3. Seems there's a downside to having VCLinux integrated into Visual Studio.

**Comment by wakerley** [comment]
Yeah, running VS2017 on VM Win10 with VCLinux 1.0.7 as well. Projects that compile with 1.0.7 on VS2015 fail with errors on 2017. And latest features in 1.0.7 on 2015 aren't in 1.0.7 on 2017.

**Comment by stanthomas** [comment]
Finally got around to looking at VS2017 Preview(2), aka 15.3 (26510.0-Preview). [Visual Studio 2017 Preview](https://www.visualstudio.com/vs/preview/?utm_source=VSIDE-15-3)

Help/About reports VClinux 1.0.7 and my projects build and run (Debian Jessie).
Plus:

- Natvis watch window visualisation of standard library collections : list, vector, unique_ptr but not unordered_map. Visualisation available in Watch window and Quick Watch dialog but not from mouse hover over variable (says "Explicit refresh required for visualised expressions").

- Ctrl-F5 to run w/o debugger works.

**Comment by robotdad** [comment]
For VS 2017 you get the workload as part of the installer. 15.2 has v 1.0.6 and 15.3 (currently preview) has v 1.0.7,
For VS 2015 the marketplace/extension gallery you can get 1.0.7.
