### ISSUE TITLE
Check prerequisites exist on Linux machine

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#14]
We get fairly regular reports that can be traced to missing prereqs on the Linux machine. Since we know what they are we should check for them and inform people if anything is missing.

**Comment by robotdad** [comment]
One common prereq we see missing is gdbserver. If gdbserver is missing you'll get a dialog box thrown with no error message. That should be corrected when we address this one, but noting this here as I just saw this come up again.

**Comment by itodirel** [comment]
this is now fixed, and will be available in the next release of the extension
