### ISSUE TITLE
Failure Dialog open When clicked on Remote GDB Debugger

### ISSUE THREAD

**Issue by Ayyappatheegala** [Microsoft/VSLinux#140]
Hi,
I trying to use the linux plugin for VS2015
I have my project on a linux machine and was able to successfully build [I have given the commands for building and specified the directories] 
But, when I am trying to use the Remote GDB Debugger, It is successfully building and after which simply a Failure Dialog is shown. 
There is no clear message of where the error occurred.
Can you help me in solving this issue ?
I have attached the screen shot of the failure dialog for your reference.

![image](https://cloud.githubusercontent.com/assets/13075257/25693496/3ab56cae-30c7-11e7-8b16-9545336d9342.png)

**Comment by Ayyappatheegala** [comment]
Can Some one Help me with this issue ??

**Comment by paulmaybee** [comment]
Which version of the plug-in are you using? If not 1.0.7 (https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.VisualCforLinuxDevelopment) please uninstall your current extension and install this one.

Also, is there anything in the VS output window? Can you include a screenshot of your debugger project settings?

**Comment by robotdad** [comment]
@Ayyappatheegala any update from your side?

**Comment by AvantsGit** [comment]
I also have same problem. It can build successfully, but fail to debug.  Error message asks me to set Remote Build- Outputs. I tried to set the Outputs, but still failed.

**Comment by robotdad** [comment]
@AvantsGit that is not the same issue.. Can you please open a new issue with details about what project type you are using where you experience this problem?

**Comment by robotdad** [comment]
@Ayyappatheegala if this is still an issue please reopen with the details @paulmaybee requested
