### ISSUE TITLE
Debug/Attach to process works only on first attempt

### ISSUE THREAD

**Issue by giuseppepaoletti** [Microsoft/VSLinux#143]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
Debug/Attach to process works only on first attempt

* Expected results
Should work fine on next attempts

* Actual results (with build output window contents if applicable)
After 2nd launch of attach command, there is the following dialog error message:
![image](https://cloud.githubusercontent.com/assets/7680977/26102009/91ee7374-3a33-11e7-9749-9b76ad97d2f4.png)
Looking at running process, there is a gdb process still in execution; after killing it, you can attach the debugger. I've tried to quit the program normally, press stop debugging and detach all options, but gdb remains always in execution.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
VC++ 1.0.7
Linux Lubuntu Trusty 14.04
GDB/gdbserver 7.7.1
CPU Intel Core i7

* Steps required to reproduce the error
Debug/Attach to process
Terminate debugging
Debug/Attach to process again

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by paulmaybee** [comment]
After you finish debugging and you see the gdb process still active on the Linux machine do you also see a process called "shellexec" running on your windows machine? Can you reproduce your error condition (the original case where the gdb does not terminate) and send us a log? See https://github.com/Microsoft/MIEngine/wiki/Logging for logging instructions.

**Comment by robotdad** [comment]
Please reopen if you can collect logs for this error, we're interested in taking a look.
