### ISSUE TITLE
Can't debug on Ubuntu Bash

### ISSUE THREAD

**Issue by Raffa50** [Microsoft/VSLinux#144]
Hello I've installed and configured Ubuntu Bash on Windows 10
I'm using VS17.
I could connect to the Ubuntu Bash but when I run it I can't see any output (no window for the linux console output)

and in the output windows I get:
```
Stopped due to shared library event:
  Inferior loaded /lib/x86_64-linux-gnu/libc.so.6
    /lib64/ld-linux-x86-64.so.2
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Cannot find or open the symbol file.
Loaded '/lib64/ld-linux-x86-64.so.2'. Cannot find or open the symbol file.
```

**Comment by stanthomas** [comment]
Do either of these shed any light on your issue? #129 , #119

**Comment by itodirel** [comment]
@paulmaybee any idea?

**Comment by itodirel** [comment]
@Raffa50 can you share your Ubuntu version?

**Comment by lukka** [comment]
Please reopen if you are still experiencing the issue on the most recent version of VS, thanks.
