### ISSUE TITLE
SSH via gateway support 

### ISSUE THREAD

**Issue by npryntsova** [Microsoft/VSLinux#145]
Hi, can you please expand you ssh support to allow using it with gateways or allow to plug custom ssh tool into studio. 
Dev linux machines may be remote in different network and it makes current ssh connection unusable for me. Any ideas on workaround are appreciated.

**Comment by AlexanderViand** [comment]
Yes, this would be a greatly appreciated feature. I currently use an ssh tunnel for this but it'd be nicer to have this integrated into the connection manager directly.

**Comment by itodirel** [comment]
As mentioned by Alexander, you can create a tunnel yourself and connect the two networks, this is a suggestion that I think we are not planning on getting to soon.

**Comment by robotdad** [comment]
I'm removing the enhancement label as we're not going to do anything for this. I will look at documenting how to do this.
