### ISSUE TITLE
External dependencies aren't added when compiling on remote server

### ISSUE THREAD

**Issue by monofur** [Microsoft/VSLinux#146]
When compiling on remote server, external dependencies aren't added, thus causing the build to fail.

When including dependencies normally using project properties (dependency directories), I expected the compiler to upload the dependencies with the main.cpp file to build it.

When compiling, the main.cpp gets uploaded, but the dependencies of which I require for the project to build don't get added, thus causing the build to fail because dependencies aren't being added.

Visual Studio 2017, Ubuntu 16.04 LTS, latest g++ available in Ubuntu's repositories, x64 architecture.

Add the dependencies by doing:

- Project -> [Project Name] Properties
- Click the VC++ Directories item in the drop-down already shown
- Add Include and Library directories, click Apply and OK
- Get a server to build it on, after writing the main.cpp to include the dependencies (I use Ubuntu 16.04, also note that it is able to find the dependencies in VS2017, which leads one to believe it will compile)
- The build will process, then fail saying it can't find the dependencies needed to build (which are the ones we included).

I just use g++ with sudo apt install g++

**Comment by itodirel** [comment]
we don't currently upload dependencies, we expect to find them on the remote Linux system, and we expect them to be expressed in terms of remote paths

**Comment by robotdad** [comment]
Please let us know if @itodirel reply didn't answer your question
