### ISSUE TITLE
Step out didn't work

### ISSUE THREAD

**Issue by NeitrinoK** [Microsoft/VSLinux#148]
* A brief description
Step out from function didn't work.
* Expected results
Step out work
* Actual results (with build output window contents if applicable)
Gdb stepped out, but studio think that process is running.
* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

* Steps required to reproduce the error
`shellexec 1.0
Copyright (C) 2016 Microsoft Corporation. All rights reserved.
BusyBox v1.20.2 (2017-05-15 17:34:35 CEST) multi-call binary.
Copyright(C) 1998-2008 Erik Andersen, Rob Landley
Denys Vlasenko and others. Licensed under GPLv2.
See source distribution for full notice.
# gdb --interpreter=mi
=thread-group-added,id="i1"
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
-gdb-set target-async on
-enable-pretty-printing
-gdb-set solib-search-path /bin:
-gdb-set stop-on-solib-events 1
-environment-cd /
-file-exec-and-symbols /bin/product
-break-insert main
-break-insert -f control_impl.cpp:446
`-exec-run``
-exec-finish
=thread-selected,id="91"
[New Thread 0x7fffb9f5a700 (LWP 2700)]
[New Thread 0x7fffba75b700 (LWP 2699)]
[New Thread 0x7fffbaf5c700 (LWP 2698)]
[New Thread 0x7fffbcf60700 (LWP 2697)]
[New Thread 0x7fffb9759700 (LWP 2701)]
[New Thread 0x7fffb8f58700 (LWP 2702)]
[New Thread 0x7fffb8757700 (LWP 2703)]
[Thread 0x7fffb9f5a700 (LWP 2700) exited]
[New Thread 0x7fffb9f5a700 (LWP 2704)]
[Thread 0x7fffb9f5a700 (LWP 2704) exited]
[New Thread 0x7fffb9f5a700 (LWP 2705)]
[Thread 0x7fffb9f5a700 (LWP 2705) exited]
[New Thread 0x7fffb9f5a700 (LWP 2706)]
[Thread 0x7fffb9f5a700 (LWP 2706) exited]
[New Thread 0x7fffb9f5a700 (LWP 2707)]
[Thread 0x7fffb9f5a700 (LWP 2707) exited]
[0m[1;32m2017-05-31 03:03:09:233 140737240954624 I00000000: -- Server started --
[0m=thread-created,id="103",group-id="i1"
[New Thread 0x7fffb9f5a700 (LWP 2708)]
[Thread 0x7fffb9f5a700 (LWP 2708) exited]
[Thread 0x7ffff140f700 (LWP 2557) exited]
[New Thread 0x7fffb9f5a700 (LWP 2709)]
[New Thread 0x7fffb9f5a700 (LWP 2710)]
[Thread 0x7fffb9f5a700 (LWP 2709) exited]
[Thread 0x7fffb9f5a700 (LWP 2710) exited]
[New Thread 0x7fffb9f5a700 (LWP 2711)]
[Thread 0x7fffb9f5a700 (LWP 2711) exited]
[New Thread 0x7fffb9f5a700 (LWP 2712)]
[Thread 0x7fffb9f5a700 (LWP 2712) exited]
[New Thread 0x7fffb9f5a700 (LWP 2713)]
[Thread 0x7fffb9f5a700 (LWP 2713) exited]
[0m[0m~"[Thread 0x7fffb9f5a700 (LWP 2714) exited]\n"
[0m[0m*stopped,reason="function-finished",frame={addr="0x00007fffe84757fb",func="Binding::Detail::RoutineImpl<Features::EsxAgent::Control, Common::Error (Features::EsxAgent::Control::*)() const, void ()>::RunMethod()",args=[{name="this",value="0x35d6e80"}],file="k:\\main\\enterprise\\common\\ipc/routine_impl_0.h",fullname="k:/main/enterprise/marshalling/xidl_server/k:\\main\\enterprise\\common\\ipc/routine_impl_0.h",line="41"},gdb-result-var="$1",return-value="<incomplete type>",thread-id="74",stopped-threads="all",core="0"
-exec-interrupt

**Comment by NeitrinoK** [comment]
Ha-ha, always disable output of program by tty /dev/null in Addition debugger command

**Comment by robotdad** [comment]
I missed your remark, closing this out. Please reopen if I misinterpreted that there isn't a problem.
