### ISSUE TITLE
Debug source files path mapping support

### ISSUE THREAD

**Issue by super-kevin** [Microsoft/VSLinux#150]
* A brief description
When step into some source files that not in the solution, VS Linux said it cannot find '/my/src/on/linux/machine.c'. Yes, we are on Windows, and VS Linux will not find a file whose path starts with slash.
I have that code on Windows side. We need Path Mapping support like this: http://visualgdb.com/documentation/pathmapping
to map '/my/src/on/linux/machine.c' to 'D:\my\src\on\windows\machine.c'.

BTW, Debug Source Files (https://msdn.microsoft.com/en-us/library/hdks6de6.aspx) not working on VS Linux.

* Expected results
Debugger can find the source file I stepped into.

* Actual results (with build output window contents if applicable)
Debugger cannot find the source file and display the No Source Loaded or No Symbols Loaded pages.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
VS 2017 15.2 (26430.12); Debian 8.8; GNU gdb (Debian 7.11.1-2~bpo8+1) 7.11.1; x64.
It is a normal Linux install in a virtual machine.

* Steps required to reproduce the error
Make sure you have source code and debug symbol installed for glibc.
Debug a "hello world" project on Linux.
Step into printf().
I take glibc and printf() for example to make it simple. The same problem occurs when you step into a function in a (not stripped) shared object.

* Required packages and commands to install
Make sure you step into a not stripped library, or you have debug symbol for it on Linux side. Or the debugger will not find the source path.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by paulmaybee** [comment]
The "path mapping" support you request is in VS2017 version 15.3. You can find a preview of this release at https://www.visualstudio.com/vs/preview/
See the new project property "Properties->Debugging->Additional Source File Path Map"

**Comment by robotdad** [comment]
15.3 has been released now. Please let us know if this isn't working for you.
