### ISSUE TITLE
[msbuild] remote target issues

### ISSUE THREAD

**Issue by somnium-labs** [Microsoft/VSLinux#151]
The build in the visual studio IDE was successful.
However, building with the msbuild command line failed.

msbuild "C:\work\myproj.vcxproj" /p:VisualStudioVersion=14.0;Platform=x64;Configuration=Release /t:Rebuild

* Actual results (with build output window contents if applicable)
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.targets(121,6): error : Could not find the credentials for remote machine or device 'x.x.x.x (username=myaccount, port=22, authentication=Password)'. Please select a different remote machine target. [C:\work\myproj.vcxproj]

How can I build from the command line like msbuild or devenv?

**Comment by lukka** [comment]
@acepm83 it is likely you are using msbuild of a Visual Studio instance where you do not have the connection entry for your remote machine. Could you please check?

**Comment by itodirel** [comment]
I verified that this currently works and it should be fixed, please let us know if you still have issues
