### ISSUE TITLE
Python pretty printer issue from 1.0.6 to 1.0.7

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#152]
Grabbing a report from #4 by @pootle73 and tagging @paulmaybee 

I tried the -enable-pretty-printing above with version 1.06 and it was working for me. I have now installed 1.07 and when I try to launch the debugger I see this:

![image](https://cloud.githubusercontent.com/assets/24373831/26405714/75b024c8-4096-11e7-900e-e0c0ef532031.png)

This is how I have the debugging properties set, which worked fine before version 1.07:

![image](https://cloud.githubusercontent.com/assets/24373831/26405776/a0cdb850-4096-11e7-8cca-e52af7ff0363.png)

**Comment by paulmaybee** [comment]
Is it possible that after switching to 1.0.7 the build is dropping the .out file in a different location? Have you looked in ~/dev/sentinel/test/CMessageToFile/ on the remote machine to see if "testmtof" is there?

**Comment by pootle73** [comment]
Thanks for your response. I have got debugging working again since I reported this issue. Unfortunately I can't remember specifically what I did to overcome this issue, but I'm happy for it to be closed.

**Comment by robotdad** [comment]
Thanks @pootle73
