### ISSUE TITLE
Pre Link Arguments in Visual Studio 2017 for linux compilation

### ISSUE THREAD

**Issue by imazahar** [Microsoft/VSLinux#156]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* How to set pre-link-args in visual studio  2017 for Linux compilation.

* Linux compilation should succeed because I am using  C++11 Language Standard and it's API and GCC compiler of Oracle Enterprise Linux.

* Actual results (with build output window contents if applicable)

* I am using Oracle Enterprise Linux.

* I have written code to create thread using c++11 thread API. But on compiling on remote linux, I am getting error:

Test Program:
#include <thread>
#include <iostream>

using namespace std;

void thread_function() { }

class test {
public:
	int a;
	void testFunc() {

	}
};

class ThreadTest {
public:
	void CreateThread() {
				thread t(&thread_function);	
	}
};

Error:

1>/usr/bin/ld : error : relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
1>C:\Users\MyName\Documents\Visual Studio 2017\Projects\AllPlatforms\LinuxProject\obj\x64\Release\Source.o : error : Bad value
1>collect2 : error : ld returned 1 exit status
1>Done building project "LinuxProject.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

It seems to me that I need to set -no-pie in pre-link-args . So Question is 1) How could I set pre-link-args in VS2017 for linux compilation 2) Is there any other solution for the problem ?

* Required packages and commands to install

**Comment by stanthomas** [comment]
Have you tried doing what it says and compiling with -fPIC set?

**Comment by imazahar** [comment]
Yes that is also a solution but how to set -fPIC in VS2017.

**Comment by stanthomas** [comment]
See #49.

**Comment by imazahar** [comment]
Thanks much, it worked.
