### ISSUE TITLE
VS2017(15.2) hangs forever while debugging a linux process over ssh after an idle period

### ISSUE THREAD

**Issue by braindeaddeveloper** [Microsoft/VSLinux#158]
* A brief description:
VS2017(15.2) hangs forever while debugging a linux process over ssh after an idle period.  This was also the case with 15 and 15.1.

* Expected results
Should not hang forever ... should be able to return to an idle session.

* Actual results (with build output window contents if applicable)
After an idle period in an active debugging sessions (i.e. no keyboard input) VS just hangs when debugging via gdb/gdbserver over shh to Linux.  It never returns and then needs to be terminated sometimes damaging the project file.
I believe this is related to the fact that the remote gdb process has terminated after a period of no keyboard input.  This can be determined by running : 
> ps -ef | grep gdb | grep -v grep 
which return nothing once hung but returns :
user  32645 30568  5 15:49 pts/79   00:00:00 gdb --interpreter=mi
when running an active session

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware:
Hardware:
# Physical:
#       Memory  : 96730
#       CPU's   : 24
#       Vendor  : HP
#       Model   : ProLiant DL380 G7
Remote system: Redhat 6.5
Compiler: gcc 4.8.3
GDB: gdb/server 7.11/7.11.1/7.12/8

* Steps required to reproduce the error:
Create a simple Linux console app.  Build it,
Start up a remote debugging session from VS2017 over ssh to your Linux server.
Step over a line of code.
Leave the session idle for 10 mins (I'm not exactly sure what the timeout period is ... gdb's is 2 seconds but that's too short)

* Required packages and commands to install
Nothing other than the base dependencies for VS2017 and Linux support.

**Comment by boskars** [comment]
I have reported same issue to Microsoft.

**Comment by braindeaddeveloper** [comment]
I have to add this is getting REALLY intrusive now ... I delayed just long enough to take a 5 min phone call during a remote debugging session (forgetting to terminate the session) and now VS2017 15.2 is completely dead with no way to bring it back so now I have to terminate the process ... this is REALLY BAD.

**Comment by dgrunwald** [comment]
Is there a NAT between your computer and the Linux server?
I've had NATs terminate SSH connections that were idle for 5 minutes. As a workaround, enable SSH keep-alive (in Putty: Connection > Seconds between keepalives).

**Comment by braindeaddeveloper** [comment]
Hi dgrunwald ... there's no NAT and I didn't realise VSLinux uses putty ? How does putty come into the mix ?
thanks

**Comment by dgrunwald** [comment]
Putty is just the SSH client I'm typically using.
You [used to be able to use the SSH client of your choice](https://blogs.msdn.microsoft.com/vcblog/2015/11/18/announcing-the-vs-gdb-debugger-extension/); I'm not sure when that option disappeared or how to configure the built-in SSH client it's now using.

**Comment by itodirel** [comment]
I believe we recently fixed this problem, adding Paul @paulmaybee for instructions on how to set the logging for debugging. To make sure this is fixed we will need the MIEngine log, Paul can tell you how to get it.

Regarding Putty, I can confirm we are not using it internally.

**Comment by boskars** [comment]
Is there a way to get this fix for a test.  I have been waiting for this fix for many months...

**Comment by paulmaybee** [comment]
See https://github.com/Microsoft/MIEngine/wiki/Logging for MIEngine logging instructions.

**Comment by boskars** [comment]
[db_log.txt](https://github.com/Microsoft/VSLinux/files/1230289/db_log.txt)
I have attached the log that I sent to Marc in start of July.  Is it possible for me to test the fix?

**Comment by lukka** [comment]
Visual Studio does not hang anymore when the ssh debugging session is terminated by the remote party.
Fix will be available in Visual Studio 15 Update 5.

**Comment by boskars** [comment]
Still hangs in 15.4 in preview 2 :-(, when will 15.5 be available?

**Comment by sraboy** [comment]
This is still an issue for me in VS2017 15.5.6 with WSL, even after adjusting `ClientAliveInterval` mentioned in #208. I'm just building a standard Linux project for x64 and VS hangs; I have to kill GDB via task manager (killing it via bash doesn't seem to help) to get it responding again. Attempting to stop, pause or restart the debugging session results in some generic error message recommending I save my work and close VS.
