### ISSUE TITLE
If a VSLinux project files are on a remote and copy files is switched off then a clean build removes ALL files including the project and solution

### ISSUE THREAD

**Issue by braindeaddeveloper** [Microsoft/VSLinux#164]
If a VSLinux project files are on a remote file location and copy files is switched off (in situ builds) then a clean build removes ALL files including the project and solution files.  Actually it deleted the top level folder and not just those files specified in :

Project->Properties->General->Extensions to Delete on Clean

I don't expect a clean to ever delete its own solution project source and config files from underneath it including the folder thus invalidation the folder.  If it wasn't for the .snapshots on Linux this would be fatal as ALL files would disappear.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Linux Redhat 6.5, VS2017 15.2 x64 bit builds gcc 4.8.3 gdb all versions ... I'm not sure this is relevant stuff

* Steps required to reproduce the error
Create a VSLinux project with the files on a remote and project files in situ no copying to a remote location i.e. in situ builds.  Run a clean or rebuild.

**Comment by itodirel** [comment]
sorry about that, we recently fixed that bug, the fix will be available in Visual Studio 15.4 Preview 2

**Comment by itodirel** [comment]
Closing this and using #123 for tracking
