### ISSUE TITLE
iOS Project Binaries location

### ISSUE THREAD

**Issue by imazahar** [Microsoft/VSLinux#165]
* Where can I find binaries of my iOS project ?

* In case of linux project I can find it's binaries in respective folder which is release folder in my case. But I am not able to find the binaries of iOS project in iOS project release folder after doing iOS project compilation. It's binaries are only available on Mac machine. I followed : https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios

* iOS Project binaries are only available on Mac machine but are not copied on my local machine where VS2017 is installed.

* VC2017, I followed everything mentioned @  https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios and i was successful in building iOS project

* Create simple iOS project and compile and build using steps @  https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios

I tried to find out place where i can post query specifically for VS2017 iOS issues but could not find it, thats why I am posting it here.

Thanks and Regards,
-AZ

**Comment by itodirel** [comment]
The iOS MDD experience is not related to the Visual C++ for Linux development feature. I'm going to forward this issue to the iOS tools team and close this specific one.

Note: you could technically use the Linux tooling to do Mac builds. For example you could have a Makefile invoking your iOS build on the Mac. If you need information on how to set this up, please write us an email, or myself at itodirel at microsoft dot com
