### ISSUE TITLE
compile SINGLE source file probem !!

### ISSUE THREAD

**Issue by ldcsaa** [Microsoft/VSLinux#167]
1. When I use ’Build‘ (F7) button to build project, that's OK.
2. But  when I use 'Compile' (Ctrl+F7) button to compile a single source file, then output error, means compiler not fount. like this:

>  Validating architecture
1>  Copying sources remotely to '192.168.56.13'
1>  Starting remote build
1>  Compiling sources:
1>  FuncHelper.cpp
1>  bash: -c: command not found
1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.targets(248,5): error : Could not find the specified C/C++ compiler ''. Please make sure that a default C/C++ compiler is installed on the remote system '-50468727;192.168.56.13 (username=, port=22, authentication=Password)'. You can install a compiler using your system's package manager. If overriding the default compilers, please check that the compiler is installed in the specified path.

**Comment by stanthomas** [comment]
See #5 and #160

**Comment by itodirel** [comment]
we don't currently support single file compile, I'm going to tag it with bug for fixing that

**Comment by itodirel** [comment]
this is a relatively easy fix, I'm going to see if we can make a fix shortly

**Comment by itodirel** [comment]
@ldcsaa @stanthomas @braindeaddeveloper hey guys, this is now fixed, and the fix will be available in Visual Studio 2017 Preview 2, internally called 15.4 Preview 2

**Comment by stanthomas** [comment]
Confirm that compilation of single file only is working in VS 15.4 preview 2.0 / VCLinux 1.0.8.

**Comment by itodirel** [comment]
Excellent, thank you for confirming @stanthomas, any objections against closing this issue?

**Comment by itodirel** [comment]
closing this issue, as confirmed fixed from Stan
