### ISSUE TITLE
Attach to process on remote Linux machine

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#17]
Often requested, we should do this.

**Comment by robotdad** [comment]
OK, you need to be on VS 2015 Update 3 for this to work. You also need [plink from Putty](http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html) and to identify the process you need to attach to on your Linux machine to use that id here.

Create an xml file as below for your scenario:
`
<PipeLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
  PipePath="d:\tools\plink.exe" 
  PipeArguments="-i d:\keys\keys\puttygen\puttygen-ubu.ppk pi@jinx -batch -t gdb --interpreter=mi"
  ExePath="/home/pi/projects/ConsoleApplication8/bin/ARM/Debug/ConsoleApplication8.out" 
  ExeArguments=""
  WorkingDirectory="/home/pi/projects/ConsoleApplication8/bin/ARM/Debug" 
  AdditionalSOLibSearchPath="" 
  TargetArchitecture="arm"
  ProcessId="11361">
</PipeLaunchOptions>
`
Use the VS Command window and run:
`Debug.MIDebugLaunch /Executable:foo /OptionsFile:"path\to\your\attach.xml"`

One known issue here is that attaching this way does not connect to our linux console window.

**Comment by Performer777** [comment]
I would suggest to implement it jointly with feature [#16](https://github.com/Microsoft/VSLinux/issues/16)  and to use it for configuring inclusions and exclusions from attached processes.
