### ISSUE TITLE
Please support "-L" and "-I" options

### ISSUE THREAD

**Issue by ldcsaa** [Microsoft/VSLinux#172]
I not found "-L" and "-I" options setting in the project properties page.
so I add them to the "Additional Options" text box in "Command Line" page of "C/C++" & "Linker" menu, like this:
    `-I/dependency/include -L/dependency/lib `
But the "-L" option does not work currectly, because the "-L" option is added to the END of command line.
For example: I want to use my self's static lib /dependency/lib/libjemalloc.a in my project. but the IDE generate command line like this:
    `g++ main.cpp -o main -ljemalloc -L/dependency/lib/`
    `# try to find system libjemalloc.so ...`
So, the "-L" option does NOT work actually, and the needed command line is:
    `g++ main.cpp -L/dependency/lib/ -o main -ljemalloc`
    `# "-L" option must before "-o"`

This is a widespread demand, Please check ~

**Comment by stanthomas** [comment]
Ion describes the various ways to specify libraries here: #153

**Comment by itodirel** [comment]
Thank you much @stanthomas, pasting the reply from  #153

Can you get me the command line that works, and the one that doesn't from the build ouput, and we can help you configure it correctly.

You have the following options here:

Linker - General - Additional Library Directories - this adds paths with -L to the linker command line near the beginning of the command line.
 Linker - Input - Library Dependencies - this adds the file names with -l at the very end of the linker command line
 Linker - Input - Additional Dependencies - this adds the entries verbatim after the object files, and before the Linker - Input - Library Dependencies
 Linker - Command Line - Additional Options - this adds the entries verbatim before the object files in the linker command line

**Comment by ldcsaa** [comment]
I had tried your suggest, but did not work well ...

the generated cmd line:

`-o"D:\MyWork\Linux\MyWork\TestLinux\bin\x64\Debug\TestLinux.out" "3600000" -Wl,-z,relro -Wl,-z,noexecstack -Wl,--no-undefined "g++" -l"rt" -l"pthread" -l"jemalloc" -Wl,-L"../HP-Socket/dependent/lib" -Wl,-z,now `



and the link result:

```
[bruce@bruce-7 Debug]$ ldd TestLinux.out 
	linux-vdso.so.1 =>  (0x00007ffc75107000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f46ea619000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f46ea3fd000)
	libjemalloc.so.2 => /usr/local/lib/libjemalloc.so.2 (0x00007f46ea19d000)
	libstdc++.so.6 => /usr/local/gcc/lib64/libstdc++.so.6 (0x00007f46e9e22000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f46e9b20000)
	libgcc_s.so.1 => /usr/local/gcc/lib64/libgcc_s.so.1 (0x00007f46e9908000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f46e9547000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f46ea84a000)
```

**Comment by itodirel** [comment]
Could you gives us the command line that's supposed to be passed to the compiler?

**Comment by itodirel** [comment]
Hi, I'm closing this as no repro, but, that does not mean we won't fix this if we get a repro. We're just closing it due to inactivity for tracking purposes, if this is still a problem, please just let us know and we'll reactivate the issue and investigate.
