### ISSUE TITLE
Could the VSLinux plugin provides "Generate Makefile" feature

### ISSUE THREAD

**Issue by ldcsaa** [Microsoft/VSLinux#173]
"Generate Makefile" automaticly, is very helpful, and reduce workload greatly to developers.

**Comment by robotdad** [comment]
Can I turn this around? You can use makefiles directly without a vcxproj through open folder, see [this post](https://blogs.msdn.microsoft.com/vcblog/2017/10/23/remote-tasks-in-visual-studio/) for how to do that.

With that capability do we need to do this from a vcxproj?

**Comment by itodirel** [comment]
suggestion copied to backlog
