### ISSUE TITLE
Including <random> causes 617+ IntelliSense errors

### ISSUE THREAD

**Issue by bobroberts177** [microsoft/VSLinux#174]
* A brief description

Including `<random>` causes 617+ IntelliSense errors

* Expected results

It should cause no IntelliSense errors.

* Actual results (with build output window contents if applicable)

Errors are of the form:

    Error (active)	E2778	builtin function is not available because vector types are not supported	Project1	c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include\ammintrin.h	42	
    ...
    Error (active)	E2778	builtin function is not available because vector types are not supported	Project1	c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include\avx2intrin.h	58	
    ...
    Error (active)	E2778	builtin function is not available because vector types are not supported	Project1	c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include\xopintrin.h	323	
    etc.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Version info:

    Visual Studio Microsoft Visual Studio Community 2017 
    Version 15.3.2
    VisualStudio.15.Release/15.3.2+26730.10
    Microsoft .NET Framework
    Version 4.7.02046
    
    Installed Version: Community
    
    Visual C++ 2017   00369-60000-00001-AA179
    Microsoft Visual C++ 2017
    
    Visual C++ for Linux Development   1.0.7
    Visual C++ for Linux Development

It should be noted this did not happen in the previous version.  This only appeared when I upgraded Visual Studio.  Also, I am including my own Linux header files so I don't even want Visual Studio's but I can't seem to turn them off (I unchecked "Inherit from parent or project defaults" in Include Search Path but it had no effect).

* Steps required to reproduce the error

Create a Linux project and add the line:

    #include <random>

* Required packages and commands to install

Nothing except the obvious I believe.

**Comment by prgtrdr** [comment]
I am seeing the same thing for ammintrin.h, avx512fintrin.h, and avxintrin.h, emmintrin.h, and xopintrin.h.  The program compiles and builds fine on Linux, the problem is only with Intellisense on my Windows platform.

**Comment by SamuelHenderson** [comment]
I too am seeing this problem with Visual C++ For Linux 1.0.8 and Visual Studio 2017 Enterprise 15.4.1.

I see the same errors if I try to include <SDL2/SDL.h> (in Visual Studio 2015 with VC++ for Linux I never saw these issues).

**Comment by cdeisler** [comment]
Simple program has same errors:

![image](https://user-images.githubusercontent.com/2393923/32639757-528b489c-c593-11e7-8493-673f36b29041.png)

`#include <unistd.h>`
`#include <raspicam/raspicam.h>`
`#include <raspicam/raspicam_cv.h>`
```int main(void)
{
	wiringPiSetupSys();

	pinMode(LED, OUTPUT);

	raspicam::RaspiCam_Cv Camera;

	if (!Camera.open()) {  return -1; }

	mySleep(3);

	while (true)
	{
		digitalWrite(LED, HIGH);  // On
		delay(500); // ms
		digitalWrite(LED, LOW);	  // Off
		delay(500);
	}
	return 0;
}

**Comment by guido1993** [comment]
Came here because I am currently experiencing the same error, latest VS2017 version.

**Comment by shinkounen** [comment]
Microsoft Visual Studio Community 2017 
Version 15.5.6

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Same:
<img width="375" alt="e2778" src="https://user-images.githubusercontent.com/35449127/36141090-e1bbedde-10e6-11e8-9622-a83ff3776a2d.PNG">

**Comment by JMesser81** [comment]
I'm having the same problem when building a DLL file using CLang / C2 as the front-end compiler. I'm using Visual Studio Professional 2017

**Comment by mbaugus** [comment]
I'm also am getting the exact same 600+ errors in Intellisense when I try to include Cppconnector header files into the project.  It compiles fine on Linux machine though.

**Comment by eboardman** [comment]
I will second that.  Any answers?

**Comment by itodirel** [comment]
we're currently working on Remote Headers Copy, for IntelliSense and then fixing errors like those

**Comment by rodrigo2019** [comment]
I got same error as well
opencv 3.4.0 for android

**Comment by haoyixin** [comment]
```
Microsoft Visual Studio Enterprise 2017 
Version 15.6.4
VisualStudio.15.Release/15.6.4+27428.2015
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual C++ 2017   00369-90000-00000-AA826
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

GitExtensions   1.0
Git Extensions is a graphical user interface for Git that allows you to control Git without using the command-line

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VisualKernel   3.0
Provides support for developing and debugging Linux Kernel.

VsVim   2.5.0.0
VsVim is a Vim emulator for Visual Studio
```
+1

**Comment by wcroughan** [comment]
+1

Microsoft Visual Studio Community 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA193
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.7.18116.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.7.18116.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.7.18116.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.7.18116.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.7.18116.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

**Comment by syalanurag1991** [comment]
Hi guys, I am getting a similar issue here. Was trying to build an Android-based dll for a Unity Project. The project uses OpenCV libraries. @rodrigo2019, were you able to solve this?

**Comment by rodrigo2019** [comment]
@syalanurag1991  I started to use android studio and it worked fine

**Comment by syalanurag1991** [comment]
@rodrigo2019 I am really inexperienced in Android Studio. Do you have like a tutorial for this exact thing?

One thing that I noticed was, a precompiled version of OpenCV for Android works fine. But I need bgsegm from the opencv contrib repo. So I have no choice but to compile it myself. 

I am building a dynamic shared library for Android-based Unity applications that would use opencv natively.

**Comment by itodirel** [comment]
Hi, we are aware of this bug and we are planning a fix for it soon

**Comment by JrIndie** [comment]
Hello.  I am getting this error too.  

MVSC2017 - 15.9.8
ubuntu 18.04

gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by itodirel** [comment]
@benmcmorran can you take a look?

**Comment by BorisovichAndrey** [comment]
Reproduced and facepalmed.
Eagerly waiting for the fix...

**Comment by itodirel** [comment]
Hi, this issue has been addressed since

**Comment by itodirel** [comment]
For any other issues than the original posted here, please open separate issues.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
