### ISSUE TITLE
Copying of files fails in 15.4 preview 1

### ISSUE THREAD

**Issue by boskars** [Microsoft/VSLinux#175]
I have just installed 15.4 preview 1 and all my projects fails during copying of files:

1>  Copying file 'C:\Users\xxxxxxx' to '/home/root/projects/xxxxxxx'
1>  Copying file 'C:\Users\xxxxxxx' to '/home/root/projects/xxxxxxx'
1>  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(87,5): error : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
1>Done building target "_CopySources" in project "xxxxxxxx.vcxproj" -- FAILED.
1>
1>Done building project "xxxxxxxxx.vcxproj" -- FAILED.

Version 15.3.1 does not have this issue.

**Comment by lukka** [comment]
@boskars Could you please check the length of the local file path (including file name)? If you move your project files to c:\temp\ directory (hence having a shorter path) does it help?

**Comment by boskars** [comment]
@lukka It helps moving it to c:\tmp folder.  The deepest path names are appr 60-70 chars using this location.  So it is far from 248 chars.  Thanks for your suggestion.
