### ISSUE TITLE
Output directory errors

### ISSUE THREAD

**Issue by samsinsane** [Microsoft/VSLinux#176]
* A brief description
Changing the output directory to anything (and deleting the default folder) will result in an error.

* Expected results
Changing the output directory should work.

* Actual results (with build output window contents if applicable)
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Common.targets(54,5): error : Could not find a part of the path 'c:\Users\{username}\documents\visual studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\bin\x64\Debug\ConsoleApplication1.out.recipe'.`

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
VS2017, 15.3.0, VSLinux 1.0.7

* Steps required to reproduce the error
1. Create project from VSLinux Console Application template
2. Change the output directory to `bin\`
3. Delete the existing `bin` folder (Why doesn't cleaning kill this? or the intermediate folder?)
4. Attempt to build
5. Experience error

Step 3 is very important, the files inside are *only* regenerated if the output directory is the default directory. This used to work fine with VS2015, I don't recall which version of VSLinux but I think it was 1.0.7 too.

**Comment by yuehuang010** [comment]
Hi, does the issue still repro after a Rebuild?  @lukka

**Comment by samsinsane** [comment]
> does the issue still repro after a Rebuild?

Yes.

I was able to test this with VS2015 with VSLinux 1.0.7, it works fine. It doesn't appear to generate the `.recipe` files at all and has no issues connecting and building the projects.

**Comment by samsinsane** [comment]
@yuehuang010 @lukka just wanted to follow up and see if there is anything else I can do to assist with this issue?

**Comment by samsinsane** [comment]
This is still occurring with VS2017 15.4.3 with VSLinux 1.0.8.

This is kind of a blocker for me, and since there doesn't seem to be any movement on this, I spent a few minutes comparing the VSLinux and Android extensions. Fixing this appears to be as simple as editing the `Linux.Common.props` file and adding `<ProjectRecipeFile>$([System.IO.Path]::Combine($(ProjectDir), $(OutDir)$(TargetName)$(TargetExt).recipe))</ProjectRecipeFile>` to the first `<PropertyGroup>`.

The `Combine` doesn't appear to make any difference, `bin\`, `$(ProjectDir)bin\`, `C:\bin\` all output to the expected locations, the Android extension doesn't have this but I've also encountered issues with relative paths in that extension.

**Comment by yuehuang010** [comment]
Hi Sam.  I have address this issue in Preview branch > 15.2.  Could you please give that a try?

The issue is that <ProjectRecipeFile> line should be moved to Linux.Common.targets since $(OutDir) isn't defined at the time of .props import.

**Comment by samsinsane** [comment]
@yuehuang010 VS2017 15.5.0 Preview 3.0 has the issue resolved, thank you for that!

I haven't been paying attention to the release cycle for VS2017, are you able to provide a rough ETA on when this will be available in the official release?

**Comment by samsinsane** [comment]
Just installed and tested with 15.5.1, everything looks good. Thanks!
