### ISSUE TITLE
Authentication failure but Putty connects

### ISSUE THREAD

**Issue by zdenko-s** [Microsoft/VSLinux#177]
Hi,
I am using VS2017 15.1(26403.7). I have OpenSuse Enterprise server. Firewall is off and SSH server runs. I am able to connect using Putty.
When I try to connect using **Linux connection manager** I get error "Authentication failure. Please make sure user name and password are correct". This text is shown when I hoover with mouse over user name or password text boxes (which have red rectangle). It takes less than a second to report authentication problem after pressing connect button.
I tried to write password to notepad and copy/paste it. No difference.
I tried with IP address a dns name (assigned by my ADSL router).
What could be wrong?

BR
Zdenko

**Comment by robotdad** [comment]
What version of OpenSUSE Enterprise are you using? Is sftp installed on the target machine?

**Comment by zdenko-s** [comment]
Hi,
It is openSuse 42.3.
I configured ssh to use prvate key authentication and specified private key in Linux connection manager, everything worked fine. Compiling, debugging. It means dependencies are there.
Could it be that some "flag" of ssh authentication protocol (or whatever) is not implemented by MS ssh password authentication?

**Comment by itodirel** [comment]
Are you using password authentication or private key authentication? What bitness and architecture is your OS? x64, ARM etc

**Comment by zdenko-s** [comment]
Hi,
It works with private key authentication, it did not work with password authentication. Password authentication works from Putty (and of course, PK authentication).
It is simple "Hello World", x64. I am trying to connect to openSUSE 42.3

**Comment by itodirel** [comment]
thanks for that information, I'm going to try it in openSuse and see if I can repro

**Comment by itodirel** [comment]
Hi, we're not able to reproduce the problem, I had to configure the Firewall and setup password authentication in sshd_config, but after that it worked. Could you let us know if this is still a problem for you?

**Comment by nabaco** [comment]
Hey,
I have the same issue. Working on ubuntu server 14.04. I can connect with any other SSH client, but VS connection manager gives "Authentication failure". Same results with using keys.
Is there any way to change the configuration of Connection Manager maybe?
