### ISSUE TITLE
Project properties specific to clang toolset

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#18]
Once we allow override of compiler used we know people will try clang. Options specific to this one need to be provided if used. 

Whole new toolset?

**Comment by EnoroF** [comment]
we indeed need a clang toolset to develop and debug on Linux. we can override compiler to use clang finish compile source code on Linux, but we can not debug it conveniently.

**Comment by itodirel** [comment]
copied to internal work item, and closing this, we are planning get to this in the Dev16 time frame
