### ISSUE TITLE
Issue #170 closed when not fixed

### ISSUE THREAD

**Issue by braindeaddeveloper** [Microsoft/VSLinux#180]
please reopen #170:

Adding -I /someincludepath to Additional Options is not the right way to do things when it should be in Additional Include Paths.  Additional Options gets added to the end of a command line which is not the correct location.

#170 is not fixed in 15.3.

thanks

**Comment by itodirel** [comment]
Reactivating #170, any objections to closing this one?

**Comment by braindeaddeveloper** [comment]
please do thanks


regardz
mark

On 7 Sep 2017, at 17:27, Ion Todirel <notifications@github.com<mailto:notifications@github.com>> wrote:


Reactivating #170<https://github.com/Microsoft/VSLinux/issues/170>, any objections to closing this one?

**Comment by lukka** [comment]
as requested by original poster, closing this issue
