### ISSUE TITLE
The linker should include $(LibraryPath) by default

### ISSUE THREAD

**Issue by ddrinka** [Microsoft/VSLinux#185]
When compiling, include directories listed in `<IncludePath>` are included in the command line.

When linking, library directories listed in `<LibraryPath>` are *not* included in the command line.

I expect the behavior to be the same for both top-level "VC++ Directories" entries.

Workaround:
```
<ItemDefinitionGroup>
  <Link>
    <AdditionalLibraryDirectories>$(LibraryPath);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
  </Link>
</ItemDefinitionGroup>
```

**Comment by itodirel** [comment]
thank you for reporting this, this is now fixed and will be available in 16.0 Preview 2
