### ISSUE TITLE
Need Two Factor Authentication Support for Connection Manager

### ISSUE THREAD

**Issue by hoodaticus** [Microsoft/VSLinux#186]
Description
I am unable to use VS2017 for Linux at my Fortune 50 company because of two-factor authentication requirements.

Expected Results
When creating a connection there should be an option for a challenge-response type login for supporting 2-factor authentication.  Moba X-Term implements this successfully in their SCP implementation.  What I expect is an interactive login option in which VS will get challenge text when attempting to login with my username, and prompt me for the response.  That would allow it to support two-factor auth.

Actual Results
Attempting to use two-factor authentication through the existing password mechanism fails with the correct two-factor credential string.

Notes: Moba X-Term uses something called SSH-Browser to login for its SCP feature.  It displays a dialog box with the challenge text and a text box for the user to enter the response.  A similar feature in VS is necessary if VS is to be used for Linux at my firm.  I expect this is true or will become so for most of the finance industry.

**Comment by itodirel** [comment]
I'm not very familiar with this, but is this something that SSH itself supports? The other method of authentication that can be more secure than password is keyboard authentication, and that in theory could be used to implement two factor auth.

**Comment by hoodaticus** [comment]
Keyboard auth would be perfect!

**Comment by itodirel** [comment]
plans to add keyboard authentication sometime during Dev16 time frame, no more info beyond that, we are tracking it internally, in an effort to reduce our issue list, closing
