### ISSUE TITLE
CMake generator choosing GNU instead of MSVC compiler

### ISSUE THREAD

**Issue by kevswims** [Microsoft/VSLinux#189]
I am trying to build a project using the Visual Studio 2017 CMake support with the open folder option on Windows 10 using the msvc15 compiler however Cmake compiler identification is trying to use the GNU 7.1.0 compiler installed with strawverry perl instead.

Here is the CMakeSettings.json for the configuration I am trying to build however this error also occurs with the x64-Release config.
```   
 {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64" ],
      "buildRoot": "${workspaceRoot}\\out\\${name}",
      "cmakeCommandArgs": "-Wno-dev -DCEDA_64_BIT=1",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": ""
    },
```
Here is the CMake output from Visual Studio:
```
1> -- The C compiler identification is GNU 7.1.0
1> -- The CXX compiler identification is GNU 7.1.0
1> -- Check for working C compiler: C:/Strawberry/c/bin/gcc.exe
1> -- Check for working C compiler: C:/Strawberry/c/bin/gcc.exe -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Detecting C compile features
1> -- Detecting C compile features - done
1> -- Check for working CXX compiler: C:/Strawberry/c/bin/c++.exe
1> -- Check for working CXX compiler: C:/Strawberry/c/bin/c++.exe -- works
```
Building from the command line works fine and CMake provides the following output:
```
-- The C compiler identification is MSVC 19.11.25508.2
-- The CXX compiler identification is MSVC 19.11.25508.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
```

If I uninstall the GNU compiler by removing Strawberry perl then CMake detects the correct compiler and runs correctly but then I can't use perl.

It was my understanding that the `"inheritEnvironments": [ "msvc_x64" ],` line sets the compiler to the MSVC one but this appears to not be working.

**Comment by AliAskari** [comment]
One way to get around it is to explicitly specify the path to the compiler by adding these to CMakeSettings.json

    "variables": [{
                    "name": "CMAKE_CXX_COMPILER",
                    "value": "C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/VC/Tools/MSVC/14.12.25631/bin/HostX86/x86/cl.exe"
                  },
                  {
                    "name": "CMAKE_C_COMPILER",
                    "value": "C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/VC/Tools/MSVC/14.12.25631/bin/HostX86/x86/cl.exe"
                  }
                ]

**Comment by kevswims** [comment]
@AliAskari this is not a valid solution for me since we check the CMakeSettings.json into our source and other developers will not necessarily have the compiler installed in the same location.

**Comment by lukka** [comment]
@kevswims the issue is not related to using CMake on a Linux machine. 
Please open a bug at  developercommunity.visualstudio.com
