### ISSUE TITLE
Enable cross compilation for building on local Windows machine

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#19]
Sometimes a little Linux box just doesn't have the oomph to compile. There are cross compiler tools available, we should use them.

**Comment by Performer777** [comment]
I hope that I understand idea correctly by assuming that cross compilation will be on Windows for with Linux targets. If yes I would give +100!

**Comment by timedroid** [comment]
We have a Windows->Ubuntu x86 (i686-w64-mingw32->i686-pc-linux-gnu) cross-toolchain, it would be nice if this plug-in supported that configuration.

**Comment by itodirel** [comment]
copied to internal work item for tracking, closing this, not sure when we can get to this, possibly during Update 1 time frame
