### ISSUE TITLE
gdb fails to find source when not on local C: drive

### ISSUE THREAD

**Issue by mgieselman** [Microsoft/VSLinux#194]
Use the Makefile Configuration type when you run the debugger the  x86_64-linux-gnu-gdb.exe process only looks for source code on the C: drive.  Using the "Additional Debugger Commands" and the gdb "dir" command to add an additional directory I'm able to help gdb fine the correct source file assuming it's on the C: drive, for example if I use "dir /Users/myusername/repos/project/src" all is fine.

Expected results:

Using dir command or some other method I should be able to tell gdb to find source code on a samba drive, for example "X:/repos/project/src".

Actual results:

gdb does not stop on breakpoints unless all source code is under the C: drive letter. 

Version:

VS v15.3.5
Unbuntu 16.04 LTS

Steps:

1. Create simple hello world makefile project on Linux.
2. Create vclinux Makefile project using shell scripts.
3. Set new vclinux project Remote Build command line.
4. Map hello world project location to samba drive location X:\helloworld.
5. Set breakpoint on hello world printf.
6. Run application using debugger.
7. gdb does not stop on break point.

**Comment by mgieselman** [comment]
Using the Debug.MIDebugLog /On /OutputWindow I see:

12: (6096189) <-1015-break-insert -f /home/matt/repos/barracuda/core/subsys/src/subsys.c:306
12: (6096206) ->&"No source file named /home/matt/repos/barracuda/core/subsys/src/subsys.c.\n"

the path above is valid and the file does exist.

I've tried using the AdditionalDebuggerCommands to add directories using the dir command, nothing I do helps gdb find the source code.

It's almost as if gdb is starting out in the wrong directory or something.

**Comment by mgieselman** [comment]
Some additional info, using Process Monitor I see the gdb process trying to open files and the path "looks" valid but I'm still not able to stop on the break point.

![image](https://user-images.githubusercontent.com/4323154/31362227-3778aab2-ad0c-11e7-9c57-fc67e8884d55.png)

**Comment by paulmaybee** [comment]
The error message above ("No source file named /home/matt/repos/barracuda/core/subsys/src/subsys.c.\n") indicates that the filename doesn't exist in the debugging symbols for the image you are trying to debug. This is usually because either you didn't build with '-g' or the location you built from is not the same as the location your source files are now in. Is that possible?

**Comment by robotdad** [comment]
@mgieselman thoughts?
