### ISSUE TITLE
vs2017 cross platform compiling error on “xmmintrin.h”

### ISSUE THREAD

**Issue by opentld** [Microsoft/VSLinux#198]
I’m using vs2017 for cross platform development, but I got an error while gcc4.9 compiling Andorid project, file “xmmintrin.h” , here is the error report:
D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h: In function ‘void _mm_empty()’:
1>D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h(51,24): error : ‘__builtin_ia32_emms’ was not declared in this scope
1> __builtin_ia32_emms ();
1> ^
1>D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h: In function ‘__m64 _mm_cvtsi32_si64(int)’:
1>D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h(64,54): error : ‘__builtin_ia32_vec_init_v2si’ was not declared in this scope
1> return (__m64) __builtin_ia32_vec_init_v2si (__i, 0);
1> ^
1>D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h: In function ‘int _mm_cvtsi64_si32(__m64)’:
1>D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h(107,53): error : ‘__builtin_ia32_vec_ext_v2si’ was not declared in this scope
1> return __builtin_ia32_vec_ext_v2si ((__v2si)__i, 0);
1> ^
1>D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h: In function ‘__m64 _mm_packs_pi16(__m64, __m64)’:
1>D:\Program Files\vs2017\Common7\IDE\VC\Linux\include\usr\lib\gcc\x86_64-linux-gnu\5\include/mmintrin.h(146,69): error : ‘__builtin_ia32_packsswb’ was not declared in this scope
1> return (__m64) __builtin_ia32_packsswb ((__v4hi)__m1, (__v4hi)__m2);
1> ^

thousands errors like this

I have try some ways such as -mmmx -msse2, but it does not work at all.
How could I solve this problem? 
Waiting for your answer and thanks a lot .

**Comment by robotdad** [comment]
This is an Android project, not Linux. You should install the Mobile Development with C++ workload and try one of the Android projects there.
