### ISSUE TITLE
Adding native nuget affects remote dir struct

### ISSUE THREAD

**Issue by levhaikin** [microsoft/VSLinux#199]
* A brief description
When adding a native nuget dependency - the packages.config files is added as a "None" item, and copied over to linux. Having packages.config copied is probably not harmful, BUT - when referencing sources that are not located directly in the project directory - the directory structure on the remote machine is affected - it starts having very long paths, and additional-include-paths need to be adjusted and so on. I believe this is due to a mechanism in the _CopySources msbuild-target, which finds the longest common path of the sources-to-be copied, and creates a directory structure based on the relative paths based on this common path. That, coupled with having "None" item on the SourcesToCopyRemotely list - you get packages.config disturbing the remote directory structure.

* Expected results
I'm not sure what is the best approach here, but I don't want the fact of simply having a native-nuget dependency to affect the remote directory structure.

* Actual results (with build output window contents if applicable)
Remote dir structure is altered, starting having long paths.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Visual Studio Professional 2017, Version 15.3.3
Using WSL

* Steps required to reproduce the error
Create a linux c++ project, that references sources from a different directory.
Add a native nuget (you can create a very simple nuget without much in it) to the project
Build the project
Observe how the remote dir struct becomes different compared to having no nuget dependencies. 

* Required packages and commands to install
A simple dummy empty native nuget will suffice

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by itodirel** [comment]
Interesting, I see, I think I understand what is going on and indeed this can cause a problem. We probably need a flag to say to not use certain sources in computing the remote paths.

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
