### ISSUE TITLE
Error in build window is obscure

### ISSUE THREAD

**Issue by ThorMalleuson** [Microsoft/VSLinux#2]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  While linking an error is thrown, however it is obscure: "g++ exited with code 1, please see the Output Window - Build output for more details."
- Expected results
  Error that has occurred being displayed.
- Actual results (with build output window contents if applicable)
  1>  Linking objects
  1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(183,5): error : g++ exited with code 1, please see the Output Window - Build output for more details.
  ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
- VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
  Visual Studio Community 2015 version 14.0.25421.03 Update 3
  Redhat Enterprise Linux 7.2
  gcc = 4.8.5 20150623 (Redhat 4.8.5-4)
  gdb = 7.6.1-80.el7
  gdbserver = 7.6.1-80.el7
- Steps required to reproduce the error
  Build my project.
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by ThorMalleuson** [comment]
I have tried this with a different project with the same result.  The linker throws an error, but the error itself is not displayed.

**Comment by stanthomas** [comment]
Linker errors not reported in output window at default verbosity, just that one line you see. Increasing the output verbosity does reveal the linker errors but, given that compilation errors are reported at the default level, this is an inconsistency.

Applies to VCLinux 1.0.4

**Comment by itodirel** [comment]
this is now fixed, if error occurs you will see the full compile/link outputs in minimal verbosity, the fix will be available in the next release
