### ISSUE TITLE
Use mingw32 cross compiler

### ISSUE THREAD

**Issue by sipsorcery** [Microsoft/VSLinux#200]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
I'd like to be able to test Linux builds from Visual Studio with both the standard gcc and the gcc derived  mingw32 tool chains.

* Expected results
Using the standard gcc and mingw32 tool chain both compile successfully.

* Actual results (with build output window contents if applicable)
The gcc tool chain compiles successfully. The mingw32 tool chain compiles but linking fails due to invalid options being specified by the Visual Studio template. It's not possible to turn off the problematic linker options in the property pages.

1>x86_64-w64-mingw32-ld: unrecognized option '-Wl,--no-undefined'

Would customising my local Visual Studio template for the Cross Platform Linux project be an option?

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Visual Studio 2017 15.4.1
Ubuntu 16.04.3 Windows Store App (aka WSL)
x64
gcc version 5.4.0
x86_64-w64-mingw32-g++ version 5.3.1

* Steps required to reproduce the error
Create a new vanilla Cross Platform->Linux->Console Application project. In the project properties change:
 C/C++ -> All Options -> C and C++ Compiler = x86_64-w64-mingw32-g++
 Linker -> All Options -> Linker =  86_64-w64-mingw32-ld

* Required packages and commands to install
apt install g++-mingw-w64-x86-64

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by robotdad** [comment]
You should try our open folder support for C++. We have a [post explaining how to use this with mingw and cygwin](https://blogs.msdn.microsoft.com/vcblog/2017/07/19/using-mingw-and-cygwin-with-visual-cpp-and-open-folder/).

**Comment by robotdad** [comment]
@sipsorcery does that post answer your questions on this one?

**Comment by sipsorcery** [comment]
@robotdad in my case I wanted to do it around the other way, build on Linux with the mingw32 toolchain. The reason being that an open source project I was looking at had their CI set up to do all their builds on Linux using mingw32 and therefore any changes I wanted to contribute needed to build with msvc and linux+mingw32.

I think I saw somewhere that you were going to consider making the integration between Visual Studio and WSL simpler, possibly eliminating the need for the remote SSH connections? That would probably help in this case.

**Comment by robotdad** [comment]
We haven't figured out yet what to do in the case of making things easier with WSL. As SSH just works there it hasn't gotten to high on the backlog yet.

If you want to use mingw on the remote you can override the compiler options in project properties, or try using open folder with a makefile or cmake properly configured for mingw.
