### ISSUE TITLE
CMake version '3.9.4' is not supported

### ISSUE THREAD

**Issue by phoenixchinar** [Microsoft/VSLinux#203]
I have a project that I am trying to get up and running in Visual Studio 15.4.1 with VC++ Linux 1.0.8.

After I configured the project the output I am getting is:

`CMake version '3.9.4' is not supported. Please use 3.8 or newer. See https://aka.ms/linuxcmakeconfig for more info`

**Comment by lukka** [comment]
@phoenixchinar sorry for the trouble. The problem has been fixed in version [15.5 Preview](https://www.visualstudio.com/vs/preview/). As a workaround, you should install on the Linux box a version between 3.8.0 and 3.9.0 bounds included.
