### ISSUE TITLE
Unable to modify launch.vs.json for cmake project

### ISSUE THREAD

**Issue by DanielOdenbrandQlik** [Microsoft/VSLinux#206]
Using VS2017 to build and debug a Linux cmake project. Right-clicking on the CMakeLists.txt->Debug and Launch settings->my program opens the launch.vs,json file and adds an entry looking like this:

```
{
    "version": "0.2.1",
    "defaults": {},
    "configurations": [
        {
            "type": "cppdbg",
            "name": "${buildRoot}\\benchmarks\\real_bitmaps_benchmark",
            "project": "CMakeLists.txt",
            "cwd": "${debugInfo.remoteWorkspaceRoot}",
            "program": "${debugInfo.fullTargath}",
            "MIMode": "gdb",
            "externalConsole": true,
            "remoteMachineName": "${debugInfo.remoteMachineName}",
            "pipeTransport": {
                "pipeArgs": [
                    "/s",
                    "${debugInfo.remoteMachineId}",
                    "/p",
                    "${debugInfo.parentProcessId}",
                    "/c",
                    "gdb --interpreter=mi"
                ],
                "pipeProgram": "${debugInfo.shellexecPath}"
            }
        }
    ]
}
```

It seems that modifying this entry does nothing when running the program but instead creates a new entry in the dropdown for programs to debug (named '${buildRoot}\benchmarks\real_bitmaps_benchmark' without expanding the buildRoot variable) which is not able to run with the current settings above. Am I going about this the wrong way? Is there somewhere else I modify the actual programs run?

I'm running a VirtualBox environment with debian-stretch 9,1 OS as my remote Linux machine with gdbserver version 7.12.0, gcc 6.3.0 and gdb 7.12.0. On my Windows machine I have VS2017 15.5 preview 2 with VC++ redistributable 14.11.25325.

I also tried this on a hello-world example and it seems to have the same problem.

**Comment by iwubcode** [comment]
Just adding on to this.  Currently, I can't seem to set `enable-pretty-print` which means debugging remotely is very difficult to work with.  I tried using the immediate window to set it but it kept saying undefined variable.

**Comment by paulmaybee** [comment]
@DanielOdenbrandQlik You are taking the correct steps to customize your setting. There is a bug in VS 15.5 which causes the debug target menu item to be duplicated. Once you customize it should supersede the default. We plan on having it fixed in preview 4. However in the meantime you can work around the problem by selecting that second, identically named, entry from the menu and using it instead.

@iwubcode You can turn on pretty printing from the Command Window (View->Other Windows->Command Window). Enter:
        Debug.MIExec -enable-pretty-printing

**Comment by iwubcode** [comment]
@paulmaybee  - thanks, unfortunately I get the following:

```
>Debug.MIExec -enable-pretty-printing
Command "Debug.MIExec" is not valid.
```

**Comment by paulmaybee** [comment]
Sorry, that should have been
Debug.MIDebugExec -enable-pretty-printing
And must be done after you launch the debugger.

**Comment by iwubcode** [comment]
@paulmaybee - thanks that seems to work!  Unfortunately, my `std::vector` of `std::unique_ptr` is getting treated as a `std::_Tuple_impl` and when clicking the arrow on it says 'Children cannot be evaluated'.  Should I open a new issue or is this known?

**Comment by paulmaybee** [comment]
Not  a known issue. Also likely to be a gdb/gcc lib issue. You can also try using natvis to see it that helps at all. Add this field to your launch.vs.json config:

**Comment by paulmaybee** [comment]
"visualizerFile": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\Linux\\Linux\\stl.natvis"

Adjust the path to match your installation.

**Comment by iwubcode** [comment]
@paulmaybee - thanks.  I added it under 'configurations' with the default 'cppdbg' that got generated.  Is there any way to tell it is working?  Debugging again didn't seem to show any improvement..

**Comment by paulmaybee** [comment]
Once you generate that new config you will see your target in the startup items menu twice (because of a current product bug that should get fixed in a 15.5 preview 4) . You'll need to select the new entry (should be the top entry). You can tell if it works because you'll see a "[Visualized Value]" field for the variable in the locals/watch window. Expand that to see the natvis visualization.

**Comment by iwubcode** [comment]
@paulmaybee - thank you so much for your help!  Sorry to derail this topic with all these questions.  That did work, I am now able to see the 'Visualized Value' field with a little 'refresh' button.  Click that doesn't yield any results but it's good to know my settings work.

I did find out our gdb is old, I was wondering how to point at a newer version we have on the remote box (#213) but I believe it has something to do with the multiple entries that you mention.  I'll try pointing at our new version and see if that helps.

Thanks again!

**Comment by DanielOdenbrandQlik** [comment]
@paulmaybee but then I can't change the settings of that configuration, can I?

**Comment by paulmaybee** [comment]
@DanielOdenbrandQlik You can change anything in the configuration except the name. We currently rely on the name field to find your executable file. Once the bugfix is available there will be a new field "projectTarget" that contains the path to the executable. You'll then be able to change the name to something that makes sense on the Startup Items menu.

**Comment by DanielOdenbrandQlik** [comment]
@paulmaybee ah right, so the workaround is to hardcode the name of the added executable removing the ${buildRoot} part from the name (which is autmatically generated from opening debug and launch settings)?

**Comment by paulmaybee** [comment]
Yes, and then select the new "duplicate" entry in the Startup Item menu.
