### ISSUE TITLE
GDBserver loses connection while idle at a breakpoint

### ISSUE THREAD

**Issue by boskars** [Microsoft/VSLinux#209]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
![billede](https://user-images.githubusercontent.com/25032095/32277417-afd139da-bf12-11e7-9c19-ca1663e62248.png)

Debugger in GDBserver mode is idle at breakpoint.  After few minutes I press F10 (step over) and the connection is lost.  I have included the debug log at the end of this message.

* Expected results

GDBserver should be able to be idle forever

* Actual results (with build output window contents if applicable)

The output debug log is attached at the end of this message.

VS 15.5 prev 2
Linux imx6ul-var-dart 4.1.15-2.0.0.974+g65ef23a #1 PREEMPT Wed Oct 25 15:28:50 CEST 2017 armv7l GNU/Linux
GCC version 6.3.0
GDB version 7.12.1
GDBserver v 7.9
CPU: DART-6UL CPU: NXP/Freescale i.MX 6UltraLite / i.MX 6ULL
Linux distribution: DART-6UL Yocto Pyro
* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

* Steps required to reproduce the error

Using VS autocreated project. Compile and debug using GDBserver mode.

* Required packages and commands to install
None.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

10: (9209705) ->=thread-group-added,id="i1"
=thread-group-added,id="i1"
10: (9209705) ->~"GNU gdb (GDB) 7.9\n"
10: (9209705) ->~"Copyright (C) 2015 Free Software Foundation, Inc.\n"
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
10: (9209705) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
10: (9209705) ->~"This GDB was configured as \"--host=i686-pc-mingw32 --target=arm-linux-gnueabihf\".\nType \"show configuration\" for configuration details."
This GDB was configured as "--host=i686-pc-mingw32 --target=arm-linux-gnueabihf".
Type "show configuration" for configuration details.10: (9209705) ->~"\nFor bug reporting instructions, please see:\n"

For bug reporting instructions, please see:
10: (9209705) ->~"<http://www.gnu.org/software/gdb/bugs/>.\n"
<http://www.gnu.org/software/gdb/bugs/>.
10: (9209705) ->~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\n"
10: (9209705) ->~"For help, type \"help\".\n"
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
10: (9209705) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
Type "apropos word" to search for commands related to "word".
10: (9209705) ->(gdb)
10: (9209705) <-1001-gdb-set target-async on
10: (9209706) ->1001^done
10: (9209706) ->(gdb)
10: (9209706) 1001: elapsed time 0
10: (9209706) ->&"\n"
10: (9209706) ->^done
10: (9209706) ->(gdb)
10: (9209706) <-1002-interpreter-exec console "set pagination off"
10: (9209717) ->=cmd-param-changed,param="pagination",value="off"
=cmd-param-changed,param="pagination",value="off"
10: (9209717) ->1002^done
10: (9209717) ->(gdb)
10: (9209717) 1002: elapsed time 10
10: (9209717) ->&"\n"
10: (9209717) ->^done
10: (9209717) ->(gdb)
10: (9209717) <-1003-gdb-set solib-search-path C:/Users/BO/source/repos/vs_15_5_prev2_test/bin/ARM/Debug;
10: (9209717) ->1003^done
10: (9209717) ->(gdb)
10: (9209717) 1003: elapsed time 0
10: (9209717) ->&"\n"
10: (9209717) ->^done
10: (9209717) ->(gdb)
10: (9209717) <-1004-gdb-set stop-on-solib-events 1
10: (9209728) ->1004^done
10: (9209728) ->(gdb)
10: (9209728) 1004: elapsed time 10
10: (9209728) ->&"\n"
10: (9209728) ->^done
10: (9209728) ->(gdb)
10: (9209728) <-1005-interpreter-exec console "set auto-solib-add on"
10: (9209738) ->1005^done
10: (9209738) ->(gdb)
10: (9209738) 1005: elapsed time 10
10: (9209738) ->&"\n"
10: (9209738) ->^done
10: (9209738) ->(gdb)
10: (9209738) <-1006-interpreter-exec console "target remote localhost:62535"
10: (9209754) ->~"Remote debugging using localhost:62535\n"
10: (9209810) ->=thread-group-started,id="i1",pid="894"
10: (9209810) ->=thread-created,id="1",group-id="i1"
10: (9209825) ->&"warning: Could not load vsyscall page because no executable was specified\ntry using the \"file\" command first."
10: (9209825) ->&"\n"
10: (9209860) ->~"0xb6fd79c0 in ?? ()\n"
10: (9209860) ->*stopped,frame={addr="0xb6fd79c0",func="??",args=[]},thread-id="1",stopped-threads="all",core="0"
10: (9209860) ->1006^done
10: (9209860) ->(gdb)
10: (9209860) 1006: elapsed time 121
10: (9209860) <-1007-thread-info 1
10: (9209860) ->&"\n"
10: (9209860) ->^done
10: (9209860) ->(gdb)
10: (9209862) ->1007^done,threads=[{id="1",target-id="Thread 894",frame={level="0",addr="0xb6fd79c0",func="??",args=[]},state="stopped",core="0"}]
10: (9209862) ->(gdb)
10: (9209862) 1007: elapsed time 2
10: (9209862) <-1008-interpreter-exec console "symbol-file \"C:/Users/BO/source/repos/vs_15_5_prev2_test/bin/ARM/Debug/vs_15_5_prev2_test.out\""
10: (9209862) ->&"\n"
10: (9209863) ->^done
10: (9209863) ->(gdb)
10: (9209864) ->~"Reading symbols from C:/Users/BO/source/repos/vs_15_5_prev2_test/bin/ARM/Debug/vs_15_5_prev2_test.out..."
10: (9209865) ->~"done.\n"
10: (9209904) ->1008^done
10: (9209904) ->(gdb)
10: (9209904) 1008: elapsed time 42
10: (9209904) <-1009-interpreter-exec console "set solib-search-path \"\""
10: (9209904) ->&"\n"
10: (9209904) ->^done
10: (9209904) ->(gdb)
10: (9209916) ->&"warning: Unable to find dynamic linker breakpoint function.\nGDB will be unable to debug shared library initializers\nand track explicitly loaded dynamic code."
10: (9209916) ->&"\n"
10: (9209923) ->=cmd-param-changed,param="solib-search-path",value="\"\""
10: (9209952) ->1009^done
10: (9209952) ->(gdb)
10: (9209952) 1009: elapsed time 47
10: (9209952) <-1010-enable-pretty-printing
10: (9209952) ->&"\n"
10: (9209952) ->^done
10: (9209952) ->(gdb)
10: (9209952) ->1010^done
10: (9209952) ->(gdb)
10: (9209952) ->&"\n"
10: (9209952) ->^done
10: (9209952) ->(gdb)
10: (9209952) 1010: elapsed time 0
10: (9210056) <-1011-break-insert -f /home/root/projects/vs_15_5_prev2_test/main.cpp:5
10: (9210071) ->1011^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x000104f4",func="main()",file="/home/root/projects/vs_15_5_prev2_test/main.cpp",fullname="/home/root/projects/vs_15_5_prev2_test/main.cpp",line="5",thread-groups=["i1"],times="0",original-location="/home/root/projects/vs_15_5_prev2_test/main.cpp:5"}
10: (9210071) ->(gdb)
10: (9210071) 1011: elapsed time 15
10: (9210071) <-1012-symbol-list-lines /home/root/projects/vs_15_5_prev2_test/main.cpp
10: (9210071) ->&"\n"
10: (9210071) ->^done
10: (9210071) ->(gdb)
10: (9210071) ->1012^done,lines=[{pc="0x000104ec",line="4"},{pc="0x000104f4",line="5"},{pc="0x00010500",line="6"},{pc="0x00010504",line="7"},{pc="0x0001050c",line="0"}]
10: (9210071) ->(gdb)
10: (9210072) 1012: elapsed time 0
10: (9210072) ->&"\n"
10: (9210072) ->^done
10: (9210072) ->(gdb)
10: (9210073) <-1013-interpreter-exec console "info sharedlibrary"
10: (9210093) ->~"No shared libraries loaded at this time.\n"
10: (9210093) ->1013^done
10: (9210093) ->(gdb)
10: (9210093) ->&"\n"
10: (9210093) ->^done
10: (9210093) ->(gdb)
10: (9210093) 1013: elapsed time 20
10: (9210094) <-1014-thread-info
10: (9210107) ->1014^done,threads=[{id="1",target-id="Thread 894",frame={level="0",addr="0xb6fd79c0",func="??",args=[]},state="stopped",core="0"}],current-thread-id="1"
10: (9210108) ->(gdb)
10: (9210108) ->&"\n"
10: (9210108) ->^done
10: (9210108) ->(gdb)
10: (9210111) 1014: elapsed time 17
10: (9210111) <-1015-stack-list-frames 0 1000
10: (9210156) ->1015^done,stack=[frame={level="0",addr="0xb6fd79c0",func="??"},frame={level="1",addr="0x00000000",func="??"}]
10: (9210156) ->(gdb)
10: (9210156) 1015: elapsed time 44
10: (9210156) ->&"\n"
10: (9210156) ->^done
10: (9210156) ->(gdb)
10: (9210156) <--exec-continue
Loaded 'shared libraries loaded at this time.'. Cannot find or open the symbol file.
10: (9210185) ->^running
10: (9210186) ->*running,thread-id="all"
10: (9210186) ->(gdb)
10: (9210189) ->(gdb)
10: (9210189) ->&"\n"
10: (9210190) ->^done
10: (9210190) ->(gdb)
10: (9210244) ->=library-loaded,id="/usr/lib/libstdc++.so.6",target-name="/usr/lib/libstdc++.so.6",host-name="/usr/lib/libstdc++.so.6",symbols-loaded="0",thread-group="i1"
10: (9210245) ->=library-loaded,id="/lib/libm.so.6",target-name="/lib/libm.so.6",host-name="/lib/libm.so.6",symbols-loaded="0",thread-group="i1"
10: (9210245) ->=library-loaded,id="/lib/libgcc_s.so.1",target-name="/lib/libgcc_s.so.1",host-name="/lib/libgcc_s.so.1",symbols-loaded="0",thread-group="i1"
10: (9210245) ->=library-loaded,id="/lib/libc.so.6",target-name="/lib/libc.so.6",host-name="/lib/libc.so.6",symbols-loaded="0",thread-group="i1"
10: (9210246) ->=library-loaded,id="/lib/ld-linux-armhf.so.3",target-name="/lib/ld-linux-armhf.so.3",host-name="/lib/ld-linux-armhf.so.3",symbols-loaded="0",thread-group="i1"
10: (9210246) ->&"warning: Could not load shared library symbols for 5 libraries, e.g. /usr/lib/libstdc++.so.6.\nUse the \"info sharedlibrary\" command to see the complete listing.\nDo you need \"set solib-search-path\" or \"set sysroot\"?"
10: (9210246) ->&"\n"
10: (9210252) ->~"Stopped due to shared library event:\n"
10: (9210252) ->~"  Inferior loaded /usr/lib/libstdc++.so.6\n"
10: (9210253) ->~"    /lib/libm.so.6\n"
10: (9210253) ->~"    /lib/libgcc_s.so.1\n"
10: (9210253) ->~"    /lib/libc.so.6\n"
10: (9210253) ->~"    /lib/ld-linux-armhf.so.3\n"
10: (9210253) ->*stopped,reason="solib-event",added=[library="/usr/lib/libstdc++.so.6",library="/lib/libm.so.6",library="/lib/libgcc_s.so.1",library="/lib/libc.so.6",library="/lib/ld-linux-armhf.so.3"],thread-id="1",stopped-threads="all",core="0"
Stopped due to shared library event:
  Inferior loaded /usr/lib/libstdc++.so.6
    /lib/libm.so.6
    /lib/libgcc_s.so.1
    /lib/libc.so.6
    /lib/ld-linux-armhf.so.3
10: (9210280) <-1016-interpreter-exec console "info sharedlibrary"
10: (9210287) ->~"From        To          Syms Read   Shared Object Library\n"
10: (9210287) ->~"                        No          /usr/lib/libstdc++.so.6\n"
10: (9210288) ->~"                        No          /lib/libm.so.6\n"
10: (9210288) ->~"                        No          /lib/libgcc_s.so.1\n"
10: (9210288) ->~"                        No          /lib/libc.so.6\n"
10: (9210288) ->~"                        No          /lib/ld-linux-armhf.so.3\n"
10: (9210288) ->1016^done
10: (9210288) ->(gdb)
10: (9210288) 1016: elapsed time 8
10: (9210288) ->&"\n"
10: (9210288) ->^done
10: (9210288) ->(gdb)
Loaded '/usr/lib/libstdc++.so.6'. Cannot find or open the symbol file.
Loaded '/lib/libm.so.6'. Cannot find or open the symbol file.
Loaded '/lib/libgcc_s.so.1'. Cannot find or open the symbol file.
Loaded '/lib/libc.so.6'. Cannot find or open the symbol file.
Loaded '/lib/ld-linux-armhf.so.3'. Cannot find or open the symbol file.
10: (9210291) <--exec-continue
10: (9210313) ->^running
10: (9210313) ->*running,thread-id="all"
10: (9210328) ->(gdb)
10: (9210328) ->(gdb)
10: (9210328) ->&"\n"
10: (9210328) ->^done
10: (9210328) ->(gdb)
10: (9210405) ->=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x000104f4",func="main()",file="/home/root/projects/vs_15_5_prev2_test/main.cpp",fullname="/home/root/projects/vs_15_5_prev2_test/main.cpp",line="5",thread-groups=["i1"],times="1",original-location="/home/root/projects/vs_15_5_prev2_test/main.cpp:5"}
10: (9210412) ->~"\nBreakpoint "

Breakpoint 10: (9210412) ->~"1, main () at /home/root/projects/vs_15_5_prev2_test/main.cpp:5\n"
1, main () at /home/root/projects/vs_15_5_prev2_test/main.cpp:5
10: (9210412) ->&"5\t/home/root/projects/vs_15_5_prev2_test/main.cpp: No such file or directory.\n"
10: (9210412) ->*stopped,reason="breakpoint-hit",disp="keep",bkptno="1",frame={addr="0x000104f4",func="main",args=[],file="/home/root/projects/vs_15_5_prev2_test/main.cpp",fullname="/home/root/projects/vs_15_5_prev2_test/main.cpp",line="5"},thread-id="1",stopped-threads="all",core="0"
10: (9210412) <-1017-stack-list-frames 0 1000
10: (9210422) ->1017^done,stack=[frame={level="0",addr="0x000104f4",func="main",file="/home/root/projects/vs_15_5_prev2_test/main.cpp",fullname="/home/root/projects/vs_15_5_prev2_test/main.cpp",line="5"}]
10: (9210422) ->(gdb)
10: (9210423) ->&"\n"
10: (9210423) ->^done
10: (9210423) ->(gdb)
10: (9210422) 1017: elapsed time 10
10: (9210425) <-1018-stack-list-arguments 2 0 0
10: (9210433) ->1018^done,stack-args=[frame={level="0",args=[]}]
10: (9210433) ->(gdb)
10: (9210433) 1018: elapsed time 8
10: (9210433) ->&"\n"
10: (9210433) ->^done
10: (9210433) ->(gdb)
10: (9216775) <-1019-var-create - * "main"
10: (9216788) ->1019^done,name="var1",numchild="0",value="{int (void)} 0x104ec <main()>",type="int (void)",has_more="0"
10: (9216788) ->(gdb)
10: (9216788) ->&"\n"
10: (9216788) ->^done
10: (9216788) ->(gdb)
10: (9216788) 1019: elapsed time 13
10: (9216791) <-1020-var-create - * "printf"
10: (9216799) ->1020^error,msg="-var-create: unable to create variable object"
10: (9216799) ->(gdb)
10: (9216799) ->&"\n"
10: (9216799) 1020: elapsed time 7
10: (9216799) ->^done
10: (9216800) ->(gdb)
10: (9216801) <-1021-var-create - * "this"
10: (9216809) ->1021^error,msg="-var-create: unable to create variable object"
10: (9216809) ->(gdb)
10: (9216809) ->&"\n"
10: (9216809) ->^done
10: (9216809) ->(gdb)
10: (9216809) 1021: elapsed time 7
10: (9367946) <-1022-var-create - * "main"
10: (9367955) ->1022^done,name="var4",numchild="0",value="{int (void)} 0x104ec <main()>",type="int (void)",has_more="0"
10: (9367956) ->(gdb)
10: (9367956) ->&"\n"
10: (9367957) ->^done
10: (9367957) ->(gdb)
10: (9367956) 1022: elapsed time 9
10: (9654526) <-1023-var-create - * ";"
10: (9654536) ->1023^error,msg="-var-create: unable to create variable object"
10: (9654537) ->(gdb)
10: (9654537) 1023: elapsed time 11
10: (9654538) ->&"\n"
10: (9654538) ->^done
10: (9654539) ->(gdb)
10: (9655032) <-1024-var-create - * "\"hello from vs_15_5_prev2_test!\n\""
10: (9655035) ->1024^error,msg="-var-create: unable to create variable object"
10: (9655035) ->(gdb)
10: (9655035) ->&"\n"
10: (9655035) ->^done
10: (9655036) ->(gdb)
10: (9655035) 1024: elapsed time 2
10: (9655037) <-1025-var-create - * "\"hello from vs_15_5_prev2_test!\n\""
10: (9655045) ->1025^error,msg="-var-create: unable to create variable object"
10: (9655045) ->(gdb)
10: (9655045) ->&"\n"
10: (9655045) ->^done
10: (9655045) ->(gdb)
10: (9655045) 1025: elapsed time 8
10: (9661285) <-1026-exec-next
10: (9661290) ->=thread-group-exited,id="i1"
10: (9661290) <-logout
10: (9661290) ->1026^error,msg="Warning:\nCannot insert breakpoint -1: Remote communication error.  Target disconnected.: No error.\n"
The program '' has exited with code 0 (0x0).

**Comment by braindeaddeveloper** [comment]
Is this a variant of #158 ?

**Comment by boskars** [comment]
The solution described in #208 does also apply here.
