### ISSUE TITLE
Provide a template showing usage of sensors with an IoT device

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#21]
Would this help people get going quicker with devices? There are some things it may help illustrate around parameters that need to be passed in.

**Comment by stanthomas** [comment]
I read 'template' as new project template. Currently there are templates for Linux Console, Empty Project and Makefile. I don't think a template for IoT or OpenGL #20 would be useful. Rather, I'd suggest these should be created as sample applications, complete with a VS solution, that can be downloaded in the same way as other demonstrations from Microsoft.

**Comment by robotdad** [comment]
I think I agree with you here. As I reflect on it good living samples would do more to demonstrate usage than templates.
