### ISSUE TITLE
'Break all' doesn't display any information in debugger

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#210]
**A brief description**

When choosing 'break all' after attaching the debugger to a process, there is nothing displayed.

**Expected results**

I expect to see callstacks and threads like what you would normally see in VS for a windows application.

**Actual results**

Empty thread window.  No notable pause or anything that makes me think VS reacted to the 'break all' command.

**Environment**

Visual Studio 2017 15.4.1
GDB 7.6.1

**Steps required to reproduce the error**

Attach to a running process.  Hit the pause button ('break all').  See how there is no callstack / thread information.

**Other**

I have only just started using the VSLinux capability so maybe I did something incorrectly or maybe I'm impatient and it takes some time for VS to collect the results?

**Comment by iwubcode** [comment]
Maybe VSLinux makes assumptions on what you are debugging?  Just to be clear, I am attaching to a process that isn't directly related to the VS project I have open.

**Comment by yuehuang010** [comment]
Thank you, the fix is on its way to a VS preview.

**Comment by iwubcode** [comment]
Confirmed fixed.  Thanks!
