### ISSUE TITLE
Can not find the output on linux or vs2017

### ISSUE THREAD

**Issue by LlorandoLau** [Microsoft/VSLinux#211]
@robotdad I have linked vs2017 to ubuntu (installed on vmmare). But when I run it (Ctrl+F5) I cannot find any output on vs2017 or ubuntu. When I start to debug, it shows:

![default](https://user-images.githubusercontent.com/28216165/32303369-1c9625c2-bfa3-11e7-9505-6bf90576b25e.PNG)

How to correct it?

**Comment by stanthomas** [comment]
Could it be that you don't have the Linux console window open? Open it from the Debug menu and note that the window has different display settings depending on whether you're editting or debugging (like the Find in Files results window).

**Comment by WenbinHou** [comment]
Unfortunately I'm facing the same issue.
I have opened "Linux Console" window from "Debug" menu, but still nothing is shown.

When I press "F5" for debug, the window has output:
![image](https://user-images.githubusercontent.com/26377737/34601928-db474088-f238-11e7-9cfd-0ab1da629b64.png)

However, when I press "Ctrl+F5", the window remains blank:
![image](https://user-images.githubusercontent.com/26377737/34601966-fdf50c1e-f238-11e7-968c-57f6e59d6c89.png)

This is my test code:
````c++
#include <cstdio>

int main()
{
    printf("sizeof(size_t) = %d\n", (int)sizeof(size_t));
    return 0;
}
````

**Comment by itodirel** [comment]
Ctrl+F5 does not pipe the output to the Linux console currently.

**Comment by itodirel** [comment]
we are not planning to do anything with this in the near future, but we copied it to the backlog
