### ISSUE TITLE
No 'Build' option on CMake for Linux

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#212]
**A brief description**

There is no build option after generating the cmake for linux.

**Expected results**

When generating the cache for Windows, I get all these options:

* Build All
* Rebuild All
* Clean All
* Build Only
* Install
* Run Tests
* Debug from Install Folder
* Debug from Build Folder
* Debug from Launch Settings
* Cache
  * Generate
  * Delete Cache Folders
  * View CMakeCache.txt
  * Open Cache Folder
* Change CMake Settings

(obviously View CMakeCache / Open Cache folder don't make sense in the context of a remote machine but the others seem very applicable)

**Actual results**

CMake runs fine and everything completes successfully but there are only two options:

* Cache
  * Generate
* Change CMake Settings

**Environment**

Visual Studio 2017 15.4.2
Remote CMake 3.9.0
Local CMake 3.9.4

**Steps required to reproduce the error**

Not sure.  The Microsoft blog posts and general chatter seem to indicate others are able to get a 'Build' option.  Therefore, I'm not sure if this is a bug or just something I'm doing incorrectly.

**Other**

I generated the cache multiple times and even deleted the cache on the remote machine manually (since unfortunately there was no clean option).

One thing to note, after the issue with CMake/Linux for 15.4.0, I did manually modify my files (can't find the microsoft post that says which ones they are).  However, since then, I've even tried doing a "Repair" on Visual Studio and did not see any change..

**Comment by lukka** [comment]
@iwubcode could you please provide the content of the Output pane ('CMake' section) when CMake generation should be completed? The menu mentioned are not being shown until the CMake generation and Visual Studio correctly parsed all the targets.

**Comment by iwubcode** [comment]
@lukka -

```
1> 5:36:51 PM: Copying files to remote machine...
1> 5:36:52 PM: Finished copying files (elapsed time 00h:00m:00s:789ms).
1> /usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug"  -DCMAKE_BUILD_TYPE="Debug"  -DCMAKE_MODULE_PATH="/path/to/cmake/module/"  -DCMAKE_PREFIX_PATH="/path/to/cmake/prefix/"  -DCMAKE_CXX_COMPILER="/opt/rh/devtoolset-2/root/usr/bin/g++"  "\remote\src\my-project-hash\Linux-Debug"
1> TOPLEVEL_BINARY_DIR=/remote/builds/my-project-hash/build/Linux-Debug/bin
1> CMAKE_MODULE_PATH=/path/to/cmake/module/
1> CMAKE_INSTALL_PREFIX=/path/to/cmake/prefix/
1> PLATFORM=gcc
1> COMPILER_VERSION=gcc48
1> CMAKE_EXE_LINKER_FLAGS = -Wl,-Map,output.map -rdynamic -lrt -lpthread
1> CMAKE_SHARED_LINKER_FLAGS = -Wl,-Map,output.map -rdynamic -lrt -lpthread
1> CMAKE_CXX_FLAGS = -std=c++11 -fvar-tracking-assignments -fPIC -Wno-deprecated -g3 -gdwarf-4 -pipe -Wall -Werror -Wextra -Wpedantic
1> CMAKE_CXX_FLAGS_RELEASE = -std=c++11 -fvar-tracking-assignments -fPIC -Wno-deprecated -g3 -gdwarf-4 -pipe -Wall -Werror -Wextra -Wpedantic -O2 -mtune=corei7 -DNDEBUG
1> CMAKE_CXX_FLAGS_DEBUG = -std=c++11 -fvar-tracking-assignments -fPIC -Wno-deprecated -g3 -gdwarf-4 -pipe -Wall -Werror -Wextra -Wpedantic  -O0 -DDEBUG
1> add_definitions(-DBOOST_SYSTEM_NO_DEPRECATED -DLinux -D_LINUX -DCOMPILE_64BITS)
------------------ a bunch of build specific commands -----------------------------------------------------------------  
1> Using binary_dir=/remote/builds/my-project-hash/build/Linux-Debug/bin for Project-UT unit test.
1> GenerateUnitTests.cmake:  add command with pre-test script.
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /remote/builds/my-project-hash/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> cmake exited.
```

I removed some of our build specific output and replaced some of the pathes.  Please let me know if there's anything else specific you'd like to see.

**Comment by lukka** [comment]
@iwubcode unfortuntaly that "cmake exited" text means cmake exited abnormally, it is not expected if everything goes smooth. 
If you could, please try with latest [Visual Studio Preview](https://www.visualstudio.com/vs/preview/). And if it still not working (i.e. already fixed) could you provide a small repro, we would be glad to fix it, thansk

**Comment by iwubcode** [comment]
@lukka - I might know what the issue is.

On the preview, I get the following error:

```
CMake is missing the following capability: 'serverMode'
```

It turns out, I built CMake from source, our compiler is pretty old so it doesn't have `make_unique` capability.  Without this, serverMode is turned off.. see [here](https://gitlab.kitware.com/cmake/cmake/issues/17352)

Apparently CMake 3.10 doesn't have this requirement when building from source.  I might give that a try (not sure if VS 15.5 supports that version of CMake?).

**Comment by lukka** [comment]
@iwubcode  nice catch, that indeed is the issue of the 'cmake exited' message: it is because the cmake being used does not have 'server' support. This particular issue has been already solved in VS Preview, it will provide a clear message error instead of 'cmake exited'. Regarding CMake 3.10RC, iirc it will not work because of a mismatch of the protocol VS request (1.0) and the ones CMake supports (it would offer 1.1 only). It would be safer to use 3.9.x in this moment.

**Comment by iwubcode** [comment]
@lukka - ok thanks for the information, that saved me some time!  Upgrading our compiler isn't an option but maybe I can find an already built version of 3.9 that has 'server' support.  Otherwise I can wait for 3.10 support.

Regardless, that is likely the issue, so I will go ahead and close this.  Thank you again!
