### ISSUE TITLE
Can you specify the GDB location?

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#213]
This is more a question than a bug.  Is there a way to specify the GDB location?  It seems to assume it is at `/usr/bin/gdb`.

I tried setting *miDebuggerPath* in the launch json but wasn't sure if that was the right setting.

**Comment by paulmaybee** [comment]
change your "pipeTransport" to look like this:
      "pipeTransport": {
        "pipeProgram": "${debugInfo.shellexecPath}",
        "pipeArgs": [
          "/s",
          "${debugInfo.remoteMachineId}",
          "/p",
          "${debugInfo.parentProcessId}",
          "/c"
        ],
        "debuggerPath": "/usr/bin/gdb"
      }
You can put any path in for the "debuggerPath".

**Comment by iwubcode** [comment]
Can confirm that this works well.  Thank you @paulmaybee !  I'll close this.
