### ISSUE TITLE
[FeatureRequest] Add Header sync button to automaticly copy header files from target linux system

### ISSUE THREAD

**Issue by j1and1** [Microsoft/VSLinux#215]
It would be nice if there would be some kind of button called "Manually sync headers from target"....

So if you want to create a linux APP or Lib you probably will need some linux headers for that.... in the curent state of VSLinux you have to copy header files from your linux systems manually to your dev machine and then anually ad them to your build config.... and of course if you have multiple development targets the heaers may be diferent so you have to do all this multiple times... 

and of course if you update lib you are linking to you will also have to copy those headers again..... and there is a high probability of screwing things up....

**Comment by robotdad** [comment]
We have plans to address this issue, not quite as proposed. All of the below is our plan, it could change, etc. etc. And of course feedback is welcome or I wouldn't be sharing. :-) 

What we are planning is to sync the standard include locations per connection into a local location as read only. We will provide a way to add additional locations from the remote to sync as well. The sync would occur when a connection to the remote machine is made. This local location would be accessible in VS via an environment variable in vcxproj or folder projects. As there will be a local location per connection we will use the currently selected connection for IntelliSense. 

Configuration of this capability will be in a new Tools > Options pane. We will allow it to be turned off globally or per connection.

**Comment by itodirel** [comment]
This feature was implemented and released in 15.7 Preview 2, which is now publicly available, please try it and let us know if you have any feedback or suggestions.
![capture](https://user-images.githubusercontent.com/15239856/38342246-bcd52596-386c-11e8-9e45-f16bdf473692.PNG)

**Comment by AliAskari** [comment]
@itodirel @robotdad 

Do you have any plans to support copying headers that are not system headers and are not part of the project but are used in the project? 

Let's say I have a third party library that I'm using in my project however the headers/sources are under a different path on the Linux machine. How do you suggest me to debug that third party library using visual studio? Manually copying is not really a great option.

**Comment by jensreck** [comment]
A further point is syncing of cross compile headers and a proper switching to the regarding platform e.g. depending on "intelliSenseMode" ("linux-gcc-x64", "linux-gcc-arm", ...), isn't it?

**Comment by lukka** [comment]
@AliAskari could you please create a new ticket about the copy of headers from remote target to local dev machine? thanks a lot for your support

**Comment by AliAskari** [comment]
@lukka Sure, I have created an [issue](https://github.com/Microsoft/VSLinux/issues/300) and also a demo repo so that it's a bit more clear. Let me know if you need more info.
