### ISSUE TITLE
Raspberry Pi compilation is hard to use.

### ISSUE THREAD

**Issue by ramoneeza** [microsoft/VSLinux#216]
When it is used to compile a real size project for Raspberry PI several difficulties arise that make programming very unpleasant.

1) Lack of intellisense for several C libraries. (like <unistd.h> <sys/...> etc...) no easy way or some help to include general raspberry/linux libraries to intellisense. (I made a local copy but no succesfully add path to configuration)

2) Lack of incremental compiling or cross-compiling makes developing sooo slow... each time I launch debugger I must wait to recompilation a lot of time.

3) Lack of easy includes of additional features to gcc command like "-lpthread" etc... that makes a mistery to compile slightly more avanced projects.

So... I think is necessary more automatization per target device.

**Comment by cdeisler** [comment]
I have a simple program as well. I have been able to build and run successfully until I attempt to link to anything in usr/local/include

Raspicam was originally built targeting usr/local/include and it wouldn't build:
![image](https://user-images.githubusercontent.com/2393923/32672707-14cef8b4-c61a-11e7-9641-e1c10a227349.png)

If I build raspicam into usr/include then it works but as soon as i attempt to link `opencv` modules it breaks saying it can't find `unistd.h`.

![image](https://user-images.githubusercontent.com/2393923/32672779-6300e510-c61a-11e7-99e0-19479d471374.png)


```c
#include <ctime>
#include <fstream>
#include <iostream>

using namespace std;

#include <wiringPi.h>
#include <raspicam/raspicam.h>
//#include <raspicam/raspicam_cv.h>

#ifdef __linux__
#include <unistd.h>
#endif
#ifdef _WIN32
#include <windows.h>
#endif

//#include <opencv/cv.h>
//#include <opencv2/core/core.hpp>
//#include <opencv2/imgproc/imgproc.hpp>
//#include <opencv2/opencv.hpp>

// LED Pin - wiringPi pin 0 is BCM_GPIO 17.
#define	LED	17

void mySleep(int sleepMs)
{
#ifdef __linux__
	usleep(sleepMs * 1000);   // usleep takes sleep time in us (1 millionth of a second)
#endif
#ifdef _WIN32
	Sleep(sleepMs);
#endif
}

int main(void)
{
	wiringPiSetupSys();

	pinMode(LED, OUTPUT);

	raspicam::RaspiCam Camera;

	if (!Camera.open()) {  return -1; }

	mySleep(3);

	//capture
	Camera.grab();
	
	while (true)
	{
		digitalWrite(LED, HIGH);  // On
		delay(500); // ms
		digitalWrite(LED, LOW);	  // Off
		delay(500);
	}
	return 0;
}
```

Do I need to rebuild opencv from scratch and target usr/include or is there a way to include `usr/local/include` without having GCC break the standard unix mappings?

**Comment by itodirel** [comment]
thanks, we're looking into it, @ramoneeza can you share your project with us?

**Comment by itodirel** [comment]
Incrementality for build is tracked with, which is on the roadmap and committed for us to address #29
