### ISSUE TITLE
Build 'All Target' with CMake doesn't seem to do anything

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#218]
**A brief description**

Choosing CMake > 'Build Only' > 'All Targets' gives no output.

**Expected results**

Building 'All Targets' should give the same results as if I built each project individually.

**Actual results**

No output

**Environment**

CMake 3.9.0
Visual Studio 2017 15.5 Preview 2

**Steps required to reproduce the error**

Generate your cmake project.  Then choose 'Build Only' > 'All Targets' and see that there is no output in the output window under 'Build'.

**Comment by robotdad** [comment]
Regression in the preview. I'm pretty sure @lukka pushed a fix for that yesterday. Not sure which preview that will come out in.

**Comment by yuehuang010** [comment]
The fix in on its way.  Keep an eye out on the next preview release.

**Comment by iwubcode** [comment]
I can confirm this is fixed in 15.5 preview 4.  Thank you very much!!  I will close this.
