### ISSUE TITLE
(CMake) F5 / CTRL+F5 tries to launch Linux build in Windows

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#219]
**A brief description**

When targeting linux if I use "F5" or "CTRL+F5", the program does not launch.

**Expected results**

It should either build or build and debug the startup program when pressing F5 or CTRL+F5.

**Actual results**

I get an error "Unable to start program" which points to a windows path (trying to run the process as an exe).

(Note:  choosing 'CMake' -> 'Debug from Build folder' works fine)

**Environment**

Remote CMake 3.9.0
Local CMake 3.9.4
Visual Studio 2017 15.5 (Preview 2)

**Steps required to reproduce the error**

Use cmake to initiate a project
Try to build it with F5
Notice the error

**Comment by paulmaybee** [comment]
Have you selected a "Startup Item" on the debug target menu (in the top menu next to the box with Linux-Debug)?

**Comment by iwubcode** [comment]
@paulmaybee - thank you, I did not even see that.  Somehow my startup item was a cpp file instead.  I'll go ahead and close this.
