### ISSUE TITLE
[ Feature Request ] Additional variables for Remote Tasks

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#220]
I was trying to use the remote tasks capability to create a generic 'build' option to build any cpp file.  I'm using the example provided in the [remote tasks preview](https://blogs.msdn.microsoft.com/vcblog/2017/10/23/remote-tasks-in-visual-studio/) as a base.

Here's my general idea:
```
"tasks": [
    {
      "taskName": "Build ${file_name}",
      "appliesTo": "*.cpp",
      "type": "remote",
      "contextType": "build",
      "command": "g++ ${file_name}",
      "remoteMachineName": "myMachine",
      "remoteCopyDirectory": "/somehardcoded_location/${file_directory_relative_path_from_project_root}",
      "remoteCopyMethod": "sftp",
      "remoteWorkingDirectory": "/somehardcoded_location/${current_target_name}/"
    }
  ]
```

I noticed I could leverage `${file}` to reference the full path to the actual file I clicked on.  But I need some more properties:  `${file_name}` and `${file_directory_relative_path_from_project_root}` this would allow the user to write more generic remote tasks.

Additionally useful would be a `${current_target_name}` which would have the current selected target.  This way we could set our remote working directory correctly.

Please let me know if there's a way to already do this.

And thank you for this interesting feature!

**Comment by iwubcode** [comment]
Managed to figure out the current-target-name, you can use `${cpp.activeConfiguration}`

**Comment by iwubcode** [comment]
@yuehuang010 - just curious on why this was closed?  Even if there is no desire to support more advanced tasks, is there some way to compile only specific C++ files?

**Comment by yuehuang010** [comment]
Sorry, I fat fingered closed.  I was suppose to review it.

**Comment by yuehuang010** [comment]
Hi, In 15.6 preview 3, you should now see the option for "RemotePreBuildCommand" in json.  This would allow you to export or run any scripts you see fit.  Let me know if this addresses your problem.

**Comment by iwubcode** [comment]
@yuehuang010 - thank you, this will be helpful.  However, I don't see this option in Preview 4 of the  remote-task json auto-complete.

I will say, this still doesn't address the issue of writing generic tasks (usable across multiple projects) but admittedly I'm not sure how common this will be.  So until I can come up with more use-cases (beyond building an individual C++ file), I will close this.
