### ISSUE TITLE
[ Question ] How to determine if you're using 'gdb' or 'gdbserver' mode?

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#223]
How do you determine if you're using 'gdb' or 'gdbserver' mode?  How do you configure it to be one way or the other?  My projects are typically defined in CMake.  I know 'gdbserver' is a separate process.  Do you just point `debuggerPath` to gdbserver instead?

I question this since 'pretty printers' still displayed raw data (_M_p stuff) when trying to debug a unit test.  I had to resort to natvis which has its own issues (see: #221 and #222).  I read a reply from @robotdad that pretty-printing was only available in 'gdb mode' and so I wondered how I could determine which mode I was in.

Note:  I have it configured to point at gdb currently, so I would expect to be in 'gdb mode'.

**Comment by stanthomas** [comment]
Set `gdb` or `gdbserver` in the project properties under Debugging/Debugging Mode.

**Comment by iwubcode** [comment]
Thanks @stanthomas !  Unfortunately, there is no project properties for CMake projects.  There might be something similar in the launch json?

**Comment by robotdad** [comment]
Ah, cmake should be gdb mode by default. It should be changeable in the cmake settings json.

**Comment by iwubcode** [comment]
Thanks @robotdad .  I'll try and look more into this this week.  I'm assuming I'm configured correctly then.

Per @paulmaybee, natvis has a problem with converting the "using" statements we use due to the way GDB handles this.  It's possible that this is why pretty-printing also does not display nicely.

I'm closing this, as I think my question was answered.  Thank you!
