### ISSUE TITLE
[ Feature Request ] Support for setting remote environment variables in CMake

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#224]
This might already be possible but our CMake logic can make use of certain environment variables.  Is it possible to set those in the CMakeSettings.json?

**Comment by itodirel** [comment]
we're actually working on that right now, and it will be in the next release

**Comment by iwubcode** [comment]
@itodirel - I noticed this was marked fixed and now is closed.  Is this in a public release?  Is there any documentation on how to leverage environment variables in CMake?

**Comment by iwubcode** [comment]
@yuehuang010 / @itodirel - apologies but with the recent 15.7 preview 1 release documentation, I didn't see any comment about this feature.  Is there some documentation that I missed?

**Comment by itodirel** [comment]
@yuehuang010, you coded the feature, can you reply on how to activate it?

**Comment by yuehuang010** [comment]
In CppProperties.json, under "configuration" add "environments".  You also might be interested in "remotePreGenerateCommand" and "remotePrebuildCommand" for any scripting needs.
```json
  "configurations": [
    {
      "environments": [ { "foobar": "cat" } ],
      "remotePreGenerateCommand": "echo Hello World",
      "remotePrebuildCommand": "echo Hello World2",
      "name": "Linux-Release"
}]
```

```text
1> /usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Release" "/var/tmp/src/ed9b762a-3556-4933-bd96-0ee1e35268aa/Linux-Release/CMakeLists.txt";
1> Hello World
1> -- Environment
1> -- foobar:cat
1> -- Configuring done
1> -- Generating done
```

**Comment by iwubcode** [comment]
Hi @yuehuang010 - thanks for the example!  I just attempted this with Version 15.7.0 Preview 1.0 and I am seeing what I think is an issue when there are more than one environment variables.

This is how I have it set up:

```
"environments": [
{ "CMAKE_MODULE_PATH": "mypath" },
{ "CMAKE_PREFIX_PATH": "mypath2" },
{ "CMAKE_CXX_COMPILER": "mypath3"}
],
```

However, when outputting those, I only see the first value getting outputted.  Is there something special needed for multiple environment variables?

**Comment by paulmaybee** [comment]
Try formatting like:

```
"environments": [
   { 
     "CMAKE_MODULE_PATH": "mypath",
     "CMAKE_PREFIX_PATH": "mypath2",
     "CMAKE_CXX_COMPILER": "mypath3"
   }
],

```

**Comment by iwubcode** [comment]
Thanks @paulmaybee that seemed to do the trick!
