### ISSUE TITLE
PreBuildEvent in 15.5. prev 4

### ISSUE THREAD

**Issue by boskars** [Microsoft/VSLinux#226]
When I rebuild / build my project in 15.5 prev 4, I get following error:

       (PreBuildEvent target) -> 
         C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(349,5): error MSB4044: The "Execute" task was not given a value for the required parameter "RemoteProjectDir".

I am currently using VS15.4.1 which can build/rebuild the project correctly....

**Comment by lukka** [comment]
@boskars 
FYI I could not reproduce your problem yet with VS Professional 15.5p4.

Could you please try creating a new Console Application project with VS 15.5 Preview 4 and verify whether a PreBuild event works in that scenario? We need to understand whether is it a common problem of VS, or if it is related to your project settings. In the former case, please proceed with a Repair action upon your installation. In the latter, we should proceed forward with the investigation.

**Comment by boskars** [comment]
@lukka 
**I have created new Console Application project with VS 15.5 prev 4 and added some random files to copy during Prev-Build-Event:**

../../MultiProjectSolution/Console/Touch.cpp:=$(RemoteRootDir)/PreTest/Cfg/x1.h;../../MultiProjectSolution/Console/Touch.cpp:=$(RemoteRootDir)/PreCopy/Cfg/x2.h;../../MultiProjectSolution/Console/Touch.cpp:=$(RemoteRootDir)/PreBuild/Cfg/x3.h

**And I still get the:**
1>------ Rebuild All started: Project: PreBuildTst15_5_4_1, Configuration: Debug ARM ------
1>Cleaning remote project directory
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(349,5): error MSB4044: The "Execute" task was not given a value for the required parameter "RemoteProjectDir".
1>Done building project "PreBuildTst15_5_4_1.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**If I load and build same project in 15.4.1 then every thing works as it should and I get following in the output window:**

1>------ Rebuild All started: Project: PreBuildTst15_5_4_1, Configuration: Debug ARM ------
1>Target _PrepareForClean:
1>  Deleting file "C:\Users\BO\Documents\Visual Studio 2017\Projects\PreBuildTst15_5_4_1\PreBuildTst15_5_4_1\obj\ARM\Debug\PreBuild.26b1e347.tlog\PreBuildTst15_5_4_1.lastbuildstate".
1>Target _RemoteClean:
1>  Cleaning remote project directory
1>Target InitializeBuildStatus:
1>  Touching "C:\Users\BO\Documents\Visual Studio 2017\Projects\PreBuildTst15_5_4_1\PreBuildTst15_5_4_1\obj\ARM\Debug\PreBuild.26b1e347.tlog\unsuccessfulbuild".
1>Target PreBuildEvent:
1>  Copying file 'C:\Users\BO\Documents\Visual Studio 2017\Projects\MultiProjectSolution\Console\Touch.cpp' to '~/projects/PreTest/Cfg/x1.h'
1>  Copying file 'C:\Users\BO\Documents\Visual Studio 2017\Projects\MultiProjectSolution\Console\Touch.cpp' to '~/projects/PreCopy/Cfg/x2.h'
1>  Copying file 'C:\Users\BO\Documents\Visual Studio 2017\Projects\MultiProjectSolution\Console\Touch.cpp' to '~/projects/PreBuild/Cfg/x3.h'
1>Target CreateRecipeFile:
1>  Skipping target "CreateRecipeFile" because all output files are up-to-date with respect to the input files.
1>Target _ValidateValidArchitecture:
1>  Validating architecture
1>  Current project architecture 'ARM' is compatible with the remote system architecture 'ARM' ('ARM').
1>Target _ValidateSources:
1>  Validating sources
1>Target _CopySources:
1>  Copying sources remotely to '192.168.1.243'
1>  Copying file 'C:\Users\BO\Documents\Visual Studio 2017\Projects\PreBuildTst15_5_4_1\PreBuildTst15_5_4_1\main.cpp' to '/home/root/projects/PreBuildTst15_5_4_1/main.cpp'
1>Target ClCompile:
1>  Starting remote build
1>  Compiling sources:
1>  Invoking g++
1>  g++ -c -x c++ /home/root/projects/PreBuildTst15_5_4_1/main.cpp -g2 -gdwarf-2 -o "/home/root/projects/PreBuildTst15_5_4_1/obj/ARM/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11
1>  main.cpp
1>  Done compiling '/home/root/projects/PreBuildTst15_5_4_1/main.cpp'
1>Target Link:
1>  Linking objects
1>  Invoking ld
1>  g++ -o "/home/root/projects/PreBuildTst15_5_4_1/bin/ARM/Debug/PreBuildTst15_5_4_1.out" -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack /home/root/projects/PreBuildTst15_5_4_1/obj/ARM/Debug/main.o
1>  Done linking, output file name: '/home/root/projects/PreBuildTst15_5_4_1/bin/ARM/Debug/PreBuildTst15_5_4_1.out'
1>  Copying file '/home/root/projects/PreBuildTst15_5_4_1/bin/ARM/Debug/PreBuildTst15_5_4_1.out' to 'C:\Users\BO\Documents\Visual Studio 2017\Projects\PreBuildTst15_5_4_1\PreBuildTst15_5_4_1\bin\ARM\Debug\PreBuildTst15_5_4_1.out'
1>  PreBuildTst15_5_4_1.vcxproj -> C:\Users\BO\Documents\Visual Studio 2017\Projects\PreBuildTst15_5_4_1\PreBuildTst15_5_4_1\bin\ARM\Debug\PreBuildTst15_5_4_1.out
1>Target FinalizeBuildStatus:
1>  Deleting file "C:\Users\BO\Documents\Visual Studio 2017\Projects\PreBuildTst15_5_4_1\PreBuildTst15_5_4_1\obj\ARM\Debug\PreBuild.26b1e347.tlog\unsuccessfulbuild".
1>  Touching "C:\Users\BO\Documents\Visual Studio 2017\Projects\PreBuildTst15_5_4_1\PreBuildTst15_5_4_1\obj\ARM\Debug\PreBuild.26b1e347.tlog\PreBuildTst15_5_4_1.lastbuildstate".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Then I repaired the VS 15.5. prev 4 installation as you suggested and created a new project again with same files to copy and got exactly same error again.  So repairing did not help.**

**Comment by lukka** [comment]
@boskars we identified the issue and we are working on a fix. No ETA yet.

As a workaround, please edit your .vcxproj file by appending the following target called "RemotePreBuildEvent" at the end of your .vcxproj file. The <target> must be the last element inside the <project> XML element:

```
[...]
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets" />
  

  <Target Name="RemotePreBuildEvent" Condition="'$(RemotePreBuildEventUseInBuild)' != 'false'" DependsOnTargets="_ResolveRemoteTarget">
    <Message Text="Description: %(RemotePreBuildEvent.Message)" Condition="'%(RemotePreBuildEvent.Message)' != '' and '%(RemotePreBuildEvent.Command)' != ''"/>
    <Execute Condition="'%(RemotePreBuildEvent.Command)' != '' or '%(RemotePreBuildEvent.AdditionalSourcesToCopyMapping)' != ''"
      Command="%(RemotePreBuildEvent.Command)"
      RemoteTarget="$(ResolvedRemoteTarget)"
      ProjectDir="$(ProjectDir)"
      RemoteProjectDir="PUT THE PROJECT REMOTE FULL PATH HERE, such as /home/username/projects/Project1"
      RemoteFilesToCopyLocallyMapping="%(RemotePreBuildEvent.AdditionalSourcesToCopyMapping)"
      Timeout="$(RemoteExecuteTimeout)">
    </Execute>
  </Target>

</Project>
```

Let us know if this is helpful, thanks.

**Comment by boskars** [comment]
@lukka, it does not seems to help.

**Comment by lukka** [comment]
@boskars i would like to help on this:
  -  Is it a Console Application based project right? 
  -  What is the error that are you encountering after applying the workaround?
  -  Any code snippet out of your vcxproj is welcome.

**Comment by boskars** [comment]
@lukka 
It is a console application, and the error message is still the same after applying the workaround.  I have attached project.  It copies files and compiles using VS 15.4.1 but when using prev 15.5.x it gives the mentioned error.

[For_lukka.zip](https://github.com/Microsoft/VSLinux/files/1521188/For_lukka.zip)

**Comment by lukka** [comment]
@boskars thanks for the provided files.

The workaround is to override also the target "PreBuildEvent" (coming from `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets`) in your .vcxproj with hardcoded `RemoteProjectDir`.

Your project file appended with the following should work (add these target definitions as you already done between `<ImportGroup Label="ExtensionTargets" />` and `</Project>` elements). 

Please note the following:
  - the path for RemoteProjectDir must match the one you set in the properties page of your Configuration
  - the path for RemoteProjectDir must not contain spaces;

```
  <Target Name="RemotePreBuildEvent" Condition="'$(RemotePreBuildEventUseInBuild)' != 'false'" DependsOnTargets="_ResolveRemoteTarget">
    <Message Text="Description: %(RemotePreBuildEvent.Message)" Condition="'%(RemotePreBuildEvent.Message)' != '' and '%(RemotePreBuildEvent.Command)' != ''" />
    <Execute Condition="'%(RemotePreBuildEvent.Command)' != '' or '%(RemotePreBuildEvent.AdditionalSourcesToCopyMapping)' != ''" Command="%(RemotePreBuildEvent.Command)" RemoteTarget="$(ResolvedRemoteTarget)" ProjectDir="$(ProjectDir)" RemoteProjectDir="/home/root/projects/PreBuildTst15_5_4_1" RemoteFilesToCopyLocallyMapping="%(RemotePreBuildEvent.AdditionalSourcesToCopyMapping)" Timeout="$(RemoteExecuteTimeout)">
    </Execute>
  </Target>
  <Target Name="PreBuildEvent" Condition="'$(PreBuildEventUseInBuild)'!='false'" DependsOnTargets="_ResolveRemoteTarget">
    <Message Text="Description: %(PreBuildEvent.Message)" Condition="'%(PreBuildEvent.Message)' != '' and '%(PreBuildEvent.Command)' != ''" />
    <Exec Command="%(PreBuildEvent.Command)$(_BuildSuffix)" Condition="'%(PreBuildEvent.Command)' != ''" />
    <Execute Condition="'%(PreBuildEvent.AdditionalSourcesToCopyMapping)' != ''" RemoteTarget="$(ResolvedRemoteTarget)" ProjectDir="$(ProjectDir)" RemoteProjectDir="/home/root/projects/PreBuildTst15_5_4_1" LocalFilesToCopyRemotelyMapping="%(PreBuildEvent.AdditionalSourcesToCopyMapping)" Timeout="$(RemoteExecuteTimeout)">
    </Execute>
  </Target>

```

**Comment by boskars** [comment]
Thanks @lukka  this helps on my test project.  Will this be fixed in next preview?

**Comment by lukka** [comment]
@boskars thanks for reporting us this helped. 
Yes, the fix is going to be released on one of the next Preview version of 15.6.

**Comment by lkytal** [comment]
Same problem here, expect 15.6 to be released soon.

**Comment by boskars** [comment]
It is fixed in the current 15.6 preview.

**Comment by ashokbruno** [comment]
I am running 15.8 with Windows 10 1803 and am seeing this issue.

**Comment by xXxSiMoNxXx** [comment]
Me too, I run 15.8.1 and see it suddenly. Can't do remote debugging.
 
This is the error:
error MSB4044: The "Execute" task was not given a value for the required parameter "RemoteProjectDir".

**Comment by menting311** [comment]
I am also seeing this all of the sudden on 15.8.1 and 15.9 p1 so it is probably a setting on the project that was updated and is causing the issue.
It started for me after I did a "clean" on the project, not sure if that is related or not.

error MSB4044: The "Execute" task was not given a value for the required parameter "RemoteProjectDir".

**Comment by menting311** [comment]
I was able to find a workaround. Initially I tried the workaround above with the PreBuilEvent target but that didn't work. My issue was from duruing the build itslef so I had to find the "Build" event in the below file and then copy that to my project file and update the remote build directory.

C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets

**Comment by mseklertt** [comment]
Started happening for me since yesterday I upgraded to 15.8.3. Exactly the same error.

**Comment by xXxSiMoNxXx** [comment]
@lukka 
Can you address please to the issue ?

**Comment by xXxSiMoNxXx** [comment]
Thanks ! Worked for me.
They need to fix it as is, we need to open a bug for that because it is the same for all the 15.8 releases so far.

**Comment by mseklertt** [comment]
I opened a bug, but someone "smart" closed it. I ma trying to reopen, but if I can't do it, then I will open a new ticket. They do need to fix this.

**Comment by mseklertt** [comment]
The problem is gone in new version 15.8.4.

**Comment by xXxSiMoNxXx** [comment]
Still breaks for me after I do "clean", this is without your workaround and on the new version 15.8.4.

**Comment by cagnulein** [comment]
any news about this issue?

**Comment by lukka** [comment]
@cagnulein could you please open a ticket on community.visualstudio.com? You can use the Report a Problem tool in VS to automatically open a ticket for you, thanks!

**Comment by cagnulein** [comment]
> community.visualstudio.com

i guess you mean https://developercommunity.visualstudio.com/
