### ISSUE TITLE
How to attach VS Debugger to qemu vm running cross-compiled code

### ISSUE THREAD

**Issue by ademyankov** [Microsoft/VSLinux#227]
I have successfully cross-compiled simple console application using aarch64 toolchain installed on my ubuntu vm (remote).

Now, I have a problem to solve, how to run vs debugger with the application executed inside arm vm running on qemu. If I run debugger I get **"cannot execute binary file: Exec format error"** which is totally understandable because it tries to execute arm code on ubuntu vm.

When qemu is launched with -S option it creates a port :1234 and then it waits until gdb connects to this port. So, the procedure to debug the application running in vm on qemu is the following (I've done it from my windows host Linux subsystem to verify that it works):

Obviously, I installed aarch64-linux-gnu-gdb beforehand.
So:
```
(gdb) target remote 10.*.*.156:1234
Remote debugging using 10.*.*.156:1234
```
Then I continue to let qemu to boot the vm until FVP console is launched.
`(gdb) c`

After it booted I can break gdb, load symbols of my app and set a break point.
```
(gdb) symbol-file app
(gdb) b main
Breakpoint 1 at 0x401f1c: file app/app.cpp, line 74.
(gdb) c
```
Then I run my app from FVP console and gdb hits the breakpoint.
```
Breakpoint 1, main (argc=5, argv=0xffffea49c6c8) at app/app.cpp:74
74          if (argc < 2) {
```
**Q: So, the question is how can I do something similar using vs debugger?**

My guess that, If I would have a gdb console in vs or if I can edit a gdb commands sequence executed by vs then I would be able to tweak it.

This is where my second question comes from.

 I can see all the gdb commands executed in my output window after using this command
`>Debug.MIDebugLog /On /OutputWindow`

```
11: (407732928) ->^done
11: (407732928) ->(gdb)
11: (407732928) 1009: elapsed time 2
11: (407732929) <-1010-file-exec-and-symbols /home/user/projects/.vs/app/bin/x64/Debug/app.out
11: (407732929) ->1010-file-exec-and-symbols /home/user/projects/.vs/app/bin/x64/Debug/app.out
11: (407732934) ->1010^done
11: (407732935) ->1011-break-insert main
11: (407732938) ->1011^done,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="0x004015ec",func="main(int, char const**)",file="/home/user/projects/.vs/app/app/app.cpp",fullname="/home/user/projects/.vs/app/app/app.cpp",line="70",thread-groups=["i1"],times="0",original-location="main"}
11: (407732938) ->(gdb)
```

**Q: Where all those commands coming from? Is there a script of some kind where I can change the steps need to be performed to run the debugger?**

**Comment by ademyankov** [comment]
I forgot to mention that of course I've tried to play around with all the settings in _Property Pages -> Debugging_  like: _Debugger Port Number, Debugging Mode,_ etc...

**Comment by paulmaybee** [comment]
If I understand you correctly you are already able to start aarch64-linux-gnu-gdb on your Windows machine from bash and get it to connect to the qemu hosted gdbserver using gdb's target command?

I believe that you can replicate your experience in VS using the Open Folder debugging experience. Rather than opening your solution, open the folder containing your solution (File->Open->Folder...). Then select your app.out file and right click on it. You should see a menu choice "Debug and Launch Settings" (do to a bug in the released product you will actually have to copy app.out to app.out.exe and then right click on it - this should be fixed in a coming product refresh). After selecting this you will see a "Select a Debugger" popup. Select the "Linux launch (gdb)". Then configure the launch.vs.json to look something like the json below. Save the json and select "qemu via bash" from the "Select Startup Item" menu at the top. Then start the debugger. You will probably want to turn on logging so that you can see what is happening and debug any gdb related issues. In the command window enter "Debug.MiDebugLog /On:<some file path>" to start logging and "Debug.MiDebugLog /Off" to stop it again.

    {
      "type": "cppdbg",
      "name": "qemu via bash",
      "project": "app\\bin\\x64\\Debug\\app.out",
      "cwd": "/home/user/projects/.vs/app/bin/x64/Debug",
      "program": "/home/user/projects/.vs/app/bin/x64/Debug/app.out",
      "MIMode": "gdb",
      "externalConsole": true,
      "remoteMachineName": "localhost",
      "pipeTransport": {
        "pipeProgram": "c:\\Windows\\Sysnative\\bash",
        "pipeArgs": [
          "-c"
        ],
        "debuggerPath": "<path to aarch64-linux-gnu-gdb>"
      },
      "setupCommands": [
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "miDebuggerServerAddress": "localhost:1234",
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
    }

**Comment by ademyankov** [comment]
> If I understand you correctly you are already able to start aarch64-linux-gnu-gdb on your Windows machine from bash and get it to connect to the qemu hosted gdbserver using gdb's target command?

That is correct!

Now, I am having some troubles with the magic you described but, first, I want to say that this stuff is really buggy! Whatever changes you make in launch.vs.json, even if you save them, the IDE doesn't apply it. You have to close the project/folder and reopen it again to make it work. At first, it took me a while to realize that and I spent the whole day fighting it, thinking what the heck I am doing wrong?!

Ok, now to the point.

This is what I get when I try to launch it:
> Unable to start debugging. Unable to establish a connection to GDB.

This is what the log shows:
```
19: (3036675) Starting: "c:/windows/sysnative/bash" -c "/usr/bin/gdb --interpreter=mi"
19: (3036714) "c:/windows/sysnative/bash" exited with code -1 (0xFFFFFFFF).
19: (3036715) <-logout
```

if I try to execute the command from a command line:
`c:/windows/system32/bash -c "/usr/bin/gdb --interpreter=mi"`
it works, it launches the gdb

**Comment by paulmaybee** [comment]
Buggy - hopefully getting better. What version of VS are you using?

If referencing bash out of system32 if working for you "by hand" then try replacing the “sysnative” with “system32” in the json.

**Comment by ademyankov** [comment]
> Buggy - hopefully getting better.

Don't get me wrong, I love Microsoft and Visual Studio, you guys are doing anonymous amount of work, and the fact that I got immediate support for my questions speaks for itself. Thank you for that.

I have the latest VS2017 Verson 15.4.5

So, it turned out that this problem is well-known one, here is the original [issue](https://github.com/Microsoft/vscode-cpptools/issues/877). I needed to install Creators Update to fix it.

Unfortunately, even though, I was able to see in the log that GDB is launched, it worked just for 2-3 times, and now it is broke again. :(
```
7: (634792) Starting: "c:/windows/sysnative/bash" -c "/usr/bin/gdb --interpreter=mi"
7: (635007) ->=thread-group-added,id="i1"
7: (635007) ->~"GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1\n"
7: (635007) ->~"Copyright (C) 2014 Free Software Foundation, Inc.\n"

```
Now, I have no idea why it cannot connect to GDB again. I haven't changed json or whatever. I guess I have to start all over again from scratch.  Purge the folders and modify json in small incremental steps as I did before.

This stuff is as gentle as a nuclear reactor, step to the left, step to the right and you are done! Nothing works anymore.

**Comment by ademyankov** [comment]
BTW

> After selecting this you will see a "Select a Debugger" popup. Select the "Linux launch (gdb)". 

There is no such option in my dialog, there are only:

- Default
- C/C++ attach for MunGW/Cygwin
- C/C++ launch for MunGW/Cygwin
- Managed
- Mixed (Managed + Native)
- Native

but no linux gdb.

I had to select _launch for MunGW/Cygwin_ and just modify the script completely.

**Comment by paulmaybee** [comment]
> There is no such option in my dialog, there are only:

Do you have the "Linux development for C++" option installed?

**Comment by ademyankov** [comment]
I guess so, otherwise I don't think it would work. So, I use this template:
     New Project -> Visual C++ -> Cross Platform -> Linux -> Console Application (Linux)

**Comment by pieandcakes** [comment]
@ademyankov I think @paulmaybee is talking about `C/C++ Launch for Linux (gdb)` as the option for you to choose.
![image](https://user-images.githubusercontent.com/17558378/33458575-9cfe920a-d5db-11e7-8e62-f75ddb89a967.png)

**Comment by ademyankov** [comment]
Yes, that exactly what I sad 2 posts ago. I don't have it.

![image](https://user-images.githubusercontent.com/13845895/33458935-080d0896-d5dd-11e7-95b2-759164d472ca.png)

**Comment by pieandcakes** [comment]
Can you start the "Visual Studio Installer" and see which Workloads you have selected?

**Comment by ademyankov** [comment]
![image](https://user-images.githubusercontent.com/13845895/33459159-ce6ab506-d5dd-11e7-8ad6-a615dbf4e67c.png)

**Comment by ademyankov** [comment]
Ok, I got it. I uninstalled Linux options and installed it again and now I got Linux GDB

![image](https://user-images.githubusercontent.com/13845895/33459469-deb61792-d5de-11e7-9205-fe068b475ad3.png)

**Comment by pieandcakes** [comment]
I think the difference must be the Bottom Optional item to get that menu item. I have it checked on mine and I see the item. Otherwise, yours looks similar to mine under Linux development

**Comment by ademyankov** [comment]
Ok, cool, @paulmaybee I got some good progress finally. So, now it runs gdb but, what is the next step? GDB tries to run the binary which obviously will not work, instead it supposed to connect to remote target.

```
9: (1713478) <-1008-break-insert main
9: (1713479) ->1008^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x004006c0",func="main()",file="/home/ademyankov/projects/app/main.cpp",fullname="/home/ademyankov/projects/app/main.cpp",line="4",thread-groups=["i1"],times="0",original-location="main"}
9: (1713479) ->(gdb)
9: (1713479) 1008: elapsed time 1
9: (1713569) <-1009-exec-run
9: (1713572) ->=thread-group-started,id="i1",pid="117"
9: (1713572) ->=thread-created,id="1",group-id="i1"
9: (1713572) <-1010-thread-info 1
9: (1713575) ->1009^running
9: (1713576) ->*running,thread-id="all"
9: (1713576) 1009: elapsed time 7
9: (1713583) STDERR: /bin/bash: /mnt/c/projects/app/bin/x64/Debug/app.out: cannot execute binary file: Exec format error
9: (1713584) STDERR: /bin/bash: /mnt/c/projects/app/bin/x64/Debug/app.out: Success
9: (1713584) ->=thread-exited,id="1",group-id="i1"
9: (1713584) ->=thread-group-exited,id="i1"
9: (1713585) ->1009^error,msg="During startup program exited with code 126."
```

I modified json parameter: 
`"miDebuggerServerAddress": "10.*.*.100:1234"`

**Comment by paulmaybee** [comment]
Do you have  this line in your json?
 "miDebuggerServerAddress": "localhost:1234",

**Comment by ademyankov** [comment]
I had, but I changed it to have a real remote address, I thought this is how it supposed to work? No?
```
"remoteMachineName": "localhost",
"miDebuggerServerAddress": "10.*.*.100:1234",
```

**Comment by paulmaybee** [comment]
This is the address that gdb should use to talk to qemu (target remote hostname:port). Have you started qemu?  Is gdb issuing a target remote command?  Send me the full log and I’ll take a look.

**Comment by ademyankov** [comment]
Yes, qemu is started and awaits for gdb stub, and this is the entire log:

```
11: (74552070) LaunchOptions{
11: (74552070) LaunchOptions  "target": "\\\\10.1.121.87\\projects\\app\\bin\\x64\\Debug\\app.out.exe",
11: (74552070) LaunchOptions  "type": "cppdbg",
11: (74552070) LaunchOptions  "name": "qemu via bash",
11: (74552070) LaunchOptions  "project": "app.out.exe",
11: (74552070) LaunchOptions  "cwd": "/mnt/c/projects/app/bin/x64/Debug",
11: (74552070) LaunchOptions  "program": "/mnt/c/projects/app/bin/x64/Debug/app.out",
11: (74552070) LaunchOptions  "MIMode": "gdb",
11: (74552070) LaunchOptions  "externalConsole": true,
11: (74552070) LaunchOptions  "remoteMachineName": "itru-ademyankov-ubu",
11: (74552070) LaunchOptions  "pipeTransport": {
11: (74552070) LaunchOptions    "pipeProgram": "c:\\Windows\\Sysnative\\bash",
11: (74552070) LaunchOptions    "pipeArgs": [
11: (74552070) LaunchOptions      "-c"
11: (74552070) LaunchOptions    ],
11: (74552070) LaunchOptions    "debuggerPath": "gdb"
11: (74552070) LaunchOptions  },
11: (74552070) LaunchOptions  "setupCommands": [
11: (74552070) LaunchOptions    {
11: (74552070) LaunchOptions      "text": "-enable-pretty-printing",
11: (74552070) LaunchOptions      "ignoreFailures": true
11: (74552070) LaunchOptions    }
11: (74552070) LaunchOptions  ],
11: (74552070) LaunchOptions  "miDebuggerServerAddress": "10.1.121.87:1234",
11: (74552070) LaunchOptions  "visualizerFile": "${debugInfo.linuxNatvisPath}",
11: (74552070) LaunchOptions  "showDisplayString": true
11: (74552070) LaunchOptions}
11: (74552081) Starting: "c:\Windows\Sysnative\bash" -c "gdb --interpreter=mi"
11: (74552302) ->=thread-group-added,id="i1"
11: (74552303) ->~"GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1\n"
11: (74552303) ->~"Copyright (C) 2014 Free Software Foundation, Inc.\n"
11: (74552303) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
11: (74552303) ->~"This GDB was configured as \"x86_64-linux-gnu\".\nType \"show configuration\" for configuration details."
11: (74552303) ->~"\nFor bug reporting instructions, please see:\n"
11: (74552303) ->~"<http://www.gnu.org/software/gdb/bugs/>.\n"
11: (74552303) ->~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\n"
11: (74552303) ->~"For help, type \"help\".\n"
11: (74552303) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
11: (74552308) ->(gdb)
11: (74552308) <-1001-gdb-set target-async on
11: (74552308) ->1001^done
11: (74552308) ->(gdb)
11: (74552308) 1001: elapsed time 0
11: (74552308) <-1002-enable-pretty-printing
11: (74552309) ->1002^done
11: (74552309) ->(gdb)
11: (74552309) 1002: elapsed time 1
11: (74552309) <-1003-interpreter-exec console "set pagination off"
11: (74552309) ->=cmd-param-changed,param="pagination",value="off"
11: (74552309) ->1003^done
11: (74552309) ->(gdb)
11: (74552309) 1003: elapsed time 0
11: (74552309) <-1004-gdb-set solib-search-path /mnt/c/projects/app/bin/x64/Debug:
11: (74552310) ->1004^done
11: (74552310) ->(gdb)
11: (74552310) 1004: elapsed time 0
11: (74552310) <-1005-environment-cd /mnt/c/projects/app/bin/x64/Debug
11: (74552311) ->1005^done
11: (74552311) ->(gdb)
11: (74552311) 1005: elapsed time 1
11: (74552311) <-1006-file-exec-and-symbols /mnt/c/projects/app/bin/x64/Debug/app.out
11: (74552332) ->1006^done
11: (74552332) ->(gdb)
11: (74552332) 1006: elapsed time 20
11: (74552332) <-1007-interpreter-exec console "show architecture"
11: (74552332) ->~"The target architecture is set automatically (currently i386)\n"
11: (74552332) ->1007^done
11: (74552332) ->(gdb)
11: (74552332) 1007: elapsed time 0
11: (74552332) <-1008-break-insert main
11: (74552333) ->1008^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x004006c0",func="main()",file="/home/ademyankov/projects/app/main.cpp",fullname="/home/ademyankov/projects/app/main.cpp",line="4",thread-groups=["i1"],times="0",original-location="main"}
11: (74552333) ->(gdb)
11: (74552333) 1008: elapsed time 1
11: (74552446) <-1009-exec-run
11: (74552449) ->=thread-group-started,id="i1",pid="131"
11: (74552449) ->=thread-created,id="1",group-id="i1"
11: (74552449) <-1010-thread-info 1
11: (74552453) ->1009^running
11: (74552453) ->*running,thread-id="all"
11: (74552453) 1009: elapsed time 7
11: (74552461) STDERR: /bin/bash: /mnt/c/projects/app/bin/x64/Debug/app.out: cannot execute binary file: Exec format error
11: (74552461) STDERR: /bin/bash: /mnt/c/projects/app/bin/x64/Debug/app.out: Success
11: (74552461) ->=thread-exited,id="1",group-id="i1"
11: (74552461) ->=thread-group-exited,id="i1"
11: (74552461) ->1009^error,msg="During startup program exited with code 126."
11: (74552461) ->(gdb)
11: (74552461) ->1010^done,threads=[]
11: (74552461) ->(gdb)
11: (74552462) 1010: elapsed time 13
11: (74552462) <-logout
11: (74552462) <--gdb-exit
11: (74552462) ->&"logout\n"
```

**Comment by paulmaybee** [comment]
Sorry, misdirected you no the miDebuggerServerAddress, that only seems to work when attaching to a specific process id. In this case you don't seem to have one so you'll have to give a couple of custom launch commands. Try removing the miDebuggerServerAddress and instead add this json element:

      "customLaunchSetupCommands": [
        {
          "text": "-file-exec-and-symbols /mnt/c/projects/app/bin/x64/Debug/app.out",
          "ignoreFailures": false
        },
        {
          "text": "-target-select remote 10.*.*.100:1234",
          "ignoreFailures": false
        }
      ],

**Comment by ademyankov** [comment]
![image](https://user-images.githubusercontent.com/13845895/33508399-f2644bf8-d6ae-11e7-8282-eda9ebedf5dc.png)

Is there a documentation of all those keys, options and command for MI supported debuggers? Otherwise I am like a blind kitten...

**Comment by paulmaybee** [comment]
Unfortunately there is no documentation outside of the schema - except the code (https://github.com/Microsoft/MIEngine/). Also unfortunately, since I cannot set up a repo of your environment, I also have to do a little guessing as to what will work for you. For this particular error try adding: "targetArchitecture": "ARM".

**Comment by ademyankov** [comment]
Ok, @paulmaybee we have some good progress finally! targetArchitecture helped, and I set up the right gdb to use. So, I was able to get to the point where gdb connects to qemu and launches the vm. Now, I am trying to figure out why it complains that _Cannot find or open the symbol file._ and another problem I am confused about breakpoint, now, it the log I don't see that a breakpoint to main is set up anywhere, and as you can imagine, it didn't break when I run app inside of vm.

```
10: (3200225) Starting: "c:\Windows\Sysnative\bash" -c "/home/ademyankov/projects/optee/toolchains/aarch64/bin/aarch64-linux-gnu-gdb --interpreter=mi"
10: (3200491) ->=thread-group-added,id="i1"
10: (3200491) ->~"GNU gdb (Linaro_GDB-2016.11) 7.12.0.20161122-git\n"
10: (3200491) ->~"Copyright (C) 2016 Free Software Foundation, Inc.\n"
10: (3200491) ->~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
10: (3200491) ->~"This GDB was configured as \"--host=x86_64-unknown-linux-gnu --target=aarch64-linux-gnu\".\nType \"show configuration\" for configuration details."
10: (3200491) ->~"\nFor bug reporting instructions, please see:\n"
10: (3200491) ->~"<http://www.gnu.org/software/gdb/bugs/>.\n"
10: (3200491) ->~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\n"
10: (3200491) ->~"For help, type \"help\".\n"
10: (3200491) ->~"Type \"apropos word\" to search for commands related to \"word\".\n"
10: (3200491) ->(gdb)
10: (3200491) <-1001-gdb-set target-async on
10: (3200491) ->1001^done
10: (3200491) ->(gdb)
10: (3200492) 1001: elapsed time 1
10: (3200492) <-1002-enable-pretty-printing
10: (3200492) ->1002^done
10: (3200492) ->(gdb)
10: (3200492) 1002: elapsed time 0
10: (3200492) <-1003-interpreter-exec console "set pagination off"
10: (3200492) ->=cmd-param-changed,param="pagination",value="off"
10: (3200492) ->1003^done
10: (3200492) ->(gdb)
10: (3200493) 1003: elapsed time 0
10: (3200493) <-1004-gdb-set solib-search-path /mnt/c/projects/app/bin/x64/Debug:
10: (3200493) ->1004^done
10: (3200493) ->(gdb)
10: (3200493) 1004: elapsed time 0
10: (3200493) <-1005-file-exec-and-symbols /mnt/c/projects/app/bin/x64/Debug/app.out
10: (3200497) ->1005^done
10: (3200497) ->(gdb)
10: (3200497) 1005: elapsed time 4
10: (3200497) <-1006-target-select remote 10.1.121.87:1234
10: (3210582) ->=thread-group-started,id="i1",pid="42000"
10: (3210582) ->=thread-created,id="1",group-id="i1"
10: (3210582) <-1007-thread-info 1
10: (3210605) ->&"warning: remote target does not support file transfer, attempting to access files from local filesystem.\n"
10: (3210605) ->&"warning: Unable to find dynamic linker breakpoint function.\nGDB will be unable to debug shared library initializers\nand track explicitly loaded dynamic code."
10: (3210605) ->&"\n"
10: (3210619) ->~"0x0000000000000000 in ?? ()\n"
10: (3210619) ->*stopped,frame={addr="0x0000000000000000",func="??",args=[]},thread-id="1",stopped-threads="all"
10: (3210621) ->1006^connected
10: (3210622) ->(gdb)
10: (3210622) 1006: elapsed time 10124
10: (3210629) ->1007^done,threads=[{id="1",target-id="Thread 1",details="CPU#0 [running]",frame={level="0",addr="0x0000000000000000",func="??",args=[]},state="stopped"}]
10: (3210629) ->(gdb)
10: (3210629) 1007: elapsed time 47
10: (3210746) <-1008-interpreter-exec console "info sharedlibrary"
10: (3210749) ->~"No shared libraries loaded at this time.\n"
10: (3210749) ->1008^done
10: (3210749) ->(gdb)
10: (3210749) 1008: elapsed time 3
10: (3210750) <-1009-thread-info
10: (3210758) ->1009^done,threads=[{id="1",target-id="Thread 1",details="CPU#0 [running]",frame={level="0",addr="0x0000000000000000",func="??",args=[]},state="stopped"}],current-thread-id="1"
10: (3210758) ->(gdb)
10: (3210758) 1009: elapsed time 7
10: (3210758) <-1010-stack-list-frames 0 1000
10: (3210758) ->1010^done,stack=[frame={level="0",addr="0x0000000000000000",func="??"}]
10: (3210758) ->(gdb)
10: (3210758) 1010: elapsed time 0
10: (3210758) <--exec-continue
10: (3210758) ->^running
10: (3210758) ->*running,thread-id="all"
10: (3210763) ->(gdb)
10: (3224326) STDERR: c:\Windows\Sysnative\bash -c "kill -2 42000" exited with exit code 2
10: (3224326) <-1011-exec-interrupt
10: (3224326) ->1011^done
10: (3224326) ->(gdb)
10: (3224326) 1011: elapsed time 0
10: (3224346) ->~"\nProgram"
10: (3224346) ->~" received signal SIGINT, Interrupt.\n"
10: (3224346) ->~"0xffff000008097e18 in ?? ()\n"
10: (3224346) ->*stopped,reason="signal-received",signal-name="SIGINT",signal-meaning="Interrupt",frame={addr="0xffff000008097e18",func="??",args=[]},thread-id="1",stopped-threads="all"
10: (3224346) <-1012kill
10: (3224347) ->&"kill\n"
10: (3224347) ->~"Kill the program being debugged? (y or n) [answered Y; input not from terminal]\n"
10: (3224352) ->=thread-group-exited,id="i1"
10: (3224352) <-logout
10: (3224352) ->1012^done
10: (3224354) <--gdb-exit
```

**Comment by paulmaybee** [comment]
Where are you seeing the “cannot read or open symbol file” message?  I don’t see it in the log. You should be able to set breakpoints on source lines as usual in visual studio before launching.

**Comment by ademyankov** [comment]
I see that in vs2017 output window:
![image](https://user-images.githubusercontent.com/13845895/33582140-a1eb409e-d908-11e7-9b7e-5c8e0109c9a7.png)

Ok, so I totally confused now. How am I supposed to use that magic Open Folder stuff? Because, now, I don't have any project files or source files opened, like I would have in a regular vs2017 project! I am using that Open Folder stuff:
![image](https://user-images.githubusercontent.com/13845895/33582195-e981e11a-d908-11e7-87b7-9756d6457900.png)

Am I supposed to add that laucnch.vs.json to my regular vs2017 project somewhere? And then how would I run it? Or it has to be opened as a vs2017 project in a separate vs2017 instance?

It's just I've never ever used that Open Folder debugger, no idea how it is supposed to be used.

**Comment by ademyankov** [comment]
So, to clarify, my app is a regular vs2017 project but, it's just built for aarch64, like this:

![image](https://user-images.githubusercontent.com/13845895/33582802-e911adde-d90b-11e7-98f4-b03e6192f52c.png)

**Comment by ademyankov** [comment]
Ok, I am watching [Bring your C++ codebase to Visual Studio with “Open Folder”](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/bring-your-c-codebase-to-visual-studio-with-open-folder/)... I'll let you know if I encounter any problems...

**Comment by ademyankov** [comment]
Ok! I got it working... This is freacking awesome!  👍  Thanks @paulmaybee  🥇 

![image](https://user-images.githubusercontent.com/13845895/33584532-b69c6606-d914-11e7-8c7c-0fbd2acf6f05.png)
