### ISSUE TITLE
Linker - 'Additional Library Directories' dose NOT support relative directory

### ISSUE THREAD

**Issue by ldcsaa** [microsoft/VSLinux#229]
Linker -> 'Additional Library Directories' does NOT support relative directory
but 
C/C++ -> 'Additional Include Directories' does support ~

and
'VC++ Directories' -> 'Library Directories' does NOT WORK at all  !!!

**Comment by yuehuang010** [comment]
Hello, in VS 15.7 Preview 1, the translator for paths has been revamp.  Please take a look to see if your issue is resolved.

**Comment by itodirel** [comment]
same underlying issue as #66

**Comment by itodirel** [comment]
same issue as #325

**Comment by itodirel** [comment]
Closed as dupe
