### ISSUE TITLE
When will release a new version?

### ISSUE THREAD

**Issue by ldcsaa** [Microsoft/VSLinux#230]
I wait it for a long time , please tell me ~~~

**Comment by itodirel** [comment]
Hi, we are making updates to the Linux tooling continuously, and usually have updates in every release of Visual Studio (15.6, 15.7, 15.8 etc). The most recent major features we added was CMake support in 15.6 Preview 2 and remote system headers copy support in 15.7 Preview 2. If there is something specific you are looking for please don't hesitate to ask.

We are not updating the Visual Studio 2015 Linux extension anymore, please install Visual Studio 2017, which has it, and which is where our development focus is.

**Comment by ldcsaa** [comment]
Oh ~Thanks a lot ...
