### ISSUE TITLE
Linux build error lookup doesn't jump to source code lines

### ISSUE THREAD

**Issue by AndreVergison** [microsoft/VSLinux#231]
The actual output window shows, for instance:

1>  /home/xyz/projects/Linux1/pch.cpp:188: error: ‘chunk’ was not declared in this scope
1>  /home/xyz/projects/Linux1/pch.cpp:188: error: ‘data’ was not declared in this scope
1>  /home/xyz/projects/Linux1/pch.cpp:190: error: ‘strcpy’ was not declared in this scope

Double clicking on those lines does nothing at all.
I did expect a kind of mapping of the linux paths back to the local paths. Can this be activated, or is that functionality not present?

Thanks,
Andre

VC2017 15.5.1, g++ 4.4.7 on up to date CentOS, gdb and gdbserver 7.2-92.el6

**Comment by AndreVergison** [comment]
In addition I also see a bunch of lines such as ...

1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(259,5): warning : conversion to ‘UCHAR’ from ‘int’ may alter its value

... on which double clicking shows some indigestable xml:

    <Compile Condition="'@(RemoteClCompile)' != ''"
      ProjectDir="$(ProjectDir)"
      RemoteProjectDir="$(_ResolvedRemoteProjectDir)"
      IntermediateDir="$(IntDir)"
      RemoteTarget="$(ResolvedRemoteTarget)"
      RemoteClCompile="@(RemoteClCompile)"
      ClInclude="@(ClInclude)"
      UpToDateFile="$(CompileUpToDateFile)"
      Timeout="$(RemoteCompileCommandTimeout)"
      CopyObjectFiles="$(RemoteCompileLocalCopyObjectFiles)">
      <Output TaskParameter="RemoteLink" ItemName="RemoteLink"/>
      <Output TaskParameter="IsCompileUpToDate" PropertyName="IsCompileUpToDate"/>
    </Compile>

**Comment by AndreVergison** [comment]
My project also has .cpp files generated from master files (.mf). Files are generated with #line directives pointing back to the master file. Gcc returns any errors and shows them in VS as:

../myfolder/myfile.mf:250: warning: unused variable ‘n’

Double clicking on such lines will open the master file (which is a good thing), but it will NOT go to line 250, what was expected.

**Comment by AndreVergison** [comment]
Also posted as https://developercommunity.visualstudio.com/content/problem/164691/linux-build-error-lookup-doesnt-jump-to-source-cod.html

**Comment by iwubcode** [comment]
I agree this would be useful, I opened #225 to try and capture this issue as well.

**Comment by yuehuang010** [comment]
Hello, this feature is started.  The vs error parser isn't compatible with error produced by gcc.

**Comment by yuehuang010** [comment]
Hi, could you try out 15.7 Preview?  You will see errors in the error list and should be able to double click to the file/line/column.

**Comment by deiruch** [comment]
At least for me, it doesn't work in 15.7.4. The errors do not show up in the Error List, and clicking error messages doesn't jump to the correct source file. Here's a snippet of the build output:


```
[…]
sparc-rtems-gcc --pipe -B/opt/rtems-4.8/sparc-rtems/leon3/lib/ -specs bsp_specs -qrtems   -DHW_VERSION_AX_IDPU -ffunction-sections -fdata-sections -mno-fpu -msoft-float -mcpu=v8 -fno-builtin -W -Wall -Wextra -Winit-self -Wredundant-decls  -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wundef -pedantic -Wunused-variable -Wunused-parameter -Wunused-label -Wunused-function -Wunused-value -Wparentheses -Wreturn-type -Wswitch -Waggregate-return -Wnested-externs -std=c99 -fgnu89-inline -g0 -Os -DHW_TESTING  -IBSW_ASW/src/. -IBSW_ASW/src/BSW/include -IASW/src -IASW/src/Timing -IASW/src/include -c BSW_ASW/src/BSW/Flash/ECC.c -o ASW/obj/BSW_ASW/src/BSW/Flash/ECC.o_em
sparc-rtems-gcc --pipe -B/opt/rtems-4.8/sparc-rtems/leon3/lib/ -specs bsp_specs -qrtems   -DHW_VERSION_AX_IDPU -ffunction-sections -fdata-sections -mno-fpu -msoft-float -mcpu=v8 -fno-builtin -W -Wall -Wextra -Winit-self -Wredundant-decls  -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wundef -pedantic -Wunused-variable -Wunused-parameter -Wunused-label -Wunused-function -Wunused-value -Wparentheses -Wreturn-type -Wswitch -Waggregate-return -Wnested-externs -std=c99 -fgnu89-inline -g0 -Os -DHW_TESTING  -IBSW_ASW/src/. -IBSW_ASW/src/BSW/include -IASW/src -IASW/src/Timing -IASW/src/include -c BSW_ASW/src/BSW/Flash/ECC.c -MM -MT ASW/obj/BSW_ASW/src/BSW/Flash/ECC.o_em > ASW/obj/BSW_ASW/src/BSW/Flash/ECC.o_em_d
sparc-rtems-gcc --pipe -B/opt/rtems-4.8/sparc-rtems/leon3/lib/ -specs bsp_specs -qrtems   -DHW_VERSION_AX_IDPU -ffunction-sections -fdata-sections -mno-fpu -msoft-float -mcpu=v8 -fno-builtin -W -Wall -Wextra -Winit-self -Wredundant-decls  -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wundef -pedantic -Wunused-variable -Wunused-parameter -Wunused-label -Wunused-function -Wunused-value -Wparentheses -Wreturn-type -Wswitch -Waggregate-return -Wnested-externs -std=c99 -fgnu89-inline -g0 -Os -DHW_TESTING  -IBSW_ASW/src/. -IBSW_ASW/src/BSW/include -IASW/src -IASW/src/Timing -IASW/src/include -c BSW_ASW/src/BSW/Flash/File.c -o ASW/obj/BSW_ASW/src/BSW/Flash/File.o_em
BSW_ASW/src/BSW/Flash/File.c: In function 'File_write':
BSW_ASW/src/BSW/Flash/File.c:386: warning: 'mask' may be used uninitialized in this function
BSW_ASW/src/BSW/Flash/File.c:386: note: 'mask' was declared here
sparc-rtems-gcc --pipe -B/opt/rtems-4.8/sparc-rtems/leon3/lib/ -specs bsp_specs -qrtems   -DHW_VERSION_AX_IDPU -ffunction-sections -fdata-sections -mno-fpu -msoft-float -mcpu=v8 -fno-builtin -W -Wall -Wextra -Winit-self -Wredundant-decls  -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wundef -pedantic -Wunused-variable -Wunused-parameter -Wunused-label -Wunused-function -Wunused-value -Wparentheses -Wreturn-type -Wswitch -Waggregate-return -Wnested-externs -std=c99 -fgnu89-inline -g0 -Os -DHW_TESTING  -IBSW_ASW/src/. -IBSW_ASW/src/BSW/include -IASW/src -IASW/src/Timing -IASW/src/include -c BSW_ASW/src/BSW/Flash/File.c -MM -MT ASW/obj/BSW_ASW/src/BSW/Flash/File.o_em > ASW/obj/BSW_ASW/src/BSW/Flash/File.o_em_d
sparc-rtems-gcc --pipe -B/opt/rtems-4.8/sparc-rtems/leon3/lib/ -specs bsp_specs -qrtems   -DHW_VERSION_AX_IDPU -ffunction-sections -fdata-sections -mno-fpu -msoft-float -mcpu=v8 -fno-builtin -W -Wall -Wextra -Winit-self -Wredundant-decls  -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wundef -pedantic -Wunused-variable -Wunused-parameter -Wunused-label -Wunused-function -Wunused-value -Wparentheses -Wreturn-type -Wswitch -Waggregate-return -Wnested-externs -std=c99 -fgnu89-inline -g0 -Os -DHW_TESTING  -IBSW_ASW/src/. -IBSW_ASW/src/BSW/include -IASW/src -IASW/src/Timing -IASW/src/include -c BSW_ASW/src/BSW/Flash/Flash.c -o ASW/obj/BSW_ASW/src/BSW/Flash/Flash.o_em
sparc-rtems-gcc --pipe -B/opt/rtems-4.8/sparc-rtems/leon3/lib/ -specs bsp_specs -qrtems   -DHW_VERSION_AX_IDPU -ffunction-sections -fdata-sections -mno-fpu -msoft-float -mcpu=v8 -fno-builtin -W -Wall -Wextra -Winit-self -Wredundant-decls  -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wundef -pedantic -Wunused-variable -Wunused-parameter -Wunused-label -Wunused-function -Wunused-value -Wparentheses -Wreturn-type -Wswitch -Waggregate-return -Wnested-externs -std=c99 -fgnu89-inline -g0 -Os -DHW_TESTING  -IBSW_ASW/src/. -IBSW_ASW/src/BSW/include -IASW/src -IASW/src/Timing -IASW/src/include -c BSW_ASW/src/BSW/Flash/Flash.c -MM -MT ASW/obj/BSW_ASW/src/BSW/Flash/Flash.o_em > ASW/obj/BSW_ASW/src/BSW/Flash/Flash.o_em_d
[…]
```

**Comment by deiruch** [comment]
It appears that the parser currently only supports errors and warnings that include a column marker:

Not yet supported:
```
ASW/src/QLDataAcq/QLAccuDblBuffs.c:436: warning: passing argument 2 of 'IIR_getElapsedTime' discards qualifiers from pointer target type
                                  ^^^^^
```


Supported:
```
ASW/src/XrayDataRTProc/FlareDetector.c:63:1: warning: "SCALE_K" redefined
                                      ^^^^^^
```

**Comment by mostevercxz** [comment]
I came into this issue today, and found a simple solution which redirects the stdout and stderr of gcc and then uses `sed` to replace gcc output to visual-studio-supported output.

I tested under linux using the following command:
```
make 3>&1 1>&2 2>&3 3>&- | sed 's /var/tmp/src/........\-....\-....\-....\-............/Linux\-Debug/\(.*\):\([0-9]*\):\([0-9]*\): \1(\2):\3 '
```

And here is my `CMakeSettings.json` file in the cmake project directory on Windows:
```
{
  "configurations": [
  {
    "buildCommandArgs": "-j 32 3>&1 1>&2 2>&3 3>&- | sed 's /var/tmp/src/........\\-....\\-....\\-....\\-............/Linux\\-Debug/\\(.*\\):\\([0-9]*\\):\\([0-9]*\\): \\1(\\2):\\3 '",
  }
  ]
}
```

**Comment by itodirel** [comment]
We believe this has been fixed quite a while ago in the latest version of VS, please open a issue on the Developer Community if you see any problems here, but we don't expect you to.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community
