### ISSUE TITLE
[ Debugging ] Double clicking callstack when attached does not open source file in project

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#232]
**Description**

When attaching to a remote process, double clicking on a callstack leads to unexpected results.

**Expected results**

Double clicking on the callstack should open the file in the project if applicable, or open a "cannot find file" dialog if unavailable.

**Actual results**

Double clicking on the callstack always opens a "cannot find file" dialog.

**Environment**

Visual Studio 2017 15.6 Preview 1
CMake 3.9.0

**Steps required to reproduce the error**

- Load project up
- Attach to remote process
- Double click callstack
- See how the 'cannot find file' dialog is opened even if the file exists in the project

**Comment by iwubcode** [comment]
My apologies if I'm remembering wrong but I thought the "Expected Results" was how Visual Studio worked with Windows projects.

**Comment by paulmaybee** [comment]
The attach experience is unrelated to the folder you currently have open, so unfortunately the source mapping from build file name (on the remote machine) to the location of that file on the local machine is not established. The launch experience does behave as you expect. However for attach it would be nice to at least look to the opened folder to establish some source context. We will look at adding this in a future product update.

**Comment by paulmaybee** [comment]
Mapping sources properly when attaching is now possible. With VS 15.7 preview 1 and later you can specify a SourceMap in the optional Microsoft.MIEngine.Options.xml configuration file (see https://blogs.msdn.microsoft.com/vcblog/2018/03/13/linux-c-workload-improvements-to-the-project-system-linux-console-window-rsync-and-attach-to-process/).


Something like:

```
<?xml version="1.0" encoding="utf-8"?>
<SupplementalLaunchOptions>
    <AttachOptions>
      <AttachOptionsForConnection AdditionalSOLibSearchPath="/home/user/solibs">
        <ServerOptions MIDebuggerPath="C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\VC\Linux\bin\gdb\7.9\x86_64-linux-gnu-gdb.exe"
ExePath="C:\temp\ConsoleApplication17\ConsoleApplication17\bin\x64\Debug\ConsoleApplication17.out"/>
        <SourceMap>
          <SourceMapEntry EditorPath="c:\\users\\me\\mySolution" CompileTimePath="/home/me/projects/myProject/>
        </SourceMap>
      </AttachOptionsForConnection>
    </AttachOptions>
</SupplementalLaunchOptions>
```

Where the **EditorPath** points to the root of your source on your Windows machine and the **CompileTimePath** points to the root of your source on the Linux machine where you build it.
