### ISSUE TITLE
VS fails to relink project if only a dependent static library is built

### ISSUE THREAD

**Issue by drrggibbs** [Microsoft/VSLinux#233]
I have a project that links to several static libraries (.a). If I edit a source file in one of the projects that builds a static library and select the main project for build, then VS compiles the edited file and regenerates the static library, but does not relink the main project. VS reports success.

To make VS relink the main project it is necessary to edit a source file in the main project, then it will compile the edited file and relink to the static libraries, after building them if necessary.

Using VS2015 with VSLinux 1.0.7

**Comment by drrggibbs** [comment]
Same behavior with VS 2017 (15.5.2) and VC Linux 1.0.8

**Comment by yuehuang010** [comment]
Hello, VS 15.7 Preview 1 has addressed incremental build.  Please give it a try and let us know if you encounter any problems.

**Comment by drrggibbs** [comment]
I just downloaded VS 2017 15.7.3 with Visual C++ for Linux 1.0.9. I'm still seeing a problem. The static library builds but the main project does not link

**Comment by Chronodt** [comment]
Still seeing this problem on VS 15.8.9 as well. Need to either manually link with Project Only->Link only on the main executable or trivially modify a single file in the main project so it recompiles as well and then links
