### ISSUE TITLE
VS does not recompile source files when an External Dependency changes

### ISSUE THREAD

**Issue by drrggibbs** [Microsoft/VSLinux#235]
I have projects setup with only the source files included, none of the header files. However VS is able to find header files and list them in the External Dependencies. If I edit one of these headers then build the project it does not build the source files dependent on this header, though apparently VS is aware of which source files are dependent on which headers.

On the other hand, if I add a header file to the project, then whenever I edit the header file and build the project it recompiles everything, not just the source files dependent on the header.

Using VS 2015 and VSLinux 1.0.7

**Comment by drrggibbs** [comment]
Same behavior with VS 2017 (15.5.2) and VC Linux 1.0.8

**Comment by itodirel** [comment]
Using #29 for tracking. And marking as duplicate.
