### ISSUE TITLE
Custom Build Tool executes on Windows machine, not Linux machine

### ISSUE THREAD

**Issue by drrggibbs** [Microsoft/VSLinux#236]
I tried to set up a custom build tool for a file, i.e. I right clicked on the file in the project and set Configuration Properties > General > Item Type to "Custom Build Tool". However when I try to build the project, the custom build is executed on the local Windows machine, not the remote Linux machine.

Shouldn't the custom build tool be set to send a command to Linux?

A work around is to set the file as a "C/C++ compiler" Item Type, set Configuration Properties > C/C++ > Advanced > Compile As to "Compile as C++ Code", then set the C++ Compiler for the project to some arbitrary Linux command. The only problem then is that all the compiler options are passed to this command, so it takes a bit of effort to sort out which ones to use and which to ignore. Also, this requires a separate project for each custom build tool because setting the C++ Compiler property can only be done at the project level

Using VS 2015 and VSLinux 1.0.7

**Comment by itodirel** [comment]
We have pre and post build events that execute remotely, would those work for you?

**Comment by drrggibbs** [comment]
I think a pre or post build event only applies to the project as a whole, so it's not really the same thing as just applying a custom build operation to a single file in a project.

**Comment by itodirel** [comment]
Hi, could you tell us how and commands you would execute with the custom build tool?

**Comment by itodirel** [comment]
copied to backlog
