### ISSUE TITLE
Program output not going to Linux Console in gdb Debugging Mode

### ISSUE THREAD

**Issue by drrggibbs** [Microsoft/VSLinux#238]
If the Debugging Mode is set to gdbserver then std::cout output goes to the Linux Console. This can also be used for cin. So everything is fine.

If the Debugging Mode is set to gdb then cout goes to the Output window and cin causes a dialog to display, saying "Stopped (tty input)". The only effective choice is to select "Break" and abort.

Because in one setup I'm using I don't have admin privileges and gdbserver is not installed, it's not an option, and getting it installed is a big headache.

So is this a bug or is it an unavoidable consequence of using gdb?

Also, the output to Output window in gdb mode may be corrupted. If a line starts with numeric characters, then these characters are not output, e.g. if the output is 1234.56, then only .56 is actually displayed

Using VS 2015 and VSLinux 1.0.7

**Comment by drrggibbs** [comment]
I also just realized that if the mode is gdbserver and the program is waiting for input on cin, the only indication is whatever message is displayed on the Linux Console, which may be a problem if the window is not even open.

**Comment by lukka** [comment]
@drrggibbs I/O redirection has been added for gdbserver mode on VS2017, could you please try it? Your feedback is welcome

**Comment by drrggibbs** [comment]
Output goes to the Linux Console in both gdb mode and gdbserver mode in
Visual Studio 2017/ VSLinux 1.0.8. Is version 1.0.8 only available with VS
2017?

Richard

**Comment by lukka** [comment]
@drrggibbs yes, VS 2017 is required.
