### ISSUE TITLE
Linux Console Window processes lines twice when using cin or scanf

### ISSUE THREAD

**Issue by davideideticom** [Microsoft/VSLinux#241]
When reading inputs in the linux console window connected to a remote machine (64-bit Ubuntu) the cin << ... or scanf functions appear to be interpenetrating lines twice.  That is, if I cin << int_var twice in my program it will read the same number from my first input line in the console window and will not block the second time.

I am using g++ in visual studio community version 15.5.2; g++ version 5.4, gdb version 7.11.1, gdbserver version 7.11.1, and am running my code remotely on an Intel based x64 server running Ubuntu 4.12.3

**Comment by lukka** [comment]
@davideideticom I tried the same scenario on 15.5.2 and cannot reproduce this problem. Could you please provide a small repro of the problem? Thanks for your support.

**Comment by davideideticom** [comment]
Sorry about that, I have since rebooted the linux box and the issue went away.  It appears to be an issue on my end.
