### ISSUE TITLE
Method to copy source files from ALL projects to remote machine?

### ISSUE THREAD

**Issue by SamuelHenderson** [microsoft/VSLinux#244]
My solution has 9 Visual C++ for Linux Projects in it.  There is one application (.out) project and a bunch of dynamic library (.so) projects.  Some of these library projects rely on headers found in another library project, something like:
`// In some file in LibraryA`
`#include "../LibraryB/LibB.h`

I have set up the Depedencies in Visual Studio such that LibraryB depends on LibraryA (because it does), but LibraryA also needs to see structure definitions of LibraryB ...  When I click 'Solution->Rebuild' (or 'Solution->Clean' + 'Solution->Build') it removes all remote project directories (as expected).  Then it copies the source for each project only when it begins building it.  This of course fails to build all the projects, my work around thus far has been to call 'Solution->Build' an extra time after calling 'Solution->Rebuild' (which of course works because the source files for all the projects are now copied to their respective project directories) but this is getting time consuming and I'm wondering if there is something I am missing?

* Visual C++ 2017 (15.6.0 Preview 1)
* Visual C++ For Linux Development 1.0.8
* Fedora 26 with gcc 7.1.1

* Steps required to reproduce the error
Create a Solution in Visual Studio that has multiple C++ For Linux Development Projects.  In each project reference a header file that is in one of the other projects and click 'Solution->Rebuild'.  It will fail causing you to have to click 'Solution->Build' an additional time.

**Comment by itodirel** [comment]
could you use remote build events to do the additional copying?

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
