### ISSUE TITLE
Add sooport of the serial port (tty) connection to gdbserver

### ISSUE THREAD

**Issue by youreeck** [Microsoft/VSLinux#245]
The **gdbserver** supports two ways to connect remote debugger: **SSH** or **serial port**. The first one is very common, but in real devices for production the option to connect over **Ethernet** is often **disabled** or Ethernet port is used for other purposes. In this case the user may have **a serial port connection to debug**. Unfortunately Visual Studio does not support it. There are plenty others tools such as _QTDebugger_, _NetBeans_ and very old friend _DDD_ supports this.

**Comment by robotdad** [comment]
Do you have an example you can point us to for this? Is this for an embedded device or ...?

**Comment by youreeck** [comment]
Yes, this is embedded device, where we have Ethernet network card. But this card will be used to send and receive the messages from other devices. We also expected that the performance of the Ethernet card is a point of our special attention. Doing this our application use "exclusive mode" for network card, which means no other application can send/receive the Ethernet frames via this device. And of course, if we use the same Ethernet port to debug the device we change the behavior of the system. To avoid this we select the serial port. In this case we can check if we hit the breakpoint, internal data and so on without to use typical "printf" debug technic (which is also slow down the performance). In our case it did help to find the bottleneck. Of course, the TCP/IP is more comfortable and faster way for remote debugging, but it is not always available in the field.

**Comment by itodirel** [comment]
Hi, we do not support it, but, Putty should. So something that can be done is to connect over serial with Putty, then tunnel that and connect to the tunnel from VS. Please let me know if this is something you can try, and I can provide more info.

**Comment by itodirel** [comment]
Hi, let me know if you made this work or if you need help, this should in theory work, but if you want me to try first, I can do that
