### ISSUE TITLE
[CMAKE] "remoteInstallRoot" resp. "install( TARGETS ..." at remote Linux doesn't work

### ISSUE THREAD

**Issue by jensreck** [Microsoft/VSLinux#246]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

Install of build result at remote Linux doesn't work, not output folder on remote Linux will be created and no outputs (build results) will be copied (to any folder).

* Expected results

see above...

* Actual results (with build output window contents if applicable)

Using CMake "Hello world" project, source copy and build works well at windows and also at remote Linux (Mint 18.2). 
**Linux:**
"remoteCMakeListsRoot" --> ok, sources copied
"remoteBuildRoot" --> ok, built
**Windows:**
"buildRoot": --> ok, built

While install at Windows configuration works fine because there is a context menu entry "Install" at "CMakeLists.txt", this entry is missing after switching to remote Linux configuration. 
**Linux:**
"remoteInstallRoot" --> nok, no "Install" entry
**Windows:**
"installRoot": --> ok, "Install" available

**Linux:**
"remoteCMakeListsRoot": "/var/tmp/${workspaceHash}/source/${env.MSC_TARGET_NAME}/${configurationType}",
"remoteBuildRoot": "/var/tmp/${workspaceHash}/build/${env.MSC_TARGET_NAME}/${configurationType}",
"remoteInstallRoot": "/var/tmp/${workspaceHash}/install/${env.MSC_TARGET_NAME}/${configurationType}",
"remoteCopySources": true,
"remoteCopySourcesOutputVerbosity": "Diagnostic",
"remoteCopySourcesConcurrentCopies": "10",
"remoteCopySourcesMethod": "sftp",
**Windows:**
"buildRoot": "${workspaceRoot}\\private\\generated\\${env.MSC_TARGET_NAME}\\${configurationType}", // CMAKE_BINARY_DIR
"installRoot": "${workspaceRoot}\\public\\bin\\${env.MSC_TARGET_NAME}\\${configurationType}", // CMAKE_INSTALL_PREFIX

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Microsoft Visual Studio Professional 2017 Preview
Version 15.6.0 Preview 2.0
VisualStudio.15.Preview/15.6.0-pre.2.0+27309.0
Microsoft .NET Framework
Version 4.7.02046

**Comment by jensreck** [comment]
any suggestions?

**Comment by lukka** [comment]
@jensreck thanks for the report. 
The "install target" feature for Linux has not been implemented yet. No ETA or promise about when it will.

Currently the only workaround I see is to run manually the install command, or by using 

``` 
"remotePostbuildCommand": "make install",
``` 

in your CMakeSettings.json file which will be executed after each build.
