### ISSUE TITLE
Questions about version

### ISSUE THREAD

**Issue by drrggibbs** [Microsoft/VSLinux#248]
The only info I can find about the current version of VC Linux on the web is from sites such as https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.VisualCforLinuxDevelopment which talks about version 1.0.7 for VS 2015. However VS 2017 has version 1.0.8, but I can find no information about this release. Is there a current release information page somewhere?

Is support for VS 2015 stopping with 1.0.7? It's going to be a challenge to get my employer to progress from VS 2015 to VS 2017 any time soon.

**Comment by robotdad** [comment]
We are only investing in VS 2017. Version 1.0.7 is the last for VS 2015. 

Release notes for VS 2017 include additions for the Linux C++ workload.

**Comment by drrggibbs** [comment]
Thank you for the clarification. It would be helpful for people like me, i.e. stuck with VS2015 in the work environment, if you could state on these web pages that talk about VC Linux for VS 2015 that there will be no support beyond version 1.0.7. This would then provide justification for pushing managers to install VS 2017.

**Comment by itodirel** [comment]
We updated the extension page to mention that development is in Visual Studio 2017
