### ISSUE TITLE
Security concern about stored credentials of remote machine

### ISSUE THREAD

**Issue by drrggibbs** [Microsoft/VSLinux#249]
I was wondering how securely passwords for the remote machine are stored. Are they in the registry or the user's AppData or somewhere else? How securely are they encrypted?

Maybe there should be an option not to store the password permanently. Maybe it should be stored in memory when one first logs on, such as Pageant does with the passwords for keys.

**Comment by itodirel** [comment]
we're storing it on the file system, on a per user basis only, and we encrypt it using the Windows DPAPI, which uses the current user secrets to encrypt it, that means no one but the current user can access it and decrypt it; we are not planning on doing something like Pageant, or storing it in memory

**Comment by itodirel** [comment]
Please le us know if you have other questions or concerns
