### ISSUE TITLE
Attach to running proccess with process name

### ISSUE THREAD

**Issue by sebastue** [Microsoft/VSLinux#251]
It is only possible to attach to a running process with the process id. This process id is always changing. So you always have to modify the 'processId' in the launch configuration and it is not possible to create templates. 
A better solution would be to specify a "processName" to attach to this process. For the process name it should be possible to use environment variables like '${debugInfo.fullTargetPath} or at least like '${env.MyVar}'.

Microsoft Visual Studio Professional 2017 Preview
Version 15.6.0 Preview 2.0
VisualStudio.15.Preview/15.6.0-pre.2.0+27309.0

**Comment by yuehuang010** [comment]
Hello, VS 15.7 Preview 1 has added attach to process.  Debug menu->"Attach to Process"-> Connection Type = "SSH",  "Connection Target" to your machine and you know the rest.
Thanks
