### ISSUE TITLE
Connection Manager: 'defaultRemoteMachineName' is always the first connection

### ISSUE THREAD

**Issue by sebastue** [Microsoft/VSLinux#252]
When you use the environment variable 'defaultRemoteMachineName' for your remoteMachineName in CMakeSettings.json, always the first connection of the connection manager is used. It is not possible to change the the default connection. So you have to delete other connections until the desired connection is the first one. Furthermore it is not possible to edit a connection. If you need to change something you have to remove the connection and add a new one.
There should be a possibility to set the default connection, as well it should be possible to edit a connection.

**Comment by itodirel** [comment]
thanks, that's a good suggestion, we can probably add that to the connection manager list; we have all the support to have it working, so it would just be a UI change in the Tools Options

**Comment by itodirel** [comment]
@robotdad FYI

**Comment by itodirel** [comment]
we are tackling this separately, copied to backlog
