### ISSUE TITLE
cannot no longer install "SourceLocation" breakpoints from VS GUI

### ISSUE THREAD

**Issue by vermosen** [Microsoft/VSLinux#255]
Hi,

Until last week, my win7 + VS 15.5.4 / centos 6.3 + gcc installation was working great for both compilation and debugging. 

Since a few days, I can no longer set "SourceLocation" breakpoints from the fringe in the text editor for VSLinux projects. As soon the remote debugging session starts, the breakpoints get dereferenced with a warning "The breakpoint will not currently be hit. Module containing this breakpoint has not yet loaded or the breakpoint address could not be loaded". Also, I can no longer go to the disassembly corresponding to a line during the debug session from the context menu. I get a dialog box "Disassembly cannot be displayed for the source location. There is no executable code at this location in the source code".

On the other hand, "NamedLocation" breakpoints (as denominated in the .xml file corresponding to the breakpoint) are still working perfectly: whether the debugging session is running or not, I can set a new breakpoint from the breakpoints windows/new/function breakpoint... (or Ctrl + B). I also noticed I can install these breakpoints with a file/line reference. Hence, writing main.cpp:8 in the dialog box will correctly install the breakpoint at the desired location. As a remark, this looks different from the behavior of the debugger in regular msvc projects. 

Finally, this problem **only happens on the main program**. **All** the breakpoints set in linked resources are correctly hit whether the ressources are static or dynamically linked and regardless if they are from external libraries (boost, stl) or from the solution, before or after the debugger started, etc.

Since MSVC projects debugging is just fine, I first thought the problem was coming from the symbol mapping in the binary, but doing a gdb info sources show the exact same absolute paths for all the files corresponding to the solution. I also tried to remap the sources in gdb and in visual studio to different locations without success. Also, all the components are compiled the same way with -O0 -ggdb3 -fPIC flags. The issue is still here in some dumb hello world project. Finally I reinstalled VS2017 from the installer with no success.

thx

**Comment by paulmaybee** [comment]
Sounds like the source location is not being mapped correctly to the compile time file location. Did you move any files or rename any projects since the last total rebuild of your solution? Can you collect a trace with the failure (see https://github.com/Microsoft/MIEngine/wiki/Logging - use the file logging option)?

**Comment by vermosen** [comment]
Thank for the prompt response. 

That is correct that my normal workflow is to build the binary on a specific machine and then to redeploy in several other remote locations, so the remote machine in the VS project is actually the debugging node (so I can change the machine from the project configuration sheet in a couple of clicks), while the build+deploy steps are performed through commands piped in Putty. I then generally use the set substitute-path command to get the correct remapping on the debugging machine, which works just fine in plain gdb and (until a few days ago) in VS. Unfortunately, the problem remains the same with a canonical "hello world" project (same build/debug location, no dependencies apart from the std::, etc)... Will be back with the MIEngine logs asap.

**Comment by vermosen** [comment]
Hi,

I actually sorted it out with the MIEngine logs. Great tool ! I had to modify a couple of things in the project (adjust remote build root and project Dirs) and in the .gdbinit as well but it all works very well now. 

Thx !
