### ISSUE TITLE
Please add C++17 Language Standard option

### ISSUE THREAD

**Issue by stanthomas** [Microsoft/VSLinux#258]
As of Visual Studio 15.6.0 Preview 4.0 we have options in project properties for language standards `C++03,` `C++11` and `C++14` (and some GCC dialects). Plus `Default` which doesn't pass any language standard on the `g++` command line (good). These options also set the language recognised by IntelliSense.

Please add option for `C++17` so that `-std=c++17` is passed to `g++` **and** IntelliSense recognises all C++17 features implemented in VC++,

**Comment by itodirel** [comment]
it will be available in 15.7 Preview 2

**Comment by stanthomas** [comment]
@itodirel 
I've just downloaded 15.7.0 preview 2.0 (4.7.02556) and I can't see a C++17 language option. I tried with both an existing project and a new console application project. All the previous language options are there.

**Comment by itodirel** [comment]
sorry, seems like the fix was not correctly merged and did not make it to 15.7; we'll see if we can get it in 15.7 Preview 4 if not, it will be in 15.8

**Comment by tommai78101** [comment]
I think this should be labeled as "Fixed - Pending Release".

**Comment by itodirel** [comment]
Just confirming that this is fixed and made it in the published 15.7 previews, if you update VS you should get it

**Comment by stanthomas** [comment]
@itodirel
Yes, the C++17 language option there now, thanks.  But, and I'm sorry there is a but, you seem to be adding `-std=c++17` to the `g++` command line in *all* cases.
Here are the g++` command lines in VS 15.7.0 preview 5.0 that result from setting the C++ language to C++17, C++!4 and Default :

```
C++ Language Standard = C++17(-std=c++17)
         g++ -c -x c++ .../main.cpp -g2 -gdwarf-2 -o ".../obj/x64/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++14 -std=c++17 


C++ Language Standard = C++14(-std=c++14)
         g++ -c -x c++ .../main.cpp -g2 -gdwarf-2 -o ".../obj/x64/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++17 -std=c++17 

C++ Language Standard = Default
         g++ -c -x c++ /home/monaco/projects/vc101/main.cpp -g2 -gdwarf-2 -o "/home/monaco/projects/vc101/obj/x64/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++17 
```

**Comment by itodirel** [comment]
@stanthomas I'm not seeing that and can't repro, did you add -std=c++17 in your project's command line manually? if so, then what you're seeing is by design, we are not filtering the user inputs in the Command Line options

**Comment by tommai78101** [comment]
@stanthomas Can you retest to verify if your issue is resolved?

**Comment by stanthomas** [comment]
@tommai78101 I thought I had covered that. However, to avoid any confusion, I can confirm that C++17 support has been added as per the initial request. And as of 7 May 2018 this is in the release of Visual Studio 15.7.0 / VCLinux 1.0.9. Thanks to @itodirel et al.
