### ISSUE TITLE
Remote CMake build does not copy sources after changing target machine

### ISSUE THREAD

**Issue by davideideticom** [Microsoft/VSLinux#259]
I am having issues building projects on multiple linux machines using cmake in Visual Studio.  When building a project a new linux machine I get errors saying files do not exist eg. "/var/tmp/src/99e03e62-d79b-8739-9e27-d39838c612c3/Linux-Debug/CMakeLists.txt does not exist"
 My current solution is to build the Linux-Release version on one machine and Linux-Debug on the other.  I would expect VS to check for the existence of the build folder before deciding to only push some files, or to give me the option to clean the entire remote build and start from scratch.  I am currently using VS version 15.5.5 to push cmake projects to Ubuntu 16.04.3 LTS, running cmake 3.5.1 on an intel x64 processor.

Any information on forcing Visual Studio to re-push an entire build to a new machine would be greatly appreciated.

Thanks,
David

**Comment by lukka** [comment]
@davideideticom that has been fixed on 15.6, you could try to preview of VS to verify it. 
In the mean time, the workaround is to manually delete the file under hidden directory ".vs" with a name similar to "index.bin".

**Comment by davideideticom** [comment]
Thanks, The work around has solved my issues.  I look forward to the change making it into a release update.
