### ISSUE TITLE
[ Question ] [ CMake ] Setting make launch settings

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#260]
I want to pass some parameters to 'make' (ex: `-j` or `-i`) for a Visual Studio project built with CMake.

Is this possible?
Where can I make this change?

**Comment by lukka** [comment]
@iwubcode you could do that by setting a value to buildCommandArgs, such as:
`"buildCommandArgs":"VERBOSE=1 -j8"`
to enable verbose output (i.e. display full command line invocations for each translation unit) and 8 concurrent compilations at once.

**Comment by iwubcode** [comment]
Thank you @lukka that works!  I also added a remote-task to run make with my parameter when I want to target a specific target.  Very useful stuff.
