### ISSUE TITLE
VS2017 crashes intermittently

### ISSUE THREAD

**Issue by robiwano** [Microsoft/VSLinux#262]
* A brief description
VS2017 (15.5.7) CMake + RPiZero, after a debug session, VS often stops responding and then crashes (restarts), especially when trying to scroll in the debug output window.

* Expected results
No crashes.

* Actual results (with build output window contents if applicable)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
VS2017 15.5.7
VC++ for Linux 1.0.8
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
Rasperry Pi Zero using Raspbian Stretch (with 4.15.1 kernel)

* Steps required to reproduce the error
Just run a session, and try to scroll the debug output window.

* Required packages and commands to install
N/A

Sorry not being able to be more detailed. Is there a log somewhere for VS2017 which I can attach ?

**Comment by paulmaybee** [comment]
Does this happen immediately after you have stopped debugging? Has VS returned to design mode, or does it still think you are debugging?  Please try to collect a gdb log of the session: In the VS “Command Window” enter the command:

              Debug.MIDebugLog /On:path-to-a-log-file

Then debug your project. After the failure enter:

              Debug.MIDebugLog /Off

The file you specified above should now have a complete gdb log of the session.

**Comment by paulmaybee** [comment]
Oops. Of course there is no "after failure" since you crash, so just ignore that part of the instructions.
