### ISSUE TITLE
Constant error pop-ups while debugging

### ISSUE THREAD

**Issue by MichaelGoulding** [Microsoft/VSLinux#265]
I'm debugging python that loads our custom c++ extension .so.

While connecting via Visual Studio to debug, I constantly get the following dialog box:

---------------------------
Microsoft Visual Studio
---------------------------
Exception while processing MIEngine operation. Unrecognized format of field "id" in result: result-class: None. If the problem continues restart debugging.
---------------------------
OK   
---------------------------

**Comment by paulmaybee** [comment]
I'm afraid I don't understand your scenario. Are you attempting to use gdb to debug python?
