### ISSUE TITLE
Cannot connect to remote dropbear ssh server

### ISSUE THREAD

**Issue by BMBurstein** [Microsoft/VSLinux#267]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

I tried connecting to my remote linux that was running dropbear shh server. The ssh server wroks fine (I can connect to it via mobaxterm, putty, etc.) but VS woudln't connect. After I disabled dropbear and installed opensshd instead, it now works.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

My "remote" is actually an arch-linux installation on a local Virtualbox VM. VS 2017.6.2 (just updated this morning, but I never tried using this feature before)

**Comment by lukka** [comment]
@BMBurstein iirc Dropbear ssh does not support sftp protocol, that is a requirement.
Try following this [description](https://linuxexplore.com/how-tos/sftp-secure-file-transfer-protocol-with-dropbear/), it could help.

OpenSSH does support sftp, but the sftp support is packaged as a different package, e.g. in the Debian distribution you need to install the package "openssh-sftp-server".

Please reopen the ticket if you have any followup.
