### ISSUE TITLE
VS studio 15.7 prev 1 freezes while starting VCLinux application

### ISSUE THREAD

**Issue by boskars** [Microsoft/VSLinux#268]
VS studio 15.7 prev 1 debugger freezes when starting VCLinux application. Is working correctly in VS 15.6.1

**Comment by yuehuang010** [comment]
Could you provide more information?  Does it happen on new project too?

**Comment by paulmaybee** [comment]
We really need more information in order to help you. What version of Linux is running on your target? Are you using a VS Linux Project or a CMake project? Does this happen if you simply make a new Linux console app and attempt to build and debug it?

**Comment by yuehuang010** [comment]
@boskars , Hello, do you have any update on the repro?

**Comment by boskars** [comment]
I just had time to test a little bit more.  It does not happen on a new project.  We link with -lcrypto option which always results in an Illegal instruction during start (crypto is apparently designed in that way to detect the CPU type) and I have tried also to add crypto to the a new project, but it does not freeze, it just displays the illegal instruction exception and then I am able run to the main() function.

The experience with our project is that the crypto generates illegal instruction during start and while VS 15,7 prev1 is displaying the Illegal instruction window and the Linux console Window it freezes.

I have not had time to recreate our project file with VS 15.7 prev 1 yet so I do not know if that would help.

I am using Linux Project and not CMake.

I am running Linux YoctoProject

CPU:   Freescale i.MX6ULL rev1.0 at 396 MHz

root@imx6ul-var-dart:~# uname -a
Linux imx6ul-var-dart 4.1.15-2.0.0.974+g65ef23a #1 PREEMPT Wed Oct 25 15:28:50 CEST 2017 armv7l GNU/Linux

**Comment by paulmaybee** [comment]
Can you get a gdb log file of your session? Logging instructions are here: https://github.com/Microsoft/MIEngine/wiki/Logging.

**Comment by boskars** [comment]
[DebugLog2.zip](https://github.com/Microsoft/VSLinux/files/1837310/DebugLog2.zip)
@paulmaybee 
I have attached the  log files.
I have also sent Visual Studio Debug Dump to Visual Studio Community.

**Comment by paulmaybee** [comment]
Did both of these sessions freeze, or just the session for DebugLog2.txt? In DebugLog2.txt it looks to me like you set the debugger into hex display mode just before it froze. If so, this is a known issue (https://github.com/Microsoft/MIEngine/issues/69) that has been difficult for us to reproduce. I will flag it again to raise its priority. Are you seeing this hanging behavior when you have not put the debugger in hex-display mode?

**Comment by boskars** [comment]
Both seesions did freeze and I did not do any difference other than the DebugLog2.txt was running longer time (during my lunch) before I killed VS.  I am not putting the debugger into hex display mode, I cannot because it is totally frozen, it must be a default settings.
Is the hex mode option related to the project settings or to the Visual Studio settings?  I mean how can I change the settings when the Visual Studio is frozen?

**Comment by paulmaybee** [comment]
The hex property is persistent across VS invocations. To turn it off close all open copies of VS. Then start VS and open a project that you can successfully debug (or just make a new C++ "ConsoleApplication"). Compile and F10 to step into it. In the locals window right-click and disable "Hexidecimal Display". Then close the solution. Hex display should now be off for new debugging sessions.

Afterwards try debugging your application again and see if it still hangs.

**Comment by boskars** [comment]
Thank you for your help.  Disabling hex view helped.

**Comment by itodirel** [comment]
Please let us know if there is still a problem here.
