### ISSUE TITLE
_ValidateValidArchitecture in Linux.targets blocking Linux cross compile.

### ISSUE THREAD

**Issue by EFSYS** [Microsoft/VSLinux#269]
Hi all,
For some month I started to use visual studio to compile a cross platform project, I juste have a little remark on this when building on ARM linux platform:
Steps to reproduce:
Create a C++ project for linux, with compiler for an Embedded ARM device hosted in a x86/x64 Linux machine.
Cannot compile until removing _ValidateValidArchitecture from DependsOnTargets attribute in CLCompile Target in Linux.targets
_ValidateValidArchitecture test architechture of target machin instead of target compiler.
Each update of Visual studio reenable _ValidateValidArchitecture.
Best regards,
Stéphane

**Comment by itodirel** [comment]
Hi, we made a change that should be available in 15.8, the next future release of VS, which will allow you to disable the check

**Comment by EFSYS** [comment]
Hello,
  Thank you!

**Comment by itodirel** [comment]
You're most welcome, the setting will be available as indicated below.  We will decide if we want to support more here, or change the default based on telemetry and feedback.

![image](https://user-images.githubusercontent.com/15239856/38904582-1c91701e-4260-11e8-89dd-3a679c10697b.png)
