### ISSUE TITLE
Select remote connection for build target

### ISSUE THREAD

**Issue by stanthomas** [Microsoft/VSLinux#27]
One of the attractions (and challenges) of developing applications for Linux is the wide range
of platforms it runs on and, therefore, might need to be targeted. PC(x86) and ARM are the most common but there are many others with varying levels of demand and support. And, of course, variations within a given architecture.

One possible solution is cross-compilation, Issue #19. But this can be difficult to setup and doesn't readily support debugging. Much easier to have an appropriately configured remote system available. In my case, for example, I'll use a VM for 32-bit and 64-bit Linux on PC and have a Raspberry Pi on my desk for ARM.
# Proposal

It would be very useful for a build of the ARM target to automatically select the Pi, and a build of an x86 target to select the VM.

We set the Linux Connection in Tools / Options / Cross Platform / C++ / Linux . This already allows multiple connections to be established, although it only appears to use the first one. So we can, for instance, setup a connection to an 'x86_64' target (PC) and another to an 'armv7l' target (Pi3). And the connections manager recognises the architecture and OS of the target: x64/unknown and ARM/Raspbian, in my case.

Matching the project target to a remote connection so that simply changing the 'Active Solution Platform' in the project properties would select the corresponding remote system for building and debugging.
And Build / Batch Build... would build every project configuration in turn on the corresponding
remote systems.

One question : what should happen when two connections are configured with the same target
architecture? Should the build be run on the first that can be reached, allowing for remotes
that might be turned off or changed locations? Or should the build be run on all so you might have a Debian build, a RedHat build etc. ?

**Comment by itodirel** [comment]
Not sure if this is know, but you can select the target that you use for build in the Property Pages, on a per project basis. If you go to the Property Pages - Remote settings, Target machine. Target machine is a dynamic combo box that is populated based on the entries that are available or added thru the Configuration Manager.

You are right that right now it pick the first successful connection as the default. And it doesn't give sensible defaults. We do know about this issue, and do plan on fixing it, such that the platform that you have selected matches the machine architecture. If you have more than one that matches, we indeed need to disambiguate, typically we just choose the first one or the last one in terms of recently used.

**Comment by stanthomas** [comment]
Hadn't spotted Remote settings, Target machine - thanks for the tip.
That works well and exactly addresses my needs for targetting multiple architectures by connecting different remote systems.

Automatically matching target architecture to available remote connections would be the icing on the cake.

**Comment by robotdad** [comment]
I'm closing this one as we do match arch of connection now. We'll pursue any changes off the related on #118

**Comment by itodirel** [comment]
@stanthomas, I know you know how to do it, but I created a demo on how to manage it, for posterity: [Visual C++ for Linux Development - Handling multiple connections](https://vimeo.com/251731898)
