### ISSUE TITLE
Can not add a remote ssh connection

### ISSUE THREAD

**Issue by cdcseacave** [Microsoft/VSLinux#270]
VS2017 15.6.2

After adding and removing a remote SSH in `Connection Manager`, I can not add it back. I can add any other remote SSH machine, but not the one that I removed before. Btw, I had to remove it in the first place cause I can not order the SSH connections in the manager and a project always tries to use the first connection.

Overall, this is an amazing job you guys did with this feature. Once it is setup, developing/debugging works flawlessly. Amazing debugging experience, years ahead of any other GDB based debugger.

**Comment by lukka** [comment]
@cdcseacave what exactly is happening when you add the new connection?

For your information, you can select the remote machine you want to connect to by editing the properties of the .vcxproj file, or by editing the CMakeSettings.json file (RemoteMachineName attribute set to the name of the machien in the connection manager).

**Comment by cdcseacave** [comment]
now I tried again and it worked; even before posting this I tried around 1h (restarting VS, restarting my PC and the remote PC, nothing worked); it accepted all params, but after waiting around 60s to connect it was saying it can not connect or something like that

yes, I saw that param in JSON file, but I didn't know what to write there; currently it has `${defaultRemoteMachineName}`; so should I write simply the hostname/ip, or also the port and username? it would be useful to see somewhere all the default keywords, like `${defaultRemoteMachineName}`; I was trying for instance to set for the path folder the keyword from VS projects like `${ProjectName}` and it didn't work, it was trying simply to create a folder with that name
