### ISSUE TITLE
$HOME not working in 'Additional Library Directories'

### ISSUE THREAD

**Issue by SamuelHenderson** [Microsoft/VSLinux#271]
* A brief description

I just updated to Visual Studio 2017 15.7 Preview 1.0 and my project now fails to link against some libraries I have in a directory in my home directory.  My Linker properties have the following defined in 'Additional Library Directories':
`$HOME/My_App/libs/$(Configuration);%(AdditionalLibraryDirectories)`
which now appears in the Output window as:
`2>  g++ -o "/home/shenderson/projects/MyLib/bin/x64/Debug/libMyLib.so" -Wl,--no-undefined -Wl,-L"/home/shenderson/projects/MyLib/$HOME/My_App/libs/Debug" ... etc`

In Visual Studio 2017 15.5.1 the same 'Additional Library Directories' setting results in the following in the output window:
`g++ -o "/home/shenderson/projects/MyLib/bin/x64/Debug/libMyLib.so" -Wl,--no-undefined -Wl,-L"$HOME/My_App/libs/Debug" ... etc` which would allow ld to link against the shared object files in `~/My_App/libs/Debug/`

So it seems like in 15.7 preview 1.0 something changed in how paths are evaluated.  

* Expected results
$HOME in 'Additional Library Directories'  ultimately evaluates to the equivalent path of '~'

* Actual results (with build output window contents if applicable)
`2>  Invoking 'ld'`
`2>  g++ -o "/home/shenderson/projects/MyLib/bin/x64/Debug/libMyLib.so" -Wl,--no-undefined -Wl,-L"/home/shenderson/projects/MyLib/$HOME/My_App/libs/Debug"`

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

- VC++ 15.7.0 Preview 1.0
- Fedora 27 (x86_64)
- gcc version 7.1.1 20170622 (Red Hat 7.1.1-3) (GCC)

* Steps required to reproduce the error

1. Create a directory in your linux home directory, something like:
`mkdir -p MyApp/libs/Debug/`

2. Put some shared object files in the directory created above

3. In your VC++ For Linux Project, add the following to 'Additional Library Directories':
`$HOME/LT_App/libs/$(Configuration);%(AdditionalLibraryDirectories)`

4. Make sure to add the libraries in the 'Library Dependencies' setting

* Required packages and commands to install
N/A

**Comment by SamuelHenderson** [comment]
The work around I have come up with is to have the following in my 'Additional Library Directories' setting:
`/home/shenderson/LT_App/libs/$(Configuration);$HOME/LT_App/libs/$(Configuration);%(AdditionalLibraryDirectories)`
This keeps it backwards compatible with other developers on my team who are still using the non-preview release of Visual Studio 2017.

**Comment by yuehuang010** [comment]
Hello @SamuelHenderson , Thank you for using VS.  I see the issue is caused by VS failing to detect that $HOME is full path.
Could you try using '~/' instead of '$home/'?

Could you also try Project To Project Reference?  It should automatically add the output lib for you.

Thanks
Felix

**Comment by yuehuang010** [comment]
After some investigation, it appeared that the Fullpath detector wasn't working, thus converting all paths to full paths.

**Comment by SamuelHenderson** [comment]
Hi yuehuang010, thanks for looking into this.

I tried replacing '$HOME' with '~/' as per your suggestion but it seems like ld still fails to find the libraries (despite the fact they are definitely in that directory)
`2>  Invoking 'ld'`
`2>  g++ -o "/home/shenderson/projects/MyLib/bin/x64/Debug/libMyLib.so" -Wl,--no-undefined -Wl,-L"~/MyApp/libs/Debug" ...snip... -lMyOtherLib`
`2>  /usr/bin/ld: cannot find -lMyOtherLib`

> Could you also try Project To Project Reference? It should automatically add the output lib for you.
Could you elaborate on this?  Is this the same thing as the 'Project Dependencies' and 'Build Order' ? Because we do have that set up already.

**Comment by yuehuang010** [comment]
@SamuelHenderson , could you please email me vcpplinux-support@microsoft.com ?  I would like to work with you on a fix.

Thanks.

**Comment by SamuelHenderson** [comment]
@yuehuang010 I sent an email a while with some sample project files and MSBuild log outputs ... has any progress been made?

**Comment by SamuelHenderson** [comment]
Although not ideal, I have discovered a work around to $HOME not being evaluated properly for the Additional Library Directories (-L) path.

My workaround is something like this:
`../../My_App/libs/$(Configuration)`

Which is evaluated to this g++ command:
`g++ -o "/home/shenderson/projects/MyLib/bin/x64/Debug/libMyLib.so" -Wl,--no-undefined -Wl,-L/home/shenderson/projects/MyLib/../../My_App/libs/Debug`

**Comment by joe-livedata** [comment]
I have observed the same issue when upgrading to VS 15.7.1  The issue presents itself in a large solution with 85 projects, each with 4 configurations.  A fix would be nice, much preferable to the workaround that SamuelHenderson describes.

**Comment by itodirel** [comment]
using #325 for tracking, same underlying issue
