### ISSUE TITLE
CMake for Linux on VS - Local header cache for intellisense

### ISSUE THREAD

**Issue by alexBraidwood** [Microsoft/VSLinux#272]
UPDATE: See @itodirel's comment below for a workaround. 

With the normal MSBuild-ish workflow for Linux, you can use header include paths for intellisense without worrying about them getting copied over to your target machine. With CMake, as far as I can tell, this doesn't seem to be possible.

It would be fantastic if we could define, maybe in CMakeSettings.json, header search paths just for intellisense data. 

Version Info: 
```
Microsoft Visual Studio Enterprise 2017 
Version 15.6.3
VisualStudio.15.Release/15.6.3+27428.2011
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA717
Microsoft Visual C++ 2017

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27406.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit. 
```

Linux Platform: 
In our particular case, we're targeting a Debian-based (Raspbian and otherwise) ARM device. 
``` 
gdbserver v 7.12 and GCC v 6.3.0
raspbian 4.9.35-v7+ armv7l GNU/Linux 
```

**Comment by iwubcode** [comment]
Does `includePath` work for your needs?  It's in 'CppProperties.json', see the [latest blog](https://blogs.msdn.microsoft.com/vcblog/2018/01/10/intellisense-enhancements-for-cpp-open-folder-and-cmake/) that comments about some new features involving it.

**Comment by alexBraidwood** [comment]
@iwubcode Thanks for the suggestion, I tried it out one more time this morning. It just doesn't seem to work with CMake. We've been able to make it work for us in folder or makefile-based projects, however. So, we're working without it, but this would be cool to have support for on the CMake side.

**Comment by itodirel** [comment]
this can be done using a syntax like the following:

```
{
 "environments": [    
    {
      "environment": "includes",
      "INCLUDE": "includes\\include1;includes\\include2"
    },
  ],
  "configurations": [
    {
      "name": "Linux-Debug",
      "generator": "Unix Makefiles",
      "remoteMachineName": "king100",
      "configurationType": "Debug",
      "remoteCMakeListsRoot": "/var/tmp/src/${workspaceHash}/${name}",
      "cmakeExecutable": "/usr/local/bin/cmake",
      "buildRoot": "C:\\Users\\itodirel\\source\\repos\\CMakeProject18",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "remoteBuildRoot": "/var/tmp/build/${workspaceHash}/build/${name}",
      "remoteInstallRoot": "/var/tmp/build/${workspaceHash}/install/${name}",
      "remoteCopySources": true,
      "remoteCopySourcesOutputVerbosity": "Normal",
      "remoteCopySourcesConcurrentCopies": "10",
      "remoteCopySourcesMethod": "sftp",
      "remoteCopyBuildOutput": true,
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "linux_x64", "includes" ]
    }
  ]
}
```

**Comment by alexBraidwood** [comment]
@itodirel Alright, cool, that works. Is there anywhere I could've found the information for that? It seems more like internal magic fiddling to me, and it's not very intuitive. For instance, why doesn't includePath in CppProperties work for CMake? I take it it's the `INCLUDE` in the environment settings? Does it just add a CMake `include` call? Why does this not copy the include directories over the way  target_include_directories` does?

**Comment by itodirel** [comment]
we're looking into consolidating the two

**Comment by alexBraidwood** [comment]
@itodirel This caused a lot of other Intellisense errors to start popping up. All of a sudden, Visual Studio has forgotten about C++11. E0035, E1774, E0771, E1670, E0864, E1696... All sorts of SFINAE template errors. Any magic to make intellisense know about C++11, 14, or 17 again?
