### ISSUE TITLE
Remote File Copy

### ISSUE THREAD

**Issue by dkosawa** [Microsoft/VSLinux#273]
The Solution Explorer seems to utilize the .gitignore file,  only showing files that are not "ignored", but when building on a remote Linux system all files starting from the root directory are copied over. 

Does it seem reasonable to only copy files that make it past the .gitignore filtering rules?  If not, is there a way to restrict what gets copied to a remote system?

**Comment by itodirel** [comment]
is this in the context of vcxproj? CMake or something else?

**Comment by itodirel** [comment]
please let us know if this is still an issue, and what kind of projects are you using
