### ISSUE TITLE
out of box WSL VS2017preview 2 Raspberry project will not build

### ISSUE THREAD

**Issue by melvyn1950** [Microsoft/VSLinux#275]
* A brief description
out of box WSL VS2017preview 2 Raspberry project will not build
* Expected results
Microsoft published code and examples should work out here in user land

* Actual results (with build output window contents if applicable)
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error		Current project architecture 'ARM' is incompatible with the remote system architecture 'x64' ('x64'). Please switch the project architecture to 'x64' in Configuration Manager.	Blink5	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets	92	

* VC++ version, Linux system name and version, 
Visual studio 2017 preview 2

* Steps required to reproduce the error,.
Use a clean ( i.e. not a in house Microsoft dev system)
Remove dependency on "<wiringPi.h>"
build simple hello world app.....

#include <stdio.h>;
int main(void)
{	while (true)
	{
		printf("hello \n");
	}
	return 0;
}

How did you ever manage to build Windows for ARM that runs on my "Lumia Windows phone" ????????

**Comment by lukka** [comment]
@melvyn1950 are you trying to compile a .vcxproj Raspberry (architecture ARM) project on a WSL Linux (architecture x64) instance?

**Comment by itodirel** [comment]
The Raspberry Pi template is not designed to work on x64; if you need to target x64, please use the Console Application template
