### ISSUE TITLE
Google tests not producing any output

### ISSUE THREAD

**Issue by ckubrak** [Microsoft/VSLinux#276]
Hi,
I've cloned a git project I'm developing in a Linux (Ubuntu) computer. In this project, for unit testing I'm using [gtests](https://github.com/google/googletest).

I'm using this [CMakeLists.txt](https://gist.github.com/ckubrak/7f8c0a0271cf5807cfe50dcb8d47e591). The project seems to build and run correctly, but I'm not getting any output. I should be getting at least the test results.

When I run it on my Ubuntu computer get the expected output, but not when I run it from visual studio.

I'm using Visual Studio 2017 in Windows 10
The computer I SSH to has CMake 3.9.0 and it's running Ubuntu 16.04

Thanks

**Comment by itodirel** [comment]
we do not support Google test yet

**Comment by itodirel** [comment]
copied to backlog
