### ISSUE TITLE
Incompatible with other shells than sh/bash

### ISSUE THREAD

**Issue by gpakosz** [microsoft/VSLinux#28]
Visual Studio C++ Development for Linux fails when the user on the remote machine runs anything else but `sh`/`bash` as default shell.

For instance, when using `fish` shell on Archlinux, the linux console window remains blank and trying to debug gives **"Could not select a remote port for gdbserver to listen on."**

This is because you're sending the following command:

```
netstat -tln | awk '{gsub(/.*:/,"",$4); print $4}' | grep -o '[0-9]\+' | sort -un | awk -v n=4444 '$0 < n {next}; $0 == n {n++; next}; {exit}; END {print n}'
```

Which is not valid in `fish` syntax. You may want to send all this through `sh -c` to be independent of the user's default shell.

While debugging this, I noticed the two following additional points:
- you don't list `netstat` as a required dependency: the command above semi-fails and selects port `4444` when `netstat` is not present
- you may want to start the command you're issuing with a space character to avoid filling shell's history (assumes `bash` and `HISTCONTROL` set to `ignorespace` but well...)

Hope that helps

**Comment by robotdad** [comment]
Excellent feedback, thank you.

**Comment by itodirel** [comment]
Thanks for bringing this to our attention, we will fix it

**Comment by TTimo** [comment]
+1

**Comment by MaxDZ8** [comment]
Hello, after my positive experience with VS for Pis, I had the naughty idea of... trying to remote debug & build Omega2.

They're basically access point chips running OpenWRT/BusyBox/ash. After inserting IP and login credentials and pushing the Connect button, it tries to do something for a few seconds and then it gives up, highlighting in red the IP.

I figured this might be related. Time to go without a safety net I'm afraid.

**Comment by itodirel** [comment]
Hi, yes, I think it is related

**Comment by itodirel** [comment]
I created this ticket: https://developercommunity.visualstudio.com/idea/956725/compatibility-with-other-shells.html

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.

**Comment by gpakosz** [comment]
🤷‍♂️

**Comment by itodirel** [comment]
This issue has been addressed

**Comment by gpakosz** [comment]
Thanks for the notice @itodirel 👍

**Comment by itodirel** [comment]
You're most welcome. We also addressed a lot other shell issues. You can even override the shell VS is using. So if you default shell on Linux is something like Power Shell (some users do it), it would still work. A blog post with the details is coming up in coming week as well.

**Comment by itodirel** [comment]
This is now fixed.
