### ISSUE TITLE
Remote header download error with non-bash default shell

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/VSLinux#280]
* A brief description

I have PowerShell set as my default shell inside WSL for Ubuntu and the headers fail to download due to the command timing out. This is because the command is invoked through SSH as-is, and even though the PowerShell folk really tried not to hide typical Unix commands with PS aliases on Linux builds, `echo` seems to have slipped through, hijacking the command and invoking `Write-Host` instead, which opens a dialog for a missing parameter.

* Expected results

Stuff to work with non-bash default shells.

* Actual results (with build output window contents if applicable)

Log content:

```
liblinux.Shell.CommandingException: Timed out executing command 'echo | g++ -x c -E -v -', waited for 15111,8656ms. ---> liblinux.Ssh.Common.SshOperationTimeoutException: Command 'echo | g++ -x c -E -v -' has timed out.
   at liblinux.Ssh.SshCommand.WaitOnHandle(WaitHandle waitHandle)
   at liblinux.Ssh.SshCommand.EndExecute(IAsyncResult asyncResult)
   at liblinux.Shell.NonHostedCommand.OnRun()
   --- End of inner exception stack trace ---
   at liblinux.Shell.NonHostedCommand.OnRun()
   at liblinux.Shell.CommonCommandBase.Run()
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText, TimeSpan timeout)
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText, Int32 timeout)
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText)
   at liblinux.Services.RemoteCompiler.CalculatePathsUsingCompiler()
   at liblinux.Services.RemoteCompiler.RetrieveCompilerInformation()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)

liblinux.Shell.CommandingException: Timed out executing command 'echo | g++ -x c -E -v -', waited for 15109,3514ms. ---> liblinux.Ssh.Common.SshOperationTimeoutException: Command 'echo | g++ -x c -E -v -' has timed out.
   at liblinux.Ssh.SshCommand.WaitOnHandle(WaitHandle waitHandle)
   at liblinux.Ssh.SshCommand.EndExecute(IAsyncResult asyncResult)
   at liblinux.Shell.NonHostedCommand.OnRun()
   --- End of inner exception stack trace ---
   at liblinux.Shell.NonHostedCommand.OnRun()
   at liblinux.Shell.CommonCommandBase.Run()
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText, TimeSpan timeout)
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText, Int32 timeout)
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText)
   at liblinux.Services.RemoteCompiler.CalculatePathsUsingCompiler()
   at liblinux.Services.RemoteCompiler.RetrieveCompilerInformation()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)
```

The command when executed inside the default PS:

```PowerShell
PS /home/mnagy> echo | g++ -x c -E -v -                                                                                                                                                                                             
cmdlet Write-Output at command pipeline position 1
Supply values for the following parameters:
InputObject[0]:
```

When invoked from bash:

```
mnagy@MATTY-GL702ZC:~$ echo | g++ -x c -E -v -
Using built-in specs.
COLLECT_GCC=g++
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.1-2ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~16.04)
COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/cc1 -E -quiet -v -imultiarch x86_64-linux-gnu - -mtune=generic -march=x86-64 -fstack-protector-strong -Wformat -Wformat-security
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
```

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

VS2017 15.7 prev3, GCC 5.4 inside Ubuntu 16.04 (WSL), Ryzen 7 1700 (amd64)

* Steps required to reproduce the error

[Install PowerShell for Ubuntu](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-macos-and-linux?view=powershell-6) and change the default shell to it via `chsh --shell /usr/bin/pwsh`.

* Required packages and commands to install

```
sudo apt install powershell
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by itodirel** [comment]
we are not likely to make this work with all shells, but we will investigate; for now I recommend using bash

**Comment by itodirel** [comment]
Hi, we are interested in supporting other shells, but we likely won't be supporting PowerShell, do you have bash on your system, even if not default? if so, that is something we can make work

**Comment by MathiasMagnus** [comment]
Yes, bash is installed. It's not a problem if the infrastructure depends on a package, I just don't like changing the default shell for remote dev and back again after I'm done.

**Comment by itodirel** [comment]
Thank you, tracked with, and planned to be addressed, in our roadmap: https://developercommunity.visualstudio.com/idea/956725/compatibility-with-other-shells.html

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
