### ISSUE TITLE
How to link libgattlib.so from a Raspberry Pi3 board into a VS2017 VC++ for Linux project

### ISSUE THREAD

**Issue by PTmv** [Microsoft/VSLinux#282]
I tried to build a VC++ for Linux (Raspbian) project in VS2017 (from my PC)using libgattlib.so static library residing in Raspberry Pi 3 board. The compilation went without errors. I can reliably include in the project .h files using e.g. **\\<Board IP Address>usr\include**. I also need a reference to the libgattlib.so library file. It resides in /usr/lib on the Raspberry Pi 3 and the link is correctly set to **\\<Board IP Address>\usr\lib** in VS2017 Project->Configuration Properties->VC++ Directories->Library Directories and **-lgattlib** in Project->Configuration Properties->Linker->Input->Library Dependencies but the linker reports error:

Target Link:
1>  Linking objects    
1>  Invoking 'ld'    
1>  g++ -o "/home/pi/projects/Id2Monitor_For_Linux/bin/ARM/Debug/Id2Monitor_For_Linux.out" -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack /home/pi/projects/Id2Monitor_For_Linux/obj/ARM/Debug/main.o -lbluetooth -llibgattlib    
1>  **/usr/bin/ld: cannot find -llibgattlib**    
1>  /usr/bin/ld: cannot find -llibgattlib    
1>  collect2: error: ld returned 1 exit status    
1>  collect2: error: ld returned 1 exit status    
1>  /usr/bin/ld: cannot find -llibgattlib    
1>  collect2: error: ld returned 1 exit status    
1>  collect2 : error : ld returned 1 exit status    
1>  Done linking, output file name: '/home/pi/projects/Id2Monitor_For_Linux/bin/ARM/Debug/Id2Monitor_For_Linux.out'    
1>Done building target "Link" in project "Id2Monitor_For_Linux.vcxproj" -- FAILED.    
1>    
1>Done building project "Id2Monitor_For_Linux.vcxproj" -- FAILED.    
1>    
1>Build FAILED.    
1>    
1>collect2 : error : ld returned 1 exit status    
1>    0 Warning(s)    
1>    1 Error(s)

Please advise me how to correctly set up the references for libgattlib.so library in VS2017. Thanks.

**Comment by lukka** [comment]
@PTmv are you sure you are just drop the 'lib' prefix, it should just be just 'gattlib' in the Library Dependencies box (semicolon separated):
![image](https://user-images.githubusercontent.com/681992/39068603-ae21fd72-4491-11e8-93c5-60d2bbe8e39b.png)

**Comment by PTmv** [comment]
Hi Lukka,

Thank you for your prompt response. Yes, I tried to set up gattlib into  Project->Configuration Properties->->Linker->Input and got errors:

Error                      undefined reference to symbol 'pthread_join@@GLIBC_2.4'        Project_For_Linux           C:\usr\bin\ld                1
Error                      DSO missing from command line               Project_For_Linux           \\lib\arm-linux-gnueabihf\libpthread.so.0           1
Error                      ld returned 1 exit status Project_For_Linux                C:\Projects\Id2Monitor_For_Linux_Projects\Id2Monitor_For_Linux\Id2Monitor_For_Linux\collect2          1
Please advise me how to solve this problem.

Best regards,

   Paul

**Comment by PTmv** [comment]
Adding **-lpthread**  to Project->Configuration Properties->Linker->Command Line solved the problem. Here is the link which helped me: https://stackoverflow.com/questions/24096807/dso-missing-from-command-line?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa. Thank you for your help.
