### ISSUE TITLE
Adding WSL in Visual Studio fails with "Failed to archive sysroot [...]"

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/VSLinux#284]
Hi!

I've filed this over at Microsoft/WSL/issues/3124 because I wasn't aware of this repository - but I just found it, and I think the issue is a better fit here!

I'm following the instructions here: https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/ to the point.
When going to "Tools > Options > Cross Platform > Connection Manager", entering the details, and clicking "Connect", it results in the following error:
![image](https://user-images.githubusercontent.com/4967343/39217420-ddab9966-4817-11e8-9bd3-22a06eb752fb.png)

The log file contains the following:

> liblinux.ExceptionBase: Failed to archive sysroot, command used: 'zip -r /var/tmp/sysroot_bd10b29c-e9ef-409f-94da-ad87165daa75.zip '.
   at liblinux.Services.RemoteCompiler.CreateSysrootArchive()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)

My system:

* Windows build number:  Microsoft Windows [Version 10.0.16299.402]

* WSL installed today (Ubuntu) from Microsoft Store; then did `apt update` & `apt upgrade`, added `ubuntu-tool-chain-r` repo, installed `g++-7` and `g++`. (and then the packages from https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/).

* VS 2017 15.7.0 Preview 4.0 (very latest)

**Comment by lukka** [comment]
@patrikhuber could you ensure you have the zip tool on your Ubuntu? Just install it with apt if it is missing. Then report back if the problem persists.

**Comment by patrikhuber** [comment]
Hi @lukka, I can confirm that `zip` is installed in WSL.

**Comment by patrikhuber** [comment]
Okay, this is something very sneaky: The instructions tell you to start the ssh daemon in WSL, on the default port. And it starts, without any warning or error. But: **Windows 10** has actually already an ssh daemon running (and on port 22)! This caught me by surprise. So when you (or VS) tries to do "ssh localhost", it connects to the ssh daemon running from Windows 10 (!!!), and not the one running in WSL.

The solution is to run the ssh daemon inside WSL on a different port, and then use that port in the VS configuration dialog. Then, everything works.

This is not trivial to find out (who would have guessed that Windows runs an ssh daemon by default, and on port 22?). And the VS error message is also very bad and tells you not much about what's going on.

I would suggest that Microsoft improves the error messages and documentation on this. Pretty sure I wouldn't be the only one to run into this.

**Comment by stanthomas** [comment]
It's discussed in the comments to the [original blog](https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/) and if you follow the links you'll see that this [workaround](https://superuser.com/questions/1123552/how-to-ssh-into-wsl) has been required for quite some time.

**Comment by stanthomas** [comment]
@patrikhuber Hey, I'm not sniping. Just joining you in suggesting Marc updates his blog.

**Comment by patrikhuber** [comment]
@stanthomas Ok cool! :-) 👍

**Comment by itodirel** [comment]
@patrikhuber unfortunately it's difficult to provide diagnostics because there's not much information available, we can get the identity of the SSH server but that does not say much, and in the end it is presented to us as authentication failure, which is correct. We could see if port 22 is used locally and maybe find the process or service owning it, but that would be hacky

**Comment by itodirel** [comment]
If the case for when the connection failed or if zip is missing, we already made a fix to tell you exactly why, that one is done, but not yet in one of the currently published Previews

**Comment by xwxbug** [comment]
same issue in centos 6/7.
zip command exist.
vs version: vs 2017 15.8.0 pre 1.1/vs 2017 15.7.2

**Comment by Berrysoft** [comment]
It succeed in Ubuntu 16.04, but after upgraded to 18.04 it failed.

Zip exists.

vs version: 15.7.6

**Comment by itodirel** [comment]
can you attach the log?

**Comment by itodirel** [comment]
Hi, I believe this should be now fixed in the latest release, can you try it?

**Comment by itodirel** [comment]
@Berrysoft could you provide us with a repro? please open a separate issue for the problem you are seeing

**Comment by Berrysoft** [comment]
Seems that it works now, and I needn't open a new issue.
