### ISSUE TITLE
OpenFolder: Impossible to select a binary via Select Startup Item when git is used as a source control!

### ISSUE THREAD

**Issue by ademyankov** [Microsoft/VSLinux#286]
When using OpenFolder the binary has to be selected manually through _Solution Explorer_, right click -> _Set as Startup Item_. When git is used _Solution Explorer_ does't show binary files because _/Debug_ or _/Bin_ folders are in _.gitignore_.

* Expected results:
A few things I would suggest:
1. _Select Startup Item_ list box has to be populated with configurations from _launch.vs.json_, then startup project can be selected even if it is ignored by _Solution Explorer_!
2. In case of OpenFolder populating _Select Startup Item_ list box with _*.sln_ and _*.vsproj_ files has no sense whatsoever. Those are useless for OpenFolder.
3. If a binary doesn't have **.exe** extension it is not select-able as well. If item 1 is implemented then this no longer becomes an issue.

* Actual results:
No way to select a binary until _.gitignore_ is removed and vs open folder is reloaded.

VS 2017 Pro: 15.7.0
Win10: Enterprise 1709

**Comment by yuehuang010** [comment]
1 & 2) Could you please a screen shot of Open Folder and the content of launch.vs.json?
3) could you please share what filename you expect to be select-able?

FYI, extensions with .exe, .bin, .elf , and .out should be selectable.

**Comment by ademyankov** [comment]
3) I haven't realized that .out and .elf works, in my case binaries doesn't have extensions at all, which is not uncommon for Linux!

As you can see on the screenshot:
![vs](https://user-images.githubusercontent.com/13845895/39831095-4b0b4928-5378-11e8-841a-f24b8df7ad53.jpg)
* Debug folders are missing in _Build\Targets\aarch64-gp-gnu-ree, Build\Targets\aarch64-gp-gnu-tee_, obviously, because SolutionExplorer filters them out according to _.gitignore_;
* _SelectStartupItem_ list box has a whole bunch of project and solution files, which are useless, because I cannot use them to select configuration to debug;

I trimmed my _launch.vs.json_ file but it shows that I have for now 6 configurations:
```
{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "cppdbg",
      "name": "Remote QEMU-HOST: Marpal",
      "project": "Build\\Targets\\aarch64-gp-gnu-ree\\Debug\\Marpal.exe",
 
    ...

    },
    {
      "type": "cppdbg",
      "name": "Remote QEMU-TA: DRM",
      "project": "Build\\Targets\\aarch64-gp-gnu-tee\\Debug\\ta.exe",
      "cwd": "c:\\projects\\manatee\\Build\\Targets\\aarch64-gp-gnu-tee\\Debug",
      "program": "c:\\projects\\manatee\\Build\\Targets\\aarch64-gp-gnu-tee\\Debug\\758ee8b4-f485-45fb-8fb0-3d0cc027b84a.ta",

    ...

    },
    {
      "type": "cppdbg",
      "name": "WSL Linux: Marpal",
      "project": "Build\\Targets\\x86_64-unknown-linux\\Debug\\Marpal.exe",
      "cwd": "/mnt/c/projects/manatee/Build/Targets/x86_64-unknown-linux/Debug/",
    
    ...

    },
    {
      "type": "cppdbg",
      "name": "WSL QEMU-HOST: WasabiSecureKeyExport",
      "project": "Build\\Targets\\aarch64-gp-gnu-ree\\Debug\\WasabiSecureKeyExport.exe",
    ...

    },
    {
      "type": "cppdbg",
      "name": "WSL Linux: WasabiSushiAction",
      "project": "Build\\Targets\\x86_64-unknown-linux\\Debug\\WasabiSushiAction.exe",
      "cwd": "/mnt/c/projects/manatee/Build/Targets/x86_64-unknown-linux/Debug/",

    ...

    },
    {
      "type": "cppdbg",
      "name": "Remote QEMU-HOST: MarpalTest",
      "project": "Build\\Targets\\aarch64-gp-gnu-ree\\Debug\\MarpalTest.exe",
      "cwd": "\\\\10.x.xxx.87\\projects\\manatee\\Build\\Targets\\aarch64-gp-gnu-ree\\Debug",
      "program": "\\\\10.x.xxx.87\\projects\\manatee\\Build\\Targets\\aarch64-gp-gnu-ree\\Debug\\MarpalTest",

    ...

  ]
}
```
And what I would expect to see in _SelectStartupItem_ list box is a list of available configurations from that json:
* Remote QEMU-HOST: Marpal
* Remote QEMU-TA: DRM
* WSL Linux: Marpal
* WSL QEMU-HOST: WasabiSecureKeyExport
* WSL Linux: WasabiSushiAction
* Remote QEMU-HOST: MarpalTest

**Comment by paulmaybee** [comment]
What I am seeing is that the elements in the launch.vs.json do appear in the list of available configurations. But that also all the sln and csproj files appear. Have you tried scrolling down in the list to see if your items are there?

Also, have you tried selecting the "Show All Files" icon at the top of the solution explorer?

**Comment by ademyankov** [comment]
Shoot! :) "Show All Files" - works (I noticed not the elephant at all :)))) 

Ok, as for scrolling down in the list it stops on projects with 'M' letters, and doesn't scroll more. It gave me an idea and I tried to rename one of my configurations with the name starting with 'A' and voila it showed up in the beginning of the list!

I'll will use it as a workaround.

Thanks! 👍
