### ISSUE TITLE
remoteCopySourcesMethod: rsync appears to break remote build after clean phase

### ISSUE THREAD

**Issue by brettadams53** [Microsoft/VSLinux#289]
Microsoft Visual Studio Enterprise 2017
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.02558
Installed Version: Enterprise
Visual C++ 2017   00369-90250-37601-AA553
Microsoft Visual C++ 2017
Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package
Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

So lets say I have a CMake project with the .json config as follows:

{
      "name": "Linux-Debug",
      "generator": "Unix Makefiles",
      "remoteMachineName": "${defaultRemoteMachineName}",
      "configurationType": "Debug",
      "remoteCMakeListsRoot": "/home/brettadams/foo",
      "cmakeExecutable": "/usr/local/bin/cmake-3.9.6-Linux-x86_64/bin/cmake",
      "remoteBuildRoot": "/home/brettadams/foo/platform/${name}",
      "remoteInstallRoot": "/home/brettadams/foo/platform/install/${name}",
      "remoteCopySources": true,
      "remoteCopySourcesOutputVerbosity": "Normal",
      "remoteCopySourcesConcurrentCopies": "10",
      "remoteCopySourcesMethod": "rsync",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": ["linux-x64"]
},

When using "remoteCopySourcesMethod": "sftp"

1> 11:20:14 AM: Copying files to remote machine...
1> 11:27:57 AM: Copied 3110 files out of 3157...
1> 11:28:01 AM: Finished copying files (elapsed time 00h:07m:47s:026ms).

(a) On my VM All my files are copied over, I end up with a /home/brettadams/foo/platform/Linux-Debug folder
(b) I can run CMake Build All from the menu and my project builds as expected

I completely blow away my remote files on my VM and switch the config to rsync

When "remoteCopySourcesMethod": "rsync",
time is about 40 seconds, nice improvement!

//during cmake generation phase, all is well and I see that

1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /home/brettadams/foo/platform/Linux-Debug

(c) When I run CMake Build All from the menu (notice the last cleanup items are to remove both
(platform/Linux-Debug and platform folders)

Copying files to remote machine...
rsync -t --delete -v -r --exclude=.git --exclude=.vs  /C/Projects/foo/ rsync://root@localhost:28527/temp
sending incremental file list
./
....lots of cleanup done
..
..
deleting platform/Linux-Debug/
deleting platform/

sent 64929 bytes  received 361 bytes  26116.00 bytes/sec
total size is 177311234  speedup is 2715.75
cd /home/brettadams/foo/platform/Linux-Debug;/usr/local/bin/cmake-3.9.6-Linux-x86_64/bin/cmake --build "/home/brettadams/foo/platform/Linux-Debug"   --  ;

bash: line 0: cd: /home/brettadams/foo/platform/Linux-Debug: No such file or directory
Error: /home/brettadams/foo/platform/Linux-Debug is not a directory

Build failed.

The platform/Linux-Debug folders do not get recreated after the clean.  So what am I missing?  I really like the speedup of the files copy under rsync vs. sftp but the clean step appears under rsync to breaks the build process.   I can still use the sftp route to get the files across initially and do my work, but would like to use rsync instead.

**Comment by brettadams53** [comment]
lukka, yes I understand about the regeneration after a clean.  On my windows builds I have it going to external folders already, so I will do have it target the same on Linux.   Thought it was something simple. Thanks

**Comment by lukka** [comment]
Please reopen this issue or a newer one if you have any other question or issue to report, thanks!
