### ISSUE TITLE
build with remote Makefile

### ISSUE THREAD

**Issue by mprevot** [Microsoft/VSLinux#293]
When we do cross-platform dev, GNU make and Makefiles are pretty standards. 
I'm having a linux crossplatform project, with the local lxss as remote linux box.

However, I'm building the binaries with GNU make, but I wasn't able to make it work since it seems to be understood as a local (windows) command.

(it fails with C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(164,5): error MSB3073: The command "make td2b" exited with code 9009.)

VS need to be able to give a choice to build local or remote crossplatform projects.

![lxss-build](https://user-images.githubusercontent.com/8375354/40311142-4df1b096-5d0f-11e8-8b8c-41d056ff9b67.jpg)

**Comment by mprevot** [comment]
I actually had the `make` command to *remote build*. But I still have:

1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(163,5): warning : Build command not configured. Skipping...

of course, since I'm building everything on remote machine.

So, what do we need to do ?
Regards

**Comment by itodirel** [comment]
Hi @mprevot, sorry for the confusion, please use **Remote Build**, that will execute these commands on the remote machine if that is desired. **Build** will execute them locally. 

But to understand your issue more, since you mentioned cross, are you trying to run make on Windows, locally?

**Comment by mprevot** [comment]
@itodirel I'll give a try to remote build indeed, however, this seems over complicated since I'm coding in Windows, and building in WSL (locally).

Maybe a `bash make ###` should do the trick.

**Comment by itodirel** [comment]
I see, I can try that and report back, I think you need to do bash -c make or something like that

**Comment by itodirel** [comment]
closed, please let me know if that worked for you
