### ISSUE TITLE
Copying binary from remote Linux machine takes 30+ minutes

### ISSUE THREAD

**Issue by daniel347x** [Microsoft/VSLinux#294]
I have set up a Makefile project connecting to a remote Linux server running as a Docker container on a GCP VM.

VSLinux connects successfully and (using the 'Remote Build' command) successfully triggers the build of the project on the remote machine (I see the console output for the build in the VS console).

However, at that point, VSLinux proceeds to download the binary that was just built to the Windows machine.  The binary is ~150 MB, but the copy operation is very slow, requiring ~30 minutes.  I have confirmed via 'speedtest' (to install: 'sudo pip install speedtest-cli') that both download and upload speeds from the Linux container are fast (~1Gbit/s); also, my Windows internet is fast (~100 Mbit/s).  But the file copy is unusably slow.

Is this a known issue?  Is there something I can do to overcome the show-stoppingly slow file copy of the binary that is necessary prior to being able to debug?

**Comment by stanthomas** [comment]
There is a trick you can use - create a tiny little file as a final step in the makefile after your executable is built then set as the build target in VCLinux. Something like `echo "build ok" > a.out` should do it.

VCLinux doesn't do anything with the copied target when you debug in `gdb mode` and it doesn't even use it to test that the project is up to date.

**Comment by itodirel** [comment]
Hi, we need to investigate this, but usually, copies can be slow for various reasons. One thing I'd like to ask, could you debug directly on the container, with gdb mode, so that you do not need to copy the file back? Is the reason for the copy debugging? 

We also have knobs in the Property Pages that can disable any copy, let me know if you want to know how.

**Comment by itodirel** [comment]
let us know if this is still a problem
