### ISSUE TITLE
cannot open source file "iostream"

### ISSUE THREAD

**Issue by galah92** [microsoft/VSLinux#298]
* A brief description

Using a linux makefile project and WSL as remote, I'm able to compile & debug.
I do, however, get purple squiggles on basic includes and STL containers (iostream, string, memory, etc).
Remote headers loaded successfully.

![screenshot](https://preview.ibb.co/du8ztJ/Capture.png)

* Expected results

Well, intellisense for that too.

* Actual results (with build output window contents if applicable)

No intellisense.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Visual studio Community 2017 15.7.2, WSL with Ubuntu 18.04

* Steps required to reproduce the error

A basic cpp project, nothing more.

**Comment by itodirel** [comment]
the purple squiggles is not the same as the red squiggles; if you try to open the header iostream, what happens? does it open? you might get purple squiggles if you have another configuration where does headers are not available, I would have to know more about your project and solution to understand why that happens

**Comment by galah92** [comment]
@itodirel I'm sorry, I though I was clear enough.
I've got three projects: shared files, windows console and linux makefile.
Both windows and linux project reference the shared files project.

<a href="https://ibb.co/mzfw8J"><img src="https://thumb.ibb.co/mzfw8J/Capture.png" alt="Capture" border="0"></a>

I am able to open and watch the headers - the windows ones. `iostream`, for example, is opened from:
> c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\iostream

However, I'm getting errors from the linux project saying `cannot open source file "iostream"`, for example.
I believe the WSL headers **do** available, though, because is says so in the first screenshot I uploaded.

Is there a chance this is a bug in the "Remote Header IntelliSense" feature?

Thanks for you help.

**Comment by itodirel** [comment]
oh I see, thank you for explaining it; I think there might be a bug here with shared project support

**Comment by ShakeNBlake96** [comment]
Hi, I am getting a similar error. Everything was working a few days ago, but now I am getting a bunch of red squigglies. It recognizes the headers but now says 'namespace "std" has no member "vector"'. Something with the recent update messed up my iostream and vector. I would like to think I can't be the only one with this problem. Any ideas???

**Comment by rwinte** [comment]
I have the same issue with a Linux Makefile project in 15.7.4. This is with the same Remote Header settings from the original post.

![image](https://user-images.githubusercontent.com/906691/41740649-a2eac82a-7566-11e8-8f14-cb1fae0868e2.png)

**Comment by HymanZHAN** [comment]
Same problem here. Using VS2017 15.8.3 with Linux Makefile Project.

![image](https://user-images.githubusercontent.com/26806995/45313959-6391ea00-b4fe-11e8-85c0-e62ea8621e87.png)

**Comment by therealwolf42** [comment]
Have the same problem. What worked is to copy & paste the files from:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\Linux\include\usr` into `C:\Users\therealwolf42\AppData\Local\Microsoft\Linux\HeaderCache\1.0\<randomnumber>\usr`

I also copied over the lib folder, where the usr folder is. So I guess these folders aren't correctly copied AND/OR deleted.

**Comment by lukka** [comment]
@therealwolf42  do you have the `iostream `file on the remote Linux box? Could you please check where it is on the remote LInux machine, where it is the same file on the Windows machine under the HeaderCache directory? Thanks.

**Comment by JulyLeaver** [comment]
(C:\Users\Juliver\AppData\Local\Microsoft\Linux) 
It was good to delete the folder.
(I hope you have a backup.)

**Comment by gilmishal** [comment]
Any Update on this?

**Comment by lukka** [comment]
@gilmishal please try with the most recent version of VS, and if you still experience the issue, open a new ticket at Developer Community forums. Closing this issue.

**Comment by igots27** [comment]
Successfully merging a pull request may close this issue.
