### ISSUE TITLE
Incremental project build always results in a full rebuild.

### ISSUE THREAD

**Issue by stanthomas** [Microsoft/VSLinux#3]
Build project should compile only those source files that are not up to date, i.e. have been changed or did not compile in last build.
Instead, Build causes all source files to be copied to Linux target and recompiled, i.e. it does a Rebuild.

Known issue added here to track progress.

Visual Studio 2015 Pro Update 3
Windows 10 insider latest
VC_Linux 1.0.4
Mageia Linux 5 (x64)
gcc 4.9.2 / gdb 7.8.1 / gdbserver 7.8.1

**Comment by itodirel** [comment]
Thank you. Performance is very important to us, and we are working on this, in fact we are currently testing the improvements that we made here. Those will be available in 1.0.5, which we are planning on releasing soon.

**Comment by robotdad** [comment]
@stanthomas good with closing this one now that 1.0.5 is out?

**Comment by stanthomas** [comment]
Clossed this issue because 1.0.5 distinguishes between Build and Rebuild, only copying and building changed source files (.cpp / .c).
I have opened a new issue for header dependencies #29.
