### ISSUE TITLE
Copy headers from remote machine to local

### ISSUE THREAD

**Issue by AliAskari** [Microsoft/VSLinux#300]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

The CMake/Open Folder integration is awesome on Windows and everything Just Works&trade;. On remote machine building is very nice however there are still some problems with debugging. For example I use Conan package manager on Windows and Linux to manage my dependencies and I also expect to be able to debug and step into the headers and sources of those dependencies. On Windows it is possible to step into the headers of Conan packages because everything is local and Intellisense knows about them. However if I try to debug a Conan package on a remote machine I cannot do it because the headers are not available to Intellisense on the local machine. 

* Expected results

Be able to step into headers/sources of libraries. Also keep in mind that the version of the packages might change (You can try and edit `fmt/5.0.0@bincrafters/stable` to `fmt/4.1.0@bincrafters/stable`), so the solution should be able to fetch the new headers from the remote machine in this case and not depend on old headers.

* Actual results (with build output window contents if applicable)

![image](https://user-images.githubusercontent.com/4864412/41212390-84ed2f06-6d0b-11e8-8c7c-d1b08661f8f7.png)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Visual Studio 2017 15.7.3
This issue is independent from the remote machine settings (GCC/GDB/gdbserver versions)

* Steps required to reproduce the error
    - Clone this: repo: https://github.com/AliAskari/conan_demo
    - install Conan on remote/local machines (requires python/pip): `python -m pip install conan`
    - Open project using the open folder feature and build it on Windows/Linux
    - On Windows you are able to right click on `#include "fmt/format.h"` and open the `format.h` file however on the Linux configuration you will get an error stating that the header cannot be found.

* Required packages and commands to install

    - explained above

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by AliAskari** [comment]
Are there any updates on this issue? I have the latest version of Visual Studio Preview installed. I would love to test report possible issues. If there is a way to get your latest day builds that would also be amazing.

**Comment by lukka** [comment]
@AliAskari yes, you are right, headers files from the remote machine are copied over locally on the VS machine in order to have full Intellisense support. Please report back any feedback or suggestion, thanks!

**Comment by AliAskari** [comment]
@lukka I just tried it and I can't see any difference with the previous version. Intellisense is still not working. 

It would be awesome if you could add a simple "hello world" sample project in this repo that everyone could use as reference and report bugs/errors.

**Comment by martinkalkhofer** [comment]
I'm running into the same issue using 15.8pre4. Intellisense isn't working.

**Comment by AliAskari** [comment]
@lukka Do you have any updates on this issue?

**Comment by lukka** [comment]
@AliAskari could you please elaborate what is not working? 
Note that the current preview of Visual Studio downloads the headers file from the remote machine onto the Windows box by means of rsync, and those files will be used for Intellisense on VS. 
This is currently working only for the standard headers (e.g. /usr/include), i.e. if you have a headers installed at /anything/else it would not currently work yet.

**Comment by AliAskari** [comment]
@lukka I see. Well, my header files are actually under `/something/else`, so no wonder it's not working. Do you have any plans to support this feature?

**Comment by itodirel** [comment]
@AliAskari you can specify that in the Additional Include Directories and it will be copied and set for IntelliSense; we will detect it is a remote directory, copy it to Windows and automatically set IntelliSense

**Comment by AliAskari** [comment]
@itodirel Is this Additional Include directory a new option? Should I set it in CMakeSettings.json?
