### ISSUE TITLE
On downloading headers for IntelliSense, exceeds directory's max 260 character limit

### ISSUE THREAD

**Issue by tawe141** [microsoft/VSLinux#305]
On creating a remote cmake setup, VS establishes a connection and downloads the zip of headers. On unzipping, it tries to create directories exceeding the max 260 character limit on Windows, throwing an error. Setting the registry's LongPathsEnabled to 1 does not solve this even after restarting. IntelliSense now cannot even find the standard libraries. 

Local computer is running:
Windows 10 Home
Visual Studio 15.7.3

Remote server is running:
CentOS 6.6
gcc 4.4.7
gdb 7.2
cmake 2.8.3

Is there a temporary workaround? Maybe have IntelliSense use local includes instead?

**Comment by itodirel** [comment]
we're looking into it, thank you for the report
