### ISSUE TITLE
Option to delete CMake cache folder on the remote machine?

### ISSUE THREAD

**Issue by AliAskari** [Microsoft/VSLinux#307]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

For Windows CMake projects I get 4 options in the CMake menu after creating the cache, see below:

![image](https://user-images.githubusercontent.com/4864412/42466168-2620fce6-837c-11e8-8b89-88aa8b5bca49.png)

however when I switch the configuration to build on Linux I only have one option, Generate Cache and it's always there. Then after the cache is generated on the remote machine I don't get any new entries in the CMake and the Open Cache Folder option is greyed out. I can't know if cache is already generated for this project or not

![image](https://user-images.githubusercontent.com/4864412/42466230-47ba03b6-837c-11e8-80aa-6fd591de9283.png)

* Expected results

Change the `Generate Cache` option to `Regenerate Cache` after the first cache generation on both Windows and Linux.
At least add a `Delete Cache Folder` option for Linux based projects.

* Actual results (with build output window contents if applicable)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Visual Studio Preview 15.8.0
CMake 3.11.3 on the remote machine

* Steps required to reproduce the error

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by itodirel** [comment]
we are planning to adding this support in 16.0 Preview 2

**Comment by itodirel** [comment]
Hi, it should be in the next 1 month, but we can't say for sure. Sorry regarding the delay, we are trying to get to all the issues as soon as we can and are ramping up on that.

**Comment by itodirel** [comment]
this is now fixed, please install latest preview from here: https://visualstudio.microsoft.com/vs/preview/

**Comment by itodirel** [comment]
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
