### ISSUE TITLE
Configure tasks.vs.json to copy remote build output back to local machine

### ISSUE THREAD

**Issue by deiruch** [microsoft/VSLinux#308]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
I would like to configure a remote build task in tasks.vs.json to copy build output from the remote machine to my local machine. Alternatively, custom post-build steps that are run locally would also work.

* Expected results
Add support for a tasks.vs.json property called "copyTheFollowingBuildOutputFilesBackToSimonsLocalMachine"

* Actual results (with build output window contents if applicable)
I couldn't find a property that let's me copy files back to my machine automatically.

Here's an example:
```
{
  "version": "0.2.1",
  "tasks": [
    {
      "taskName": "Run make",
      "appliesTo": "Makefile",
      "type": "remote",
      "contextType": "custom",
      "command": "make clean ASW_em",
      "remoteMachineName": "some-machine.somewhere.com",
      "remoteCopyMethod": "rsync",
      "remoteCopyDirectory": "~/RemoteBuild",
      "remoteWorkingDirectory": "~/RemoteBuild/ASW"
    }
}
```

I would like to add the following property and expect VS to copy the specified files back to my machine after running make:
```
{
  "version": "0.2.1",
  "tasks": [
    {
      "taskName": "Run make",
      "appliesTo": "Makefile",
      "type": "remote",
      "contextType": "custom",
      "command": "make clean ASW_em",
      "remoteMachineName": "some-machine.somewhere.com",
      "remoteCopyMethod": "rsync",
      "remoteCopyDirectory": "~/RemoteBuild",
      "remoteWorkingDirectory": "~/RemoteBuild/ASW",
      "copyTheFollowingBuildOutputFilesBackToSimonsLocalMachine": [ "ASW_em.bin" ]
    }
}
```

**Comment by itodirel** [comment]
We don't really envision tasks.vs.json used like that. However. You can easily support this scenario first class with a Makefile Linux project, note than Makefile does not mean a Make project, or Make support. We believe Makefile will easily support your scenario. See https://docs.microsoft.com/en-us/cpp/linux/prop-pages/makefile-linux?view=vs-2019 and https://docs.microsoft.com/en-us/cpp/linux/create-a-new-linux-project?view=vs-2019
