### ISSUE TITLE
Build / Rebuild stops on first source file with error

### ISSUE THREAD

**Issue by stanthomas** [Microsoft/VSLinux#31]
VC++ on Windows continues build to end so that **all** sources are compiled, successfully or not.
Sometimes, when the error is in a header file and the same error occurs in multiple surce files this can generate rather a lot of error messages but then you're a superstar for fixing dozens of errors with a single correction  :wink: .
Using incremental build ensures that, once the errors are fixed, only the failed sources need be compiled again which is usually quick.

But VCLinux stops at the first source with errors. So the edit/build cycle results in not only compilation of previously failed sources but all the ones that follow it in the project too. Which, on larger applications, can defeat the object of going to lunch while the solution builds. Although this is, to a large extent, contingent on issue #29 : header dependencies and incremental builds.

For consistency, VCLinux should do the same as VC++ on Windows. This is what is expected and desired. It is also the behaviour of `make` when the `--keep-going` option is specified.
Keep Calm and Carry On, as the popular slogan has it.

Visual Studio 2015 Pro Update 3
Windows 10 insider latest
VC_Linux 1.0.5
Mageia Linux 5 (x64)
gcc 4.9.2 / gdb 7.8.1 / gdbserver 7.8.1

**Comment by itodirel** [comment]
this is now fixed and will be available in the next release

**Comment by stanthomas** [comment]
Working in VS2017 Preview 2 (15.3 26510.0) / VCLinux 1.0.7.
