### ISSUE TITLE
CMake remote project is not taking the input arguments specified in launch.vs.json

### ISSUE THREAD

**Issue by necktwi** [Microsoft/VSLinux#312]
* A brief description
I am trying to debug a remote Linux CMake project. I have specified the command line input arguments for the application in `launch.vs.json` as shown below

```
{
   "version": "0.2.1",
   "defaults": {},
   "configurations": [
   {
      "type": "cppdbg",
      "name": "CMakeRemoteTest",
      "project": "CMakeLists.txt",
      "cwd": "/media/Tin/Workspace/CMakeRemoteTest/Build/VS/",
      "program": "/media/Tin/Workspace/CMakeRemoteTest/Build/VS/CMakeRemoteTest",
      "args": [ "-s", "normal" ],
      "MIMode": "gdb",
      "externalConsole": true,
      "remoteMachineName": "192.168.2.23",
      "pipeTransport": {
         "pipeProgram": "${debugInfo.shellexecPath}",
         "pipeArgs": [
            "/s",
            "${debugInfo.remoteMachineId}",
            "/p",
            "${debugInfo.parentProcessId}",
            "/c",
            "${debuggerCommand}",
            "--tty=${debugInfo.tty}"
         ],
         "debuggerPath": "/usr/bin/gdb"
      },
      "setupCommands": [
         {
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
         }
      ],
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
   }
   ]
}
```
* Expected results
Program should receive input arguments

* Actual results (with build output window contents if applicable)
The program doesn't receive input arguments

* VC++ version:
Visual C++ 2017 00369-60000-00001-AA086,
VisualStudio.15.Release/15.7.5+27703.2042
Linux: 4.9.78-v7 armv7l GNU/Linux,
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1\~16.04.10) 5.4.0 20160609
gdb (Ubuntu 7.11.1-0ubuntu1\~16.5) 7.11.1
gdbserver (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1

**Comment by paulmaybee** [comment]
I am not able to reproduce your problem. Did you select "ferryfair" as the startup item before you launched the debugger? Can you attach a trivial repro case?

**Comment by necktwi** [comment]
Oops! Didn't know VS generates another target apart to the ones specified in CMake.

**Comment by itodirel** [comment]
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
