### ISSUE TITLE
linker error 

### ISSUE THREAD

**Issue by 23pret** [microsoft/VSLinux#314]
I am getting the following linker error:

Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(341,5): error : Packet is too big. Maximum packet size is 68536 bytes.

Does anyone know what this error means?

here is the full error log:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(376,5): warning MSB8004: Intermediate Directory does not end with a trailing slash. This build instance will add the slash as it is required to allow proper evaluation of the Intermediate Directory.
1>Validating architecture
1>Starting remote build
1>Compiling sources:
1>Linking objects
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(341,5): error : Packet is too big. Maximum packet size is 68536 bytes.
1>Done building project "Applications.vcxproj" -- FAILED.

**Comment by 23pret** [comment]
here is the full error log:
>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(376,5): warning MSB8004: Intermediate Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Intermediate Directory.
1>Validating architecture
1>Starting remote build
1>Compiling sources:
1>Linking objects
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(341,5): error : Packet is too big. Maximum packet size is 68536 bytes.
1>Done building project "Applications.vcxproj" -- FAILED.

**Comment by lukka** [comment]
@23pret  which version of VS are you using?

**Comment by jambagigirish** [comment]
After running the diagnostic
Task "Ld"
1>    Task Parameter:ProjectDir=C:\ViewStore\workspace\project1\Config_Files\Linux_workspace\
1>    Task Parameter:ProjectFileName=Applications.vcxproj
1>    Task Parameter:RemoteProjectDir=/home/user1/project/project1/Source/Applications
1>    Task Parameter:IntermediateDir=~/project/project1/temp/Applications/Release/
1>    Task Parameter:RemoteTarget=1824558917;localhost (username=, port=22, authentication=Password)

**** there are 1660 sources which are .o files*****
1>    Task Parameter:
    Sources=
1>            ~/project/project1/temp/Applications/Release/object1.o
1>                    AdditionalDependencies=/mnt/c/ViewStore/workspace/Release/linkLibrary1.so;;
1>                    AdditionalLibraryDirectories=
1>                    AdditionalOptions=linkLibrary1.so 
1>                    DebuggerSymbolInformation=true
1>                    EnableUAC=
1>                    FunctionBinding=true
1>                    IgnoreDefaultLibraries=false
1>                    ImportLibrary=~/project/project1/Release/Applications.so
1>                    IncrementalLink=false
1>                    LinkDLL=true
1>                    ManifestFile=
1>                    NoExecStackRequired=true
1>                    OptimizeForMemory=false
1>                    OutputFile=~/project/project1/Release/Applications.so
1>                    PrintMap=true
1>                    Relocation=true
1>                    SharedLibrarySearchPath=
1>                    ShowProgress=true
1>                    TimestampSurrogate=~/project/project1/temp/Applications/Release/1824558917.CompileUpToDateFile.tlog
1>                    Trace=true
1>                    UnresolvedSymbolReferences=true
1>                    VerboseOutput=true
1>                    Version=false
1>                    WholeArchiveBegin=true


1>    g++ -o "~/project/project1/Release/Applications.so" -Wl,--stats -Wl,--verbose -Wl,--trace -Wl,--print-map -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -shared -Wl,--whole-archive <122239 character length .o objects> (like '~/project/project1/temp/Applications/Release/object1.o" -there are 1660 object files like this some filenames are longer than this )

How should we compress or lessen the command line parameters length?

**Comment by 23pret** [comment]
As a test ,we reduced  the length of the g++ linker command to less then 68K characters long and it fixed the issue.  But unfortunately our project is huge and the command length is currently three times longer. 

Is there a configuration parameter for this somewhere in visualstudio to change 68536 limit???

**Comment by 23pret** [comment]
hi - any suggestion how to fix this one?

**Comment by itodirel** [comment]
I think this is a bug on our side and we need to fix it

**Comment by 23pret** [comment]
Yes,  Our project has 3k+ files and we were able to build directly on linux but not using VS.

**Comment by itodirel** [comment]
We will be tracking this bug internally, and update this thread here when we have a fix.

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
