### ISSUE TITLE
CMakeListst.txt add_subdirectory that is not a sub directory of the project

### ISSUE THREAD

**Issue by Necktwi** [Microsoft/VSLinux#318]
In my CMakeLists.txt I did
```
add_subdirectory (
   ${CMAKE_CURRENT_SOURCE_DIR}/../OtherCMakeProject 
   ${CMAKE_CURRENT_SOURCE_DIR}/../OtherCMakeProject/Build/VS
)
```
* Expected results
A reference of sub project in the SolutionExplorer's file system tree

* Actual results
No reference of sub project in the SolutionExplorer's file system tree

* VC++ version:
Visual C++ 2017 00369-60000-00001-AA086,
VisualStudio.15.Release/15.7.5+27703.2042
Linux: 4.9.78-v7 armv7l GNU/Linux,
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1\~16.04.10) 5.4.0 20160609
gdb (Ubuntu 7.11.1-0ubuntu1\~16.5) 7.11.1
gdbserver (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1

**Comment by lukka** [comment]
@necktwi could you provide us a screenshot of the solution explorer? have you tried with VS 15.8 preview?

**Comment by necktwi** [comment]
I did try VS 15.8.0 preview 5.0
![se](https://user-images.githubusercontent.com/2793912/43460521-798d1512-94ee-11e8-95da-7ef256269064.png)

**Comment by lukka** [comment]
@necktwi The solution explorer is showing the content of the files in the subtree of the folder you opened.
My suggestion is to have a root folder that contains your CMakeLists.txt file that does include all the project you need, and these must be in the subdirectories of the root dir. Regarding external project, you do not need to include them by add_subdirectory.
I would strongly suggest to use [FIND_PACKAGE](https://cmake.org/cmake/help/v3.12/command/find_package.html
) in 'config' mode in order to include dependency on a external project.
Let us know!

**Comment by necktwi** [comment]
But putting a dependency inside the project makes it impractical for the other internal projects to include the same dependency. A dependency doesn't always have to be an external project it could be some another internal project.

**Comment by lukka** [comment]
@necktwi Could you provide a small repro of the depending and dependant projects in a zip file attached to this issue? thanks

**Comment by lukka** [comment]
@necktwi  thanks for the repro.
Right now CMake VS for Linux support requries you to have all source files under the subtree where CMakeLists.txt is at the root of it.

I would suggest you to resolve external project references by using FIND_PACKAGE, and please avoid using ADD_SUBDIRECTORY and then you add a parent directory, as that is not how CMake is supposed to work.

In your particular case you would suggest to:
1 -  could create another Git repository that contains CMakeList.txt at the root, and make the two repositories submodule of the first one;
2 - merge the repositories in one and avoid the usage of submodules;

Note that with your two separate Git projects that depends each other like the one you shown, you would not be able to run any CI build server: in fact you need to have in each Git repository project that builds without requiring other source code coming from other repositories, but you could have external dependencies that must be resolved using FIND_PACKAGE.


Hope this helps, I am open to discuss this further, thanks for your patience.

**Comment by necktwi** [comment]
Yes to build on travis-ci is bit of a pain but just a couple of lines as [here](https://github.com/necktwi/LiSpScPaRo/blob/50518394ed29171b69ed13b5af0639a6c041b7ef/.travis.yml#L46) should do the trick.

**Comment by itodirel** [comment]
seems like solution found

**Comment by Necktwi** [comment]
hey kiddo! seems like you didn't understand the problem!

**Comment by itodirel** [comment]
We are not supporting directories outside the workspace directory, if that is the question. If it is something else, please provide clear, self sufficient repro steps that we can use to further investigate. If you can provide this info, please open a ticket on the Developer Community and provide the info in there. 

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.

**Comment by MichaelCoutlakis** [comment]
I recently came across this issue. Fortunately in my case it was possible to work around the issue by making a folder link to the out-of-tree directory so that it effectively became a subdirectory
