### ISSUE TITLE
VS 15.7.6 can't Generate CMake cache, possible symlink issue

### ISSUE THREAD

**Issue by BenArtes** [microsoft/VSLinux#320]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
I'm trying to import a Robot Operating System (ROS) project from a Ubuntu 16.04 VM. After cloning the Linux project onto the windows machine and configuring the Remote in Connection Manager I can see the /usr folder has been copied onto the windows machine but not the files in /opt (which contains the ROS files).

When I try to Generate the CMake Cache I receive the following error:
>CMake Error at C:\proj\src\CMakeLists.txt:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake".

cd /var/tmp/build/c1806afe-be12-4b38-bdfd-a022e7c09616/build/Linux-Debug;/opt/cmake/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "\var\tmp\src\c1806afe-be12-4b38-bdfd-a022e7c09616\Linux-Debug"; returned with exit code: 1		C:\proj\src\CMakeLists.txt	1	

* Expected results
The CMake cache generation should succeed.

* Actual results (with build output window contents if applicable)
>Output:
>
>1> Copying files to remote machine...
1> rsync -t --delete -v -r --exclude=.git --exclude=.vs  /C/proj/src/ rsync://cbrr@localhost:58230/temp
1> sending incremental file list
1> 
1> sent 355 bytes  received 13 bytes  736.00 bytes/sec
1> total size is 26800  speedup is 72.83
1> /opt/cmake/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "/var/tmp/src/c1806afe-be12-4b38-bdfd-a022e7c09616/Linux-Debug/CMakeLists.txt";
1> -- Configuring incomplete, errors occurred!
1> CMake Error at C:\proj\src\CMakeLists.txt:1:
1>   Parse error.  Expected a command name, got unquoted argument with text
1>   "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake".
1> 
1> 
1> cd /var/tmp/build/c1806afe-be12-4b38-bdfd-a022e7c09616/build/Linux-Debug;/opt/cmake/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "\var\tmp\src\c1806afe-be12-4b38-bdfd-a022e7c09616\Linux-Debug"; returned with exit code: 1

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
VS Version: 15.7.6
Ubuntu 16.04.10 x86_64
GCC: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
GDB: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
CPU: x86_64

* Steps required to reproduce the error
Try to import basic ROS CMake / Catkin based project with ROS files in /opt

* Required packages and commands to install
[ROS Kinetic](http://wiki.ros.org/kinetic)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by lukka** [comment]
@BenArtes  thanks for the report. Please could tell us which project you cloned? We need the git repo url.

**Comment by BenArtes** [comment]
Sorry for not including that; I'd been hoping this was a known issue.

Tomorrow I'll spin up a fresh Ubuntu 16.04 VM with fresh installs of ROS etc and make a github repo for a basic ROS hello world (as described in [A Gentle Introduction to ROS](https://cse.sc.edu/~jokane/agitr/agitr-letter.pdf)).

Would a link to that repo be sufficient? Should I include links / instructions for basic ROS installation and configuration from the fresh Ubuntu Install?

**Comment by lukka** [comment]
@BenArtes yes, that should be fine. Is the symlink already on the remote target? Or is the symlink expected to be copied over from Windows to Linux by mean of rsync? The former should not be a problem the latter needs investigation if it is possible and how.

**Comment by BenArtes** [comment]
Sorry for the delay, and I solved the symlink issue and found what I believe are the core issues with ROS.

First: [My Test Repo](https://github.com/BenArtes/catkin_vstest_ws) - I've included the normally .gitignored devel and build directories which should be deleted before attempting to build. This project was located `~/catkin_vstest_ws` and contains a package `hello` with node `hello` that should print `Hello, ROS!`.

Installation and testing:
* On clean Ubuntu VM Install [ROS Kinetic](http://wiki.ros.org/kinetic/Installation/Ubuntu)
* Update CMake to support version >= 3.8.x
* Install Git
* `cd ~/`
* `git clone https://github.com/BenArtes/catkin_vstest_ws`
* `cd ~/catkin_vstest_ws`
* `source /opt/ros/kinetic/setup.bash`
* `catkin_make`
* `roscore`
* In a second terminal:
  * `cd ~/catkin_vstest_ws`
  * `source devel/setup.bash`
  * `rosrun hello hello`
* You should see `Hello, ROS!` on the second terminal

To reproduce this issue, clone the project on Windows, create remote connection to Ubuntu VM / copy sysroot, import cmakeproject, and try to generate cache / build. (Note, as discussed below, need to use `-c core.symlinks=true` while cloning in console running as administrator.

### Symlink Solutions and Remaining Issues:

*  ROS uses a symlink for one of it's CMakeLists.txt files (pointing to a CMakeLists.txt file in /opt/ros) and when I git cloned that project to my Windows machine it stopped being a symlink. I needed to clone the repo with `-c core.symlinks=true`

*  Now when I try to generate the cache from the CMakeLists.txt I get the following error:
  * >1> Copying files to remote machine...
1> rsync -t --delete -v -r --exclude=.git --exclude=.vs  /C/ulc_robotics/firmware/cbrr_app_ws/src/eth/ rsync://cbrr@localhost:55772/temp
1> sending incremental file list
1> ./
1> CMakeLists.txt
1> eth.cpp
1> package.xml
1> sick_socket.cpp
1> sick_socket.h
1> 
1> sent 19741 bytes  received 106 bytes  39694.00 bytes/sec
1> total size is 19398  speedup is 0.98
1> /opt/cmake/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "/var/tmp/src/63b7a0e1-5b64-7431-839f-8fbbb255dc6f/Linux-Debug/CMakeLists.txt";
1> -- The C compiler identification is GNU 5.4.0
1> -- The CXX compiler identification is GNU 5.4.0
1> -- Check for working C compiler: /usr/bin/cc
1> -- Check for working C compiler: /usr/bin/cc -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Detecting C compile features
1> -- Detecting C compile features - done
1> -- Check for working CXX compiler: /usr/bin/c++
1> -- Check for working CXX compiler: /usr/bin/c++ -- works
1> -- Detecting CXX compiler ABI info
1> -- Detecting CXX compiler ABI info - done
1> -- Detecting CXX compile features
1> -- Detecting CXX compile features - done
1> CMake Error at C:\ulc_robotics\firmware\cbrr_app_ws\src\eth\CMakeLists.txt:10 (find_package):
1>   By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
1>   asked CMake to find a package configuration file provided by "catkin", but
1>   CMake did not find one.
1> 
1>   Could not find a package configuration file provided by "catkin" with any
1>   of the following names:
1> 
1>     catkinConfig.cmake
1>     catkin-config.cmake
1> 
1>   Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
1>   "catkin_DIR" to a directory containing one of the above files.  If "catkin"
1>   provides a separate development package or SDK, be sure it has been
1>   installed.
1> 
1> 
1> -- Configuring incomplete, errors occurred!
1> See also "/var/tmp/build/63b7a0e1-5b64-7431-839f-8fbbb255dc6f/build/Linux-Debug/CMakeFiles/CMakeOutput.log".
1> cd /var/tmp/build/63b7a0e1-5b64-7431-839f-8fbbb255dc6f/build/Linux-Debug;/opt/cmake/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "\var\tmp\src\63b7a0e1-5b64-7431-839f-8fbbb255dc6f\Linux-Debug"; returned with exit code: 1
Configuration switch to Linux-Debug complete.
  * This makes sense as ROS requires sourcing some files [(`source devel/setup.bash`)](https://github.com/BenArtes/catkin_vstest_ws/tree/master/devel) to correctly configure the environment. What would be the best way to do this in VSLinux?
* I believe even after I resolve this issue, sysroot not having the /opt directory will cause further issues.
* Finally, I can't open the catkin_vstest_ws folder because 'File->Open->CMake' doesn't understand the symlink, so I can either open the project as 'File->Open->CMake' for the Node which gives the above, or 'File->Open->Folder' and try to Generate Cache which has other rsync issues. What would you suggest?

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
