### ISSUE TITLE
Natvis DisplayString Missing, Tooltip Refresh Not Working

### ISSUE THREAD

**Issue by conwayk** [Microsoft/VSLinux#321]
I'm having an issue where Natvis DisplayStrings are not working when using VS2017 to debug a Linux project. 

Essentially I'm having the same issues as described in issues #112 and #222 although both these issues say they have been fixed.

Here is some very simple sample code I am trying:
`class Rectangle { public: int height; int width; };

int main()
{
  Rectangle square;
  square.height = 5;
  square.width = 2;

  Rectangle toto = square;

  return 0;
}`

With the following Natvis file:
`<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
   <Type Name="Rectangle">
    <DisplayString>{height}</DisplayString>
    <Expand>
      <Item Name="CustomHeight">height</Item>
      <Item Name="CustomWidth">width</Item>
    </Expand>
  </Type>
</AutoVisualizer>`

When hovering over the variable, the DisplayString does not work and the Visualized View says it requires an explicit refresh. Pressing the refresh button does nothing, however.
![visualization](https://user-images.githubusercontent.com/42149782/43729423-3b557938-9976-11e8-9a8e-a549551d6b92.png)

When added as a watch variable, Natvis is working for items in the "Expand" block but the Display String still does not work.
![visualization2](https://user-images.githubusercontent.com/42149782/43729424-3d67197a-9976-11e8-84cb-6ffa1c306b65.png)

VS2017 v15.7.6
Linux CentOS 7.5.1804, x64 
gcc v4.8.5
gdb v7.6.1
Using gdb mode

Any ideas how I can get this to work? Thanks!

**Comment by paulmaybee** [comment]
This is a bug in the VS Linux support. There is no project property to allow the user to turn on the default display of "DisplayString" elements. Until it gets fixed you can hack around the problem by taking advantage of another bug: replace the default stl visualizer file in Properties->Debugging->Visualization File (**$(LinuxNatvisPath)\stl.natvis**) with the string (**$(LinuxNatvisPath)\stl.natvis" ShowDisplayString="true**). Note the absence of both an opening and closing quote on this string. This should result in enabling the DisplayStrings.

**Comment by paulmaybee** [comment]
Fixed in the next major release of VS.

**Comment by itodirel** [comment]
@conwayk please let us know if this isn't working for you

**Comment by itodirel** [comment]
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
