### ISSUE TITLE
Debugging with cross-platfrom device without ssh

### ISSUE THREAD

**Issue by avalon1610** [Microsoft/VSLinux#322]
Our embedded device does not have ssh access for some security reason. how can I debug with it?

- write source code on windows (VS2017)
- build app use cross-platform g++ (Build machine, Linux, x64)
- run app on embedded device (Target embedded device, armv7)

Because device can not be accessed via ssh, I can not set it as a remote build machine.
I tried set Debugging Mode to gdbserver,  it seems try to start up a gdbserver on remote build machine.
So I tried startup a gdbserver on device, then use a port forwarding to forward all network traffic from build machine 's port to gdbserver listening port which on target device, but with no luck, it's not working.

**Comment by paulmaybee** [comment]
To debug on a remote device without SSH try these steps:
1. start gdbserver on the device listening on some port (e.g. 12345)
2. In VS open a folder (File->Open->Folder) containing your sources and binary.
3. In the solution explorer enable "Show all files" at the top of the explorer.
4. Find your binary (e.g. a.out) and right click on it. Select "Debug and Launch Settings".
5. From the popup select "C/C++ Launch for Linux".
6. The file launch.vs.json should now be open and you should see some json that looks like this:
```{
      "type": "cppdbg",
      "name": "ConsoleApplication46.out",
      "project": "bin\\x64\\Debug\\ConsoleApplication46.out",
      "cwd": "${debugInfo.remoteWorkspaceRoot}",
      "program": "${debugInfo.fullTargetPath}",
      "MIMode": "gdb",
      "externalConsole": true,
      "remoteMachineName": "${debugInfo.remoteMachineName}",
      "pipeTransport": {
        "pipeProgram": "${debugInfo.shellexecPath}",
        "pipeArgs": [
          "/s",
          "${debugInfo.remoteMachineId}",
          "/p",
          "${debugInfo.parentProcessId}",
          "/c",
          "${debuggerCommand}",
          "--tty=${debugInfo.tty}"
        ],
        "debuggerPath": "/usr/bin/gdb"
      },
      "setupCommands": [
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
    }
```
  Edit the content to make it look like this where the paths and address match your folder locations and device address:

```
    {
      "type": "cppdbg",
      "name": "ConsoleApplication46.out",
      "project": "bin\\x64\\Debug\\ConsoleApplication46.out",
      "cwd": "C:\\Users\\your-name\\Source\\Repos\\ConsoleApplication46\\bin\\x64\\Debug",
      "program": "C:\\Users\\your-name\\Source\\Repos\\ConsoleApplication46\\bin\\x64\\Debug\\ConsoleApplication46.out",
      "MIMode": "gdb",
      "miDebuggerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\VC\\Linux\\bin\\gdb\\8.1\\arm-linux-gnueabihf-gdb.exe",
      "miDebuggerServerAddress": "device-name-or-address:12345",
      "setupCommands": [
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true
    }
```
  7. Select you program as the "Startup Item" on the VS run button and press the button to start debugging.

**Comment by avalon1610** [comment]
Thanks for the reply.
I tried this solution, it show me an error said: 
> D:\Project\LinuxDebugTest\LinuxDebugTest\bin\x64\Debug\LinuxDebugTest.out is not a valid Win32 application.

here is my launch.vs.json
```
{
 "version": "0.2.1",
 "defaults": {},
 "configurations": [
   {
     "type": "cppdbg",
     "name": "LinuxDebugTest.out",
     "project": "bin\\x64\\Debug\\LinuxDebugTest.out",
     "cwd": "D:\\Project\\LinuxDebugTest\\LinuxDebugTest\\bin\\x64\\Debug\\",
     "program": "D:\\Project\\LinuxDebugTest\\LinuxDebugTest\\bin\\x64\\Debug\\LinuxDebugTest.out",
     "MIMode": "gdb",
     "miDebuggerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\VC\\Linux\\bin\\gdb\\7.9\\arm-linux-gnueabihf-gdb.exe",
     "miDebuggerServerAddress": "172.29.2.176:7777",
     "setupCommands": [
       {
         "text": "-enable-pretty-printing",
         "ignoreFailures": true
       }
    ],
    "visualizerFile": "${debugInfo.linuxNatvisPath}",
    "showDisplayString": true
   }
 ]
}
```

by the way, there is a red squiggle under `cppdbg` says:
> JSON validation failed: Should be one of: '"dll"'

Does this have any effect?

**Comment by paulmaybee** [comment]
Sorry for the long break. Are you still having this issue? What version of VS2017 are you running? Do you have the Visual C++ for Linux Development installed?

**Comment by itodirel** [comment]
please reactivate if you still have a problem here

**Comment by itodirel** [comment]
We also added debug deploy, that might be relevant here, please check it out. 

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
