### ISSUE TITLE
Configure GDB to ignore 'raise.c not found' exception

### ISSUE THREAD

**Issue by duncangravill** [Microsoft/VSLinux#324]
I'm working on a solution that consists of a .net core console app interoperating with a VCLinux shared object project.

When the .net core console app project is set as the startup project the solution runs as expected and the shared object file produced by the VCLinux project runs smoothly. However when the VCLinux project is setup as the startup project, so that it can be debugged and developed, Visual Studio breaks on an unhandled exception and notifies that it cannot find `raise.c` source and states `You need to find raise.c to view the source for the current call stack frame`.

The call stack looks like:

`libc.so.6!__GI_raise(int sig) Line 51`
`libc.so.6!__GI_abort() Line 79`
`libcoreclr.so![Unknown/Just-In-Time compiled code]`	

So it seems the exception originates from dot net core code.

Is there a way that GBD can be configured within VCLinux to ignore this exception? Preferably I'd like to ignore exceptions and source not found issues that don't relate directly to the project I'm working on.

If this isn't currently possible with VCLinux can you shine some light on and alternative way to configure the debug environment?

**Comment by duncangravill** [comment]
The exception was actually a DllNotFoundException being thrown from PInvoke, the error message just seemed really strange to me and not relevant to the cause, and the call stack led me to believe the exception was originating from a dotnet background thread, which could potentially be ignored.

It seems I was off track, sorry for the confusion.

**Comment by itodirel** [comment]
Great, thank you.

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
