### ISSUE TITLE
Python Pretty-Printing when attaching with Linux makefile vcxproj

### ISSUE THREAD

**Issue by conwayk** [Microsoft/VSLinux#327]
I've tried to use Python Pretty-Printing with a Linux makefile vcxproj. It seems to work when doing a debug launch but not when attaching. If I try directly on the Linux machine, pretty printing works for both debug and attach.

Is there a way to enable Python pretty-printing when attaching using a Linux makefil vcxproj? There is a blog post about this at [Attach to Process improvements](https://blogs.msdn.microsoft.com/vcblog/2018/03/13/linux-c-workload-improvements-to-the-project-system-linux-console-window-rsync-and-attach-to-process/) but it's not clear if this applies for Linux vcxproj makefile projects (and it didn't work when I tried it).

VS2017 v15.8
Linux CentOS 7.5.1804, x64
gcc v4.8.5
gdb v7.6.1
Using gdb mode

**Comment by paulmaybee** [comment]
You can enable pretty-printing using the command windows (View->Other Windows->Command Window). Just enter 
`debug.miexec -enable-pretty-printing`

**Comment by conwayk** [comment]
Thanks! This worked with a minor modification of using debug.midebugexec rather than debug.miexec.

Is there any way to automate it, perhaps with Microsoft.MIEngine.Options.xml? I added this file with the following contents to my project but it doesn't seem to execute automatically.

`<?xml version="1.0" encoding="utf-8"?>
<SupplementalLaunchOptions>
    <AttachOptions>
      <AttachOptionsForConnection>        
        <SetupCommands>
          <Command IgnoreFailures="true">-enable-pretty-printing</Command>
        </SetupCommands>
      </AttachOptionsForConnection>
    </AttachOptions>
</SupplementalLaunchOptions>`

Thanks!

**Comment by paulmaybee** [comment]
That options file looks like it should work. Do you have the file placed in the solution directory?

**Comment by paulmaybee** [comment]
Hmm. Ok, this is what I have done and it works, even when the solution open contains a Makefile project.

1. Opened a solution in VS.
2. Copied your xml from above into Microsoft.MIEngine.Options.xml in c:\users\me\Repos\ConsoleApplication1 (the solution directory)
3. Started ConsoleApplication1.out running on the target linux machine
4. Opened the Debug>Attach to Process dialog and selected ConsoleApplication1 on the target.

I also turned on logging ("Debug.MIDebugLog /On:c:\users\me\out.log") and when I examined the log file after the debug session I see the following text at the top of the file:
```
SupplementalOptions<?xml version="1.0" encoding="utf-8"?>
SupplementalOptions<SupplementalLaunchOptions>
SupplementalOptions  <AttachOptions>
SupplementalOptions    <AttachOptionsForConnection>
SupplementalOptions      <SetupCommands>
SupplementalOptions        <Command IgnoreFailures="true">-enable-pretty-printing</Command>
SupplementalOptions      </SetupCommands>
SupplementalOptions    </AttachOptionsForConnection>
SupplementalOptions  </AttachOptions>
SupplementalOptions</SupplementalLaunchOptions>

If you try this do you see the SupplementalOptions show up in the log?



```

**Comment by conwayk** [comment]
Hi @paulmaybee , actually it was my mistake, I was putting the xml file in the project folder location, not the solution folder location. When I was following the steps you did I realized the mistake. It works now! And the log command is very useful especially for debugging the pretty printers! Thanks!

**Comment by itodirel** [comment]
Thank you.

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
