### ISSUE TITLE
Memory Window read memory failed when debug

### ISSUE THREAD

**Issue by cxh852456** [Microsoft/VSLinux#328]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

**When i debug a test case, i found that it is valid in variants window but not valid in memory window**

* Expected results

**In the Memory window i can see the same result with the variants windows**

* Actual results (with build output window contents if applicable)

**not the same**

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

VS : 15.8.2
VSLinux: 1.0.9.27924
Target: WSL  ubuntu 18.04
host:  Win10 x64 latest
GCC: gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)
GDB :GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
gdbserver:GNU gdbserver (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git

* Steps required to reproduce the error

* Required packages and commands to install

![_20180830135502](https://user-images.githubusercontent.com/1539666/44832175-57836e00-ac5c-11e8-92aa-c37c4ef9f52f.png)

**Comment by paulmaybee** [comment]
I am not able to reproduce your problem. Does this happen on every project? Do you have a small repro project that you can share?

**Comment by cxh852456** [comment]
it is a sample in code of follow link 

https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore

this problem happen every time in this project, other projects is testing, if i have some progress i will tell u

**Comment by paulmaybee** [comment]
Still not able to duplicate using the Linux sample from https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/Linux_OSX. 

You seems to be using the Windows sample and somehow building it for Linux. Are you defining "_WIN32" for your Linux build? Is that what you intended?

Perhaps if you told me how you built the sample code I could reproduce your behavior.

**Comment by itodirel** [comment]
closed, please reactivate with more info @cxh852456

**Comment by itodirel** [comment]
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
