### ISSUE TITLE
Issues debugging embedded ARM device

### ISSUE THREAD

**Issue by ConductedForce** [Microsoft/VSLinux#331]
I've been following [this tutorial](https://blogs.msdn.microsoft.com/vcblog/2018/01/10/debugging-an-embedded-arm-device-in-visual-studio/) on the Microsoft blogs for debugging and embedded ARM device. 

I've gotten to the end but I'm having two issues. The first is that the `tasks.vs.json` doesn't run when I build the Makefile or run the debug. It should copy the BIN file to the drive letter, but it doesn't. First question on that: Is there a way to have it output completion or failure notices?

 When I start the debug procedure, it completely ignores the breakpoints, but I can hit the pause button and it will stop where ever it is in the program.

I am using Visual Studio 2017 Community, but not the Preview version. Should I use the Preview version instead?

Lastly, I'm uncertain if the order of my setup commands are correct:
```
      "setupCommands": [
        {
          "text": "-environment-cd ${workspaceRoot}/BUILD"
        },
        {
          "text": "-file-exec-and-symbols Nucleo_blink_led.elf",
          "description": "load file",
          "ignoreFailures": false
        },
        {
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        },
        {
          "text": "monitor reset halt",
          "ignoreFailures": true
        },
        {
          "text": "monitor reset init",
          "ignoreFailures": true
        }
      ],
```

I'm using Windows 7 64bit
Visual Studio 2017 Community Version 15.8.3
OpenOCD 0.10.0
Internal ARM GDB included in Visual Studio
Using an ST Nucleo F429ZI board found [here](https://os.mbed.com/platforms/ST-Nucleo-F429ZI/)

Here is the Output when I start debugging:

```
openocd: Open On-Chip Debugger 0.10.0
openocd: Licensed under GNU GPL v2
openocd: For bug reports, read
openocd: 	http://openocd.org/doc/doxygen/bugs.html
openocd: Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
openocd: adapter speed: 2000 kHz
openocd: adapter_nsrst_delay: 100
openocd: none separate
openocd: srst_only separate srst_nogate srst_open_drain connect_deassert_srst
openocd: Info : Unable to match requested speed 2000 kHz, using 1800 kHz
openocd: Info : Unable to match requested speed 2000 kHz, using 1800 kHz
openocd: Info : clock speed 1800 kHz
openocd: Info : STLINK v2 JTAG v28 API v2 SWIM v18 VID 0x0483 PID 0x374B
openocd: Info : using stlink api v2
openocd: Info : Target voltage: 3.241967
openocd: Info : stm32f4x.cpu: hardware has 6 breakpoints, 4 watchpoints
=thread-group-added,id="i1"
GNU gdb (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 7.12.1.20170417-git
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
openocd: Info : accepting 'gdb' connection on tcp/3333
openocd: Info : device id = 0x20016419
openocd: Info : flash size = 2048kbytes
openocd: Info : Dual Bank 2048 kiB STM32F42x/43x/469/479 found
openocd: undefined debug reason 7 - target needs reset
0x00000000 in ?? ()
Note: automatically using hardware breakpoints for read-only addresses.
openocd: Warn : WARNING! The target is already running. All changes GDB did to registers will be discarded! Waiting for target to halt.
@"WARNING! The target is already running. All changes GDB did to registers will be discarded! Waiting for target to halt.\n"
Loaded 'shared libraries loaded at this time.'. Cannot find or open the symbol file.
```

tasks.vs.json

```
{
  "version": "0.2.1",
  "tasks": [
			{
				"taskName": "task-Nucleo_blink_led",
				"appliesTo": "BUILD/Nucleo_blink_led.bin",
				"type": "launch",
				"command": "${env.COMSPEC}",
				"args": [
					"copy BUILD\\Nucleo_blink_led.bin L:"
				]
			}
  ]
}

```

**Comment by paulmaybee** [comment]
Can you generate a gdb log file for your failure case? In the Command Window enter
`debug.midebuglog /On:some-file-name`
Then run your repro case. Then enter
`debug.midebuglog /Off`

**Comment by paulmaybee** [comment]
Also, the task is run manually from the context menu in the solution explorer. Its output will appear in the output window's Build pane. For example:

**Comment by ConductedForce** [comment]
I may have figured it out. When I have a breakpoint set before running the debugger, it ignores it. But if I set a breakpoint while debugging, it stops the program at that spot. Is this normal behavior? It also doesn't let me stop the program on the led assignment variable (switching to 1 or 0, see repro output).

I did see how to run the task now, thanks on that.

Here's the repro case:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>type F:\Projects\N
ucleo_blink_led\main.cpp
#include "mbed.h"

DigitalOut myled(LED1);

int main() {
    while(1) {
        myled = 1; // LED is ON
        wait(0.2); // 200 ms
        myled = 0; // LED is OFF
        wait(1.0); // 1 sec
    }
}

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl /EHsc /nologo /
W4 /MTd F:\Projects\Nucleo_blink_led\main.cpp
main.cpp
F:\Projects\Nucleo_blink_led\main.cpp(1): fatal error C1083: Cannot open include
 file: 'mbed.h': No such file or directory
```

I also notice that when I place a breakpoint on the first `wait()` function, it doesn't stop, and gives no error in the console either. It does stop when I place a breakpoint on the last `wait()` routine, the one lasting 1 second.

**Comment by ConductedForce** [comment]
The program itself runs fine on the board, I just have unexpected behavior for debugging. In the tutorial article also, the last screenshot at the end of the page shows them being able to see into the memory. My [view](https://cdn.discordapp.com/attachments/264162717240131595/488860241534910475/unknown.png) does not go as deep.

**Comment by paulmaybee** [comment]
From what I can see of the text on the far right in your autos window screenshot it looks like the expression evaluation is complaining about a lack of debugging information. Have you tried this again after ensuring that your app is compiled with "-g"?

**Comment by ConductedForce** [comment]
Here's the lines that have the `-g` in them. I also figured out that changing the `-Os` to `-Og` in the makefile makes the compiler more supportive of debugging. It still doesn't let me see the led variables.

```
CC      = 'arm-none-eabi-gcc' '-g' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Og' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CPP     = 'arm-none-eabi-g++' '-g' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Og' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'

```

**Comment by paulmaybee** [comment]
I think your problem may be the "-g1". Try removing it. From the gcc docs:

> -glevel
> -ggdblevel
> -gstabslevel
> -gxcofflevel
> -gvmslevel
> Request debugging information and also use level to specify how much information. The default level is 2. 
> Level 0 produces no debug information at all. Thus, -g0 negates -g. 
> **Level 1 produces minimal information, enough for making backtraces in parts of the program that you don’t plan to debug. This includes descriptions of functions and external variables, and line number tables, but no information about local variables.** 
> Level 3 includes extra information, such as all the macro definitions present in the program. Some debuggers support macro expansion when you use -g3.

**Comment by ConductedForce** [comment]
That was it. I can see everything now. That'll be something to note for mbed-generated projects. Thanks for your help!

**Comment by itodirel** [comment]
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
