### ISSUE TITLE
Question: Targeting 'Remote Build Machine' in 'Pre-Build' event

### ISSUE THREAD

**Issue by SamuelHenderson** [Microsoft/VSLinux#334]
* A brief description

Is there a way to pass the 'Remote Build Machine' setting to a script that is run as a 'Pre-Build Event'?  

I work in a team with several other developers on a fairly large and complex solution that contains many interdependent libraries.  The problem is that some of our library projects require header files from our other library projects, but due to the build order they may not yet be copied to the remote build machine.  This causes our initial solution build to fail.  We can build the solution a second time and it will build fine because the missing headers will have already been copied over.

I'd like to write a script (either a small C# application or powershell script) that I can call as a 'Pre-Build Event' that will parse all #include statements in the project and copy missing headers from the other projects (so something like #include "../LibraryA/LibraryA.h").  

Each developer would have the script in the solution directory so all the projects in the solution could call it and pass the currently selected Remote Build Machine and $(ProjectDir) as parameters for the script.

So is there anyway to get the Remote Build machine's hostname/ip address as well as selected username and password to pass to a script?

**Comment by lukka** [comment]
@SamuelHenderson  yes, you could leverage that environment variable indeed.

**Comment by itodirel** [comment]
Excellent.

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
