### ISSUE TITLE
VS IntelliSense doesn't give correct __cplusplus

### ISSUE THREAD

**Issue by Berrysoft** [Microsoft/VSLinux#336]
VS 15.8.4 with WSL(Ubuntu 18.04, gcc 8.1, cmake 3.12):

The IntelliSense doesn't give correct value of __cplusplus. Even after I set the language version to C++17(I've tried MSBuild and CMake), the value is still `201406L`, and I get error when using `std::string_view` because it requires `__cplusplus >= 201703L`.

**Comment by Berrysoft** [comment]
Visual Studio 2019 Preview 1.1, MSBuild project for Linux, even after I set the C++ standard to C++17, the value of __cplusplus is still 199711L and _MSVC_LANG is 201402L. Therefore, I can't get correct Intelliense for <filesystem>.

**Comment by itodirel** [comment]
this works correctly for me, we fixed a few bugs here, it is possible this was one of them, I'm using the 4.3 Preview, currently, which is public available

**Comment by Berrysoft** [comment]
Thanks, it works!

**Comment by sbluemin** [comment]
I have same problem too.
-> VS2017 15.9.8 (Ubuntu 18.04, gcc 7.3.0) with Linux MakeFile Project.

Was VS2017 reporting the same issue?

@itodirel

**Comment by nindolabs** [comment]
Still have the same issue with VS2019 16.3.0 Preview 1

**Comment by jvallesf** [comment]
I had the same problem with VS2019 Version 16.4.5 in a project for Linux (not using WSL).
Works now after I changed to VS2019 Version 16.5.0 Preview 3.0.

**Comment by itodirel** [comment]
Thank you for confirming the fix @jvallesf! 

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
