### ISSUE TITLE
C++ compiler options applied to C compiler

### ISSUE THREAD

**Issue by TimKendall76** [Microsoft/VSLinux#34]
C++ compiler options -frtti and -fthreadsafe-statics are applied to C source files. Don't see a way to disable them under properties.

gcc -c -x c /root/projects/LinDemo/MainDemoSource/TcimDemo.cpp -I /root/projects/LinDemo/MainDemoInclude -g2 -gdwarf-2 -o "/root/projects/LinDemo/obj/x86/Debug/TcimDemo.o" -Wall -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): warning : command line option "-fthreadsafe-statics" is valid for C++/ObjC++ but not for C

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): warning : command line option "-frtti" is valid for C++/ObjC++ but not for C

VC_Linux 1.0.5

**Comment by xanather** [comment]
It is possible to disable them under properties. Configuration Properties -> C/C++, All Options, Delete the entry in "Statics are thread safe" and "Enable Run-Time Type Information".

**Comment by boskars** [comment]
Still, options incorrectly applied to C files in VC Linux 1.0.8  (15.4. prev 2)

1>  cc1: warning: command line option '-fthreadsafe-statics' is valid for C++/ObjC++ but not for C
1>  cc1: warning: command line option '-fthreadsafe-statics' is valid for C++/ObjC++ but not for C
1>  cc1: warning: command line option '-frtti' is valid for C++/ObjC++ but not for C
1>  cc1: warning: command line option '-frtti' is valid for C++/ObjC++ but not for C

**Comment by itodirel** [comment]
fixed and it should be available in 16 Preview 2

**Comment by ravichandhraRean** [comment]
When will be 16 Preview 2 available

**Comment by itodirel** [comment]
hi, that is available now https://visualstudio.microsoft.com/vs/preview/
