### ISSUE TITLE
Clean Solution/Project not removing source files if 'Remote Build Root Directory' is not under /home/<user>/

### ISSUE THREAD

**Issue by SamuelHenderson** [microsoft/VSLinux#342]
* A brief description
Using a Linux Console Application project called 'MyProject' as an example:

I have 'Remote Build Root Directory' set to /data/src and when I click "Solution->Clean Solution" (or "Project Only->Clean Only MyProject") the output window reports that the operation succeeded with 0 warnings and 0 errors ... Yet the Project directory and source still exist in /data/src

I've given ownership of '/data' to my remote user account so it should not be a permissions issue (the remote user account is able to add the src/ and project directory after all)

* Expected results
The project directory is removed in the same way it is if 'Remote Build Root Directory' was set to '/home/myuser/src'

* Actual results (with build output window contents if applicable)
```
1>Target _RemoteClean:
1>  Cleaning remote project directory
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.62
```
... Yet the source and compiled objects are still present /data/src/MyProject

* Versions:
Visual Studio 2017 v.15.8.5
Fedora 26
GCC 7.3.1

* Steps required to reproduce the error
Create a new Linux Console Application project (or even an empty Linux Project) and change the 'Remote Build Root Directory' to '/data/src'

* Required packages and commands to install
None.

**Comment by itodirel** [comment]
@elizabethmorrow can you take a look? Maybe Felix has some ideas

**Comment by itodirel** [comment]
this is a "security optimization" we make to make sure we don't delete things that might be dangerous to and destroy the system if the project is created in the wrong path, is using the home directory a workaround you could use?

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
