### ISSUE TITLE
openmp support?

### ISSUE THREAD

**Issue by leiyu1980** [Microsoft/VSLinux#349]
hi
How do I enable openmp support?

**Comment by leiyu1980** [comment]
thinke you！

**Comment by leiyu1980** [comment]
other：Add -fopenmp to your Linker  (Project>Configuration Properties>Linker>All Options>Additional Options: -fopenmp)

**Comment by itodirel** [comment]
We are not planning first class support for OpenMP at this time, that might change depending on demand. Please open a suggestion on the Developer Community if interested in first class support for Open MP.
