### ISSUE TITLE
Wrong source displayed when debugging

### ISSUE THREAD

**Issue by TimKendall76** [Microsoft/VSLinux#35]
I am developing a C lang DLL for Windows and a SO for Linux 
using the same code. In one solution I have 4 projects 1-Linux SO, 2-Linux OUT, 3-Win DLL, 4- Win EXE. The Linux projects and Windows projects "share" the same source files with some #ifdefs (WIN32 vs **Linux**). "h" files and "c" files are in common folders. I've set the configuration manager to build either Linux or Win32. The debugger is displaying wrong source code at times. If I step into a func that is in the Linux SO, the source code displayed is the Win32 source (meaning the ifdefs think that it is WIN32 and not **linux**). If I first set a break in the Linux version of the file, then it will display correctly. However, there seems to be no rhyme or reason for which project it chooses from at times. If I have the Linux project set as "Startup project", shouldn't VS know which project to pull source code from? With Linux, it appears that you cant set a reference to a SO from the main app as you can with WIN32, so that may be a factor. If you try to set a reference the path is bad. 
VC_Linux 1.0.5

**Comment by robotdad** [comment]
This seems related to #13 as we don't actually have proper support for project to project references yet. @itodirel may have some thoughts on whether this needs to wait for that work to be done or if this is a bug that could be addressed sooner.

**Comment by paulmaybee** [comment]
This bug was fixed in VC_Linux 1.0.7.
