### ISSUE TITLE
How to run 7zip on Win and Linux platforms with the same C++ code?

### ISSUE THREAD

**Issue by 10manjunath** [microsoft/VSLinux#350]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description: 
I would like to run a cross platform application like 7zip to compress files on windows and linux with the same C++ code. I selected project type as Cross Platform -> Linux. With the starter code that i have attached, it is not generating any output on my windows when i build and do Ctrl + F5. However, on linux, it is working fine.  

* Expected results: 
I would like to get a final release application after building my C++ code on both windows and linux. 

* Actual results (with build output window contents if applicable): 
Its not even opening a console window on windows to show the output.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware: 
Microsoft Visual C++ 2017 Redistributable (x64) and (x86) - 14.15.26706
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
Windows 10 Enterprise-2016 LTSB
64-bit Operating System, x64-based processor

* Steps required to reproduce the error

* Required packages and commands to install

* Starter Code

```cpp
#include <stdio.h>
#include <iostream>
#include <string>
using namespace std;

#if defined(_WIN32)
string PLATFORM_NAME = "Windows";
#else
string PLATFORM_NAME = "Linux";
#endif

string get_platform_name()
{
	return PLATFORM_NAME;
}

int main(int argc, char *argv[]) 
{
	cout << get_platform_name();

	if (get_platform_name() == "Windows")
	{
		string windowsPathtoFilesThatNeedCompression;
		system("7za");
                // TODO: implement

	}
	else
	{
		string linuxPathtoFilesThatNeedCompression;
		system("7za");
                // TODO: implement
	}

	return 0;
}
```

**Comment by itodirel** [comment]
You will have to use two different projects, one for Linux and one for Windows, you can structure this with Shared Projects such that the code is shared across both. Another option is to use CMake, with CMake you can have one single CMake project, then switch between Linux and Windows. With vcxproj/MSBUILD you have to have 2, one for each.

**Comment by itodirel** [comment]
@10manjunath sorry for the delay, yes, please give a day or so, I'll try to get that tomorrow

**Comment by itodirel** [comment]
Hi, you can use two projects, or CMake, or one project with shared projects. If you need additional details, follow our blog, or open a suggestion on the Developer Community. You can also open a doc issue on https://github.com/MicrosoftDocs/cpp-docs/issues
