### ISSUE TITLE
"CMake 3.8.x or above is not available", though it is

### ISSUE THREAD

**Issue by nunoplopes** [Microsoft/VSLinux#351]
I'm using VS 15.8.7 cmake open folder + Linux remote build.
However it is not working and I get the error: "Error occurred during copy: CMake 3.8.x or above is not available on the remote system".

Logging in on the remote server, /var/log/secure shows the login being successful:
```
Oct 14 10:46:01 sshd[129065]: Accepted publickey for nuno from xx.xx.xx.xx port xx ssh2: RSA foo
Oct 14 10:46:02 sshd[129065]: pam_unix(sshd:session): session opened for user nuno by (uid=0)
Oct 14 10:46:02 sshd[129086]: Received disconnect from xx.xx.xx.xx port xx:11: Connection terminated by the client.
Oct 14 10:46:02 sshd[129086]: Disconnected from xx.xx.xx.xx port xx
Oct 14 10:46:02 sshd[129065]: pam_unix(sshd:session): session closed for user nuno
```

The CMakeSettings.json file has the following line:
"cmakeExecutable": "/usr/bin/cmake",

and running that on the maching:
```
$ /usr/bin/cmake --version
cmake3 version 3.12.1
```
So this is more recent than the required 3.8.
I'm sure this CMakeSettings.json file is being picked up because I see the output changing depending on the value of "remoteCopySourcesOutputVerbosity".
I've opened the "Linux Console Window", but it shows no output.

At this point I'm unable to debug the issue any further. I don't know which command VS is executing (if any, since I don't see anything in ~/.bash_history).

Is cmake open folder + remote build supported?  The remote server has CentOS 7 (Azure VM).

**Comment by ToM-MaS** [comment]
Same here, I'm trying to connect to my raspberry pi 3 with VS Community 2017 V15.8.9. 
The VS SSH connection is succesfully established!

In the current raspbian repository (stretch), only cmake 3.7.2 is available.
So I've installed cmake from the future repository (buster):   

1. added "deb http://raspbian.raspberrypi.org/raspbian/ buster main" to "/etc/apt/sources.list"

2. added (set-up/reduce repository priority = apt pinning): 

> Package: *
Pin: release n=buster
Pin-Priority: 400

 to " /etc/apt/preferences.d/buster"

3. executed: 

> sudo apt-get install -t buster cmake
_____________________________________________________

The execution of:

> sudo apt-cache policy cmake 

shows me: 

> cmake:
  Installiert:           3.12.3-3
  Installationskandidat: 3.12.3-3
  Versionstabelle:
 *** 3.12.3-3 400
           400 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
           100 /var/lib/dpkg/status
     3.7.2-1 500
           500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages

So the installed version of CMake is 3.12.3 but VS and IntelliSense complains that the CMake-Cache must get updated:

> 1> 01:58:37: Copying files to remote machine...
1> Error occurred during copy: CMake 3.8.x or above is not available on the remote system. See https://aka.ms/linuxcmakeconfig for more info

What is wrong here?

**Comment by aWeinzierl** [comment]
Same problem with ubuntu WSL:

> 1> 22:32:05: Copying files to remote machine...
1> Error occurred during copy: CMake 3.8.x or above is not available on the remote system. See https://aka.ms/linuxcmakeconfig for more info


````
cmake -E capabilities:
{"generators":[{"extraGenerators":[],"name":"Watcom WMake","platformSupport":false,"toolsetSupport":false},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4"],"name":"Ninja","platformSupport":false,"toolsetSupport":false},{"extraGenerators":["CodeBlocks","CodeLite","Sublime Text 2","Kate","Eclipse CDT4","KDevelop3"],"name":"Unix Makefiles","platformSupport":false,"toolsetSupport":false}],"serverMode":true,"version":{"isDirty":false,"major":3,"minor":8,"patch":2,"string":"3.8.2","suffix":""}}
````

**Comment by lukka** [comment]
@aWeinzierl  you are correct, the cmake must be correctly specified in the cmake attribute of the json file, it does not search on the $PATH at all. 

Please open a suggestion at [DevComm](https://developercommunity.visualstudio.com/)!

**Comment by aWeinzierl** [comment]
I did: https://developercommunity.visualstudio.com/idea/383719/cmake-search-for-the-cmake-executeable-in-path.html

**Comment by nunoplopes** [comment]
I've tried both:
```"cmakeExecutable": "/usr/bin",```

and
```"cmakeExecutable": "/usr/bin/cmake",```

And I still get the same error message. @lukka Can you please reopen this bug report?  There *is* a bug.

**Comment by aWeinzierl** [comment]
if `whereis cmake` lists `/usr/bin/cmake` the second version should be correct.

**Comment by itodirel** [comment]
Please see the dupe. We believe this is now fixed (VS 2019), if this is still a problem for you, please open a issue on the Developer Community.
