### ISSUE TITLE
IntelliSense broken in Visual Studio 2017 15.9

### ISSUE THREAD

**Issue by JulienTheron** [Microsoft/VSLinux#355]
Hi,

* A brief description
When specifying additional include directories on Linux projects, IntelliSense can no longer find included files. This works in 15.8.
* Expected results
We can specify local include directories for IntelliSense to work.
* Actual results (with build output window contents if applicable)
IntelliSense is not helping and Visual Studio looks worse than Notepad++.
* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
VC++ 1.0.9.28218. Does not need an actual Linux system to repro the issue.
* Steps required to reproduce the error
1. Create a new Linux project.
2. Create an "include" folder and add a "MyClass.h" header file in it.
3. Create a "src" folder and add a "MyClass.cpp" source file in it, that includes MyClass.h.
4. Specify "include" in the project properties -> C/C++ -> General -> Additional Include Directories.
5. Open MyClass.cpp, IntelliSense cannot find MyClass.h.
* Required packages and commands to install
None

Thanks,
Julien.

**Comment by JulienTheron** [comment]
Tested again with Preview 5, same issue.

**Comment by rynpc** [comment]
I wish I would have read about this issue before updating to 15.9. This has chewed up an entire day at work trying to find a resolution.

**Comment by rynpc** [comment]
I do have my copy sources set to no. reason for this is because I am mounted to a docker container. If I unmount and set to yes it may resolve the specific error, but I am left with the problem of changes on the remote not reflecting back. In our dev environment this is a problem.

**Comment by oelison** [comment]
Hi all,
Nearly the same error when switching to Configtype as Makefile.
Linux.Makefile.Targets(x,y): error MSB4044:

**Comment by meisterm** [comment]
Havin' the same issue. Is there a workaround available?

**Comment by rynpc** [comment]
Want to share this issue with everyone, because it may end up containing the work around. [issues 310](https://github.com/Microsoft/VSLinux/issues/310)  I guess we will see after the doc is published.

**Comment by JulienTheron** [comment]
The current issue is not related to remote headers, but local ones. It may not end up with the same fix/workaround.

**Comment by itodirel** [comment]
Could you tell me if this is in a Linux Makefile project? We just made a fix that fixed this issue the fix will be in 16 Preview 2.

**Comment by Chronodt** [comment]
I had the same problem, but we weren't using a makefile, but an ordinary Linux project. Had to downgrade to 15.8.9 because it was unusable

**Comment by JulienTheron** [comment]
@itodirel This is in a VS C++ Linux project (.cxproj). I don't know if this issue occurs with Makefile projects.

**Comment by chrishoen** [comment]
I found this workaround:

Specify "include" in the project properties -> Configuration Properties -> VC++ Directories -> Include Directories.

The project builds and intellisense works.

**Comment by itodirel** [comment]
hi, this issue is fixed and will be available in 16 Preview 2, which is due to release soon

**Comment by JulienTheron** [comment]
Tested and working in 16 Preview 2. Thanks!

**Comment by lzhprigrammer** [comment]
我也有这个问题，IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(81,3): error MSB4044: 未给任务“ComputeHeaders”的必需参数“IncludePath”赋值。最开始 是  "LinuxIncludePath" 按照别人的方法修改 Linux.Makefile.Targets
    后   "  
  
     ProjectDir="$(ProjectDir)" 
     RemoteProjectDir="$(RemoteProjectDir)" 
     TargetLinuxPlatform="$(TargetLinuxPlatform)" 
     WiringPiIncludePath="$(wiringPiIncludePath)" 
     IncludePath="$(IncludePath)" 
     LinuxIncludePath="$(LinuxIncludePath)" 
     RemoteTargetId="$(ResolvedRemoteTargetId)" Sources="@(ClCompile)"> 
      
     

    "
  即可。

**Comment by BrainStone** [comment]
No Fix for VS 2017?

**Comment by tylerccg** [comment]
> No Fix for VS 2017?

^^^Same

**Comment by itodirel** [comment]
Please open a feedback ticket on the Developer Community, for VS 2017 support
