### ISSUE TITLE
slow rsync.exe

### ISSUE THREAD

**Issue by eroller** [microsoft/VSLinux#359]
Have you benchmarked rsync.exe shipped with VSLinux? In my hands it seems to be about 4 times slower than mingw64's scp and about 10 times slower than rsync over ssh on WSL.

My CMakeSettings.json contains:
"remoteCopySourcesConcurrentCopies": "10"
but this doesn't seem to have any effect. Does this setting apply to rsync? I only ever see one rsync process running under Task Manager.

My repo is about 4 GB in size with 18000 files. rsync on WSL takes about 2 minutes. If there is no fix to slow rsync on windows it could be a cool feature to add support for using rsync on WSL assuming windows drives are mounted at /mnt

Note: CLion's tar-based remote copy mechanism seems to be on par with mingw64's scp

**Comment by lukka** [comment]
@eroller 
 - "remoteCopySourcesConcurrentCopies" is only for sftp.
 - for rsync you could play with the rsyncCommandArg to make the transfer faster in your scenario. What are you currently passing in?
 - could you explain in detail the scenarios where you run the benchmarks?

**Comment by eroller** [comment]
I tried first with the following rsync args (note: VSLinux automatically adds `-v -r --exclude=.vs --exclude=.git`) :
`-t --delete --delete-excluded -v -r --exclude=.vs --exclude=.git`

I also tried adding -W which seemed to slow it down from 15 minutes to about 20 minutes. 

The scenarios where I run my benchmarks:
*3 GB repo with ~18000 files
* Transfer is from a Windows 10 x64 (build 1809) machine to a Centos7 box on a local Gigabit network
* Scenario 1: Using VSLinux rsync.exe through Visual Studio IDE (15 minutes)
```
      sent 3057075779 bytes  received 351451 bytes  3425688.77 bytes/sec
      total size is 3055556187  speedup is 1.00
```
* Scenario 2: Using git bash (mingw64) scp (5 minutes)
* Scenario 3: CLion 2018.3 (5 minutes)
* Scenario 3: Ubuntu WSL rsync (<2 minutes)
```
       sent 3,057,432,291 bytes  received 365,505 bytes  40,500,633.06 bytes/sec
       total size is 3,055,546,711  speedup is 1.00
``` 

One notable difference is that rsync.exe with VSLinux uses the rsync protocol while rsync on WSL was just over regular ssh.

**Comment by itodirel** [comment]
that is quite significant, thanks for the numbers, @lukka @elizabethmorrow can you look into this?

**Comment by dedmen** [comment]
Just my observation as additional info:

Just looking at my project's rsync I'm getting a steady transfer at EXACTLY 2MB/s.
Wheras a SFTP transfer of a sample file transfers with 4.6MB/s (4.8MB/s is my theoretical max upload speed)

**Comment by itodirel** [comment]
what is your theoretical upload speed limited by? is it the internet connection or something else? could you try it with a VM on the local network?

**Comment by dedmen** [comment]
Antergos on VMWare VM.
Syncing headers 2,3MB/s download
CMake sync 2,05MB/s upload constant. 

![NLClientApp_2019-03-23_14-10-48](https://user-images.githubusercontent.com/3768165/54866552-7a4eae80-4d75-11e9-9178-c68e0b5aedc0.png)

**Comment by elizabethmorrow** [comment]
This issue has been fixed with the upgraded build of rsync.exe shipping with 16.1.

**Comment by itodirel** [comment]
If this is a problem, please open a ticket for us on the Developer Community
