### ISSUE TITLE
Line endings being mixed up

### ISSUE THREAD

**Issue by eroller** [Microsoft/VSLinux#360]
This isn't necessarily a feature request for VSLinux, but since the goal is to support development targeting Linux platforms it would make sense to tackle this feature request in Visual Studio:

https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4160768-save-text-files-with-the-newline-convention-presen?page=2&per_page=20

Any chance someone from the VSLinux team could walk over to Mark Wilson-Thomas's desk over there in Redmond and put in a good word? :smiley:

**Comment by itodirel** [comment]
thank you for the feedback, I pinged Mark

**Comment by lukka** [comment]
Closing as the relative suggestion has been created already.

**Comment by itodirel** [comment]
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here.
