### ISSUE TITLE
Include C++ Linux development in VS build tools

### ISSUE THREAD

**Issue by Sam13** [Microsoft/VSLinux#365]
It would be nice to have this VS extension also available in Visual Studio Build Tools...

**Comment by lukka** [comment]
@Sam13 thanks for the suggestion. Please go ahead and submit a suggestion request at [Developer Community forum](https://developercommunity.visualstudio.com/), where you could "Suggest a Feature".

**Comment by Sam13** [comment]
Feature request posted

**Comment by itodirel** [comment]
Thank you! https://developercommunity.visualstudio.com/idea/444311/include-c-linux-development-in-visual-studio-build.html
