### ISSUE TITLE
Improve Intelisense support

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#37]
We currently have Intelisense support for the STL by default. To add support for your own environment you need to setup the VC++ Directories to point to your include files, we cover on way to do that [here](https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#includes).

We could make this more discoverable by doing something like what is done in VS Code for C++, when there are squiggles prompt an action bulb that offers help in setting this up.

Another option would be to add the capability to sync all of the include files locally from common locations for each Linux connection we have.

Of course things may not be in a common location so perhaps a bit of both?

**Comment by stanthomas** [comment]
I am curious about how the include path is parsed for IntelliSense. It seems I have to add the folders in twice, once for the compiler and again for IntelliSense, even when they are on the same relative path on both local and remote systems.

**Comment by bazzilic** [comment]
Hi, any movement on this?

**Comment by robotdad** [comment]
Actually yes, we have spec for syncing folders and hope to get it is rising up our backlog. I can't quite commit to a release yet though. I'm going to close this one and track off of #215 which is a bit more specific.

**Comment by itodirel** [comment]
As an update, we implemented this feature

**Comment by bazzilic** [comment]
When is it available?

**Comment by itodirel** [comment]
it's available right now, publicly, in 15.7 Preview 2
