### ISSUE TITLE
$(OutDir)/$(RemoteOutDir) problem

### ISSUE THREAD

**Issue by MichaelKv** [microsoft/VSLinux#372]
Hello. I believe there is still a problem with solution variables in the latest VS 2019.
I have
set LINUX_MKS=/home/mike/sigman
set LINUX_MKSBIN=/home/mike/sigman/Build
In my solution I have:
Output Directory: $(LINUX_MKSBIN)/bin/$(Platform)/$(Configuration)/
Build root and Build project root are set to $(LINUX_MKS).
In a new property sheet I add 
Library Directories (VC++ Directories): $(OutDir)
But it points to my Windows path and gcc linker does not find the library.
Ok. I write down $(OutDir) again manually above the inherited values. This time VS shows the correct path but gcc linker does not find the library again because it looks for it in /home/mike/sigman/$(ProjectName)/bin/x64/Debug/ directory. This directory appears to be the $(RemoteOutDir). So, I have
$(OutDir) -- either Windows or correct path in the VS but turns into $(RemoteOutDir) on the Linux machine.
$(OutDirWasSpecified) -- false. Why???? But Ok.
$(RemoteOutDir) -- /home/mike/sigman/$(ProjectName)/bin/x64/Debug/ . Why does it have ProjectName part? It shall not be there.

Could you, please, have a look at the issue?

**Comment by MichaelKv** [comment]
I have managed to workaround the problem by redefining $(OutDir) with the macro. Just curious why redefining RemoteRootDir does not work. BTW VS Add Macro window misbehaves. At least on two monitors (different sized) over RDP -- it opens behind the screen.

**Comment by MichaelKv** [comment]
And I get the error message from the VS -- 
MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.targets(192,5): error : Exception occured while copying sources to remote machine - Could not create directories, mkdir exit code: 1

it cannot copy cpp sources in Dir1 and Dir2 for the following structure:
Dir
-Dir1
-Dir2

I have three projects here: a kind of a front-end in Dir and two back-ends Dir1 and Dir2. VS manages to copy complex header file structures correctly but it fails on cpp files in Dir1 and Dir2 with the error as above.

**Comment by MichaelKv** [comment]
Heh, it looks like the directory you choose to copy source files of a project to heavily depends upon where the files of the project lie. So depending which directories the project references through the files it consists of the magic "Remote Build Project Directory" may be $(RemoteRootDir)/, $(RemoteRootDir)/$(ProjectName)/ or $(RemoteRootDir)/SomethingSpecial. And this weirdness is vitally essential for the VS to be able to copy files right and to call g++ right. The last necessity makes it impossible to use a thirdparty file sync tool -- I would be able to copy files right but compilation fails.

**Comment by NiklasNiebr** [comment]
I also found out that you should not use the ~ for dynamically home path. If the build and debug machine are different and have different users, visual studio looks under the ~ path of the debug machine on the build machine to deploy the file.  Another thing is the new linker property page. There are two Output file entries. 
The upper one is a path relative to the root folders (root project, root build and root deploy folders) where the output file shall be put to.
 The second Output File entry goes for the absolute path where the output file lies on the build machine during deploy time.

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
