### ISSUE TITLE
How to debug shared lib for IoT device via gdbserver (Openfolder project launch.vs.json)

### ISSUE THREAD

**Issue by Mingyiz** [microsoft/VSLinux#376]
I have successfully debug 'hello world' program in my arm board according the guide [debugging-an-embedded-gdbserver](https://devblogs.microsoft.com/cppblog/debugging-an-embedded-arm-device-in-visual-studio/). 

Actually my project include some shared lib and used by the exacuteble, I want to know how to debug the shared lib.

**Comment by Mingyiz** [comment]
I past the launch.vs.json as below. the test_package are main app, which call the liblibepm.so, I can step into the code in test_package, but can not set vailid break point for liblibepm.so code.

{
  "version": "0.2.1",
  "defaults": {},
  "configurations": [
    {
      "type": "cppdbg",
      "name": "arm-liblibepm.so",
      "processId": 23802,
      "project": ".epm\\Linux.Hi3536.Debug-dynamic\\build\\lib\\liblibepm.so",
      "cwd": "${workspaceRoot}",

      "program": "${workspaceRoot}\\.epm\\Linux.Hi3536.Debug-dynamic\\test_build\\bin\\test_package",
      "sourceFileMap": {
        "/home/conan/project": "${workspaceRoot}"
      },
      "MIMode": "gdb",
      "externalConsole": true,
      "inheritEnvironments": [
        "gcc_arm"
      ],
      "miDebuggerPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Linux\\gcc_arm\\bin\\arm-none-eabi-gdb.exe",
      "setupCommands": [
      ],


      "visualizerFile": "${debugInfo.linuxNatvisPath}",
      "showDisplayString": true,
      "miDebuggerServerAddress": "172.16.192.242:12345",
    }
  ]
}

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
