### ISSUE TITLE
How to load a existing linux project on the WSL

### ISSUE THREAD

**Issue by QinjieLyu** [microsoft/VSLinux#378]
I'm new to VSLinux.

I have a project download from Github in my WSL. The project will be generated using CMakelist. 
Is that possible to load the project from Visual studio? Or should I create a new project in VisualStudio and include all the files?

Thank you.

**Comment by itodirel** [comment]
You can simply change the toolset, in the Property Pages, no other changes are needed @QinjieLyu. Please use the Developer Community for questions or reporting new issues
