### ISSUE TITLE
Special chars like accent in passwords are not managed

### ISSUE THREAD

**Issue by OhSoGood** [microsoft/VSLinux#379]
VS 2019 16.3.8 / Win 10 64 1909 / Remote linux is Debian 10

SSH connection to a remote linux server, using either login/password or login/SSH key/SSH key password:
- fails if the password contains any special characters like accent  
  (linux auth.log says: fatal: userauth_passwd: unexpected bytes remain after decoding [preauth] )
- succeeds for the same remote linux server if the password does not have accent.

Man, it has been 15-20 years since linux handles well special chars like accents in password. Please, MS guys, wake up!

**Comment by itodirel** [comment]
We will investigate this bug, and will resolve it if it reproduces for us in the next update of VS 2019.

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here.
