### ISSUE TITLE
Ability to add Assembly code to project

### ISSUE THREAD

**Issue by dedmen** [microsoft/VSLinux#380]
You cannot add a assembly.s file to be built into your project.
I tried to add the file, setting it to C/C++ compiler hoping I can just pipe it through gcc.

What VSLinux runs on remote:

`/usr/local/libexec/gcc/x86_64-pc-linux-gnu/10.0.0/cc1 -quiet -v -imultiarch x86_64-linux-gnu /home/xx/projects/xx/assembly.s -quiet -dumpbase assembly.s -mtune=generic -march=x86-64 -auxbase-strip /home/xx/projects/xx/obj/x86/Debug/assembly.o -g2 -gdwarf-2 -O0 -Wall -version -fno-strict-aliasing -fno-omit-frame-pointer -fpic -fexceptions -o /tmp/cc0J4gqC.s
`

However tries to compile it as a c++ file. I cannot seem to find a way to make it compile assembly. 

CMake projects work though, but it would be nice to have in normal VS projects too.

I hope my utterances make sense. Also I assume Assembly files are a very rarely used thing and thus don't have any priority, but I wanted to make sure that its atleast on the radar.

**Comment by itodirel** [comment]
I created a ticket, here: https://developercommunity.visualstudio.com/idea/956470/support-assembly-in-msbuild-linux-projects.html

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
