### ISSUE TITLE
How to set defaultRemoteMachineName?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/VSLinux#381]
Variable defaultRemoteMachineName can be used in CMakeSettings.json to specify the remote machine name.  How can I set this variable?

#252, raised 2 years ago, suggests that the Connection Manager should support setting the default connection, as well as editing connections.  That issue was closed last year with the statement "we are tackling this separately, copied to backlog". But the Connection Manager still does not support these features.  This is a real problem when seeking to support multiple remote machines.

**Comment by itodirel** [comment]
@DavidA2014 as an update to this, we are tracking this internally, and this will be available in the next update of VS, the feature is in development.
