### ISSUE TITLE
ConnectionManager.exe Failed to add connection: No common host key algorithm found

### ISSUE THREAD

**Issue by gc435** [microsoft/VSLinux#384]
_I know new issues should not be reported here, but I tried on the Developer Community site and repeatedly got an "unexpected error"._

In Visual Studio 16.8.3, I cannot create a new connection to a Fedora 33 system.  I get this error:

```
ConnectionManager.exe add user@192.168.1.5 --password mypassword
Verifying connection with remote system.
Failed to add connection: No common host key algorithm found
```

The same procedure works just fine when connecting to Arch Linux.

When connecting from Visual Studio, and not the **ConnectionManager.exe** command line tool, I just get red boxes around the username and password.  Nothing useful appears in the **RemoteConnectionsLogging** logfile.

Running `sftp.exe -v user@192.168.1.5` shows this host key:

```
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
```

What host key algorithm is expected by **ConnectionManager.exe**?

**Comment by paulmaybee** [comment]
Most likely you only allow ssh-ecdsa and ssh-ed25519 in your server configuration. We don't support these in 16.8. Try either enabling ssh-rsa  on your Fedora system, or updating to 16.9 preview 2.

**Comment by gc435** [comment]
Thanks, @paulmaybee.  16.9 preview 2 worked just fine.
