### ISSUE TITLE
STL containers cannot be inspected in debugger

### ISSUE THREAD

**Issue by stanthomas** [Microsoft/VSLinux#4]
Debugger only shows raw gdb view of STL containers: std::list, std::vector etc., which is uninformative.
On most Linux systems, gdb print command is extended with a number of additional commands: plist, pvector etc., via a gdbinit script. This is sometimes referred to as 'pretty printing'. See [http://www.yolinux.com/TUTORIALS/GDB-Commands.html#STLDEREF](http://www.yolinux.com/TUTORIALS/GDB-Commands.html#STLDEREF)  for more information.

On Windows, the VS debugger can inspect STL containers and the same functionality should be made available to VC_Linux.

Known issue added here to track progress.

Visual Studio 2015 Pro Update 3
Windows 10 insider latest
VC_Linux 1.0.4
Mageia Linux 5 (x64)
gcc 4.9.2 / gdb 7.8.1 / gdbserver 7.8.1

**Comment by paulmaybee** [comment]
In the command window enter "Debug.MIDebugExec -enable-pretty-printing". This should turn on the gdb pretty printers.

**Comment by stanthomas** [comment]
`Debug.MIDebugExec -enable-pretty-printing` had no effect. But I found something that did. Kinda. The big question now is how to get that integrated into the VS IDE.

Using this simple example:
```
#include <iostream>
#include <list>

int main()
{
	std::list <int> lst {1, 4, 9};
	for (auto v : lst)					// set breakpoint on this line
		std::cout << v << std::endl;
	return 0;
}
```

Inspecting std::list <int> lst in shows only the raw gdb information.
Rather than paste a bunch of screenshots, this is the same information in text form that you can get in the VS command window:

```
>Debug.MIDebugExec print lst
$1 = {<std::_List_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<std::_List_node<int> >> = {<__gnu_cxx::new_allocator<std::_List_node<int> >> = {<No data fields>}, <No data fields>}, _M_node = {_M_next = 0x603010, _M_prev = 0x603050}}}, <No data fields>}
```

Try suggested remedy
```
>Debug.MIDebugExec -enable-pretty-printing
result-class: done
```

But no, just the same
```
>Debug.MIDebugExec print lst
$2 = {<std::_List_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<std::_List_node<int> >> = {<__gnu_cxx::new_allocator<std::_List_node<int> >> = {<No data fields>}, <No data fields>}, _M_node = {_M_next = 0x603010, _M_prev = 0x603050}}}, <No data fields>}
```

Here's something I tried
```
>Debug.MIDebugExec set print pretty
=cmd-param-changed,param="print pretty",value="on"
```

Prettier but no more useful
```
>Debug.MIDebugExec print lst
$3 = {
  <std::_List_base<int, std::allocator<int> >> = {
    _M_impl = {
      <std::allocator<std::_List_node<int> >> = {
        <__gnu_cxx::new_allocator<std::_List_node<int> >> = {<No data fields>}, <No data fields>}, 
      members of std::_List_base<int, std::allocator<int> >::_List_impl: 
      _M_node = {
        _M_next = 0x603010, 
        _M_prev = 0x603050
      }
    }
  }, <No data fields>}
```


The usual gdb command would be plist, but it's not defined
```
>Debug.MIDebugExec plist lst
Undefined command: "plist".  Try "help".
```

Load [gdbinit script](https://github.com/Microsoft/VSLinux/files/401417/gdbinit.txt) to define plist etc. (have to do this every time debugger is run). N.B. attached gdbinit has a .txt extension added to keep GitHub happy.
```
>Debug.MIDebugExec source -v gdbinit
+define pvector
+document pvector
+define plist
+document plist
+define plist_member
+document plist_member
+define pmap
+document pmap
+define pmap_member
+document pmap_member
+define pset
+document pset
+define pdequeue
+document pdequeue
+define pstack
+document pstack
+define pqueue
+document pqueue
+define ppqueue
+document ppqueue
+define pbitset
+document pbitset
+define pstring
+document pstring
+define pwstring
+document pwstring
+set print pretty on
=cmd-param-changed,param="print pretty",value="on"
+set print object on
=cmd-param-changed,param="print object",value="on"
+set print static-members on
+set print vtbl on
=cmd-param-changed,param="print vtbl",value="on"
+set print demangle on
+set demangle-style gnu-v3
=cmd-param-changed,param="demangle-style",value="gnu-v3"
+set print sevenbit-strings off
=cmd-param-changed,param="print sevenbit-strings",value="off"
```

Now plist is available and we can see into the list
```
>Debug.MIDebugExec plist lst
List size = 3 
List type = std::list<int, std::allocator<int> >
Use plist <variable_name> <element_type> to see the elements in the list.
```
```
>Debug.MIDebugExec plist lst int
elem[0]: $5 = 1
elem[1]: $6 = 4
elem[2]: $7 = 9
List size = 3 
```

**Comment by robotdad** [comment]
So, taking another look at this. I've learned Debug.MIDebugExec -enable-pretty-printing only works with our gdb mode, not the default gdbserver. That also means it can't be used in conjunction with the Linux command window. So getting some natvis together seems like the next step. There is [one here in the MIEngine](https://raw.githubusercontent.com/Microsoft/MIEngine/master/src/AndroidDebugLauncher/Microsoft.Android.natvis) but it doesn't have cxx11 stl types in it. When I get something that can demonstrate a couple of those types together I'll post something back here.

**Comment by stanthomas** [comment]
Yes, working when debugging in gdb mode. I've tried list, vector, unordered_map, pair, string. All good. Thanks for the tip.

Is there a way I can get the `Debug.MIDebugExec -enable-pretty-printing` instruction executed automatically, rather than having to open the command window? And, gdb-server mode would be great too.

Although not strictly an STL container, I'll mention that STL pointer types are not dereferenced, i.e. std::shared_ptr, std::unique_ptr. Debugger shows only the memory address of the contained object. Would like to have these handled too.

Is everything we see in VCLinux debug handled by MIEngine? Given that MIEngine is open-sourced, can I swap in my own build of MIEngine with custom gdb scripts?

**Comment by robotdad** [comment]
Apologies for the long delays on this one. 

For python pretty printing support in gdb mode add -enable-pretty-printing  to the additional debugger commands option.
![image](https://cloud.githubusercontent.com/assets/1429895/23522890/8b0ead38-ff39-11e6-9d93-f4c220b72dbb.png)

The other is using natvis which will work with gdbserver mode (thus you can still use the linux console window). We will be adding this capability in a future update, but for now I am attaching a file you can add in your project. You need to put the file in your project and reference it, e.g. add existing item.

[stl.zip](https://github.com/Microsoft/VSLinux/files/814854/stl.zip)

**Comment by itodirel** [comment]
this is fixed and will be available in the 1.0.7 release

**Comment by itodirel** [comment]
1.0.7 is now available

**Comment by pootle73** [comment]
I tried the -enable-pretty-printing above with version 1.06 and it was working for me. I have now installed 1.07 and when I try to launch the debugger I see this:

![image](https://cloud.githubusercontent.com/assets/24373831/26405714/75b024c8-4096-11e7-900e-e0c0ef532031.png)

This is how I have the debugging properties set, which worked fine before version 1.07:

![image](https://cloud.githubusercontent.com/assets/24373831/26405776/a0cdb850-4096-11e7-8cca-e52af7ff0363.png)

**Comment by robotdad** [comment]
@pootle73 opened #152 for your report above to not lose it in closing out this feature.
