### ISSUE TITLE
Copied file hierarchy not as expected 

### ISSUE THREAD

**Issue by olivier-haddad** [Microsoft/VSLinux#40]
See UPDATE at the end of the post.

Hi,
I have a project hierarchy similar to the following:
SolutionFolder
---Project.Shared (contains files shared by multiple projects/platforms)
      fileShared.cpp
---Project.Pi (used to compile on Raspberry Pi)
      filePi.cpp
---Project.Win (used to compile on windows)
      fileWin.cpp

On the target (RPi), I expect the following:
<RemoteRoot>/Project.PI/filePi.cpp
<RemoteRoot>/Project.PI/fileShared.cpp

but I get instead:
<RemoteRoot>/Project.PI/Project.PI/filePi.cpp
<RemoteRoot>/Project.PI/fileShared.cpp
ERRATUM: should be: <RemoteRoot>/Project.PI/Project.Shared/fileShared.cpp

UPDATE [12 SEPT 2016]
The extension seems to copy the files differently according to if some source files are present in Project.PI.

If there are no source files in Project.PI but only settings then I get:
<RemoteRoot>/Project.PI/fileShared.cpp

After adding filePi.cpp to Project.Pi I got:
<RemoteRoot>/Project.PI/Project.PI/filePi.cpp
<RemoteRoot>/Project.PI/**Project.Shared/**fileShared.cpp

The path of the files from Project.Shared is now changed on the target. This may be the intended behavior.

Environment: VS2015, Raspbian (RPi3, ARM), extention version: 1.0.5

**Comment by stanthomas** [comment]
I do something similar but it does what I expect and I haven't seen any change between 1.0.4 and 1.0.5. What project settings do you have under Remote Settings for Remote Root Directory and Remote Project Directory ?

I use another way to share code between projects that doesn't require a third 'common code' project. Add all the source files to the first project, the Windows one say. Then, in Solution Explorer, copy the sources from the first project to the second, Linux one. VS will link the sources in the second project to the first so you have a common source. You can still add project specific sources, just don't copy them. You end up with two projects that appear in Solution Explorer to contain all the source files. With this arrangement I don't have any issues with sub-folders being arbitrarily create and files ending up in an unexpected location on the remote.

**Comment by olivier-haddad** [comment]
I think you haven't noticed any difference because if I understood you well enough, you don't actually use the Shared Project feature. This feature is meant to let VS consider the files "as if they were there" with no fear of locking, failed sync between the folders and else. The thing is that it doesn't work anymore and it doesn't deal with the files of the compiled project and those of the shared one anymore.

If you copy the files with a pre-build event script, you open the door to all kinds of sync errors.
If you only link the files, then you'll need to manage the links for each target you compile for, and I already have 3 and many files to share....

**Comment by stanthomas** [comment]
You're quite right, I don't use a Shared Project (one with capitals).

I too have multiple targets and many files. But these break down into just two projects : one for Windows targets and one for Linux targets, with multiple configurations of each. I don't encounter any issue with synchronisation, it's the same file, or managing links to common code. Inter-project sharing via copying in Solution Explorer just works.

VCLinux has been a huge step forward 'cos before I had VS on WIndows and Eclipse on Linux; now that was a real bugbear to keep in sync.

**Comment by olivier-haddad** [comment]
Great work guys! It now works flawlessly in 1.0.6.
