### ISSUE TITLE
Compilation of project dependent on shared project now fails on 1.0.5 (worked on 1.0.4)

### ISSUE THREAD

**Issue by olivier-haddad** [Microsoft/VSLinux#41]
Hi,
The following was working flawlessly on 1.0.4 but was broken on 1.0.5.

I have a project hierarchy similar to the following:
SolutionFolder
---Project.Shared (contains files shared by multiple projects/platforms)
fileShared.cpp
---Project.Pi (used to compile on Raspberry Pi)
filePi.cpp
---Project.Win (used to compile on windows)
fileWin.cpp

The compilation fails with the following for each file:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): error : /home/pi/projects/Project.Pi/../Project.Shared/fileShared.cpp: No such file or directory

Of course this fails as the file was copied to /home/pi/projects/Project.Pi as it should.

Environment: VS2015, Raspbian (RPi3, ARM)

**Comment by robotdad** [comment]
Sorry about that, I've uploaded the previous [1.0.4 release here](https://aka.ms/ar0dr6). Hopefully this is something easy we can correct in the next release.

**Comment by olivier-haddad** [comment]
This may be connected to the behaviour noticed in issue  #40. Maybe the code at different locations does not use the same folders resolution logic.

**Comment by itodirel** [comment]
we found out what the problem was, but not sure if it will make it in 1.0.6, just because we want to ship 1.0.6 soon and do not want to destabilize the release

**Comment by olivier-haddad** [comment]
Too bad it won't make it as the build times are very long.
I guess we'll stay on 1.0.4 then.
Thanks for letting me know.

On Nov 16, 2016 05:50, Ion Todirel <notifications@github.com> wrote:

we found out what the problem was, but not sure if it will make it in 1.0.6, just because we want to ship 1.0.6 soon and do not want to destabilize the release

**Comment by itodirel** [comment]
We fixed this issue and it will be available in the 1.0.6 release.

**Comment by olivier-haddad** [comment]
This is real good. Can't wait.
Thanks guys.

On Nov 19, 2016 04:48, Ion Todirel <notifications@github.com> wrote:

We fixed this issue and it will be available in the 1.0.6 release.

**Comment by robotdad** [comment]
The 1.0.6 version of the extension is now available on the extension gallery
