### ISSUE TITLE
Automatically sync include files from Linux

### ISSUE THREAD

**Issue by avinabmalla** [Microsoft/VSLinux#43]
Currently, the include files need to be manually copied from the Linux system. It would be nuce to have a feature which automatically copies the headers and adds them to VC++ directories, while syncing any changes made on the remote system.

**Comment by robotdad** [comment]
I know this is an older one but there is more recent discussion on #215 so closing this one in favor of that one.

**Comment by itodirel** [comment]
As an update, we implemented this feature
