### ISSUE TITLE
Make CTRL-F5 work

### ISSUE THREAD

**Issue by lgolding** [Microsoft/VSLinux#45]
Today if you accidentally press CTRL-F5 instead of F5, you get the cryptic message: "Unable to start program 'app_process'. The filename, directory name, or volume label syntax is incorrect."

**Comment by itodirel** [comment]
this is now fixed, and will be available in the next release

**Comment by WenbinHou** [comment]
May I ask when is the next release? VS2017 suffers from the same issue.

**Comment by itodirel** [comment]
this now works and is available in 1.0.7, you can download 1.0.7 from the extension gallery

**Comment by robotdad** [comment]
1.0.7 is also in VS 2017 15.3 which is the current preview release.
