### ISSUE TITLE
Weird file layout on remote machine when using sources from multiple non-child directories

### ISSUE THREAD

**Issue by rubu** [Microsoft/VSLinux#46]
**Description**
In case when a project is including source files from multiple non-child directories something weird happens with the layout on the remote machine. I am currently porting an existing VisualGDB based project to this extension and it kept the sources in an external folder, VisualGDB seemed to handle that but because of this bug I can't port the project to VSLinux.

Assume the following file layout:

src/
&nbsp;&nbsp;&nbsp;&nbsp;bad_folder/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bad_include.h
&nbsp;&nbsp;&nbsp;&nbsp;bad_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main.cpp
&nbsp;&nbsp;&nbsp;&nbsp;good_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main.cpp
projects/
&nbsp;&nbsp;&nbsp;&nbsp;windows/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bad_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;project file
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;good_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;project file
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;solution file

bad_layout_project project uses the main.cpp from the src/bad_layout_project/ folder and the bad_include.h from the src/bad_folder/ folder, while good_layout_project references the main.cpp from src/good_layout_project/ folder.

What happens (at least what I expect) is that when I build the solution the layout on the remote machine for both projects is similar, however that is not the case.

**Expected results**

I would expect the remote layout to look like this:

remote root/
&nbsp;&nbsp;&nbsp;&nbsp;bad_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bad_folder/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bad_include.h
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main.cpp
&nbsp;&nbsp;&nbsp;&nbsp;good_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main.cpp

**Actual results**

This is the remote layout I get:

remote root/
&nbsp;&nbsp;&nbsp;&nbsp;bad_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bad_folder/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bad_include.h
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bad_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main.cpp <--- shouldn't it be a lever higher?
&nbsp;&nbsp;&nbsp;&nbsp;good_layout_project/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main.cpp <-- as expected

screenshots from winscp:
![image](https://cloud.githubusercontent.com/assets/1997432/18609772/0c713084-7d13-11e6-9cdb-236ffb5a1e34.png)

![image](https://cloud.githubusercontent.com/assets/1997432/18609774/1cfff0a2-7d13-11e6-8f9e-f27245c4fcbb.png)

**Steps required to reproduce the error**

I've attached a zipped version of the project so it should be very easy to reproduce the issue.
- Required packages and commands to install
  [bad_layout_solution.zip](https://github.com/Microsoft/VSLinux/files/478269/bad_layout_solution.zip)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by cthulhua** [comment]
This is expected behavior - when you build, do you see any intellisense errors? I saw an error about the bad_folder/bad_include.h file not existing. When I changed that to ../bad_folder/bad_include.h, the intellisense error, as well as the remote build failure went away.

as for the differing remote file structures, that's expected - we have to reproduce the minimal directory tree that contains all the files required for the project to build. In this case, we have to copy everything under src that is included in the project. In the good_layout_project case, it's satisfactory to copy over only the contents of src/good_layout_project.
