### ISSUE TITLE
Support Building / Running with Docker for Windows

### ISSUE THREAD

**Issue by simonferquel** [microsoft/VSLinux#48]
Docker now provides Windows users with Docker for Windows that basically hides all the complexity of running a Linux host on Hyper-V, sharing files between Windows and the linux containers etc.

One very good usage of Docker is to use containers to build code using a special purpose container image (or even build code directly from a Dockerfile to benefit from the docker image cache), and run/debug in a container supporting GDB.

It would be really nice to get this experience from Visual Studio.
If you need some support or more info from the Docker for Windows team, fill free to contact me.

**Comment by robotdad** [comment]
Docker has been on my backlog for too long. I just started setting up a container to try this out and I don't see an immediate reason why we can't get this working with the current extension. We just need to setup a container that has our prereqs installed and opens up SSH. That could give us a quick win here.

We could do more I'm sure.

**Comment by DuncanGravill** [comment]
This is already possible! I am currently using a docker container along with docker for Windows and it is working nicely!


[https://hub.docker.com/r/ducatel/visual-studio-linux-build-box/](Visual Studio Linux Build Box image on Docker Hub)

See my SO post...

[http://stackoverflow.com/questions/38960335/visual-c-for-linux-development-docker](http://stackoverflow.com/questions/38960335/visual-c-for-linux-development-docker)

**Comment by robotdad** [comment]
Thanks @duncangravill! I will try to make time to try you image tomorrow.

**Comment by simonferquel** [comment]
Oh, I almost forgot : having this kind of work flows available from VS Code on both Windows and Mac would be very nice as well :)





On Wed, Sep 21, 2016 at 4:27 AM +0200, "Marc Goodner" <notifications@github.com> wrote:












Thanks @duncangravill! I will try to make time to try you image tomorrow.

**Comment by robotdad** [comment]
The machine I was verifying this on had some issues I just straightened out so I was finally able to verify the image above. That is very slick. @simonferquel we should look at getting this promoted into an official repository.

**Comment by simonferquel** [comment]
The image seems a bit large. I'll try to build a lighter one based on alpine instead of Ubuntu. 

Anyway, it is great for a dev/debug/refactoring work flow,  but not for a release one (where we might not want to deploy gdb, opensshserver etc.)





On Fri, Sep 23, 2016 at 8:14 PM +0200, "Marc Goodner" <notifications@github.com> wrote:












The machine I was verifying this on had some issues I just straightened out so I was finally able to verify the image above. That is very slick. @simonferquel we should look at getting this promoted into an official repository.

**Comment by duncangravill** [comment]
@robotdad @simonferquel All credit to D. Ducatel. I imagine there could be many different flavours of linux docker build boxes. Perhaps a Docker repository for a collection of Docker build boxes would be worthwhile, (plus github for community to contribute different flavours) . Personally I wanted to build the most barebones Docker build-box possible (partly as I'm learnig Docker and Linux and it seems like nice simple real world case-study image to learn on), when I first looked at Ducatel's build-box I thought that some of the components of the image might be superflous, on a second look it actaully seems pretty barebones. I'm not sure that git is strictly necessary... Creating an official VSLinux Docker repository would be excellent. But as there could be many different flavours a blog post elucidating building an absolutely barebones Docker build-box would very helpful. Then people could adapt to which ever Linux flavour they which to develop on.

My interest is in developing a Shared Object library (dependent on other Shared Object libraries), which will be called into from a C# asp.net MVC Core project by means of PlatformInvoke. This setup will be running in a Linux Docker container deployed to Azure Container Services. I've used PlatformInvoke on a similar setup running in Windows Server so hopefully all will go smoothly on Linux.

As I'm learning Docker it seemed natural to me to use a Docker container as a build box. Developing in a build-box which is similar to the container which I deploy my app to may have advantages too. As I'm new to Linux and Docker, Ubuntu seems like a good starting point. 

Tip: Use the following Docker command to connect to the build-box container while developing
`#docker exec -it container_name /bin/bash`

**Comment by iontodirel** [comment]
Hi, we have this in the backlog, and we are evaluating native Docker support. Docker can be used over SSH, and we made a recent blog post about it here: https://devblogs.microsoft.com/cppblog/build-c-applications-in-a-linux-docker-container-with-visual-studio/

**Comment by itodirel** [comment]
Hi, we have this in the backlog, and we are evaluating native Docker support. Docker can be used over SSH, and we made a recent blog post about it here: https://devblogs.microsoft.com/cppblog/build-c-applications-in-a-linux-docker-container-with-visual-studio/
