### ISSUE TITLE
Compilation of single C++ source file includes C compiler options

### ISSUE THREAD

**Issue by stanthomas** [Microsoft/VSLinux#5]
When a single C++ source file is compiled  (via Build/Compile Ctrl+F7) the compilation
uses the C language options from the project settings in addition to the C++ language options.
C++ source file has extension .cpp.
When the same file is compiled as partion of Build project, only the C++ language options are used - as expected.

This appears to be something that changed after Visual Studio Update 3.

Visual Studio 2015 Pro Update 3
Windows 10 insider latest
VC_Linux 1.0.4
Mageia Linux 5 (x64)
gcc 4.9.2 / gdb 7.8.1 / gdbserver 7.8.1
## log from Build/Compile Ctrl+F7

`g++ -c /***/***/***/vcl01/main.cpp -g2 -gdwarf-2 -o "/***/***/***/vcl01/obj/x64/Debug/main.o" -Wall -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fno-threadsafe-statics -fno-exceptions -fno-rtti -std=c11 -std=c++14 -Wextra`

```
     main.cpp
     cc1plus: warning: command line option '-std=c11' is valid for C/ObjC but not for C++
```
## log from Build/Build Solution

`g++ -c -x c++ /***/***/***/vcl01/main.cpp -g2 -gdwarf-2 -o "/***/***/***/vcl01/obj/x64/Debug/main.o" -Wall -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fno-threadsafe-statics -fno-exceptions -fno-rtti -std=c++14 -Wextra`

**Comment by itodirel** [comment]
Single file compile is terribly broken. I need to fix that.

**Comment by braindeaddeveloper** [comment]
This is still happening in VS2017 build 15.2 is this likely to be fixed anytime soon ? ... I have a colleague that is about to dump VS2017 entirely over this

**Comment by stanthomas** [comment]
Consolidate on #167 as single file compile bug.
