### ISSUE TITLE
no way to access the Unix Clients through target machine

### ISSUE THREAD

**Issue by terrylyons** [Microsoft/VSLinux#50]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  The extension does not seem correctly installed although it works well in most ways. The tools/options/crossplatform/C++/connection manager does not have the LINUX field shown in your how to, and more importantly the servers that I have installed there do not appear in any sort of list in the properties of projects so I can select them for debugging.
- Expected results
  In the property pages under remote settings - to be able to see and select from the ssh linux servers configured.
- Actual results (with build output window contents if applicable)
  no way to get VS to choose the server.
- VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

VS2015 enterprise Ubuntu servers
- Steps required to reproduce the error
  none - it is persistent.
- Required packages and commands to install
  the extension for Linux.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by robotdad** [comment]
This sounds like your MEF cache in VS is corrupted. I was experiencing the same symptom on one of my machines, this fixed it.

Delete this folder: 
%homepath%\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache 

Open a Developer Command prompt and run:
devenv /updateconfiguration

Start VS, your dropdown for remote settings should work now.

**Comment by robotdad** [comment]
@terrylyons did you ever get past this?

**Comment by terrylyons** [comment]
Not really. you need to look at tools like putty, which set up this sort of functionality of chaining through ssh connection to a gateway to ssh access the machine behind. It only requires a slightly more complex ssh script than a direct connection.

The only "practical" solution is to use a third party tool to tunnel the ssh port on the remote machine to a port on local host which the visual studio can connect to directly. This is very fragile and also requires strong local admin rights.

 Best

Terry

On 17 Nov 2016, at 18:13, Marc Goodner <notifications@github.com<mailto:notifications@github.com>> wrote:


@terrylyons<https://github.com/terrylyons> did you ever get past this?

**Comment by lukka** [comment]
@terrylyons could you please provide a brief description about what feature are you requesting? We could then add it to our backlog, thanks.

**Comment by itodirel** [comment]
We are not developing the Visual Studio 2015 extension anymore, can you try it in Visual Studio 2017 and let us know if there are any problems?
