### ISSUE TITLE
Home directory issues when switching remote connections

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#53]
When you are changing the remote target and not changing architectures, if the new remote has a different user name the previous home directory will still be used (and probably fail since it likely doesn't exist).

This can be worked around by hitting rebuild when switching to the new remote machine.

@itodirel has detailed log files on this one.

**Comment by itodirel** [comment]
this is the same issue as https://github.com/Microsoft/VSLinux/issues/55

**Comment by itodirel** [comment]
The 1.0.6 version of the extension is now available on the extension gallery
