### ISSUE TITLE
Log connection information

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#57]
It would be helpful to log connection information in the output window when making a new connection, during build, debug, etc. to diagnose issues.

**Comment by itodirel** [comment]
we are planning to have this in the Update 1 time frame, this is tracked internally, and this is a feature, closing in an effort to reduce the number of issues

**Comment by itodirel** [comment]
wanted to let everyone know that we did this and you can see what we are doing on the remote system, this will be available in 16.1 Preview 2
