### ISSUE TITLE
Support Cross Compile and Debug

### ISSUE THREAD

**Issue by reid-p** [Microsoft/VSLinux#58]
It'd be great if the extension support cross compilation.
This is mostly there with the make file support.
ie: Makefile can be setup to build and copy file to remote target.
The only thing remaining is to allow gdb to be started on a different remote device.
Or to allow for custom gdb commands to be run on the build machine that sorts this out.

I'm still trying to figure out if this can be worked around at the moment.

**Comment by robotdad** [comment]
Tracked by #19 

[Here is an example of how to workaround this today](https://github.com/robotdad/LinuxCrossCompile).
