### ISSUE TITLE
Using external libraries

### ISSUE THREAD

**Issue by T-Dimov** [Microsoft/VSLinux#59]
Hello,
To start off I'm sorry if this has been answered already, I couldn't find what I needed. So my issue is that when I add an external library by providing its path in the Include Directories filed of the properties the program doesn't build and I get the error "No such file in directory" with regards to main.cpp and the line on which I include it. I also need to use a shared object library. Any help with using external libraries(both header-only and shared objects) would be much appreciated.
- Expected results: Successful build.
- Actual results ([output.txt](https://github.com/Microsoft/VSLinux/files/505793/output.txt)): Build fails.
- VC++ 1.0.5, CentOS 7, gcc-c++-4.8.5-4.el7.x86_64/gdb-7.6.1-80.el7.x86_64/gdb-gdbserver-7.6.1-80.el7.x86_64, x64.
- Steps required to reproduce the error: Add and additional include path and include a header from it.

**Comment by stanthomas** [comment]
The generated GCC command line:

```
g++ -c -x c++ /home/tdvm/projects/LinuxTest1/main.cpp -g2 -gdwarf-2 -o "/home/tdvm/projects/LinuxTest1/obj/x64/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11
```
does not contain a `-I` option to specify the path to the headers for your external project.

You say you've set the path for the header in the Additional Include Directories of the project properties page for C/C++ (like the screenshot below). So the most likely cause is that you've set the option for a project configuration that you're not using. Check that both the Configuration and Platform, at the top of the Property Pages window are marked Active, e.g. Active (Debug) and Active (x64). If not, set the active configuration to suit the one you want to build, in Configuration Manager) and set the Additional Include Directories in the active configuration (or indeed, all configurations).

![Image](https://dnpv6w-ch3301.files.1drv.com/y3m_-Hjk2eIdP1u1TupH3P-Q8AIfO9tAwBHsh4EmVfrUxV_qP5v2F_4LpahcM8gGDhURYxJ7E_5srY8IPCEoOha7JQRxAlzEx85INnW_RHoGifjgfRNj1Je3BmTFyd_2iMA1kS8CgzpCHP-aZ9J-EkOMOJYAL_LNRBNujPyyydNBYc?width=1104&height=408&cropmode=none)

**Comment by T-Dimov** [comment]
I've included the Windows-side directory, so that may be the problem. I'll check it on Friday, thanks for the reply. What about dynamic linking libraries where you normally have to provide include path for the headers and and the path to the .dll(.so)? Also will IntelliSence work when the files are on the Linux side?

**Comment by stanthomas** [comment]
For IntelliSense add the path(s) to the header files on the Windows system as well as the path to the files on the Linux system. Most headers for the C++ standard library are already known to VCLinux so you only need paths for your own projects and third-party libraries.

I think you've answered your own question about shared libraries.

**Comment by T-Dimov** [comment]
I'm sorry I'm continuing with the stupid questions but I must be missing something obvious.
I've added both the Windows-side and Linux-side paths (pugixml is header-only, the other one is header + .so).
C/C++ -> General -> Additional Include Directories:
![additincldirecevalval](https://cloud.githubusercontent.com/assets/9215537/19182386/95705258-8c7b-11e6-9a0b-ecc3743e7fdc.PNG)
Linker -> General -> Shared Library Search Path:
![sharlibsearchpatheval](https://cloud.githubusercontent.com/assets/9215537/19182385/956ecece-8c7b-11e6-9e77-75f3ffdcaca4.PNG)
But I'm still getting errors:
![errors](https://cloud.githubusercontent.com/assets/9215537/19182522/481c38ae-8c7c-11e6-8d6d-6807ce1e7f80.PNG)
The constructor and destructor errors are quoting a non-existent file (but when I hover over them it's just main.cpp) and are saying there is an invalid reference to ctor and dtor on the same line (where I create the object). The append_child is the same but on the line where I call it. The last 2 errors are quoting a non-existent file in the project directory.

**Comment by itodirel** [comment]
@T-Dimov, this seems easy to fix, could you help us get a small repro?

**Comment by lukka** [comment]
Closing this issue, please feel free to reopen the issue with a repro on the most recent version of Visual Studio 2017, thanks.
