### ISSUE TITLE
Remote GDB Debugger getting "Segmentation fault" error

### ISSUE THREAD

**Issue by charint0** [Microsoft/VSLinux#60]
If I create a simple project (kind of "hello world" with some boost filesystem instructions), the Remote GDB Debugger works well. I can set breakpoints and debug step by step. Instead If I add some more code, linking to nana gui library and creating a gui, the Remote Debugger does not work anymore. The program is compiled and linked without any problem but whenever I start debugging I get a "Segmentation fault" error and the program exit. Please notice that the same program (.out file) when launched by terminal on the Linux machine works without any problem.
I am sure this occurred to me before and after a clean and rebuild while changing the code it started working again. Now after a few more changes in the code It stopped working. I have tried to clean and rebuild the program a few times, even deleting the bin and obj folders, but I cannot get rid of the problem. 
(The same code when compiled for Windows works and is always fully debuggable).

My environment:

```
Microsoft Visual Studio Professional 2015 Version 14.0.25421.01 Update 3 Visual C++ for Linux Development 1.0.5 connet to virtual machine running CentOS: Linux 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks a lot,
CR

**Comment by charint0** [comment]
One more thing: 
Running GDB from bash on the Linux machine I can Debug the program without any problem.

**Comment by stanthomas** [comment]
Have you put `export DISPLAY=:0.0` in project settings Debugging/Pre-Launch Command ? (Will send to the default Linux display)

You have to tell X-Windows where to send the display for a GUI application. It knows when you start it from Linux and console applications don't use X.

**Comment by charint0** [comment]
I added the Pre-Launch Condition but nothing changed. I am still getting this:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000528686 in nana::detail::platform_spec::platform_spec (this=0x850800 <nana::detail::platform_spec::instance()::object>) at ../../source/detail/platform_spec_posix.cpp:525
Segmentation fault
```

**Comment by stanthomas** [comment]
Other possible reasons include:

- VCLinux doesn't start the application from the directory where the executable is located. This might mean configuration files are not found.
- Command line options required by your application have not been supplied.
- Environment variables are not set up correctly. These can include DISPLAY (above), LD_LIBRARY_PATH and others that your application requires. VCLinux runs the application via `ssh` which does not necessarily create the same environment as a direct login. You can set missing environment variables by adding commands into the VCLinux settings or modify the `ssh` init scripts.

All I can do is assure you that it **does** work. But it looks like something is missing from your setup that the nana library requires.

**Comment by charint0** [comment]
Update:
I was working on the code and made some changes but nothing specific for the GUI as suggested in the previous comment. And today after a solution rebuild the Remote GDB debugger is partially working. 
I say partially because in the beginning everything is working and I can debug step by step but after a while I get a Visual Studio Exception "GDB Exited unexpectedly with exit code 255 (0xFF). Debugging willl now abort". 

![gdb_exception](https://cloud.githubusercontent.com/assets/22167936/19479511/630d1010-9547-11e6-9b86-b2b72439d092.PNG)

**Comment by charint0** [comment]
I have tried to attach a new instance of Visual Studio to the x86_64-linux-gnu-gdb.exe process to debug the chrash, but since then It has not chrashed anymore. 
What I don't understand is that I haven't made any change to the environment. I just removed the reference to a library for serial communication and added a new class and recompiled my Solution and now the remote debugger is fully working. I hope It will keep on working...

**Comment by charint0** [comment]
Update a few few months later: I have ported my code to Visual Studio 2017 with C++ for Linux 1.6. As soon as I tried to Debug remotely I had the "segmentation fault" issue. But while migrating the code I forgot to add the "export DISPLAY=:0.0" command in the Pre-Launch Condition. After adding the command everything works. Therefore I close the issue.

**Comment by izzyonstage** [comment]
I am also getting this error.

I was just using the Raspberry Pi Blinker project template.
When I run the application it works until the execution stops.

Also if I try to set a breakpoint, it does get hit, but I then cant step through the code or continue as I also get the SIGSEGV error then too.

Any ideas?

Currently using v1.0.6 as that is all that would install with my VS2017.

**Comment by joseangelmt** [comment]
Same for me using RaspBerry Pi.
My application runs correctly, but when I debug it, if I set a breakpoint, the execution runs until the breakpoint. When I press F10 I get the SIGSEGV error.

**Comment by boskars** [comment]
I have had the same problem during all the versions, also in 1.0.7.  If I press "step over" F10 or "step into" F11 I get segmentation error.  I can use only use break points.   Also I can only use the debugger for some few minutes.  The connection will always timeout after some while making it impossible to make reliable debug session over time.

**Comment by charint0** [comment]
Since the problem seems to be general I will reopen this issue. Anyway in my specific case (app with GUI) the  "export DISPLAY=:0.0" command was the solution.

**Comment by boskars** [comment]
I am making console application without any display output and the "export DISPLAY=:0.0" makes no difference for me.

**Comment by stanthomas** [comment]
Since VCLinux is perfectly fine for me on a Pi, I suggest trying to narrow the problem down.

First, if you are debugging in gdbserver mode, change to gdb mode (or vice-versa). But note you might be affected by issue #33.
Next, try debugging locally by starting the GDB session on the Pi. If that works, try debugging with GDB over ssh (the environment configuration for ssh is not the same as a local terminal).

@boskars 
`export DISPLAY=:0.0` tells XWindows where to send the GUI display. This has no relevance for a console application. When running a GUI application locally the environment is set up to do something sensible. When running a GUI application over ssh from another XWindows (Linux) system the environment is _often_ configured automatically. The ssh from MS Windows used by VCLinux does not configure the display, presumably because MS Windows can't show it.

**Comment by joseangelmt** [comment]
@stanthomas Thanks for your solution. Debugging in GDB mode works fine with a Odroid XU4 (3.10.92-71) and with a Raspberry PI (4.9.24-v7+)

**Comment by boskars** [comment]
Debugging is still giving me problems.
Leaving VS 15_5_prev2 at this breakpoint for some while....

![billede](https://user-images.githubusercontent.com/25032095/31996167-b24ce0dc-b987-11e7-9678-6601f9237fb2.png)

results in following error:

![billede](https://user-images.githubusercontent.com/25032095/31996076-52854d1a-b987-11e7-8c79-70de557f92ee.png)

Now, VS no longer hangs :-|

**Comment by lukka** [comment]
@boskars could you please provide more information about your remote system? (e.g. _VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware_). 
Or if you could create a  new issue specific to your setup would be fine too. Thanks.

**Comment by boskars** [comment]
@lukka, thanks for your answer.  I have created two new issues one for GDB mode #208 and one for GDBserver mode #209, both debugging modes are losing connection.

The issue regarding the segmentation fault has disappeared.  Now the debugger stops at the very first breakpoint in main() as it should.  I sometimes start my project using VS 15.4 and sometimes 15.5, after I´ve done that the breakpoints started to work again.

**Comment by lukka** [comment]
Closing this issue, please feel free to reopen the issue with a repro on the most recent version of Visual Studio 2017, thanks.
