### ISSUE TITLE
Makefile projects are never up to date

### ISSUE THREAD

**Issue by ardatur** [Microsoft/VSLinux#61]
Pressing F5 or Ctrl-F5 always results in the "This project is out of date" dialog box (even though Ctrl-F5 does not work as per #45, it still complains). Of course, there's a "don't bother me again" checkmark, but it shouldn't really be necessary in this case.

Prereqs:
Windows 7 SP1 Prof, VS 2015.3, VSLinux 1.0.5, Fedora 24 x86_64 on a VirtualBox, GCC 6.1.1, GDB 7.11.1;
a trivial hello-world style project, "makefile" configuration type.

**Comment by stanthomas** [comment]
Is the executable (or whatever the build target is) being copied back to the Windows host? That file, with the correct date/time is the way MSBuild determines the project is up to date. The usual reason for the build target not being copied back is that you haven't set its name (and path) in the remote build section of the project settings.

**Comment by stanthomas** [comment]
I'm sure this was working but when I try it now I see the same as you : build always does a build, run in debugger always pops up "project out of date" dialog. Make reports "nothing to be done" and the up to date executable is copied to Windows host. Oddly the executable is also copied into folder `...\obj\x64\Debug` although I can't see any action for this in the build log. The only recent change I can think of is Windows 10 Insider Update 14942 although it's hard to see what difference that would make.

**Comment by ardatur** [comment]
> Windows 10 Insider Update 14942

Probably not; I have added the host OS info to the original post.

**Comment by itodirel** [comment]
Does it report that the build is not up to date if you just use Ctrl-Shft-B when building, or F5 when debugging?

**Comment by stanthomas** [comment]
`Ctrl-Shft-B` and `F5` cause project to build, even though previously built. As do building / starting from the VS menu.

This is the VS output showing that `make` knows it's already built.

````
1>------ Build started: Project: make101, Configuration: Debug x64 ------
1>  Validating architecture
1>  Validating sources
1>  Copying sources remotely
1>  Invoking cd ~/projects/make101;make debug OBJDIR=Debug
1>  make: Nothing to be done for 'debug'.
1>
1>  Copying file '*****/projects/make101/Debug/make101.exe' to 'C:\projects\vcl01\make101\bin\x64\Debug\make101.exe'
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
````
The EXE copied back has the correct time stamp.
[Full build log here](https://github.com/Microsoft/VSLinux/files/588112/make101.log.txt)

**Comment by itodirel** [comment]
Makefiles are never up to date, with respect to not invoking MSBUILD during debug, because we can't see past the commands that you invoke. I do agree that the experience should be perhaps better and not pop up a dialog, but that is a core change in VS, and not in the extension itself.

**Comment by stanthomas** [comment]
Surely this fits right into the standard MSBUILD framework : you have a build target (usually the executable) that's copied back and the command to build it (`make ...`). So MSBUILD can compare the timestamp of the build target against the files in the VS project in the usual way. Ok, there may be dependencies on things outside the project but VS can't see these anyway (#29); in these cases it's for the user to understand the behaviour and do a full rebuild or invoke `make` as a pre-execute command.

**Comment by itodirel** [comment]
it does, but if you have a reasonable big project you have to document all your inputs, this would be all the headers and sources files, that is not necessarily practical; I recommend disabling the dialog from showing up, otherwise, the Makefile will be up to date on the remote system

**Comment by stanthomas** [comment]
A makefile is very much a 'black box' to VCLinux. And it's fair to assume that anyone using them will have some idea of what they are doing. So I would argue that a VCLinux user would reasonably expect that changes in the current project/solution trigger a make, otherwise it can be assumed to be up to date.

VCLinux doesn't know about dependencies on sources outside the project on the remote system whether msbuild or makefile (#29), and it's going to be difficult to address this. Documenting this and doing what most people would expect seems to be approach.

**Comment by robotdad** [comment]
Reading through this again I don't think there is anything we can do here. We are improving our story for open folder with arbitrary remote builds and cmake, hopefully that will make the msbuild makefile variant less necessary.

I suggest we close this one with no action. @itodirel ?

**Comment by stanthomas** [comment]
I still think my suggestion to bring makefile projects into line with MSBuild, i.e. re-build only when the target is out of date, is reasonable. And, I would imagine, readily incorporated into the current framework.

That said, I have only a passing interest in makefile projects. And no interest at all in CMake, which strikes me as a retrograde step, more suited to VS Code than Visual Studio. My needs are well served by MSBuild projects and I hope this will remain the primary focus for VCLinux.

**Comment by itodirel** [comment]
that would involve connecting to the remote machine, to check if things are up to date, so the performance saving would be slim; and that's what we're talking about here, not connecting and re-invoking the make script; how would be the dependencies expressed, remotely or locally, if remotely then we'd have to make a connection to check if they are up to date, if locally, why only locally? I don't think at this time we can have a nice solution for it, so closing but that does not mean we won't do more here.

**Comment by stanthomas** [comment]
@itodirel 
But why do you need to connect to the Linux remote? You've declared the makefile target to VS and you've copied that target back to the Windows host. Your other comments apply equally to MSBuild projects.

I really don't understand why a makefile project is uniquely different as far as checking whether it's up to date.
