### ISSUE TITLE
Support for crash dumps & debugging

### ISSUE THREAD

**Issue by ashH** [Microsoft/VSLinux#62]
Hello,

My team have asked me to investigate porting one of our project's server components from Windows to Linux, with the caveat that they'd like the programmers to still be able to use Visual Studio rather than a native Linux environment.

An absolute requirement for the team right now is crash reporting & debugging of this server component.

We have briefly experimented with a test project linked against Google's breakpad module, which lets our crashing Linux executable write out a Minidump file readable by Visual Studio and other tools. This seemed like a low-friction approach, however it is limited by VS2015 being able to proceed no further than loading in the Minidump and showing us the modules. We are unable to load in the corresponding Linux exe and symbol information.

Are there plans to allow this kind of debugging via crashdumps, similar to how we would do it for Windows executables?

Kind regards.

**Comment by mikey-h** [comment]
I'm interested in the same question, it would be useful to know if something like this is on the roadmap or if we should look for a solution elsewhere.

**Comment by robotdad** [comment]
We're actively talking about this. There are a couple of different ways we could approach this. I try and post some alternatives soon.

**Comment by iwubcode** [comment]
I'm also interested in this.  Today, we use gdb to debug crash dumps.  Visual Studio would be much nicer!!

**Comment by itodirel** [comment]
copied internal backlog, no plans for this, if that changes, I'll update this
