### ISSUE TITLE
Build Path error

### ISSUE THREAD

**Issue by cf-isys** [Microsoft/VSLinux#64]
I make a new proyect for test, but some source code are in other directory. When I compile the path that use is reference to my windows directory not to remote directory and make a error.

This is the build output.

_1>------ Operación Recompilar todo iniciada: proyecto: iAfUalMem_Ex_Lx, configuración: Debug x86 ------
1>Compilación iniciada a las 10/10/2016 7:44:09 p. m..
1>     1>
1>_PrepareForClean:
1>         Se eliminará el archivo "D:\IntegriSys\ftes\iCL\iAppFramework\Samples\iAfUalMem_Ex_Lx\obj\x86\Debug\iAfUalMem_Ex_Lx.tlog\iAfUalMem_Ex_Lx.lastbuildstate".
1>       _RemoteClean:
1>         Cleaning remote project directory
1>       InitializeBuildStatus:
1>         Aplicando tarea Touch a "D:\IntegriSys\ftes\iCL\iAppFramework\Samples\iAfUalMem_Ex_Lx\obj\x86\Debug\iAfUalMem_Ex_Lx.tlog\unsuccessfulbuild".
1>       _ValidateValidArchitecture:
1>         Validating architecture
1>         Current project architecture 'x86' is compatible with the remote system architecture 'x86' ('x86').
1>       _ValidateSources:
1>         Validating sources
1>       _CopySources:
1>         Copying sources remotely to '192.168.1.113'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Utils\iAfUalMem.c' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Utils/iAfUalMem.c'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Samples\iAfUalMem_Ex_Lx\iAfUalMem_Ex.c' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Samples/iAfUalMem_Ex_Lx/iAfUalMem_Ex.c'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfBuildDefs.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfBuildDefs.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfCallBackDefs.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfCallBackDefs.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfErrorDefs.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfErrorDefs.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfGlbInc.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfGlbInc.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfMemDefs.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfMemDefs.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfPackDefs.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfPackDefs.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfStatusDefs.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfStatusDefs.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Types\iAfTypeDefs.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Types/iAfTypeDefs.h'
1>         Copying file 'D:\IntegriSys\ftes\iCL\iAppFramework\Utils\iAfUalMem.h' to '/home/administrador/projects/iAfUalMem_Ex_Lx/Utils/iAfUalMem.h'
1>       ClCompile:
1>         Starting remote build
1>         Compiling sources:
1>         Invoking g++
1>         g++ -c -x c /home/administrador/projects/iAfUalMem_Ex_Lx/../../Utils/iAfUalMem.c -g2 -gdwarf-2 -o "/home/administrador/projects/iAfUalMem_Ex_Lx/obj/x86/Debug/iAfUalMem.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-pointer-sign" -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c11
1>         iAfUalMem.c
1>         g++: error: /home/administrador/projects/iAfUalMem_Ex_Lx/../../Utils/iAfUalMem.c: No such file or directory
1>         g++: warning: ‘-x c’ after last input file has no effect
1>         g++: fatal error: no input files
1>         compilation terminated.
1>
1>     1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): error : /home/administrador/projects/iAfUalMem_Ex_Lx/../../Utils/iAfUalMem.c: No such file or directory
1>     1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): warning : ‘-x c’ after last input file has no effect
1>     1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): error : no input files
1>         Done compiling '/home/administrador/projects/iAfUalMem_Ex_Lx/../../Utils/iAfUalMem.c'
1>
1>ERROR al compilar.
1>
1>Tiempo transcurrido 00:00:22.28
========== Recompilar todo: 0 correctos, 1 incorrectos, 0 omitidos ==========

Time Elapsed 00:00:22.458_

You can see that when copy the file to remote is different to the path in g++

Why happend this? Which is the solution? Is a bug?

I am using VS 2015 Update 3 and for the remote UBUNTU 14.04

I make the same example with a Raspberry PI 3 and work fine. Why?

Thank for help me.

Regards,

**Comment by robotdad** [comment]
Since it works for the Pi I suggest checking the project settings between ARM and x86. Are there any obvious differences in the path options set there?

**Comment by cf-isys** [comment]
Dear,

Two project are exactly the same! If to the ARM project change the remote connections to x86 make the same error with the path.

I double check all and not found anything. But if install the V1.0.4 version work fine in ARM and x86, but I cannot change the compiler and this is necesary for my project. We are use differents cross-tools in ubuntu.

When you think are ready a new version?

Regards,

**Comment by cthulhua** [comment]
This path is suspicious: "/home/administrador/projects/iAfUalMem_Ex_Lx/../../Utils/iAfUalMem.c"
Does the "/home/administrador/Utils/" directory exist?
This looks at first glance to be similar to the path translation issue at the root of #47, but I wasn't aware that targeted architecture had any bearing on the bug.

**Comment by cf-isys** [comment]
Dear Danny

I make a simple proyect for test this bug. Attach a zip with all files 
and visual studio solution.

For this proyect this is the output for that you see the error. Please 
try this proyect and tell me if you have the same error and if possible 
fix. Please!

Thanks!!!!

1>------ Operación Compilar iniciada: proyecto: RemotePathTest, 
configuración: Debug x86 ------
1>Compilación iniciada a las 27/10/2016 11:50:50 a. m..
1> 1>
1>InitializeBuildStatus:
1> Aplicando tarea Touch a 
"D:\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\RemotePathTest.tlog\unsuccessfulbuild".
1> _ValidateValidArchitecture:
1> Validating architecture
1> Current project architecture 'x86' is compatible with the remote 
system architecture 'x86' ('x86').
1> _ValidateSources:
1> Validating sources
1> _CopySources:
1> Copying sources remotely to '192.168.30.172'
1> Copying file 'D:\VCLinuxTest\Utils\Utils.c' to 
'/home/administrador/projects/RemotePathTest/Utils/Utils.c'
1> Copying file 'D:\VCLinuxTest\Samples\RemotePathTest\RemotePathTest.c' 
to 
'/home/administrador/projects/RemotePathTest/Samples/RemotePathTest/RemotePathTest.c'
1> Copying file 'D:\VCLinuxTest\Utils\Utils.h' to 
'/home/administrador/projects/RemotePathTest/Utils/Utils.h'
1> ClCompile:
1> Starting remote build
1> Compiling sources:
1> Invoking g++
1> g++ -c -x c 
/home/administrador/projects/RemotePathTest/../../Utils/Utils.c -g2 
-gdwarf-2 -o 
"/home/administrador/projects/RemotePathTest/obj/x86/Debug/Utils.o" 
-Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" 
-Wconversion -W"return-type" -Wparentheses -W"no-pointer-sign" 
-W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" 
-W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing 
-fno-omit-frame-pointer -fexceptions -std=c11
1> Utils.c
1> g++: error: 
/home/administrador/projects/RemotePathTest/../../Utils/Utils.c: No such 
file or directory
1> g++: warning: ‘-x c’ after last input file has no effect
1> g++: fatal error: no input files
1> compilation terminated.
1>
1> 1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application 
Type\Linux\1.0\Linux.Common.targets(245,5): error : 
/home/administrador/projects/RemotePathTest/../../Utils/Utils.c: No such 
file or directory
1> 1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application 
Type\Linux\1.0\Linux.Common.targets(245,5): warning : ‘-x c’ after last 
input file has no effect
1> 1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application 
Type\Linux\1.0\Linux.Common.targets(245,5): error : no input files
1> Done compiling 
'/home/administrador/projects/RemotePathTest/../../Utils/Utils.c'
1>
1>ERROR al compilar.
1>
1>Tiempo transcurrido 00:00:02.00
========== Compilar: 0 correctos, 1 incorrectos, 0 actualizados, 0 
omitidos ==========

Time Elapsed 00:00:02.385











------ Mensaje original ------
De: "Danny Hua" <notifications@github.com>
Para: "Microsoft/VSLinux" <VSLinux@noreply.github.com>
CC: "Carlos A. Fernandez" <carlos.fernandez@integri-sys.com>; "Author" 
<author@noreply.github.com>
Enviado: 27/10/2016 3:19:20 a. m.
Asunto: Re: [Microsoft/VSLinux] Build Path error (#64)

**Comment by cf-isys** [comment]
Dear Danny,

You can try the example?

Regards,

------ Mensaje original ------
De: "Carlos A. Fernandez" <carlos.fernandez@integri-sys.com>
Para: "Microsoft/VSLinux" 
<reply@reply.github.com>; 
"Microsoft/VSLinux" <VSLinux@noreply.github.com>
CC: "Author" <author@noreply.github.com>
Enviado: 27/10/2016 11:55:27 a. m.
Asunto: Re[2]: [Microsoft/VSLinux] Build Path error (#64)

**Comment by itodirel** [comment]
I think we might know what the problem is, can you Rebuild the whole project and see if it builds successfully. So we can confirm we are looking at the same issue? Thanks. The theory is that the bug was introduced with the up-to-date checks, and now when things are up to date they do not participate in the computation of the new paths, which results in the new path being incorrectly computed.

**Comment by cf-isys** [comment]
Dear Ion,

I update to V1.0.5 and load the solution.

Then clean solution, and rebuild solution and the same error. Clean 
project, and rebuild project and the same error.

If you rebuild the project work fine? And if compile have the error?

Is possible that the problem are the update from V1.0.4 to V1.0.5 in the 
same directory? Is not possible change the directory in the install.

What you think?

Tell me if you want that try or test anything more. It is a pleasure to 
help you!

Best Regards,


  REBUILD OUTPUT LOG

1>------ Operación Recompilar todo iniciada: proyecto: RemotePathTest, 
configuración: Debug x86 ------
1>Compilación iniciada a las 1/11/2016 12:26:56 a. m..
1> 1>
1>_RemoteClean:
1> Cleaning remote project directory
1> InitializeBuildStatus:
1> Aplicando tarea Touch a 
"D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\RemotePathTest.tlog\unsuccessfulbuild".
1> _ValidateValidArchitecture:
1> Validating architecture
1> Current project architecture 'x86' is compatible with the remote 
system architecture 'x86' ('x86').
1> _ValidateSources:
1> Validating sources
1> _CopySources:
1> Copying sources remotely to '192.168.1.112'
1> Copying file 'D:\VCLinuxTest\VCLinuxTest\Utils\Utils.c' to 
'/home/administrador/projects/RemotePathTest/Utils/Utils.c'
1> Copying file 
'D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\RemotePathTest.c' to 
'/home/administrador/projects/RemotePathTest/Samples/RemotePathTest/RemotePathTest.c'
1> Copying file 'D:\VCLinuxTest\VCLinuxTest\Utils\Utils.h' to 
'/home/administrador/projects/RemotePathTest/Utils/Utils.h'
1> ClCompile:
1> Starting remote build
1> Compiling sources:
1> Invoking g++
1> g++ -c -x c 
/home/administrador/projects/RemotePathTest/../../Utils/Utils.c -g2 
-gdwarf-2 -o 
"/home/administrador/projects/RemotePathTest/obj/x86/Debug/Utils.o" 
-Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" 
-Wconversion -W"return-type" -Wparentheses -W"no-pointer-sign" 
-W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" 
-W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing 
-fno-omit-frame-pointer -fexceptions -std=c11
1> Utils.c
1> g++: error: 
/home/administrador/projects/RemotePathTest/../../Utils/Utils.c: No such 
file or directory
1> g++: warning: ‘-x c’ after last input file has no effect
1> g++: fatal error: no input files
1> compilation terminated.
1>
1> 1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application 
Type\Linux\1.0\Linux.Common.targets(245,5): error : 
/home/administrador/projects/RemotePathTest/../../Utils/Utils.c: No such 
file or directory
1> 1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application 
Type\Linux\1.0\Linux.Common.targets(245,5): warning : ‘-x c’ after last 
input file has no effect
1> 1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application 
Type\Linux\1.0\Linux.Common.targets(245,5): error : no input files
1> Done compiling 
'/home/administrador/projects/RemotePathTest/../../Utils/Utils.c'
1>
1>ERROR al compilar.
1>
1>Tiempo transcurrido 00:00:07.84
========== Recompilar todo: 0 correctos, 1 incorrectos, 0 omitidos 
==========

Time Elapsed 00:00:07.934




------ Mensaje original ------
De: "Ion Todirel" <notifications@github.com>
Para: "Microsoft/VSLinux" <VSLinux@noreply.github.com>
CC: "Carlos A. Fernandez" <carlos.fernandez@integri-sys.com>; "Author" 
<author@noreply.github.com>
Enviado: 31/10/2016 11:10:54 p. m.
Asunto: Re: [Microsoft/VSLinux] Build Path error (#64)

**Comment by cthulhua** [comment]
@cf-isys Can you post your project file for your example? it looks like your attachment did not get uploaded.

**Comment by cf-isys** [comment]
Dear Danny 

I send a email with the test proyect. Please tell me if you received.

Thanks

**Comment by cthulhua** [comment]
@cf-isys I have not been able to reproduce the issue you're seeing locally (I am using 64-bit Ubuntu, though). I'm standing up ARM and 32-bit Linux instances right now, though to see if that changes anything.

Can you post the build log with verbosity set to Diagnostic? (Tools -> Options -> Projects and Solutions -> Build and Run) From the log you've posted, I can tell that the remote path for Utils.c is incorrect, but additional logs would shed light on where exactly that is happening.

One thing I noticed is that I was not able to build without changing the include directive in RemotePathTest.c to "../../Utils/Utils.h" rather than "Utils.h", but you mentioned you were able to build with the Raspberry Pi?

**Comment by cf-isys** [comment]
Dear Danny

I uninstall the V1.0.4 and install V1.0.5.

I change to diagnostic how to say.

I have the same problem, In ARM Raspberry PI build Ok but in x86 Ubuntu 
32 path error.

The #include "utils.h" not have any effect. Remark or delete this line.

Attach the diagnostic log for X86 and ARM. I hope that you found the 
problem.

I wait for your comments.

Thank you very much!!!





------ Mensaje original ------
De: "Danny Hua" <notifications@github.com>
Para: "Microsoft/VSLinux" <VSLinux@noreply.github.com>
CC: "Carlos A. Fernandez" <carlos.fernandez@integri-sys.com>; "Mention" 
<mention@noreply.github.com>
Enviado: 4/11/2016 5:22:36 p. m.
Asunto: Re: [Microsoft/VSLinux] Build Path error (#64)

**Comment by cthulhua** [comment]
I do not see any attachments

**Comment by cf-isys** [comment]
Dear Danny

I resend in .zip

Please tell me if you received now.

Regards,



------ Mensaje original ------
De: "Danny Hua" <notifications@github.com>
Para: "Microsoft/VSLinux" <VSLinux@noreply.github.com>
CC: "Carlos A. Fernandez" <carlos.fernandez@integri-sys.com>; "Mention" 
<mention@noreply.github.com>
Enviado: 4/11/2016 6:25:21 p. m.
Asunto: Re: [Microsoft/VSLinux] Build Path error (#64)

**Comment by cthulhua** [comment]
I see no attached file.

**Comment by cf-isys** [comment]
Danny

I send to gmail account.

Please confirm.

Thanks,

------ Mensaje original ------
De: "Danny Hua" <notifications@github.com>
Para: "Microsoft/VSLinux" <VSLinux@noreply.github.com>
CC: "Carlos A. Fernandez" <carlos.fernandez@integri-sys.com>; "Mention" 
<mention@noreply.github.com>
Enviado: 4/11/2016 9:58:55 p. m.
Asunto: Re: [Microsoft/VSLinux] Build Path error (#64)

**Comment by cthulhua** [comment]
Thanks got it.

**Comment by cf-isys** [comment]
Good                                                                                                                                                                        Saludos/Regards,Carlos A. FernandezDirectorIntegriSys S.A.Móvil: +54.9.261.5136993www.integri-sys.com                                                                                                                                                                            De: notifications@github.comEnviados: 4 de noviembre de 2016 10:30 PMPara: VSLinux@noreply.github.comResponder a: reply@reply.github.comCC: carlos.fernandez@integri-sys.com; mention@noreply.github.comAsunto: Re: [Microsoft/VSLinux] Build Path error (#64)  Thanks got it.

**Comment by cthulhua** [comment]
@cf-isys, I was able to repro this locally with an (x86 box and a x64 box), and I have a workaround that worked on my test case that you can try: add `RemoteTarget="$(RemoteTarget)"` to the MakeClCommandLine invocation under the ClCompile target in "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets"

e.g.
`...
MakeClCommandLine Condition="'%(ClCompile.ExcludedFromBuild)' != 'true'"
      ProjectDir="$(ProjectDir)"
      RemoteProjectDir="$(_ResolvedRemoteProjectDir)"
      RemoteTarget="$(RemoteTarget)"
...`

**Comment by cf-isys** [comment]
Dear Danny

Your are the BEST!!!! Work!!!

This fix include in the new release?

Thank you very much!!!!


1>------ Operación Recompilar todo iniciada: proyecto: RemotePathTest, 
configuración: Debug x86 ------
1>Compilación iniciada a las 10/11/2016 11:46:18 p. m..
1> 1>
1>_PrepareForClean:
1> Se eliminará el archivo 
"D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\RemotePathTest.tlog\RemotePathTest.lastbuildstate".
1> _RemoteClean:
1> Cleaning remote project directory
1> InitializeBuildStatus:
1> Se creará 
"D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\RemotePathTest.tlog\unsuccessfulbuild" 
porque se especificó "AlwaysCreate".
1> _ValidateValidArchitecture:
1> Validating architecture
1> Current project architecture 'x86' is compatible with the remote 
system architecture 'x86' ('x86').
1> _ValidateSources:
1> Validating sources
1> _CopySources:
1> Copying sources remotely to '192.168.1.111'
1> Copying file 'D:\VCLinuxTest\VCLinuxTest\Utils\Utils.c' to 
'/home/administrador/projects/RemotePathTest/Utils/Utils.c'
1> Copying file 
'D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\RemotePathTest.c' to 
'/home/administrador/projects/RemotePathTest/Samples/RemotePathTest/RemotePathTest.c'
1> Copying file 'D:\VCLinuxTest\VCLinuxTest\Utils\Utils.h' to 
'/home/administrador/projects/RemotePathTest/Utils/Utils.h'
1> ClCompile:
1> Starting remote build
1> Compiling sources:
1> Invoking g++
1> g++-6 -c -x c 
/home/administrador/projects/RemotePathTest/Utils/Utils.c -g2 -gdwarf-2 
-o "/home/administrador/projects/RemotePathTest/obj/x86/Debug/Utils.o" 
-Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" 
-Wconversion -W"return-type" -Wparentheses -W"no-pointer-sign" 
-W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" 
-W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing 
-fno-omit-frame-pointer -fexceptions -std=c11
1> Utils.c
1>
1> Done compiling 
'/home/administrador/projects/RemotePathTest/Utils/Utils.c'
1> Copying file 
'/home/administrador/projects/RemotePathTest/obj/x86/Debug/Utils.o' to 
'D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\Utils.o'
1> Invoking g++
1> g++-6 -c -x c 
/home/administrador/projects/RemotePathTest/Samples/RemotePathTest/RemotePathTest.c 
-g2 -gdwarf-2 -o 
"/home/administrador/projects/RemotePathTest/obj/x86/Debug/RemotePathTest.o" 
-Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" 
-Wconversion -W"return-type" -Wparentheses -W"no-pointer-sign" 
-W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" 
-W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing 
-fno-omit-frame-pointer -fexceptions -std=c11
1> RemotePathTest.c
1>
1> Done compiling 
'/home/administrador/projects/RemotePathTest/Samples/RemotePathTest/RemotePathTest.c'
1> Copying file 
'/home/administrador/projects/RemotePathTest/obj/x86/Debug/RemotePathTest.o' 
to 
'D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\RemotePathTest.o'
1> Link:
1> Linking objects
1> Invoking ld
1> g++ -o 
"/home/administrador/projects/RemotePathTest/bin/x86/Debug/RemotePathTest.out" 
-Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack 
/home/administrador/projects/RemotePathTest/obj/x86/Debug/Utils.o 
/home/administrador/projects/RemotePathTest/obj/x86/Debug/RemotePathTest.o
1>
1> Done linking, output file name: 
'/home/administrador/projects/RemotePathTest/bin/x86/Debug/RemotePathTest.out'
1> Copying file 
'/home/administrador/projects/RemotePathTest/bin/x86/Debug/RemotePathTest.out' 
to 
'D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\bin\x86\Debug\RemotePathTest.out'
1> RemotePathTest.vcxproj -> 
D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\bin\x86\Debug\RemotePathTest.out
1> FinalizeBuildStatus:
1> Se eliminará el archivo 
"D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\RemotePathTest.tlog\unsuccessfulbuild".
1> Aplicando tarea Touch a 
"D:\VCLinuxTest\VCLinuxTest\Samples\RemotePathTest\obj\x86\Debug\RemotePathTest.tlog\RemotePathTest.lastbuildstate".
1>
1>Compilación correcta.
1>
1>Tiempo transcurrido 00:00:09.10
========== Recompilar todo: 1 correctos, 0 incorrectos, 0 omitidos 
==========

Time Elapsed 00:00:09.187

------ Mensaje original ------
De: "Danny Hua" <notifications@github.com>
Para: "Microsoft/VSLinux" <VSLinux@noreply.github.com>
CC: "Carlos A. Fernandez" <carlos.fernandez@integri-sys.com>; "Mention" 
<mention@noreply.github.com>
Enviado: 10/11/2016 9:06:48 p. m.
Asunto: Re: [Microsoft/VSLinux] Build Path error (#64)

**Comment by itodirel** [comment]
Hi, yes, this fix will be available in the next release of the extension. We are hopping to push a new release in about one week from now.

**Comment by cf-isys** [comment]
Excellent!!  And congratulations for this excellent tool!!!                                                                                                                                                                        Saludos/Regards,Carlos A. FernandezDirectorIntegriSys S.A.Móvil: +54.9.261.5136993www.integri-sys.com                                                                                                                                                                            De: notifications@github.comEnviados: 11 de noviembre de 2016 11:46 PMPara: VSLinux@noreply.github.comResponder a: reply@reply.github.comCC: carlos.fernandez@integri-sys.com; state_change@noreply.github.comAsunto: Re: [Microsoft/VSLinux] Build Path error (#64)  Hi, yes, this fix will be available in the next release of the extension. We are hopping to push a new release in about one week from now.
