### ISSUE TITLE
Dialog box "gdbserver failed to debug" appears 

### ISSUE THREAD

**Issue by damienhocking** [Microsoft/VSLinux#67]
I'm trying to get a gdbserver session attached to my Ubuntu64 VM, using VS2015 update 3.  I've followed the instructions at 

https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/

A few things are different.  We build our software with SCons, and the debug build is already done so we don't copy any source or have any other build steps.  It debugs fine directly on the VM with Eclipse.

I _think_ the security credentials are OK, I get no errors on the Linux connection setup with either password or private key.  The Linux Console Window doesn't show anything either.  When I kick off the Remote GDB Debugger session the "gdbserver failed to debug" box appears.

I'm pretty sure this is some dumbo error on my part.  Can you tell me what to start checking?

Damien

**Comment by robotdad** [comment]
No, we have had other reports of this. I think @itodirel is looking at it.

**Comment by robotdad** [comment]
Can you double check if gdbserver is installed on your Linux machine? We still shouldn't throw a blank error, but that may be the root cause here.

**Comment by damienhocking** [comment]
Yes, gdbserver is installed.  That was one of the first things I checked :-)

**Comment by bcabes** [comment]
I am also having this issue.

**Comment by robotdad** [comment]
@damienhocking which version of Ubuntu is this? Are you still seeing this issue in 2017?

**Comment by damienhocking** [comment]
Oops, I forgot to close this.  As of a couple of months ago this works.  Closing now, my apologies.

**Comment by damienhocking** [comment]
BTW it was an update to the Linux component that fixed it, it works on any gdbserver that I've used now.
