### ISSUE TITLE
"~/" is not recognized in Additionnal Include Directories

### ISSUE THREAD

**Issue by kinju** [microsoft/VSLinux#68]
- Description
  It seems that the "~" Linux shortcut is not recognized in the Additionnal Include Directories property during the build process.

Here's is my small test project called "vclinux" with 2 files in the root directory :

' test.h (empty)
' main.cpp which contains :

`#include <vclinux/test.h>

int main(int argc, char*\* argv)
{
    return 0;
}`

In my Remote settings, I let the Remote Root Directory to de default value : "~/projects"

In my Additionnal Include Directories, I have "$(RemoteRootDir);$(StlIncludeDirectories);%(AdditionalIncludeDirectories)"
- Expected results

The path "/home/user/projects" is added to the search include directories and <vclinux/test.h> is found during the compilation.
- Actual results

A compilation error

> 1>------ Build started: Project: vclinux, Configuration: Debug x64 ------
> 1>  Validating architecture
> 1>  Validating sources
> 1>  Copying sources remotely
> 1>  Starting remote build
> 1>  Compiling sources:
> 1>  main.cpp
> main.cpp(1,26): error : vclinux/test.h: No such file or directory

If I do one of these change, it works :
' Change the Remote Root Directory from "~projects" to "/home/user/projects"
' Change the search include directories form "$(RemoteRootDir)" to "/home/user/projects"
- Versions

' VC++ version, 2015 Enterprise Update 3
' Linux system name and version, Ubuntu 14.04 Desktop
' GCC/GDB/gdbserver version, 4.8.4, 7.7.1, 7.7.1
' CPU arch, x86_64
- Steps required to reproduce the error

Use the Linux "~" shortcut in the Additionnal Include Directories property (maybe also in the Additionnal Library Path)
- Unpleasantness

' I have 4 projects (3 static libraries and 1 executable) on the root directory. The executable need to include files from the others projects
' The workaround is not clean since it implies to set a Linux user name in the VS projects configuration

I tried to set the root directory to "/projects" instead of "~/projects" to avoid the "~" but I had some security problems and it's not a good idea in a virtual machine with more than one user.

Thank you :)

kin

**Comment by SuCasa** [comment]
I found the same problem.  If an Additional Sources To Copy is specified as:
  $(ProjectDir)Makefile:=$(RemoteProjectDir)Makefile,
where $(RemoteProjectDir) is defined as ~/projects/myproj
a remote directory is made in my Linux home directory literally named "~", i.e. the full directory name is
"/home/SuCasa/~/projects/myproj" (that's an actual tilde).  To its credit, the Makefile is actually copied.

**Comment by lorenzrox** [comment]
same for the Additional Library Directories

**Comment by robotdad** [comment]
@lukka made some fixes in this area recently, tagging him to investigate.

**Comment by amit-ezra** [comment]
+1 for Additional Library Directories - using ~/projects doesn't work, while using /home/user/project does.
VS2017 PRO 15.5.2

**Comment by percin** [comment]
simon says +1 for a bug still exist in 2019 summer.

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
