### ISSUE TITLE
#pragma message (and corresponding _Pragma) do not appear in build log

### ISSUE THREAD

**Issue by shlublu** [Microsoft/VSLinux#69]
`#pragma message` and corresponding `_Pragma` do not appear in the build output window, they are silently ignored regrdless the log level (here: minimal):

![image](https://cloud.githubusercontent.com/assets/12934696/19787112/4fc0fc40-9ca1-11e6-91f8-40aed1d2dfd9.png)

These messages don't appear in the error window either:

![image](https://cloud.githubusercontent.com/assets/12934696/19787379/aaa2dace-9ca2-11e6-9c45-b79689c4d745.png)

_g++_ handles these pragma properly though. In the compile output, they appear as "notes":

![image](https://cloud.githubusercontent.com/assets/12934696/19787090/354c8550-9ca1-11e6-9608-56170954bf2d.png)

(Sorry for these _FR_fr_ screenshots by the way)

I'm running _Visual Studio Community 2015, Version 14.0.25431.01 Update 3_ and _Visual C++ for Linux Development  1.0.5_.

The Linux machine is actually a Win32 with Cygwin and all prerequisites installed (I'll switch it to a plain Linux soon). The version of _GCC_ is  v5.4.0.

To reproduce this, simply try inserting a `#pragma message ("This is a test")` in a Hello World program. The screenshots above were produced by the following code:

`#include <cstdio>

int main()
{
# pragma message ("This is a test")

```
printf("Hello world!");
return 0;
```

}`

It would be great to see these messages in the output window. This would allow using more advanced messages including __FILE__ and __LINE__, like what is feasible with C++ for Windows:

![image](https://cloud.githubusercontent.com/assets/12934696/19787662/3f8eb2ce-9ca4-11e6-8a7b-fef4e33f3761.png)

Thanks a lot!

**Comment by stanthomas** [comment]
A pragma message is displayed in the output/build window when `MSBuild project output verbosity` is set to `normal`.

E.g.

```
#pragma message "Compiling " __FILE__ "..."
```
produces compilation output:

```
1>         ......../main.cpp:17:39: note: #pragma message: Compiling ......../main.cpp...
1>          #pragma message "Compiling " __FILE__ "..."
1>                                                ^
```

VS 2015 Pro + VCLinux 1.0.5 + g++ 4.9.2

**Comment by shlublu** [comment]
Oh, that's right, missed it.

It would be very useful to have these in the minimal build though. 

"Normal" logging level is already too verbose and when you set such a message in your code, it is for it to appear at build time even in default loggin level. The idea is to do the same way as Visual Studio for Windows does, and also the same way as GCC does.

**Comment by itodirel** [comment]
this is now fixed, you will see the message with Minimal verbosity, the fix will be available in the next release of the extension, and likely in the Update 1 of Visual Studio 2017
