### ISSUE TITLE
There is no linux console

### ISSUE THREAD

**Issue by kikuznetsov** [Microsoft/VSLinux#70]
I run test programm "Hello linux!" from VS2015, but there is no linux console window. I could not get output of my programm. But rest processes of debugging is going well. 
![bug_vs_linux](https://cloud.githubusercontent.com/assets/1779698/19962817/7b2eb8d0-a1ca-11e6-8d59-16d60fd9c57f.png)
Is it bug or I made some mistakes?

**Comment by stanthomas** [comment]
You have to explicitly open the Linux Console window. Select the VCLinux project as your Startup Project and the `Linux Console` item will appear in the Debug menu.

**Comment by kikuznetsov** [comment]
Oh... Thank you very much!

**Comment by mlauronen** [comment]
![image](https://cloud.githubusercontent.com/assets/25513951/22620928/c8f4e65e-eb1f-11e6-855d-4cd03d7d0ef6.png)

My Startup project for the solution is set up properly (please see the picture) but still no Linux Console tab exists. If I try to activate it from the the Debug pull down menu it still doesn't come up.

I am using Visual Studio Community 2015 Version 14.0.25431.01 Update 3 and the Linux templates were downloaded today.

So what to do next to get this thing to work ?
