### ISSUE TITLE
Cpp file cannot locate outside project folder

### ISSUE THREAD

**Issue by tonytse** [Microsoft/VSLinux#74]
Here is my folder structure:
Linux_test
|-Project
  |- App1
       |- App1.sln
       |- App1.vcxproj
  |- source
       |- main.cpp

When I compile my project, it shows the following error:

Error		/home/tony/projects/App1/../../source/main.cpp: No such file or directory	App1	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets	245	

The file path on Linux is /home/tony/projects/App1/source/main.cpp 

I am using Ubuntu and CentOS7 ( GCC 6.2 ) with Virtual Box,  and i can have a success compile on RedHat 6.1

Anyone help and suggest ? thanks in advance .

**Comment by charint0** [comment]
I had a very similar problem. Everything worked until I switched to compile from x64 to x86 with a different VM (running CentOS 6.8). 
After that I kept getting an error:

> g++: /root/projects/TestDriverLibLinux/../src/PumpDriver.cpp: No such file or directory

I have found the solution here. See: CLOSED BUG: "Build Path error #64"
in short, add a line to the file "Linux.Common.targets" in the installation folder:

> add RemoteTarget="$(RemoteTarget)" to the MakeClCommandLine invocation under the ClCompile target in "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets"
> 
> e.g.
> ... MakeClCommandLine Condition="'%(ClCompile.ExcludedFromBuild)' != 'true'" ProjectDir="$(ProjectDir)" RemoteProjectDir="$(_ResolvedRemoteProjectDir)" RemoteTarget="$(RemoteTarget)" ...

I hope that this help you too!
CR

**Comment by tonytse** [comment]
Hi charint0,

Thank you very much , it's works
