### ISSUE TITLE
error without any information 

### ISSUE THREAD

**Issue by rosrad** [Microsoft/VSLinux#75]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
Debug under gdbserver mode with a centos linux.
but I got a error without any information.

* Expected results
how to get the actual error information, and how could I fix it .
* Actual results (with build output window contents if applicable)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware'

VS2015.3 enterprise 
with linux centos 7, with (GDB) Red Hat Enterprise Linux 7.6.1-80.el7

**Comment by itodirel** [comment]
I believe we fixed this issue in 1.0.6, which we just released, can you install 1.0.6 and see if it fixes your issue?

**Comment by itodirel** [comment]
Just to clarify, to get the fix, for VS2015 you need the extension from here: https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.VisualCforLinuxDevelopment 

And for VS2017, at least RC2 of Visual Studio.
