### ISSUE TITLE
Cant resolve include directories

### ISSUE THREAD

**Issue by bikeaccdnt** [Microsoft/VSLinux#77]
I am trying to create a library of utilities that several projects will use.
The problem I am having is if I don't copy the .h and .cpp file to the project the compiler cant resolve the include folder.
In the example below I have created a project EmptyLinuxProject that contains SimpleClass.
The project is in C:\Temp\EmptyLinuxProject

**SimpleClass.cpp**
`#include "SimpleClass.h"

SimpleClass::SimpleClass()
  {
  iInteger = 100;
  }

SimpleClass::~SimpleClass()
  {
  iInteger = 0;
  }

int SimpleClass::GetInteger()
  {
  return iInteger;
  }`

**SimpleClass.h**
`#pragma once

class SimpleClass
  {
  private:
    int iInteger;
  public:
    SimpleClass();
    ~SimpleClass();
    int GetInteger();
  };`

Then I created a project LinuxConsoleApp that will attempt to use the SimpleClass
LinuxConsoleApp
**Main.cpp**
`#include <cstdio>
#include "SimpleClass.h"

int main()
  {
  SimpleClass *SC = new SimpleClass();

  printf("hello from LinuxConsoleApp! SimpleClass returned %d\n", SC->GetInteger());

  delete SC;
  return 0;
  }`

**Settings for Project:**
All Configurations - All Platforms
VC++ Directories
    Include Directories: C:\Temp\EmptyLinuxProject;$(IncludePath)
![image](https://cloud.githubusercontent.com/assets/24412794/20929692/e39217ae-bb98-11e6-856d-f43bf9080d27.png)

C/C++
  General
  Additional Include Directories
    C:\Temp\EmptyLinuxProject;%(AdditionalIncludeDirectories)
![image](https://cloud.githubusercontent.com/assets/24412794/20929712/f2750b14-bb98-11e6-8634-c0e01feb3618.png)

**Expected Results:**
I expect this to resolve the folder for SimpleClass.h

Actual Results:
Severity	Code	Description	Project	File	Line	Suppression State
Error		SimpleClass.h: No such file or directory	LinuxConsoleApp	C:\Temp\EmptyLinuxProject\SimpleClass.cpp	1	
![image](https://cloud.githubusercontent.com/assets/24412794/20929765/26dbecba-bb99-11e6-8a4c-f2c542b33cb8.png)

VC++ Version
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Linux Centos OS 3.10.0-229.14.1.el7.x86_64
gcc version 4.8.5

* Steps required to reproduce the error

Create EmptyLinuxProject with SimpleClass.h and SimpleClass.cpp
as an empty linux project in C:\Temp\EmptyLinuxProject
Create LinuxConsoleApp with main.cpp
as a Linux Console App in C:\Temp\LinuxConsoleApp
Select LinuxConsoleApp and add existing item C:\Temp\SimpleClass.cppp

Really all I want to do is create my own static library file and use that.
I have tried all variants of #include
#include "SimpleClass.h"
#include "..\EmptyLinuxProject\SimpleClass.h"
#include "C:\Temp\EmptyLinuxProject\SimpleClass.h"

it just gives me the same error every time.

**Comment by stanthomas** [comment]
The include path must be the one on the remote Linux system. For IntelliSense you should also specify the path on the Windows host.
My preference is to specify Additional Include Directories in the C/C++ General page of the project properties.

**Comment by bikeaccdnt** [comment]
Stan,

Thanks.. was not sure which directories to put there the Windows side or Unix side.

Now working!!
