### ISSUE TITLE
Include flag not added for specific directory

### ISSUE THREAD

**Issue by kaiscode** [Microsoft/VSLinux#80]
First off, I want to say thanks for the great work on this Linux build functionality.  Everything has been working quite well.

I've run into an incredibly odd issue with build include flags though.  I have a Linux project which I've been using for a while that's been working quite well.  I add additional include directories under Configuration Properties > C/C++ > General > Additional Include Directories.

I've added several directories to the list, but recently needed to add two more:
/usr/lib/x86_64-linux-gnu/glib-2.0/include
/usr/include/glib-2.0

However, it doesn't look like /usr/include/glib-2.0 is ever actually being added to the flags being passed to g++.  I've changed the verbosity to Normal so I can see exactly what g++ is being called with, and I can see it's passing -I "/usr/lib/x86_64-linux-gnu/glib-2.0/include", but there is no -I /usr/include/glib-2.0.

Changing /usr/include/glib-2.0 to something else results in that being included, even if I just change it to /usr/include/glib-2.00, or any other random directory.  This is incredibly frustrating, because it seems like only that SPECIFIC directory name is not being added.  It'll include everything EXCEPT that one directory.  

My guess is some directory caching is happening in the build system, and something's broken with that.  Does anyone know how I can clear the cache?

For now I have the incredibly hacky solution of symlinking /usr/include/glib-2.00 to the proper directory on the Linux build machine.  Tried restarting Visual Studio several times, to no avail.  I don't know where the build system caches files, or if it works differently for VC++ Linux.

Thanks.

**Comment by stanthomas** [comment]
Not a direct answer to your issue but you could use `pkg-config` as a better solution in general. Add `%24(pkg-config --cflags glib-2.0)` to C++/All Options/Additional Options in project properties rather than specifying the include path directly.

`%24` is an encoded `$` otherwise Visual Studio tries (and fails) to interpret the string as a macro.

**Comment by kaiscode** [comment]
@stanthomas Thanks for the suggestion.  I am using pkg-config already for the project on Linux, so that works well for me.  That's definitely a good work around for now.  Still curious if anyone knows if there's a solution to the problem, or if that's already been fixed in some dev build.  Thanks again!

**Comment by reneherrero** [comment]
Having the same problem with 2017 RC.

When setting the output to diagnostic, I see this:
 Task Parameter:
1>        ClInclude=
1>            ..\Include

There is however no -I flags passed to g++.

**Comment by itodirel** [comment]
@kaiscode the Additional Include Directories is a semicolon separated list, so to add the two directories, you'll have to have something like this: /usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/glib-2.0

Additionally, you want to make sure in Property Pages that you're setting the Additional Include Directories for the active configuration and platform. At the top of the Property Pages, both Configuration and Platform should read "Active"

**Comment by ReneHerrero** [comment]
Noticed something odd with the Additional Include Directories:
If you put: $(ProjectDir)include -> no I flag gets added
But if you put just: include -> the I flag does get added

This obviously only works for directories within the project.
Hope it helps,

**Comment by kaiscode** [comment]
@itodirel I was using a semicolon separated list when adding multiple directories.  If I weren't, I wouldn't see it work for glib-2.00 and not glib-2.0 (only difference was adding another character).  As I said, there must be some caching going on somewhere, but I don't have the tools to debug that.  I was on the properties page for the active configuration and platform.

It has been quite a while since I reported this issue, and so I'm no longer actively working on the project that has this issue.  If you have other questions, feel free to ask.  But if no one can repro the issue, it's fine if you close it too.

**Comment by itodirel** [comment]
Thank you @kaiscode, if you can reproduce again, please attach the build logs, or just let us know, we'll reactivate and take it from there
