### ISSUE TITLE
parallel remote compile

### ISSUE THREAD

**Issue by itodirel** [Microsoft/VSLinux#82]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
We should run multiple parallel compile tasks to improve compile performance

**Comment by dedmen** [comment]
Will parallel source file uploads be part of this? 1.0.6 didn't do parallel uploads so i don't know if this is already on the radar.

**Comment by itodirel** [comment]
we could that with little effort, however I found that running the file copies asynchronously in parallel doesn't really improve the performance, and overall they take as long to copy as when done sequentially; more so, on the Raspberry Pi, this is unreliable and can bring the whole sftp session down

**Comment by PhilippeMazouer** [comment]
No news on the parallel remote compile feature?
I was eager to test VS15.4 ... but sadly it isn't there.

Large projects takes way too long to compile on a single ssh connection.

**Comment by pwc357** [comment]
Parallel compile is critical for us too.

**Comment by Rini4286** [comment]
We are migrating our env. from Linux to Windows (Studio is much more friendly than Netbeans) and parallel compilation  is critical for the success of the migration. Any idea when this feature will be available?

**Comment by itodirel** [comment]
We actually have an internal beta completion of this feature. Might be out as soon as the next release.
