### ISSUE TITLE
VS 2017 Open Folder Support

### ISSUE THREAD

**Issue by janbernloehr** [Microsoft/VSLinux#83]
Allow to use this extension in "Open Folder" Projects created with VS2017.

To provide a more natural development workflow for cross platform developers, VS2017 adds the ability to open a folder as a VS project. Enabling this extenion for these kind of projects would also make building and debugging more natural. In addition working with CMake projects would be much simpler.

**Comment by robotdad** [comment]
Agreed. We won't be able to get to this for RTM but we are looking at it.

**Comment by MathiasMagnus** [comment]
Indeed. Open Folder to pop a CMake project, setup several Configurations (MSVC-Win, Clang-Win, Clang-WSL, GCC-WSL), hotkey for Batch Building all of them and see build output for all of them. Boy, X-plat developer dream come true.

Most likely needs Creators Update features to launch bash.exe -c and capture cout and cerr with exit codes. No copying sources, but linux builds use them from the NTFS partition (CMake would naturally find dependencies on the linux file system.)

+100

**Comment by longyn** [comment]
+1

**Comment by robotdad** [comment]
This is coming for cmake in 15.4 preview 1.

**Comment by itodirel** [comment]
As Marc mentioned, both of those are coming in Preview 2
