### ISSUE TITLE
Inferior loaded /lib/x86_64-linux-gnu/libc.so.6 - WSL, version 1.0.6

### ISSUE THREAD

**Issue by canesin** [Microsoft/VSLinux#86]
Hi,

On VS2017 RC I was able to setup a SSH connection with WSL (so localhost) and the extension works with the example from (https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/) but the Debug window always show the warning:

Loaded 'shared libraries loaded at this time.'. Cannot find or open the symbol file.
Stopped due to shared library event:
  Inferior loaded /lib/x86_64-linux-gnu/libc.so.6
    /lib64/ld-linux-x86-64.so.2
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Cannot find or open the symbol file.
Loaded '/lib64/ld-linux-x86-64.so.2'. Cannot find or open the symbol file.

This is on the extesion version 1.0.6

Regrads,

**Comment by jerett** [comment]
same problem

**Comment by leagmain** [comment]
me too.

**Comment by raphaelts3** [comment]
I was able to solve this problem changing "Project >> Properties >> Configuration >> Debug >> Debugging Mode" to gdb instead of gdbserver. I hope it helps you guys as well.

**Comment by fpGHwd** [comment]
I set the Debugging Mode as you say, and click remote GDB debug program, then it is stuck for a long time and I can do nothing except stopping Visual Studio via Task Manager...

**Comment by paulmaybee** [comment]
In gdbserver mode gdb runs on the Windows machine and gdbserver runs on the Linux machine. Gdb requires access to the .so files in order to read the symbols. The debugger will not automatically copy non-project shared libraries over to the Windows machine in order to look for the symbols. If you require the symbols for these libraries then copy the libraries manually and  point to the location using "Properties->Debugging->Additional Symbol Search Paths". 

No idea why you are getting a hang, but to find out what is happening under the covers with gdb, turn on gdb logging. In the command window type:
**Debug.MIDebugLog /On:**_some-logfile-path_
Then repeat your scenario and type:
**Debug.MIDebugLog /Off**
Or kill the process if that is required. You may be able to tell what is going on from the log file, if not attach it and I can take a look.

**Comment by fpGHwd** [comment]
I do as you said,  so the proper reason is no gdb is available in my target device? there is no gdb in my target device indeed...
[mslog.txt](https://github.com/Microsoft/VSLinux/files/1043803/mslog.txt)

**Comment by paulmaybee** [comment]
When in 'gdb' debugging mode Visual Studio makes use of the gdb.exe on the target device to perform debugging operations. If you wish to use this mode then you need to install gdb. If gdb is not available then your only choice is to use 'gdbserver' mode (provided gdbserver.exe **is** available for your device).

**Comment by fpGHwd** [comment]
I can use GDBserver mode to debug now! But there is something wrong with interruptions from exception from VS...  I set arbitrary break points and start debugging, then VS stop at the break point, unfortunately it ALWAYS get a segmentation fault when I step the following statement...   I get a printscreen following. 
![segmenation fault interruption after step statement](https://cloud.githubusercontent.com/assets/11605000/26721839/10cf2410-47c0-11e7-8cea-e6ab988d033c.png)

**Comment by fpGHwd** [comment]
And I find and run executable binary file in my target device without any segmentation fault, so I am sure that the code has no problem.

**Comment by paulmaybee** [comment]
This sounds like an architectural mismatch between gdb and gdbserver. Are you debugging on an ARM or x86 device? Can you collect another log and attach it?

**Comment by fpGHwd** [comment]
VS version is VS2017 enterprise edition, and vs c++ version I think is g++(gcc) 4.8.1 (as following printscreen shows), and I have the log(
[msvslog.txt](https://github.com/Microsoft/VSLinux/files/1049324/msvslog.txt)
) when I regenerate the resolution and debug and get a "step" segmentation fault.  Thank you for your patience!

![qq 20170603101347](https://cloud.githubusercontent.com/assets/11605000/26749834/43a41360-4846-11e7-93c1-da7fb4301965.png)

**Comment by chinanrui** [comment]
@raphaelts3 good for me, thanks

**Comment by trogper** [comment]
why is this issue closed?
it was not solved and no reason provided

**Comment by TanLingxiao** [comment]
There may be no problems. Please open the linux console instead of windows ,you can see the result. (Debug -> Linux Console)

**Comment by TanLingxiao** [comment]
![q rz ng tjvs8umqduyw](https://user-images.githubusercontent.com/8078355/43768527-2698fcbe-9a6a-11e8-89fe-6a3aee3cf5f6.png)

**Comment by fpGHwd** [comment]
I'll try this.
