### ISSUE TITLE
Specifying different remotes for building vs debuggin

### ISSUE THREAD

**Issue by AliAskari** [microsoft/VSLinux#87]
It would be cool if we could specify one remote as the build machine and a different remote for debugging. 
This could already be done manually but it becomes annoying after some time. 

This is my current workflow:

* Open project settings, select the build remote.
* Build the project.
* A post build script copies the binary from build machine to debug machine.
* Open project settings, select the debug machine as the new remote.
* Start debugging
    * The build fails on the debug machine because there is no source code/make file.
    * Accept the prompt and run the previous successful build which will run the binary copied from the build machine. (In the project settings the path to the program should be the path on the debug machine, obviously)
* Debug ... modify code.
* Change remote back to build machine
* Build and ...

Although it already somehow works but it is becomes annoying after a few build/debugging sessions.

**Comment by itodirel** [comment]
hi, we not support this feature, and is publicly available @AliAskari https://devblogs.microsoft.com/cppblog/linux-development-with-c-in-visual-studio-2019-wsl-asan-for-linux-separation-of-build-and-debug/
