### ISSUE TITLE
Build error messages unclear if local or remote problem

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#90]
From a user report, when you try to build on a remote Linux device, and the necessary library was not yet compiled there (i.e. there are no xxx.so or xxx.a libraries there) or a header is missing, you get an error such as:
fatal error: foo.h: No such file or directory

* Expected results
fatal error: foo.h: No such file or directory **on remote Linux machine**.

* Actual results (with build output window contents if applicable)

**Comment by itodirel** [comment]
There is a way to filter this by selecting to show errors from either IntelliSense or build 
![capture](https://user-images.githubusercontent.com/15239856/38343252-49fc9d5a-3872-11e8-98fc-32bd270558a4.PNG)

**Comment by itodirel** [comment]
tentatively closing, can reopen if we want to do something here
