### ISSUE TITLE
Problem with build errors lookup with Makefile projects

### ISSUE THREAD

**Issue by dixonqmg** [Microsoft/VSLinux#91]
I created two identical test solutions. The only difference is one of them is set as a Makefile project, and another is set for direct g++ use. They both transfer sources properly, and invoke the appropriate compilers etc. 

The problem is - when I have errors in compilation, Makefile version refuses to open source file associated with error location. 
Here's the build output:

1>------ Build started: Project: vs_test, Configuration: Debug x64 ------
1>Validating architecture
1>Validating sources
1>Copying sources remotely
1>Invoking cd /n/local2/denis/vs_test;./build.sh
1>test.cpp: In function 'int main()':
1>test.cpp:5:8: error: 'exit' was not declared in this scope
1>  exit(1);
1>        ^
1>test.cpp: In function 'int main()':
1>test.cpp:5:8: error: 'exit' was not declared in this scope
1>  exit(1);
1>        ^
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets(135,5): error : cd /n/local2/denis/vs_test;./build.sh exited with code 1, please see the Output Window - Build output for more details (NOTE: the build output verbosity might need to be changed in Tools Options to see more information in the Output Window).

1>Done building project "vs_test.vcxproj" -- FAILED.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

And here's an example of a direct g++ compilation, where jumping to errors works:
1>------ Build started: Project: gcc_test, Configuration: Debug x64 ------
1>Validating architecture
1>Validating sources
1>Copying sources remotely
1>Starting remote build
1>Compiling sources:
1>main.cpp
1>\\VMWARE-HOST\SHARED FOLDERS\Documents\Visual Studio 2017\Projects\gcc_test\gcc_test\main.cpp(6,8): error : 'exit' was not declared in this scope

1>Done building project "gcc_test.vcxproj" -- FAILED.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by itodirel** [comment]
we fixed this bug and the fix will be available in the Preview 2 of Visual Studio 2017

**Comment by itodirel** [comment]
If you need help finding the Visual Studio version having this fix, or have any other feedback, please let us know
