### ISSUE TITLE
IntelliSense language level not configurable for Makefile projects

### ISSUE THREAD

**Issue by Hunter522** [Microsoft/VSLinux#92]
In Makefile projects, the IntelliSense language level cannot be set. Any C++14 language features or STL features will show linted errors. We are using CMake and C++14 in our project but would like IntelliSense to also use C++14. Project otherwise builds and debugs fine with Visual Studio.

Here are my project IntelliSense properties:
![intellisense_opts](https://cloud.githubusercontent.com/assets/9222431/22129927/d5ac0b08-de5d-11e6-9ddc-2810abd0bd4d.png)

It doesn't seem to matter what I put in for "Additional Options".

I am running on VC++ 2015 Community Edition (14.0.25431.01 update 3) with the 1.0.6 version of this extension.

**Comment by Agalin** [comment]
Issue still not fixed in VS2017 (26403.3). Tried both Intellisense syntax and GCC/Clang syntax.

**Comment by itodirel** [comment]
fixed and it will be available in 16.0 Preview 2

**Comment by ravichandhraRean** [comment]
When will be 16.0 Preview released.

**Comment by itodirel** [comment]
it is currently out https://visualstudio.microsoft.com/vs/preview/
