### ISSUE TITLE
private key connection failure: DER length is '39' and cannot be more than 4 bytes

### ISSUE THREAD

**Issue by ilnurkh** [Microsoft/VSLinux#95]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* Can not connect to remote linux host

* Actual results (with build output window contents if applicable)
logs:
System.InvalidOperationException: DER length is '39' and cannot be more than 4 bytes.
   в liblinux.Ssh.Common.DerData.ReadLength()
   в liblinux.Ssh.Common.DerData..ctor(Byte[] data)
   в liblinux.Ssh.Security.Key..ctor(Byte[] data)
   в liblinux.Ssh.Security.RsaKey..ctor(Byte[] data)
   в liblinux.Ssh.PrivateKeyFile.Open(Stream privateKey, SecureString passPhrase)
   в liblinux.Ssh.PrivateKeyFile..ctor(String fileName, SecureString passPhrase)
   в liblinux.RemoteSystemBase.Connect(PrivateKeyConnectionInfo privateKeyConnectionInfo)
   в liblinux.RemoteSystemBase.Connect()
   в liblinux.RemoteSystemBase.Connect(ConnectionInfo connectionInfo)
   в SSHConnectionUI.MainWindow.login_Click(Object sender, RoutedEventArgs e)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

I think - the latest ones.
There to get actual info about the extension? I have evene failed to find the extension in VS galary installed list.

**Comment by robotdad** [comment]
Did you export the key you are using from Putty?

**Comment by yuehuang010** [comment]
Please confirm if you are using OpenSSH formatted keys.  
Please create a new issue if it is still a problem.

**Comment by ilnurkh** [comment]
If I remember correctly, I tried to use putty key. There I can find instruction for generating keys in correct format.
