### ISSUE TITLE
Stop Debug throws an exception

### ISSUE THREAD

**Issue by aao111** [Microsoft/VSLinux#97]
* Upon stopping debug I receive en error  dlg
![stopdebugerror](https://cloud.githubusercontent.com/assets/4949746/22352703/e10edd4c-e3e2-11e6-95be-710f2ae30ebc.png)

* Expected results - no error , just stop

* Actual results- see above

* VC++ version(14.0.25431.01 Update 3) , Linux system name and version(CentOS release 6.5), GCC/GDB/gdbserver version(GNU gdb (GDB) Red Hat Enterprise Linux (7.5.0.20120926-26.el6)

* Steps required to reproduce the error - stop debugging

* Required packages and commands to install - does not matter

**Comment by CarlosPark** [comment]
I encountered exactly same problem too.

VC++ 14.0.25431.01 Update 3
Ubuntu 16.04 LTS (xenial)
GDB 7.11.1

**Comment by jinukkim** [comment]
I'm also having the same issue with the same environment to CarlosPark's. (Ubuntu 16.04 / VC++ 14 update 3)

For the first debugging session, I could debug the target process successfully. After that, I cannot debug the program anymore.
It looks like gdb (gdb-server?) process is not terminated normally after debugging session.

**Comment by paulmaybee** [comment]
Are you still having this problem? Have you upgraded to VC++ for Linux 1.0.7?

**Comment by lukka** [comment]
Closing this issue, please feel free to reopen the issue with a repro on the most recent version of Visual Studio 2017, thanks.
