### ISSUE TITLE
attempt to copy remote output file somewhere for no reason 

### ISSUE THREAD

**Issue by aao111** [Microsoft/VSLinux#98]
* A brief description
A makefile project attempts to copy  "Outputs" from "Remote Build" tab for no reason whatsoever 
"1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Makefile.Targets(135,5): warning : Cannot copy file 'WHATEVER I PUT IN THE OUTPUTS', file not found on the remote system."

* Expected results - dont copy anything I did not ask for , there is a remote post build step for that

* Actual results (with build output window contents if applicable) - "1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Makefile.Targets(135,5): warning : Cannot copy file 'WHATEVER I PUT IN THE OUTPUTS', file not found on the remote system." 

VC++ version(14.0.25431.01 Update 3) , Linux system name and version(CentOS release 6.5), GCC/GDB/gdbserver version(GNU gdb (GDB) Red Hat Enterprise Linux (7.5.0.20120926-26.el6)

* Steps required to reproduce the error - put anything in the outputs section and click build

* Required packages and commands to install - none

**Comment by SenorCMasMas** [comment]
I am still having this issue with VS2017 and centos7

**Comment by itodirel** [comment]
Hi, you can disable build output copy in Property Pages, we disabled copy of object files by default, the copy of the out put is still enabled by default. But you can disabled it from here:

![capture](https://user-images.githubusercontent.com/15239856/38343149-d1cf3806-3871-11e8-8eeb-a627b7c78a5d.PNG)
 
Please let us know if you have any other problems
